const multer=require('multer');
const XLSX=require('xlsx');
const Organization=require('../../models/platform/Organization');
const WorkPackage=require('../../models/platform/WorkPackage');
const BeneficiaryContext=require('../../models/platform/BeneficiaryContext');
const Farmer=require('../../models/Farmer');
const ComplianceRecord=require('../../models/platform/ComplianceRecord');
const ApprovalRequest=require('../../models/platform/ApprovalRequest');
const Warehouse=require('../../models/platform/Warehouse');
const Driver=require('../../models/platform/Driver');
const Vehicle=require('../../models/platform/Vehicle');
const InventorySerial=require('../../models/platform/InventorySerial');
const Shipment=require('../../models/platform/Shipment');
const ServiceCase=require('../../models/platform/ServiceCase');
const CommercialClaim=require('../../models/platform/CommercialClaim');
const PurchaseOrder=require('../../models/platform/PurchaseOrder');
const ReplenishmentPlan=require('../../models/platform/ReplenishmentPlan');
const AssetServicePlan=require('../../models/platform/AssetServicePlan');
const InsurancePolicy=require('../../models/platform/InsurancePolicy');
const platformAudit=require('../../utils/platformAudit');
const {cleanImportRows,rowNumber,extraFields,workbookBuffer}=require('../../utils/excelImport');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}}).single('file');
exports.uploadMiddleware=upload;
const MASTER_TEMPLATES={
 AGENCIES:['Name','Code','State','Country','Contact Name','Email','Mobile'],
 WAREHOUSES:['Name','Code','Type','City','District','State','Country','Pincode'],
 DRIVERS:['Name','Mobile','Email','License Number','Base Location','Status'],
 VEHICLES:['Registration No','Type','Capacity','Base Location','Status']
};
const importExtras=(row,known)=>extraFields(row,known);
exports.masterTemplate=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const type=String(req.params.type||'').toUpperCase(),cols=MASTER_TEMPLATES[type];if(!cols)return res.status(404).json({message:'Template type not found.'});const samples={AGENCIES:[{Name:'Nagpur Field Ops Agency',Code:'AG-NAG-001',State:'Maharashtra',Country:'India','Contact Name':'Operations Manager',Email:'ops@example.com',Mobile:'9876502001'},{Name:'Nashik Solar Services',Code:'AG-NSK-001',State:'Maharashtra',Country:'India','Contact Name':'Regional Lead',Email:'nashik@example.com',Mobile:'9876502002'}],WAREHOUSES:[{Name:'Nagpur Central Warehouse',Code:'WH-NAG-01',Type:'CENTRAL',City:'Nagpur',District:'Nagpur',State:'Maharashtra',Country:'India',Pincode:'440001'},{Name:'Agency Transit Store',Code:'WH-NAG-02',Type:'TRANSIT',City:'Nagpur',District:'Nagpur',State:'Maharashtra',Country:'India',Pincode:'440010'}],DRIVERS:[{Name:'Rahul Pawar',Mobile:'9876503001',Email:'rahul@example.com','License Number':'MH40-2026-001','Base Location':'Nagpur',Status:'AVAILABLE'},{Name:'Amit Kale',Mobile:'9876503002',Email:'amit@example.com','License Number':'MH40-2026-002','Base Location':'Nashik',Status:'OFF_DUTY'}],VEHICLES:[{'Registration No':'MH40AB1001',Type:'Pickup',Capacity:'2 Ton','Base Location':'Nagpur',Status:'AVAILABLE'},{'Registration No':'MH15XY2002',Type:'Truck',Capacity:'5 Ton','Base Location':'Nashik',Status:'MAINTENANCE'}]}[type]||[];const validations=type==='WAREHOUSES'?{Type:['CENTRAL','REGIONAL','AGENCY','TRANSIT','OTHER'],Country:['India']}:type==='DRIVERS'?{Status:['AVAILABLE','ASSIGNED','OFF_DUTY','INACTIVE']}:type==='VEHICLES'?{Status:['AVAILABLE','ASSIGNED','MAINTENANCE','INACTIVE']}:{Country:['India']};const buf=workbookBuffer({sheetName:type,columns:cols,samples,validations,instructions:[['Duplicate key',type==='AGENCIES'?'Code':type==='WAREHOUSES'?'Code':type==='DRIVERS'?'Mobile':'Registration No'],['Import behavior','Duplicate keys inside the same file are skipped and reported. Existing master records are updated; new records are created.'],['Extra columns','All non-standard columns are preserved in metadata.importExtras and remain available to detail/export flows.']]});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="opsynq-${type.toLowerCase()}-template.xlsx"`);res.send(buf);};

const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.params.companyId||req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
async function ensureCompany(req,res){const id=companyIdFor(req);if(!id){res.status(400).json({message:'Company context is required.'});return null}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null}return c}
const text=v=>String(v??'').trim();
const esc=s=>String(s??'').replace(/"/g,'""');
const csvRow=a=>a.map(v=>`"${esc(v)}"`).join(',');
const defaultItems=[
 ['beneficiary_approved','Approved beneficiary / application present'],['survey_complete','Survey completed'],['coordinates_verified','Site coordinates captured / verified'],['approved_material','Approved material / model used'],['serials_verified','Required serial numbers verified'],['installation_evidence','Installation photographs / evidence available'],['technician_trace','Installing technician traceable'],['final_inspection','Final inspection completed'],['commissioning','Commissioning / completion captured'],['documents_complete','Required documents complete']
];
exports.listCompliance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id};if(req.query.status)q.status=req.query.status;if(req.query.type)q.type=req.query.type;res.json({items:await ComplianceRecord.find(q).populate('agencyId','name code').populate('farmerId','beneficiaryId beneficiaryName district village inspectionStatus applicationStatus installationDoneYesNo').populate('workPackageId','code name').sort({createdAt:-1}).limit(500).lean()});};
exports.createCompliance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;let farmer=null;if(b.farmerId)farmer=await Farmer.findById(b.farmerId).lean();if(!farmer&&b.beneficiaryId)farmer=await Farmer.findOne({beneficiaryId:text(b.beneficiaryId)}).lean();if(!farmer)return res.status(400).json({message:'Valid Farmer/Beneficiary ID is required.'});const ctx=await BeneficiaryContext.findOne({companyId:c._id,farmerId:farmer._id});if(!ctx)return res.status(400).json({message:'Beneficiary is not mapped to this company.'});const recordNo=`CMP-${Date.now().toString(36).toUpperCase()}`;const items=defaultItems.map(([key,label])=>({key,label,status:key==='beneficiary_approved'?'PASS':key==='survey_complete'&&farmer?.inspectionStatus==='Completed'?'PASS':key==='final_inspection'&&farmer?.inspectionStatusFinal?'PASS':key==='commissioning'&&farmer?.installationDoneYesNo==='Yes'?'PASS':'PENDING'}));const item=await ComplianceRecord.create({companyId:c._id,programId:ctx.programId,workPackageId:ctx.workPackageId,agencyId:ctx.agencyId,farmerId:farmer._id,installedAssetId:b.installedAssetId||null,recordNo,type:b.type||'INSTALLATION',status:'IN_REVIEW',items,notes:b.notes||''});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'COMPLIANCE_RECORD_CREATED',entityType:'ComplianceRecord',entityId:item._id,after:{recordNo:item.recordNo,type:item.type}});res.status(201).json({item});};
exports.updateCompliance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await ComplianceRecord.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Compliance record not found.'});const before=item.toObject();if(Array.isArray(req.body.items)){const byKey=new Map(item.items.map(x=>[x.key,x]));for(const patch of req.body.items){const row=byKey.get(patch.key);if(row){if(['PENDING','PASS','FAIL','WAIVED'].includes(patch.status))row.status=patch.status;if(patch.notes!==undefined)row.notes=patch.notes;if(patch.evidence!==undefined)row.evidence=patch.evidence;row.checkedAt=new Date();}}}if(req.body.notes!==undefined)item.notes=req.body.notes;const required=item.items.filter(x=>x.required);const failed=required.some(x=>x.status==='FAIL');const pending=required.some(x=>x.status==='PENDING');item.status=failed?'FAIL':pending?'IN_REVIEW':'PASS';if(req.body.status==='WAIVED')item.status='WAIVED';item.reviewedBy=req.platformUser._id;item.reviewedAt=new Date();await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'COMPLIANCE_RECORD_REVIEWED',entityType:'ComplianceRecord',entityId:item._id,before,after:item.toObject(),reason:req.body.reason});res.json({item});};
exports.complianceSummary=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const agg=await ComplianceRecord.aggregate([{$match:{companyId:c._id}},{$group:{_id:'$status',count:{$sum:1}}}]);res.json({byStatus:agg,total:agg.reduce((a,b)=>a+b.count,0)});};
exports.agencyPerformance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const now=new Date();const oid=c._id;const [agencies,beneficiaryAgg,packageAgg,serviceAgg,shipmentAgg]=await Promise.all([
 Organization.find({type:'AGENCY',parentOrganization:oid,status:{$ne:'ARCHIVED'}}).select('name code status state contact metadata updatedAt').lean(),
 BeneficiaryContext.aggregate([{$match:{companyId:oid,agencyId:{$ne:null}}},{$lookup:{from:'farmers',localField:'farmerId',foreignField:'_id',as:'farmer'}},{$unwind:{path:'$farmer',preserveNullAndEmptyArrays:true}},{$group:{_id:'$agencyId',assigned:{$sum:1},surveyed:{$sum:{$cond:[{$in:['$farmer.inspectionStatus',['Completed','Approved']]},1,0]}},installed:{$sum:{$cond:[{$or:[{$eq:['$farmer.installationDoneYesNo','Yes']},{$in:['$farmer.applicationStatus',['Installation Completed','Closed']]}]},1,0]}},openComplaints:{$sum:{$cond:[{$in:['$farmer.complaintStatus',['Open','In Progress']]},1,0]}},lastBeneficiaryActivity:{$max:'$farmer.updatedAt'}}}]),
 WorkPackage.aggregate([{$match:{companyId:oid,agencyId:{$ne:null}}},{$group:{_id:'$agencyId',packages:{$sum:1},activePackages:{$sum:{$cond:[{$not:[{$in:['$status',['COMPLETED','CLOSED','CANCELLED']]}]},1,0]}},completedPackages:{$sum:{$cond:[{$in:['$status',['COMPLETED','CLOSED']]},1,0]}},blockedPackages:{$sum:{$cond:[{$eq:['$status','BLOCKED']},1,0]}},delayedPackages:{$sum:{$cond:[{$and:[{$lt:['$dueDate',now]},{$not:[{$in:['$status',['COMPLETED','CLOSED','CANCELLED']]}]}]},1,0]}},states:{$addToSet:'$geography.state'},districts:{$addToSet:'$geography.district'},lastPackageActivity:{$max:'$updatedAt'}}}]),
 ServiceCase.aggregate([{$match:{companyId:oid,agencyId:{$ne:null}}},{$group:{_id:'$agencyId',serviceOpen:{$sum:{$cond:[{$in:['$status',['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART']]},1,0]}},serviceBreached:{$sum:{$cond:[{$eq:['$slaState','BREACHED']},1,0]}},lastServiceActivity:{$max:'$updatedAt'}}}]),
 Shipment.aggregate([{$match:{companyId:oid,agencyId:{$ne:null},status:{$ne:'CANCELLED'}}},{$unwind:{path:'$items',preserveNullAndEmptyArrays:true}},{$group:{_id:'$agencyId',shipments:{$addToSet:'$_id'},dispatched:{$sum:{$ifNull:['$items.quantity',0]}},received:{$sum:{$ifNull:['$items.receivedQty',0]}},damaged:{$sum:{$ifNull:['$items.damagedQty',0]}},missing:{$sum:{$ifNull:['$items.missingQty',0]}},lastShipmentActivity:{$max:'$updatedAt'}}}])
 ]);
 const map=a=>new Map(a.filter(x=>x._id).map(x=>[String(x._id),x])),bm=map(beneficiaryAgg),pm=map(packageAgg),sm=map(serviceAgg),shm=map(shipmentAgg);
 const rows=agencies.map(a=>{const b=bm.get(String(a._id))||{},p=pm.get(String(a._id))||{},sv=sm.get(String(a._id))||{},sh=shm.get(String(a._id))||{};const assigned=Number(b.assigned||0),installed=Number(b.installed||0),surveyed=Number(b.surveyed||0),dispatched=Number(sh.dispatched||0),received=Number(sh.received||0),exceptions=Number(sh.damaged||0)+Number(sh.missing||0);const completionPct=assigned?Math.round(installed*1000/assigned)/10:0,surveyPct=assigned?Math.round(surveyed*1000/assigned)/10:0,receiptPct=dispatched?Math.round(received*1000/dispatched)/10:100;const lastActivity=[b.lastBeneficiaryActivity,p.lastPackageActivity,sv.lastServiceActivity,sh.lastShipmentActivity,a.updatedAt].filter(Boolean).sort((x,y)=>new Date(y)-new Date(x))[0]||null;return{agency:{_id:a._id,name:a.name,code:a.code,status:a.status,state:a.state,contact:a.contact},states:(p.states||[]).filter(Boolean).sort(),districts:(p.districts||[]).filter(Boolean).sort(),assigned,surveyed,installed,completionPct,surveyPct,openComplaints:Number(b.openComplaints||0),serviceOpen:Number(sv.serviceOpen||0),serviceBreached:Number(sv.serviceBreached||0),packages:Number(p.packages||0),activePackages:Number(p.activePackages||0),completedPackages:Number(p.completedPackages||0),blockedPackages:Number(p.blockedPackages||0),delayedPackages:Number(p.delayedPackages||0),shipments:(sh.shipments||[]).length,dispatched,received,damaged:Number(sh.damaged||0),missing:Number(sh.missing||0),receiptPct,materialExceptions:exceptions,lastActivity};});
 const totals=rows.reduce((o,x)=>({assigned:o.assigned+x.assigned,installed:o.installed+x.installed,surveyed:o.surveyed+x.surveyed,delayed:o.delayed+x.delayedPackages,issues:o.issues+x.openComplaints+x.serviceOpen+x.serviceBreached+x.blockedPackages,dispatched:o.dispatched+x.dispatched,received:o.received+x.received}),{assigned:0,installed:0,surveyed:0,delayed:0,issues:0,dispatched:0,received:0});totals.completionPct=totals.assigned?Math.round(totals.installed*1000/totals.assigned)/10:0;totals.surveyPct=totals.assigned?Math.round(totals.surveyed*1000/totals.assigned)/10:0;totals.receiptPct=totals.dispatched?Math.round(totals.received*1000/totals.dispatched)/10:100;res.json({generatedAt:new Date(),totals,items:rows.sort((a,b)=>(b.openComplaints+b.serviceOpen+b.serviceBreached+b.blockedPackages+b.delayedPackages)-(a.openComplaints+a.serviceOpen+a.serviceBreached+a.blockedPackages+a.delayedPackages)||b.assigned-a.assigned)});};
exports.listApprovals=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id};if(req.query.status)q.status=req.query.status;res.json({items:await ApprovalRequest.find(q).populate('requestedBy','name role').populate('decidedBy','name role').sort({createdAt:-1}).limit(500).lean()});};
exports.createApproval=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!b.title)return res.status(400).json({message:'Approval title is required.'});const item=await ApprovalRequest.create({companyId:c._id,requestNo:`APR-${Date.now().toString(36).toUpperCase()}`,type:b.type||'OTHER',title:b.title,description:b.description||'',entityType:b.entityType||'',entityId:b.entityId||null,requestedBy:req.platformUser._id,payload:b.payload||{}});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'APPROVAL_REQUEST_CREATED',entityType:'ApprovalRequest',entityId:item._id,after:{requestNo:item.requestNo,type:item.type,title:item.title}});res.status(201).json({item});};
exports.decideApproval=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const status=String(req.body.status||'').toUpperCase();if(!['APPROVED','REJECTED','CANCELLED'].includes(status))return res.status(400).json({message:'Decision must be APPROVED, REJECTED or CANCELLED.'});const item=await ApprovalRequest.findOne({_id:req.params.id,companyId:c._id,status:'PENDING'});if(!item)return res.status(404).json({message:'Pending approval not found.'});if(item.type==='PURCHASE_ORDER_APPROVAL'&&!['platform_superadmin','company_owner','company_admin'].includes(req.platformUser.role))return res.status(403).json({message:'Only Company Owner/Admin can approve a replenishment purchase order.'});if(item.type==='PURCHASE_ORDER_APPROVAL'&&item.entityId){const po=await PurchaseOrder.findOne({_id:item.entityId,companyId:c._id});if(!po)return res.status(409).json({message:'Related purchase order was not found.'});if(status==='APPROVED'){if(po.status!=='DRAFT')return res.status(409).json({message:'Related purchase order is no longer awaiting approval.'});po.status='ISSUED';await po.save();await ReplenishmentPlan.updateOne({companyId:c._id,draftPurchaseOrderId:po._id},{$set:{status:'APPROVED',approvedBy:req.platformUser._id,approvedAt:new Date()}});}else{if(po.status==='DRAFT'){po.status='CANCELLED';await po.save();}await ReplenishmentPlan.updateOne({companyId:c._id,draftPurchaseOrderId:po._id},{$set:{status:'DISMISSED',dismissedReason:req.body.reason||`Purchase order approval ${status.toLowerCase()}.`}});}}
if(status==='APPROVED'&&item.requestOrigin==='SYSTEM'&&item.entityId){const kind=String(item.payload?.proposalKind||'');if(kind==='SERVICE_PRIORITY_ESCALATION'){const row=await ServiceCase.findOne({_id:item.entityId,companyId:c._id});if(row){const proposed=['HIGH','CRITICAL'].includes(item.payload?.proposedPriority)?item.payload.proposedPriority:'HIGH';row.priority=proposed;row.metadata={...(row.metadata||{}),automationDecision:{approvedAt:new Date(),approvalRequestId:item._id,kind,approvedBy:req.platformUser._id}};await row.save();}}else if(kind==='CLAIM_FOLLOWUP'){const row=await CommercialClaim.findOne({_id:item.entityId,companyId:c._id});if(row){row.metadata={...(row.metadata||{}),followUpRequired:true,followUpConfirmedAt:new Date(),approvalRequestId:item._id};await row.save();}}else if(kind==='COVERAGE_REVIEW'){const row=await AssetServicePlan.findOne({_id:item.entityId,companyId:c._id});if(row){row.metadata={...(row.metadata||{}),reviewRequired:true,reviewConfirmedAt:new Date(),approvalRequestId:item._id};await row.save();}}else if(kind==='INSURANCE_REVIEW'){const row=await InsurancePolicy.findOne({_id:item.entityId,companyId:c._id});if(row){row.metadata={...(row.metadata||{}),reviewRequired:true,reviewConfirmedAt:new Date(),approvalRequestId:item._id};await row.save();}}}item.status=status;item.decidedBy=req.platformUser._id;item.decidedAt=new Date();item.decisionReason=req.body.reason||'';await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:`APPROVAL_${status}`,entityType:'ApprovalRequest',entityId:item._id,reason:item.decisionReason,after:item.toObject()});res.json({item});};

exports.actionCenter=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const now=new Date();const soon=new Date(now.getTime()+7*24*60*60*1000);const [approvals,serviceBreached,serviceDueSoon,claimsBlocked,claimsBreached,complianceExceptions,shipmentsOpen,inventoryExceptions,workBlocked,workDueSoon]=await Promise.all([
 ApprovalRequest.countDocuments({companyId:c._id,status:'PENDING'}),
 ServiceCase.countDocuments({companyId:c._id,status:{$nin:['RESOLVED','CLOSED','CANCELLED']},slaState:'BREACHED'}),
 ServiceCase.countDocuments({companyId:c._id,status:{$nin:['RESOLVED','CLOSED','CANCELLED']},slaState:'DUE_SOON'}),
 CommercialClaim.countDocuments({companyId:c._id,blockedAmount:{$gt:0},status:{$nin:['PAID','CANCELLED']}}),
 CommercialClaim.countDocuments({companyId:c._id,slaState:'BREACHED',status:{$nin:['PAID','CANCELLED']}}),
 ComplianceRecord.countDocuments({companyId:c._id,status:{$in:['FAIL','IN_REVIEW']}}),
 Shipment.countDocuments({companyId:c._id,status:{$in:['DISPATCHED','IN_TRANSIT','PARTIAL']}}),
 InventorySerial.countDocuments({companyId:c._id,status:{$in:['DAMAGED','REJECTED','MISSING']}}),
 WorkPackage.countDocuments({companyId:c._id,status:'BLOCKED'}),
 WorkPackage.countDocuments({companyId:c._id,dueDate:{$gte:now,$lte:soon},status:{$nin:['COMPLETED','CLOSED']}})
]);
 const cards=[
  {key:'approvals',label:'Pending approvals',count:approvals,severity:approvals?'attention':'clear',page:'approval-center',description:'Controlled decisions waiting for an approver'},
  {key:'service-breached',label:'Service SLA breached',count:serviceBreached,severity:serviceBreached?'critical':'clear',page:'service-cases',description:'Open service cases already beyond SLA'},
  {key:'service-due',label:'Service due soon',count:serviceDueSoon,severity:serviceDueSoon?'attention':'clear',page:'service-cases',description:'Service cases approaching SLA due time'},
  {key:'claims-blocked',label:'Claims blocked',count:claimsBlocked,severity:claimsBlocked?'critical':'clear',page:'claims',description:'Commercial claims with blocked value'},
  {key:'claims-breached',label:'Claim SLA breached',count:claimsBreached,severity:claimsBreached?'critical':'clear',page:'claims',description:'Submitted claims beyond configured SLA'},
  {key:'compliance',label:'Compliance exceptions',count:complianceExceptions,severity:complianceExceptions?'attention':'clear',page:'compliance',description:'Failed or in-review compliance records'},
  {key:'shipments',label:'Shipments in motion',count:shipmentsOpen,severity:shipmentsOpen?'info':'clear',page:'shipments',description:'Dispatched, in-transit or partially received shipments'},
  {key:'inventory',label:'Inventory exceptions',count:inventoryExceptions,severity:inventoryExceptions?'critical':'clear',page:'reconciliation',description:'Damaged, rejected or missing serialized assets'},
  {key:'work-blocked',label:'Blocked work packages',count:workBlocked,severity:workBlocked?'critical':'clear',page:'work-packages',description:'Execution packages explicitly blocked'},
  {key:'work-due',label:'Work due within 7 days',count:workDueSoon,severity:workDueSoon?'attention':'clear',page:'work-packages',description:'Open work packages nearing due date'}
 ];
 res.json({generatedAt:new Date(),cards,totals:{critical:cards.filter(x=>x.severity==='critical').reduce((n,x)=>n+x.count,0),attention:cards.filter(x=>x.severity==='attention').reduce((n,x)=>n+x.count,0)}});
};

exports.bulkMasters=async(req,res)=>{
 const c=await ensureCompany(req,res);if(!c)return;
 if(!req.file)return res.status(400).json({message:'Excel file is required.'});
 const type=String(req.body.type||'').toUpperCase();
 if(!MASTER_TEMPLATES[type])return res.status(400).json({message:'Supported types: AGENCIES, WAREHOUSES, DRIVERS, VEHICLES.'});
 const wb=XLSX.read(req.file.buffer,{type:'buffer'}),rows=cleanImportRows(wb.Sheets[wb.SheetNames[0]]);
 let created=0,updated=0,skipped=0,failed=0;const errors=[],known=new Set(MASTER_TEMPLATES[type]),seen=new Set();
 const keyFor=r=>type==='AGENCIES'?text(r.Code).toUpperCase():type==='WAREHOUSES'?text(r.Code).toUpperCase():type==='DRIVERS'?text(r.Mobile):text(r['Registration No']).toUpperCase();
 const same=(a,b)=>JSON.stringify(a??null)===JSON.stringify(b??null);
 for(let i=0;i<rows.length;i++){
  const r=rows[i],extras=importExtras(r,known),key=keyFor(r),rowNo=rowNumber(r,i+2);
  try{
   if(!key)throw new Error(type==='DRIVERS'?'Mobile is required':type==='VEHICLES'?'Registration No is required':'Code is required');
   if(seen.has(key)){skipped++;errors.push({row:rowNo,key,message:'Duplicate key repeated inside this Excel file; later row skipped.'});continue;}
   seen.add(key);
   let Model,filter,payload;
   if(type==='AGENCIES'){
    if(!text(r.Name))throw new Error('Name and Code are required');
    Model=Organization;filter={type:'AGENCY',parentOrganization:c._id,code:key};payload={name:text(r.Name),country:text(r.Country)||c.country||'India',state:text(r.State)||c.state,status:'ACTIVE',contact:{name:text(r['Contact Name']),email:text(r.Email),mobile:text(r.Mobile)}};
   }else if(type==='WAREHOUSES'){
    if(!text(r.Name))throw new Error('Name and Code are required');
    Model=Warehouse;filter={companyId:c._id,code:key};payload={name:text(r.Name),type:['CENTRAL','REGIONAL','AGENCY','TRANSIT','OTHER'].includes(text(r.Type).toUpperCase())?text(r.Type).toUpperCase():'OTHER',address:{city:text(r.City),district:text(r.District),state:text(r.State),country:text(r.Country)||c.country||'India',pincode:text(r.Pincode)},isActive:true};
   }else if(type==='DRIVERS'){
    if(!text(r.Name))throw new Error('Name and Mobile are required');
    Model=Driver;filter={companyId:c._id,mobile:key};payload={name:text(r.Name),email:text(r.Email),licenseNumber:text(r['License Number']),baseLocation:text(r['Base Location']),status:['AVAILABLE','ASSIGNED','OFF_DUTY','INACTIVE'].includes(text(r.Status).toUpperCase())?text(r.Status).toUpperCase():'AVAILABLE',isActive:true};
   }else{
    Model=Vehicle;filter={companyId:c._id,registrationNo:key};payload={type:text(r.Type),capacity:text(r.Capacity),baseLocation:text(r['Base Location']),status:['AVAILABLE','ASSIGNED','MAINTENANCE','INACTIVE'].includes(text(r.Status).toUpperCase())?text(r.Status).toUpperCase():'AVAILABLE',isActive:true};
   }
   const existing=await Model.findOne(filter).lean();
   const mergedExtras={...(existing?.metadata?.importExtras||{}),...extras};
   const next={...payload,metadata:{...(existing?.metadata||{}),importExtras:mergedExtras,lastImportFile:req.file.originalname,lastImportedAt:new Date()}};
   if(existing){
    const comparable=Object.fromEntries(Object.keys(payload).map(k=>[k,existing[k]]));
    if(same(comparable,payload)&&same(existing?.metadata?.importExtras||{},mergedExtras)){skipped++;continue;}
    await Model.updateOne({_id:existing._id},{$set:next});updated++;
   }else{
    await Model.create({...filter,...next});created++;
   }
  }catch(e){failed++;errors.push({row:rowNo,key,message:e.message});}
 }
 await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'MASTER_BULK_IMPORT',entityType:type,after:{total:rows.length,created,updated,skipped,failed,extraColumnsPreserved:true}});
 res.status(201).json({type,total:rows.length,success:created+updated,created,updated,skipped,failed,errors:errors.slice(0,100),extraColumnsPreserved:true});
};
exports.exportData=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const type=String(req.query.type||'').toLowerCase();let headers=[],rows=[];if(type==='agencies'){const x=await Organization.find({type:'AGENCY',parentOrganization:c._id}).lean();headers=['Code','Name','Status','State','Contact','Mobile'];rows=x.map(a=>[a.code,a.name,a.status,a.state,a.contact?.name,a.contact?.mobile]);}else if(type==='inventory'){const x=await InventorySerial.find({companyId:c._id}).populate('itemId','sku name').populate('warehouseId','code name').populate('agencyId','code name').lean();headers=['SKU','Item','Serial','Barcode','Status','Warehouse','Agency'];rows=x.map(a=>[a.itemId?.sku,a.itemId?.name,a.serialNumber,a.barcodeValue,a.status,a.warehouseId?.code,a.agencyId?.code]);}else if(type==='shipments'){const x=await Shipment.find({companyId:c._id}).populate('agencyId','code name').populate('driverId','name mobile').populate('vehicleId','registrationNo').lean();headers=['Shipment','Status','Agency','Driver','Vehicle','Created'];rows=x.map(a=>[a.shipmentNo,a.status,a.agencyId?.name,a.driverId?.name,a.vehicleId?.registrationNo,a.createdAt?.toISOString()]);}else if(type==='service'){const x=await ServiceCase.find({companyId:c._id}).lean();headers=['Case','Type','Priority','Status','SLA','Opened','Due'];rows=x.map(a=>[a.caseNo,a.type,a.priority,a.status,a.slaState,a.openedAt?.toISOString(),a.dueAt?.toISOString()]);}else if(type==='claims'){const x=await CommercialClaim.find({companyId:c._id}).lean();headers=['Claim','Status','Eligible','Approved','Paid','Blocked','SLA'];rows=x.map(a=>[a.claimNo,a.status,a.eligibleAmount,a.approvedAmount,a.paidAmount,a.blockedAmount,a.slaState]);}else if(type==='compliance'){const x=await ComplianceRecord.find({companyId:c._id}).populate('farmerId','beneficiaryId beneficiaryName').lean();headers=['Record','Type','Status','Beneficiary ID','Beneficiary','Reviewed'];rows=x.map(a=>[a.recordNo,a.type,a.status,a.farmerId?.beneficiaryId,a.farmerId?.beneficiaryName,a.reviewedAt?.toISOString()]);}else return res.status(400).json({message:'Supported exports: agencies, inventory, shipments, service, claims, compliance.'});const body='\uFEFF'+[csvRow(headers),...rows.map(csvRow)].join('\r\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="opsynq-${type}-${new Date().toISOString().slice(0,10)}.csv"`);res.send(body);};
