const mongoose=require('mongoose');
const Organization=require('../../models/platform/Organization');
const AutomationRun=require('../../models/platform/AutomationRun');
const ServiceCase=require('../../models/platform/ServiceCase');
const CommercialClaim=require('../../models/platform/CommercialClaim');
const AssetServicePlan=require('../../models/platform/AssetServicePlan');
const InsurancePolicy=require('../../models/platform/InsurancePolicy');
const ReplenishmentPlan=require('../../models/platform/ReplenishmentPlan');
const {executeJob,JOBS}=require('../../utils/automationEngine');
const platformAudit=require('../../utils/platformAudit');
const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.query.companyId||req.body.companyId||req.params.companyId):String(req.tenant.companyId||'');
async function company(req,res){const id=companyIdFor(req);if(!id){res.status(400).json({message:'Company context is required.'});return null}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null}return c}
exports.summary=async(req,res)=>{const c=await company(req,res);if(!c)return;const now=new Date(),d30=new Date(Date.now()+30*86400000);const [serviceBreached,claimBreached,warrantyExpiring,warrantyExpired,insuranceExpiring,insuranceExpired,replenishmentCritical,replenishmentOpen,recent]=await Promise.all([ServiceCase.countDocuments({companyId:c._id,status:{$in:['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART']},slaState:'BREACHED'}),CommercialClaim.countDocuments({companyId:c._id,status:{$in:['SUBMITTED','UNDER_REVIEW']},slaState:'BREACHED'}),AssetServicePlan.countDocuments({companyId:c._id,endDate:{$gte:now,$lte:d30},status:{$ne:'CANCELLED'}}),AssetServicePlan.countDocuments({companyId:c._id,endDate:{$lt:now},status:{$ne:'CANCELLED'}}),InsurancePolicy.countDocuments({companyId:c._id,endDate:{$gte:now,$lte:d30},status:{$nin:['CANCELLED','CLAIM_SETTLED']}}),InsurancePolicy.countDocuments({companyId:c._id,endDate:{$lt:now},status:{$nin:['CANCELLED','CLAIM_SETTLED']}}),ReplenishmentPlan.countDocuments({companyId:c._id,status:{$in:['OPEN','DRAFT_PO']},urgency:'CRITICAL'}),ReplenishmentPlan.countDocuments({companyId:c._id,status:{$in:['OPEN','DRAFT_PO']}}),AutomationRun.find({companyId:c._id}).sort({startedAt:-1}).limit(25).populate('requestedBy','name role').lean()]);res.json({scheduler:{enabled:true,intervalMinutes:15,jobs:Object.keys(JOBS)},signals:{serviceBreached,claimBreached,warrantyExpiring,warrantyExpired,insuranceExpiring,insuranceExpired,replenishmentCritical,replenishmentOpen,aiConfigured:!!process.env.AI_PROVIDER_API_KEY},recent});};
exports.run=async(req,res)=>{const c=await company(req,res);if(!c)return;const job=String(req.params.job||'').toLowerCase();if(!JOBS[job])return res.status(400).json({message:`Supported jobs: ${Object.keys(JOBS).join(', ')}`});const run=await executeJob(job,{companyId:c._id,trigger:'MANUAL',requestedBy:req.platformUser._id});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'AUTOMATION_JOB_RUN',entityType:'AutomationRun',entityId:run._id,after:{job,status:run.status,metrics:run.metrics}});res.status(run.status==='FAILED'?500:200).json({run});};
exports.health=async(req,res)=>{res.json({ok:true,service:'opsynq-api',database:mongoose.connection.readyState===1?'connected':'not_connected',databaseName:mongoose.connection.name||null,uptimeSeconds:Math.round(process.uptime()),memoryMB:{rss:Math.round(process.memoryUsage().rss/1048576),heapUsed:Math.round(process.memoryUsage().heapUsed/1048576)},timestamp:new Date().toISOString()});};
