const Organization=require('../../models/platform/Organization');
const MasterDataEntry=require('../../models/platform/MasterDataEntry');
const EvidenceRequirement=require('../../models/platform/EvidenceRequirement');
const EvidenceSubmission=require('../../models/platform/EvidenceSubmission');
const Farmer=require('../../models/Farmer');
const platformAudit=require('../../utils/platformAudit');
const cid=req=>req.platformUser.role==='platform_superadmin'?(req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
async function company(req,res){const id=cid(req);if(!id){res.status(400).json({message:'Company context is required.'});return null;}if(!require('mongoose').isValidObjectId(id)){res.status(400).json({message:'Invalid company context.'});return null;}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null;}return c}
exports.listMaster=async(req,res)=>{const c=await company(req,res);if(!c)return;const f={companyId:c._id};if(req.query.domain)f.domain=req.query.domain;if(req.query.type)f.type=req.query.type;if(req.query.active==='true'||req.query.active==='false')f.isActive=req.query.active==='true';res.json({items:await MasterDataEntry.find(f).sort({domain:1,type:1,sortOrder:1,label:1}).lean()})};
exports.saveMaster=async(req,res)=>{const c=await company(req,res);if(!c)return;const b=req.body;if(!b.domain||!b.type||!b.code||!b.label)return res.status(400).json({message:'Domain, type, code and label are required.'});const item=await MasterDataEntry.findOneAndUpdate({companyId:c._id,type:b.type,code:String(b.code).trim().toUpperCase()},{$set:{domain:b.domain,label:String(b.label).trim(),parentCode:b.parentCode||'',sortOrder:Number(b.sortOrder||0),isActive:b.isActive!==false,metadata:b.metadata||{}}},{upsert:true,new:true,setDefaultsOnInsert:true});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'MASTER_DATA_SAVED',entityType:'MasterDataEntry',entityId:item._id,after:item.toObject()});res.status(201).json({item})};
exports.toggleMaster=async(req,res)=>{const c=await company(req,res);if(!c)return;const item=await MasterDataEntry.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Master record not found.'});item.isActive=req.body.isActive!==false;await item.save();res.json({item})};
exports.listRequirements=async(req,res)=>{const c=await company(req,res);if(!c)return;const f={companyId:c._id};if(req.query.stage)f.stage=req.query.stage;res.json({items:await EvidenceRequirement.find(f).populate('programId','name code').sort({stage:1,sortOrder:1,label:1}).lean()})};
exports.saveRequirement=async(req,res)=>{const c=await company(req,res);if(!c)return;const b=req.body;if(!b.stage||!b.key||!b.label)return res.status(400).json({message:'Stage, key and label are required.'});const item=await EvidenceRequirement.findOneAndUpdate({companyId:c._id,programId:b.programId||null,stage:b.stage,key:String(b.key).trim().toLowerCase().replace(/\s+/g,'_')},{$set:{label:String(b.label).trim(),evidenceType:b.evidenceType||'PHOTO',required:b.required!==false,minFiles:Number(b.minFiles??1),sortOrder:Number(b.sortOrder||0),isActive:b.isActive!==false}},{upsert:true,new:true,setDefaultsOnInsert:true});res.status(201).json({item})};
exports.evidenceStatus=async(req,res)=>{const c=await company(req,res);if(!c)return;const reqs=await EvidenceRequirement.find({companyId:c._id,isActive:true}).lean();const subs=await EvidenceSubmission.find({companyId:c._id,farmerId:req.params.farmerId}).populate('requirementId').lean();const by=new Map(subs.map(x=>[String(x.requirementId?._id||x.requirementId),x]));res.json({items:reqs.map(r=>({requirement:r,submission:by.get(String(r._id))||null}))})};
exports.verifySubmission=async(req,res)=>{const c=await company(req,res);if(!c)return;const item=await EvidenceSubmission.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Evidence submission not found.'});item.status=req.body.status||'VERIFIED';item.notes=req.body.notes||item.notes;item.verifiedBy=req.platformUser._id;item.verifiedAt=new Date();await item.save();res.json({item})};
