const multer=require('multer');
const {cloudinary}=require('../../config/cloudinary');
const Notification=require('../../models/platform/Notification');
const DocumentRecord=require('../../models/platform/DocumentRecord');
const AuditLog=require('../../models/platform/AuditLog');
const Organization=require('../../models/platform/Organization');
const Program=require('../../models/platform/Program');
const WorkPackage=require('../../models/platform/WorkPackage');
const ServiceCase=require('../../models/platform/ServiceCase');
const CommercialClaim=require('../../models/platform/CommercialClaim');
const InventorySerial=require('../../models/platform/InventorySerial');
const Shipment=require('../../models/platform/Shipment');
const PlatformUser=require('../../models/platform/PlatformUser');
const LegacyUser=require('../../models/User');
const platformAudit=require('../../utils/platformAudit');

const COMPANY_NOTIFICATION_ROLES=['company_owner','company_admin','operations_manager','program_manager','inventory_manager','procurement_manager','finance_user','quality_user','logistics_manager','viewer'];
const notificationAudience=req=>[
 {recipientUserId:req.platformUser._id},
 {recipientUserId:null,recipientRoles:req.platformUser.role},
 {recipientUserId:null,recipientRoles:{$exists:false}},
 {recipientUserId:null,recipientRoles:{$size:0}}
];
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024},fileFilter:(req,file,cb)=>{const ok=['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel'].includes(file.mimetype);cb(ok?null:new Error('Only PDF, image and Excel documents are supported.'),ok)}}).single('file');
exports.uploadMiddleware=upload;
const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.params.companyId||req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
async function ensureCompany(req,res){const id=companyIdFor(req);if(!id){res.status(400).json({message:'Company context is required.'});return null}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null}return c}
const moneyAgg=rows=>rows[0]||{eligible:0,approved:0,paid:0,blocked:0};
exports.analytics=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id},now=new Date(),d30=new Date(Date.now()-30*86400000);const [programs,packages,packageStatus,serviceOpen,serviceBreached,claims,inventoryStatus,shipmentStatus,audit30,users,unread]=await Promise.all([
 Program.countDocuments(q),WorkPackage.countDocuments(q),WorkPackage.aggregate([{$match:q},{$group:{_id:'$status',count:{$sum:1},quantity:{$sum:'$assignedQuantity'}}}]),
 ServiceCase.countDocuments({...q,status:{$in:['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART']}}),ServiceCase.countDocuments({...q,$or:[{slaState:'BREACHED'},{dueAt:{$lt:now}}],status:{$nin:['RESOLVED','CLOSED','CANCELLED']}}),
 CommercialClaim.aggregate([{$match:q},{$group:{_id:null,eligible:{$sum:'$eligibleAmount'},approved:{$sum:'$approvedAmount'},paid:{$sum:'$paidAmount'},blocked:{$sum:'$blockedAmount'}}}]),
 InventorySerial.aggregate([{$match:q},{$group:{_id:'$status',count:{$sum:1}}}]),Shipment.aggregate([{$match:q},{$group:{_id:'$status',count:{$sum:1}}}]),AuditLog.countDocuments({...q,createdAt:{$gte:d30}}),PlatformUser.countDocuments({organizationId:c._id,isActive:true}),Notification.find({companyId:c._id,$or:notificationAudience(req)}).select('recipientUserId isRead readBy').limit(500).lean()
]);const userId=String(req.platformUser._id);const unreadCount=(unread||[]).filter(n=>n.recipientUserId?(!n.isRead):!(n.readBy||[]).some(r=>String(r.userId)===userId)).length;res.json({company:{id:c._id,name:c.name,code:c.code},programs,workPackages:packages,packageStatus,service:{open:serviceOpen,breached:serviceBreached},claims:moneyAgg(claims),inventoryStatus,shipmentStatus,auditEvents30d:audit30,activeUsers:users,unreadNotifications:unreadCount});};
exports.listNotifications=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id,$or:notificationAudience(req)};const userId=String(req.platformUser._id);let items=await Notification.find(q).sort({createdAt:-1}).limit(200).lean();items=items.map(n=>({...n,isRead:n.recipientUserId?Boolean(n.isRead):(n.readBy||[]).some(r=>String(r.userId)===userId)}));if(req.query.unread==='true')items=items.filter(n=>!n.isRead);res.json({items,unread:items.filter(n=>!n.isRead).length});};
exports.createNotification=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!b.title||!b.message)return res.status(400).json({message:'Title and message are required.'});if(b.recipientUserId){const u=await PlatformUser.findOne({_id:b.recipientUserId,organizationId:c._id});if(!u)return res.status(400).json({message:'Recipient is not part of this company.'})}const roles=Array.isArray(b.recipientRoles)?[...new Set(b.recipientRoles.filter(r=>COMPANY_NOTIFICATION_ROLES.includes(r)))]:[];const item=await Notification.create({companyId:c._id,recipientUserId:b.recipientUserId||null,recipientRoles:b.recipientUserId?[]:roles,type:b.type||'INFO',title:String(b.title).trim(),message:String(b.message).trim(),entityType:b.entityType||'',entityId:b.entityId||null,actionUrl:b.actionUrl||'',createdBy:req.platformUser._id});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'NOTIFICATION_CREATED',entityType:'Notification',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.readNotification=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await Notification.findOne({_id:req.params.id,companyId:c._id,$or:notificationAudience(req)});if(!item)return res.status(404).json({message:'Notification not found.'});const now=new Date();if(item.recipientUserId){item.isRead=true;item.readAt=now;}else if(!(item.readBy||[]).some(r=>String(r.userId)===String(req.platformUser._id))){item.readBy.push({userId:req.platformUser._id,readAt:now});}await item.save();res.json({item:{...item.toObject(),isRead:true}});};
exports.listDocuments=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id,status:{$ne:'ARCHIVED'}};if(req.query.category)q.category=req.query.category;if(req.query.search){const r=new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');q.$or=[{title:r},{documentNo:r},{fileName:r}]}res.json({items:await DocumentRecord.find(q).populate('uploadedBy','name email mobile').sort({createdAt:-1}).limit(500).lean()});};
exports.uploadDocument=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!req.file)return res.status(400).json({message:'Choose a document to upload.'});if(!req.body.title)return res.status(400).json({message:'Document title is required.'});const result=await new Promise((resolve,reject)=>{const s=cloudinary.uploader.upload_stream({folder:`Opsynq/Documents/${String(c._id)}`,resource_type:'auto'},(e,r)=>e?reject(e):resolve(r));s.end(req.file.buffer)});const item=await DocumentRecord.create({companyId:c._id,category:req.body.category||'OTHER',title:req.body.title,documentNo:req.body.documentNo||'',entityType:req.body.entityType||'',entityId:req.body.entityId||null,fileUrl:result.secure_url,publicId:result.public_id,fileName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,uploadedBy:req.platformUser._id,notes:req.body.notes||''});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'DOCUMENT_UPLOADED',entityType:'DocumentRecord',entityId:item._id,after:{title:item.title,category:item.category,fileName:item.fileName}});res.status(201).json({item});};
exports.archiveDocument=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await DocumentRecord.findOneAndUpdate({_id:req.params.id,companyId:c._id},{$set:{status:'ARCHIVED'}},{new:true});if(!item)return res.status(404).json({message:'Document not found.'});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'DOCUMENT_ARCHIVED',entityType:'DocumentRecord',entityId:item._id});res.json({item});};
exports.audit=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id};if(req.query.action)q.action=req.query.action;if(req.query.entityType)q.entityType=req.query.entityType;if(req.query.from||req.query.to){q.createdAt={};if(req.query.from)q.createdAt.$gte=new Date(req.query.from);if(req.query.to){const d=new Date(req.query.to);d.setHours(23,59,59,999);q.createdAt.$lte=d;}}const items=await AuditLog.find(q).sort({createdAt:-1}).limit(750).lean();const ids=[...new Set(items.map(x=>x.actorId&&String(x.actorId)).filter(Boolean))];const [platformUsers,legacyUsers]=await Promise.all([PlatformUser.find({_id:{$in:ids}}).select('name email mobile role').lean(),LegacyUser.find({_id:{$in:ids}}).select('username mobile role').lean()]);const actors=new Map();for(const u of platformUsers)actors.set(String(u._id),{name:u.name,email:u.email,mobile:u.mobile,role:u.role,type:'PlatformUser'});for(const u of legacyUsers)actors.set(String(u._id),{name:u.username,mobile:u.mobile,role:u.role,type:'AgencyUser'});res.json({items:items.map(x=>({...x,actor:actors.get(String(x.actorId))||null}))});};
