const mongoose=require('mongoose');
const crypto=require('crypto');
const XLSX=require('xlsx');
const Organization=require('../../models/platform/Organization');
const Program=require('../../models/platform/Program');
const Contract=require('../../models/platform/Contract');
const WorkOrder=require('../../models/platform/WorkOrder');
const WorkPackage=require('../../models/platform/WorkPackage');
const BeneficiaryContext=require('../../models/platform/BeneficiaryContext');
const ImportBatch=require('../../models/platform/ImportBatch');
const Farmer=require('../../models/Farmer');
const InstalledAsset=require('../../models/platform/InstalledAsset');
const MaterialIssue=require('../../models/platform/MaterialIssue');
const ServiceCase=require('../../models/platform/ServiceCase');
const ComplianceRecord=require('../../models/platform/ComplianceRecord');
const EvidenceRequirement=require('../../models/platform/EvidenceRequirement');
const EvidenceSubmission=require('../../models/platform/EvidenceSubmission');
const platformAudit=require('../../utils/platformAudit');

const companyIdFor=(req)=> req.platformUser.role==='platform_superadmin' ? (req.params.companyId||req.query.companyId||req.body.companyId) : String(req.tenant.companyId||'');
const ensureCompany=async(req,res)=>{ const companyId=companyIdFor(req); if(!companyId){res.status(400).json({message:'Company context is required.'});return null;} const c=await Organization.findOne({_id:companyId,type:'COMPANY',status:{$ne:'ARCHIVED'}}); if(!c){res.status(404).json({message:'Company not found.'});return null;} return c; };
const text=(v)=>String(v??'').trim();

exports.dashboard=async(req,res)=>{
 const company=await ensureCompany(req,res); if(!company)return;
 const q={companyId:company._id};
 const [programs,contracts,workOrders,workPackages,agencies,beneficiaries,pendingPackages]=await Promise.all([
   Program.countDocuments(q),Contract.countDocuments(q),WorkOrder.countDocuments(q),WorkPackage.countDocuments(q),
   Organization.countDocuments({type:'AGENCY',parentOrganization:company._id,status:'ACTIVE'}),BeneficiaryContext.countDocuments(q),
   WorkPackage.countDocuments({...q,status:{$in:['READY','ASSIGNED','IN_PROGRESS','BLOCKED']}})
 ]);
 const packageAgg=await WorkPackage.aggregate([{$match:{companyId:company._id}},{$group:{_id:'$status',count:{$sum:1},quantity:{$sum:'$assignedQuantity'}}}]);
 const companyContexts=await BeneficiaryContext.find(q).select('farmerId agencyId').populate('agencyId','name code').lean();
 const farmerIds=companyContexts.map(x=>x.farmerId).filter(Boolean);
 const farmers=farmerIds.length?await Farmer.find({_id:{$in:farmerIds}}).select('applicationStatus inspectionStatus district').lean():[];
 const farmerById=new Map(farmers.map(f=>[String(f._id),f]));
 const beneficiaryStatus={},surveyStatus={},districtMap={};
 for(const ctx of companyContexts){const f=farmerById.get(String(ctx.farmerId));if(!f)continue;const app=f.applicationStatus||'Pending',survey=f.inspectionStatus||'Pending',district=f.district||'Unspecified';beneficiaryStatus[app]=(beneficiaryStatus[app]||0)+1;surveyStatus[survey]=(surveyStatus[survey]||0)+1;districtMap[district]=districtMap[district]||{district,count:0,completed:0,inProgress:0,complaints:0,agencies:new Set()};const row=districtMap[district];row.count++;if(['Installation Completed','Closed'].includes(app))row.completed++;else if(app==='Complaint Raised')row.complaints++;else row.inProgress++;if(ctx.agencyId?._id)row.agencies.add(String(ctx.agencyId._id));}
 const districts=Object.values(districtMap).map(x=>({...x,agencies:x.agencies.size,completionPercent:x.count?Math.round(x.completed/x.count*100):0})).sort((a,b)=>b.count-a.count);
 res.json({company:{id:company._id,name:company.name,code:company.code},programs,contracts,workOrders,workPackages,agencies,beneficiaries,pendingPackages,packageStatus:packageAgg,beneficiaryStatus:Object.entries(beneficiaryStatus).map(([status,count])=>({status,count})),surveyStatus:Object.entries(surveyStatus).map(([status,count])=>({status,count})),districts});
};


const parseSiteLocation=(value)=>{const parts=String(value||'').split(',').map(x=>Number(String(x).trim()));return parts.length>=2&&Number.isFinite(parts[0])&&Number.isFinite(parts[1])?{latitude:parts[0],longitude:parts[1]}:null};
exports.geoOverview=async(req,res)=>{
 const c=await ensureCompany(req,res);if(!c)return;
 const ctxFilter={companyId:c._id};if(req.query.agencyId&&mongoose.isValidObjectId(req.query.agencyId))ctxFilter.agencyId=req.query.agencyId;
 const contexts=await BeneficiaryContext.find(ctxFilter).populate('farmerId').populate('agencyId','name code').populate('workPackageId','code name status geography').populate('programId','name code').lean();
 const farmerIds=contexts.map(x=>x.farmerId?._id||x.farmerId).filter(Boolean);
 const evidence=farmerIds.length?await EvidenceSubmission.find({companyId:c._id,farmerId:{$in:farmerIds},'captureGeo.latitude':{$exists:true},'captureGeo.longitude':{$exists:true}}).sort({updatedAt:-1}).lean():[];
 const geoByFarmer=new Map();for(const e of evidence){const k=String(e.farmerId);if(!geoByFarmer.has(k))geoByFarmer.set(k,e.captureGeo)}
 const pins=[];for(const ctx of contexts){const f=ctx.farmerId;if(!f)continue;if(req.query.status&&f.applicationStatus!==req.query.status)continue;if(req.query.district&&f.district!==req.query.district)continue;if(req.query.survey&&f.inspectionStatus!==req.query.survey)continue;const id=String(f._id);const geo=geoByFarmer.get(id)||parseSiteLocation(f.siteLocation);if(!geo)continue;pins.push({farmerId:id,beneficiaryId:f.beneficiaryId,name:f.beneficiaryName,mobile:f.mobile,status:f.applicationStatus||'Pending',surveyStatus:f.inspectionStatus||'Pending',district:f.district||'',taluka:f.taluka||'',village:f.village||'',latitude:Number(geo.latitude),longitude:Number(geo.longitude),accuracy:Number(geo.accuracy||0),capturedAt:geo.capturedAt||null,geoSource:geoByFarmer.has(id)?'Evidence':'Site record',agency:ctx.agencyId?{id:ctx.agencyId._id,name:ctx.agencyId.name,code:ctx.agencyId.code}:null,program:ctx.programId?{id:ctx.programId._id,name:ctx.programId.name,code:ctx.programId.code}:null,workPackage:ctx.workPackageId?{id:ctx.workPackageId._id,code:ctx.workPackageId.code,name:ctx.workPackageId.name,status:ctx.workPackageId.status}:null});}
 const statusCounts={};const districtCounts={};for(const p of pins){statusCounts[p.status]=(statusCounts[p.status]||0)+1;districtCounts[p.district]=(districtCounts[p.district]||0)+1;}
 res.json({pins,total:pins.length,statuses:Object.entries(statusCounts).map(([status,count])=>({status,count})),districts:Object.entries(districtCounts).map(([district,count])=>({district,count})).sort((a,b)=>b.count-a.count)});
};

exports.listPrograms=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({items:await Program.find({companyId:c._id}).sort({createdAt:-1}).lean()});};
exports.createProgram=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body; if(!text(b.name)||!text(b.code))return res.status(400).json({message:'Program name and code are required.'}); const item=await Program.create({companyId:c._id,name:text(b.name),code:text(b.code).toUpperCase(),country:b.country||c.country||'India',state:b.state,authority:b.authority,scheme:b.scheme,component:b.component,financialYear:b.financialYear,sanctionedQuantity:Number(b.sanctionedQuantity||0),contractValue:Number(b.contractValue||0),currency:b.currency||'INR',startDate:b.startDate||undefined,endDate:b.endDate||undefined,status:b.status||'DRAFT'}); await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'PROGRAM_CREATED',entityType:'Program',entityId:item._id,after:item.toObject()});res.status(201).json({item});};

exports.listContracts=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const filter={companyId:c._id};if(req.query.programId)filter.programId=req.query.programId;res.json({items:await Contract.find(filter).populate('programId','name code').sort({createdAt:-1}).lean()});};
exports.createContract=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!b.programId||!text(b.number)||!text(b.title))return res.status(400).json({message:'Program, contract/LOA number and title are required.'}); const prog=await Program.findOne({_id:b.programId,companyId:c._id});if(!prog)return res.status(400).json({message:'Invalid program.'});const item=await Contract.create({companyId:c._id,programId:prog._id,type:b.type||'LOA',number:text(b.number),title:text(b.title),authority:b.authority,sanctionedQuantity:Number(b.sanctionedQuantity||0),contractValue:Number(b.contractValue||0),currency:b.currency||'INR',awardDate:b.awardDate||undefined,startDate:b.startDate||undefined,endDate:b.endDate||undefined,status:b.status||'DRAFT'});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'CONTRACT_CREATED',entityType:'Contract',entityId:item._id,after:item.toObject()});res.status(201).json({item});};

exports.listWorkOrders=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({items:await WorkOrder.find({companyId:c._id}).populate('programId','name code').populate('contractId','number title').sort({createdAt:-1}).lean()});};
exports.createWorkOrder=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!b.programId||!text(b.number))return res.status(400).json({message:'Program and work order number are required.'}); const prog=await Program.findOne({_id:b.programId,companyId:c._id});if(!prog)return res.status(400).json({message:'Invalid program.'});let contract=null;if(b.contractId){contract=await Contract.findOne({_id:b.contractId,companyId:c._id,programId:prog._id});if(!contract)return res.status(400).json({message:'Invalid contract/LOA.'});}const item=await WorkOrder.create({companyId:c._id,programId:prog._id,contractId:contract?._id||null,number:text(b.number),title:text(b.title),loaNumber:contract?.number||text(b.loaNumber),tenderNumber:text(b.tenderNumber),sanctionedQuantity:Number(b.sanctionedQuantity||0),contractValue:Number(b.contractValue||0),currency:b.currency||'INR',startDate:b.startDate||undefined,dueDate:b.dueDate||undefined,status:b.status||'DRAFT'});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'WORK_ORDER_CREATED',entityType:'WorkOrder',entityId:item._id,after:item.toObject()});res.status(201).json({item});};

exports.listAgencies=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({items:await Organization.find({type:'AGENCY',parentOrganization:c._id}).sort({createdAt:-1}).lean()});};
exports.createAgency=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!text(b.name)||!text(b.code))return res.status(400).json({message:'Agency name and code are required.'});const item=await Organization.create({name:text(b.name),code:text(b.code).toUpperCase(),type:'AGENCY',parentOrganization:c._id,country:b.country||c.country||'India',state:b.state||c.state,status:b.status||'ACTIVE',contact:b.contact||{},address:b.address||{},metadata:{...(b.metadata||{}),onboardedByCompany:true}});await platformAudit(req,{companyId:c._id,organizationId:item._id,action:'AGENCY_CREATED',entityType:'Organization',entityId:item._id,after:item.toObject()});res.status(201).json({item});};

exports.listWorkPackages=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({items:await WorkPackage.find({companyId:c._id}).populate('programId','name code').populate('workOrderId','number title').populate('agencyId','name code').sort({createdAt:-1}).lean()});};
exports.createWorkPackage=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!b.programId||!b.workOrderId||!text(b.code))return res.status(400).json({message:'Program, work order and package code are required.'});const wo=await WorkOrder.findOne({_id:b.workOrderId,companyId:c._id,programId:b.programId});if(!wo)return res.status(400).json({message:'Invalid work order/program combination.'});let agency=null;if(b.agencyId){agency=await Organization.findOne({_id:b.agencyId,type:'AGENCY',parentOrganization:c._id});if(!agency)return res.status(400).json({message:'Invalid agency.'});}const item=await WorkPackage.create({companyId:c._id,programId:b.programId,workOrderId:wo._id,code:text(b.code).toUpperCase(),name:text(b.name),agencyId:agency ? agency._id : null,geography:b.geography||{},assignedQuantity:Number(b.assignedQuantity||0),assignedAt:agency?new Date():undefined,dueDate:b.dueDate||undefined,status:agency?'ASSIGNED':(b.status||'READY'),commercialTerms:b.commercialTerms||{}});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'WORK_PACKAGE_CREATED',entityType:'WorkPackage',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.assignPackage=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const pkg=await WorkPackage.findOne({_id:req.params.id,companyId:c._id});if(!pkg)return res.status(404).json({message:'Work package not found.'});const agency=await Organization.findOne({_id:req.body.agencyId,type:'AGENCY',parentOrganization:c._id,status:'ACTIVE'});if(!agency)return res.status(400).json({message:'Select an active company agency.'});const before=pkg.toObject();pkg.agencyId=agency._id;pkg.assignedAt=new Date();pkg.status='ASSIGNED';await pkg.save();await BeneficiaryContext.updateMany({companyId:c._id,workPackageId:pkg._id},{$set:{agencyId:agency._id,assignedAt:new Date()},$push:{assignmentHistory:{agencyId:agency._id,assignedAt:new Date(),reason:text(req.body.reason)||'Work package assignment'}}});await platformAudit(req,{companyId:c._id,organizationId:agency._id,action:'WORK_PACKAGE_ASSIGNED',entityType:'WorkPackage',entityId:pkg._id,before,after:pkg.toObject()});res.json({item:pkg});};


const assignDefined=(target,body,fields)=>{for(const f of fields)if(body[f]!==undefined)target[f]=body[f];};
const closeEntity=async(req,res,Model,entityType,action)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await Model.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:`${entityType} not found.`});const before=item.toObject();item.status='CLOSED';await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action,entityType,entityId:item._id,before,after:item.toObject()});res.json({item});};

exports.updateProgram=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await Program.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Program not found.'});const before=item.toObject();assignDefined(item,req.body,['name','country','state','authority','scheme','component','financialYear','currency','startDate','endDate','status','milestoneConfig','slaConfig']);if(req.body.code!==undefined)item.code=text(req.body.code).toUpperCase();if(req.body.sanctionedQuantity!==undefined)item.sanctionedQuantity=Number(req.body.sanctionedQuantity||0);if(req.body.contractValue!==undefined)item.contractValue=Number(req.body.contractValue||0);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'PROGRAM_UPDATED',entityType:'Program',entityId:item._id,before,after:item.toObject()});res.json({item});};
exports.closeProgram=(req,res)=>closeEntity(req,res,Program,'Program','PROGRAM_CLOSED');

exports.updateContract=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await Contract.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Contract not found.'});const before=item.toObject();if(req.body.programId!==undefined){const p=await Program.findOne({_id:req.body.programId,companyId:c._id});if(!p)return res.status(400).json({message:'Invalid program.'});item.programId=p._id;}assignDefined(item,req.body,['type','number','title','authority','currency','awardDate','startDate','endDate','status','metadata']);if(req.body.sanctionedQuantity!==undefined)item.sanctionedQuantity=Number(req.body.sanctionedQuantity||0);if(req.body.contractValue!==undefined)item.contractValue=Number(req.body.contractValue||0);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'CONTRACT_UPDATED',entityType:'Contract',entityId:item._id,before,after:item.toObject()});res.json({item});};
exports.closeContract=(req,res)=>closeEntity(req,res,Contract,'Contract','CONTRACT_CLOSED');

exports.updateWorkOrder=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await WorkOrder.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Work order not found.'});const before=item.toObject();if(req.body.programId!==undefined){const p=await Program.findOne({_id:req.body.programId,companyId:c._id});if(!p)return res.status(400).json({message:'Invalid program.'});item.programId=p._id;}if(req.body.contractId!==undefined){if(!req.body.contractId)item.contractId=null;else{const ct=await Contract.findOne({_id:req.body.contractId,companyId:c._id,programId:item.programId});if(!ct)return res.status(400).json({message:'Invalid contract/LOA for this program.'});item.contractId=ct._id;item.loaNumber=ct.number;}}assignDefined(item,req.body,['number','title','loaNumber','tenderNumber','currency','startDate','dueDate','status','metadata']);if(req.body.sanctionedQuantity!==undefined)item.sanctionedQuantity=Number(req.body.sanctionedQuantity||0);if(req.body.contractValue!==undefined)item.contractValue=Number(req.body.contractValue||0);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'WORK_ORDER_UPDATED',entityType:'WorkOrder',entityId:item._id,before,after:item.toObject()});res.json({item});};
exports.closeWorkOrder=(req,res)=>closeEntity(req,res,WorkOrder,'WorkOrder','WORK_ORDER_CLOSED');

exports.updateAgency=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await Organization.findOne({_id:req.params.id,type:'AGENCY',parentOrganization:c._id});if(!item)return res.status(404).json({message:'Agency not found.'});const before=item.toObject();assignDefined(item,req.body,['name','country','state','status','contact','address','metadata']);if(req.body.code!==undefined)item.code=text(req.body.code).toUpperCase();await item.save();await platformAudit(req,{companyId:c._id,organizationId:item._id,action:'AGENCY_UPDATED',entityType:'Organization',entityId:item._id,before,after:item.toObject()});res.json({item});};
exports.archiveAgency=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await Organization.findOne({_id:req.params.id,type:'AGENCY',parentOrganization:c._id});if(!item)return res.status(404).json({message:'Agency not found.'});const activePackages=await WorkPackage.countDocuments({companyId:c._id,agencyId:item._id,status:{$nin:['COMPLETED','CLOSED']}});if(activePackages)return res.status(409).json({message:`Agency has ${activePackages} active work package(s). Reassign or close them before archiving.`});const before=item.toObject();item.status='ARCHIVED';await item.save();await platformAudit(req,{companyId:c._id,organizationId:item._id,action:'AGENCY_ARCHIVED',entityType:'Organization',entityId:item._id,before,after:item.toObject()});res.json({item});};

exports.updateWorkPackage=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await WorkPackage.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Work package not found.'});const before=item.toObject();if(req.body.agencyId!==undefined&&String(req.body.agencyId||'')!==String(item.agencyId||'')){if(!req.body.agencyId){item.agencyId=null;item.assignedAt=undefined;if(!['COMPLETED','CLOSED'].includes(item.status))item.status='READY';}else{const agency=await Organization.findOne({_id:req.body.agencyId,type:'AGENCY',parentOrganization:c._id,status:'ACTIVE'});if(!agency)return res.status(400).json({message:'Select an active company agency.'});item.agencyId=agency._id;item.assignedAt=new Date();if(!['COMPLETED','CLOSED'].includes(item.status))item.status='ASSIGNED';await BeneficiaryContext.updateMany({companyId:c._id,workPackageId:item._id},{$set:{agencyId:agency._id,assignedAt:new Date()},$push:{assignmentHistory:{agencyId:agency._id,assignedAt:new Date(),reason:text(req.body.reason)||'Work package update'}}});}}assignDefined(item,req.body,['name','geography','dueDate','status','commercialTerms']);await item.save();await platformAudit(req,{companyId:c._id,organizationId:item.agencyId||c._id,action:'WORK_PACKAGE_UPDATED',entityType:'WorkPackage',entityId:item._id,before,after:item.toObject()});res.json({item});};
exports.closeWorkPackage=(req,res)=>closeEntity(req,res,WorkPackage,'WorkPackage','WORK_PACKAGE_CLOSED');

exports.downloadBeneficiaryTemplate=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const rows=[{'Beneficiary ID':'APP-0001','Beneficiary Name':'Sample Farmer','Mobile':'9876543210','Aadhaar':'','Scheme':'','Land Address':'','Village':'','Taluka':'','District':'','Division':'','Circle':'','Zone':'','Pump HP':'5'}];const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Beneficiaries');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="opsynq-beneficiary-import-template.xlsx"');res.send(buf);};
exports.downloadImportErrors=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const batch=await ImportBatch.findOne({_id:req.params.id,companyId:c._id,type:'BENEFICIARY_IMPORT'}).lean();if(!batch)return res.status(404).json({message:'Import batch not found.'});const rows=(batch.errors||[]).map(e=>({Row:e.row||'',Beneficiary_ID:e.beneficiaryId||'',Error:e.message||''}));const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{Row:'',Beneficiary_ID:'',Error:'No row errors recorded'}]);const csv=XLSX.utils.sheet_to_csv(ws);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="beneficiary-import-errors-${batch._id}.csv"`);res.send('\ufeff'+csv);};

const rowVal=(row,names)=>{for(const n of names){if(row[n]!==undefined&&text(row[n]))return row[n];}return '';};
exports.importBeneficiaries=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!req.file)return res.status(400).json({message:'Excel file is required.'});const {programId,workOrderId,workPackageId}=req.body;const pkg=await WorkPackage.findOne({_id:workPackageId,companyId:c._id,programId,workOrderId}).lean();if(!pkg)return res.status(400).json({message:'Valid program/work order/work package is required.'});if(!pkg.agencyId)return res.status(400).json({message:'Assign the work package to an agency before importing beneficiaries.'});const hash=crypto.createHash('sha256').update(req.file.buffer).digest('hex');const exists=await ImportBatch.findOne({companyId:c._id,fileHash:hash,type:'BENEFICIARY_IMPORT',status:'COMPLETED'});if(exists)return res.status(409).json({message:'This exact file was already imported.',batchId:exists._id});const wb=XLSX.read(req.file.buffer,{type:'buffer'});const sheet=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{defval:''});const batch=await ImportBatch.create({companyId:c._id,type:'BENEFICIARY_IMPORT',sourceFileName:req.file.originalname,fileHash:hash,status:'PROCESSING',totalRows:rows.length,uploadedBy:req.platformUser._id,metadata:{programId,workOrderId,workPackageId,agencyId:pkg.agencyId}});let success=0,failed=0,skipped=0;const errors=[];for(let i=0;i<rows.length;i++){const row=rows[i];try{const beneficiaryId=text(rowVal(row,['beneficiaryId','Beneficiary ID','BeneficiaryId','Application ID','ApplicationId']));const beneficiaryName=text(rowVal(row,['beneficiaryName','Beneficiary Name','Farmer Name','Name']));if(!beneficiaryId||!beneficiaryName){failed++;errors.push({row:i+2,message:'Beneficiary ID/Application ID and Beneficiary Name are required.'});continue;}const duplicate=await Farmer.findOne({beneficiaryId});if(duplicate){const ctx=await BeneficiaryContext.findOne({farmerId:duplicate._id});if(ctx){skipped++;errors.push({row:i+2,beneficiaryId,message:'Already exists in Opsynq context.'});continue;}}
 const farmer=duplicate||await Farmer.create({beneficiaryId,beneficiaryName,mobile:text(rowVal(row,['mobile','Mobile','Mobile Number'])),alternateMobileNumber:text(rowVal(row,['alternateMobileNumber','Alternate Mobile'])),aadharNo:text(rowVal(row,['aadharNo','Aadhar','Aadhaar'])),scheme:text(rowVal(row,['scheme','Scheme']))||'',landAddress:text(rowVal(row,['landAddress','Land Address','Address'])),village:text(rowVal(row,['village','Village'])),taluka:text(rowVal(row,['taluka','Taluka','Block'])),district:text(rowVal(row,['district','District'])),divisionName:text(rowVal(row,['divisionName','Division'])),circleName:text(rowVal(row,['circleName','Circle'])),zoneName:text(rowVal(row,['zoneName','Zone'])),pumpHP:text(rowVal(row,['pumpHP','Pump HP','HP'])),excelFileName:req.file.originalname,excelUploadDate:new Date()});
 await BeneficiaryContext.create({farmerId:farmer._id,companyId:c._id,programId,workOrderId,workPackageId,agencyId:pkg.agencyId,sourceImportBatchId:batch._id,sourceRowNumber:i+2,sourceAuthority:text(req.body.sourceAuthority),originalData:row,normalizedData:{beneficiaryId,beneficiaryName},validationStatus:'VALID',assignedAt:new Date(),assignmentHistory:[{agencyId:pkg.agencyId,assignedAt:new Date(),reason:'Initial bulk beneficiary import'}]});success++;}catch(err){failed++;errors.push({row:i+2,message:err.message});}}
batch.successRows=success;batch.failedRows=failed;batch.skippedRows=skipped;batch.errors=errors.slice(0,500);batch.status=failed&&success?'PARTIAL':failed&&!success?'FAILED':'COMPLETED';await batch.save();await WorkPackage.updateOne({_id:pkg._id},{$set:{assignedQuantity:await BeneficiaryContext.countDocuments({workPackageId:pkg._id})}});await platformAudit(req,{companyId:c._id,organizationId:pkg.agencyId,action:'BENEFICIARY_BULK_IMPORT',entityType:'ImportBatch',entityId:batch._id,after:{total:rows.length,success,failed,skipped,workPackageId}});res.status(201).json({batchId:batch._id,total:rows.length,success,failed,skipped,status:batch.status,errors:errors.slice(0,100)});};
exports.listImports=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({items:await ImportBatch.find({companyId:c._id,type:'BENEFICIARY_IMPORT'}).sort({createdAt:-1}).limit(100).lean()});};


exports.listBeneficiaries=async(req,res)=>{
 const c=await ensureCompany(req,res);if(!c)return;
 const page=Math.max(1,Number(req.query.page||1)),pageSize=Math.min(100,Math.max(10,Number(req.query.pageSize||50))),q=text(req.query.q),status=text(req.query.status),agencyId=text(req.query.agencyId),district=text(req.query.district),survey=text(req.query.survey);
 const ctxFilter={companyId:c._id};if(agencyId)ctxFilter.agencyId=agencyId;
 if(q||status||district||survey){
  const farmerFilter={};
  if(status)farmerFilter.applicationStatus=status;
  if(district)farmerFilter.district=district;
  if(survey)farmerFilter.inspectionStatus=survey;
  if(q)farmerFilter.$or=[{beneficiaryId:{$regex:q,$options:'i'}},{beneficiaryName:{$regex:q,$options:'i'}},{mobile:{$regex:q,$options:'i'}},{village:{$regex:q,$options:'i'}},{district:{$regex:q,$options:'i'}}];
  const farmers=await Farmer.find(farmerFilter).select('_id').limit(5000).lean();
  ctxFilter.farmerId={$in:farmers.map(x=>x._id)};
 }
 const [total,items]=await Promise.all([
  BeneficiaryContext.countDocuments(ctxFilter),
  BeneficiaryContext.find(ctxFilter).populate('farmerId').populate('agencyId','name code').populate('programId','name code').populate('workPackageId','code name status').sort({updatedAt:-1}).skip((page-1)*pageSize).limit(pageSize).lean()
 ]);
 res.json({items,total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))});
};

exports.getBeneficiaryDetail=async(req,res)=>{
 const c=await ensureCompany(req,res);if(!c)return;
 if(!mongoose.isValidObjectId(req.params.farmerId)) return res.status(400).json({message:'Invalid beneficiary/farmer id.'});
 const ctx=await BeneficiaryContext.findOne({companyId:c._id,farmerId:req.params.farmerId}).populate('farmerId').populate('companyId','name code').populate('agencyId','name code contact address').populate('programId','name code authority scheme component').populate('workOrderId','number title status dueDate').populate('workPackageId','code name status dueDate geography').lean();
 if(!ctx)return res.status(404).json({message:'Beneficiary not found in this company.'});
 const farmerId=ctx.farmerId?._id||ctx.farmerId;
 const [assets,materialIssues,serviceCases,compliance,evidenceRequirements,evidenceSubmissions]=await Promise.all([
  InstalledAsset.find({companyId:c._id,farmerId}).populate('itemId','sku name category installationRole').populate('technicianUserId','username mobile').sort({installedAt:-1}).lean(),
  MaterialIssue.find({companyId:c._id,farmerId}).populate('technicianUserId','username mobile').sort({issuedAt:-1}).lean(),
  ServiceCase.find({companyId:c._id,farmerId}).sort({openedAt:-1}).lean(),
  ComplianceRecord.find({companyId:c._id,farmerId}).sort({createdAt:-1}).lean(),
  EvidenceRequirement.find({companyId:c._id,isActive:true,$or:[{programId:null},{programId:ctx.programId?._id||ctx.programId}]}).sort({stage:1,sortOrder:1}).lean(),
  EvidenceSubmission.find({companyId:c._id,farmerId}).lean()
 ]);
 const submissionByRequirement=new Map(evidenceSubmissions.map(x=>[String(x.requirementId),x]));
 const evidenceChecklist=evidenceRequirements.map(r=>({requirement:r,submission:submissionByRequirement.get(String(r._id))||null}));
 res.json({context:ctx,farmer:ctx.farmerId,assets,materialIssues,serviceCases,compliance,evidenceChecklist});
};
