const mongoose=require('mongoose');
const XLSX=require('xlsx');
const multer=require('multer');
const {cloudinary}=require('../../config/cloudinary');
const Organization=require('../../models/platform/Organization');
const Farmer=require('../../models/Farmer');
const BeneficiaryContext=require('../../models/platform/BeneficiaryContext');
const InstalledAsset=require('../../models/platform/InstalledAsset');
const InventorySerial=require('../../models/platform/InventorySerial');
const ItemMaster=require('../../models/platform/ItemMaster');
const Warehouse=require('../../models/platform/Warehouse');
const InsurancePolicy=require('../../models/platform/InsurancePolicy');
const PDIRecord=require('../../models/platform/PDIRecord');
const ComplianceRecord=require('../../models/platform/ComplianceRecord');
const platformAudit=require('../../utils/platformAudit');

const text=v=>String(v??'').trim();
const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
const ensureCompany=async(req,res)=>{const id=companyIdFor(req);if(!id||!mongoose.isValidObjectId(id)){res.status(400).json({message:'Valid company context is required.'});return null;}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null;}return c;};
const toDate=v=>v?new Date(v):undefined;
const effectiveInsuranceStatus=p=>{if(['CANCELLED','CLAIM_OPEN','CLAIM_SETTLED','DRAFT'].includes(p.status))return p.status;const now=Date.now(),end=new Date(p.endDate).getTime();if(end<now)return'EXPIRED';if(end-now<=30*86400000)return'EXPIRING';return'ACTIVE';};

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:8},fileFilter:(req,file,cb)=>{const ok=['application/pdf','image/jpeg','image/png','image/webp'].includes(file.mimetype);cb(ok?null:new Error('Only PDF and image files are supported.'),ok);}});
exports.insuranceUploadMiddleware=upload.single('file');
exports.pdiUploadMiddleware=upload.array('files',8);
const cloudUpload=(buffer,folder,resourceType='auto')=>new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder,resource_type:resourceType},(err,result)=>err?reject(err):resolve(result));stream.end(buffer);});
exports.uploadInsuranceDocument=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!req.file)return res.status(400).json({message:'Choose an insurance document.'});const result=await cloudUpload(req.file.buffer,`Opsynq/Insurance/${String(c._id)}`);res.status(201).json({file:{url:result.secure_url,publicId:result.public_id,fileName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size}});};
exports.uploadPDIEvidence=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!req.files?.length)return res.status(400).json({message:'Choose at least one PDI evidence file.'});const files=[];for(const file of req.files){const result=await cloudUpload(file.buffer,`Opsynq/PDI/${String(c._id)}`);files.push({url:result.secure_url,publicId:result.public_id,fileName:file.originalname,mimeType:file.mimetype,size:file.size});}res.status(201).json({files});};

exports.listInsurance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const filter={companyId:c._id};if(req.query.status)filter.status=req.query.status;if(req.query.farmerId&&mongoose.isValidObjectId(req.query.farmerId))filter.farmerId=req.query.farmerId;let items=await InsurancePolicy.find(filter).populate('farmerId','beneficiaryId beneficiaryName mobile district village').populate({path:'installedAssetId',populate:{path:'itemId',select:'sku name installationRole'}}).sort({endDate:1,createdAt:-1}).lean();const bulk=[];items=items.map(x=>{const status=effectiveInsuranceStatus(x);if(status!==x.status)bulk.push({updateOne:{filter:{_id:x._id},update:{$set:{status}}}});return{...x,status}});if(bulk.length)await InsurancePolicy.bulkWrite(bulk);res.json({items});};
exports.insuranceRefs=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const contexts=await BeneficiaryContext.find({companyId:c._id}).populate('farmerId','beneficiaryId beneficiaryName mobile district village').sort({createdAt:-1}).limit(2000).lean();const assets=await InstalledAsset.find({companyId:c._id,status:{$in:['ACTIVE','REPLACED']}}).populate('itemId','sku name installationRole').populate('farmerId','beneficiaryId beneficiaryName').sort({installedAt:-1}).limit(3000).lean();res.json({beneficiaries:contexts.map(x=>x.farmerId).filter(Boolean),assets});};
exports.createInsurance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!mongoose.isValidObjectId(b.farmerId)||!text(b.policyNumber)||!text(b.insurer)||!b.startDate||!b.endDate)return res.status(400).json({message:'Farmer, policy number, insurer, start date and end date are required.'});const ctx=await BeneficiaryContext.findOne({companyId:c._id,farmerId:b.farmerId});if(!ctx)return res.status(400).json({message:'Farmer does not belong to this company.'});let asset=null;if(b.installedAssetId){asset=await InstalledAsset.findOne({_id:b.installedAssetId,companyId:c._id,farmerId:b.farmerId});if(!asset)return res.status(400).json({message:'Selected installed asset does not belong to this farmer/company.'});}const item=await InsurancePolicy.create({companyId:c._id,farmerId:b.farmerId,installedAssetId:asset?._id,policyNumber:text(b.policyNumber),referenceNumber:text(b.referenceNumber),insurer:text(b.insurer),policyType:b.policyType||'COMPREHENSIVE',coverageAmount:Number(b.coverageAmount||0),premiumAmount:Number(b.premiumAmount||0),currency:b.currency||'INR',startDate:toDate(b.startDate),endDate:toDate(b.endDate),status:b.status||'ACTIVE',documentUrl:text(b.documentUrl),documentFileName:text(b.documentFileName),notes:text(b.notes),metadata:b.metadata||{},createdBy:req.platformUser._id});item.status=effectiveInsuranceStatus(item);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'INSURANCE_POLICY_CREATED',entityType:'InsurancePolicy',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updateInsurance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid insurance policy id.'});const item=await InsurancePolicy.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Insurance policy not found.'});const before=item.toObject();for(const key of ['referenceNumber','insurer','policyType','currency','status','documentUrl','documentFileName','claimNumber','claimStatus','notes'])if(req.body[key]!==undefined)item[key]=req.body[key];for(const key of ['coverageAmount','premiumAmount'])if(req.body[key]!==undefined)item[key]=Number(req.body[key]||0);for(const key of ['startDate','endDate','claimOpenedAt','claimSettledAt'])if(req.body[key]!==undefined)item[key]=req.body[key]?new Date(req.body[key]):undefined;if(req.body.metadata!==undefined)item.metadata=req.body.metadata||{};item.status=effectiveInsuranceStatus(item);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'INSURANCE_POLICY_UPDATED',entityType:'InsurancePolicy',entityId:item._id,before,after:item.toObject()});res.json({item});};

exports.pdiRefs=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const [serials,items,warehouses,agencies]=await Promise.all([InventorySerial.find({companyId:c._id,status:{$in:['AVAILABLE','ALLOCATED','AGENCY_STOCK','RETURNED','REJECTED','DAMAGED']}}).populate('itemId','sku name brand model manufacturer').sort({createdAt:-1}).limit(4000).lean(),ItemMaster.find({companyId:c._id,isActive:true}).sort({name:1}).lean(),Warehouse.find({companyId:c._id,isActive:true}).sort({name:1}).lean(),Organization.find({type:'AGENCY',parentOrganization:c._id,status:'ACTIVE'}).sort({name:1}).lean()]);res.json({serials,items,warehouses,agencies});};
exports.listPDI=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const filter={companyId:c._id};if(req.query.result)filter.result=req.query.result;if(req.query.disposition)filter.disposition=req.query.disposition;const items=await PDIRecord.find(filter).populate('itemId','sku name brand model installationRole').populate('inventorySerialId','serialNumber barcodeValue status').populate('warehouseId','code name').populate('agencyId','code name').populate('inspectedBy','name role').sort({inspectionDate:-1}).lean();res.json({items});};
exports.createPDI=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!text(b.pdiNumber)||!mongoose.isValidObjectId(b.inventorySerialId))return res.status(400).json({message:'PDI number and inventory serial are required.'});const serial=await InventorySerial.findOne({_id:b.inventorySerialId,companyId:c._id}).populate('itemId');if(!serial)return res.status(400).json({message:'Serial not found in this company.'});const item=await PDIRecord.create({companyId:c._id,pdiNumber:text(b.pdiNumber).toUpperCase(),itemId:serial.itemId._id,inventorySerialId:serial._id,supplierName:text(b.supplierName),brand:text(b.brand)||serial.itemId.brand,model:text(b.model)||serial.itemId.model,inspectionDate:toDate(b.inspectionDate)||new Date(),inspectedBy:req.platformUser._id,result:b.result||'PENDING',checklist:Array.isArray(b.checklist)?b.checklist:[],evidenceUrls:Array.isArray(b.evidenceUrls)?b.evidenceUrls:[],certificateUrl:text(b.certificateUrl),disposition:b.disposition||'NOT_DECIDED',warehouseId:mongoose.isValidObjectId(b.warehouseId)?b.warehouseId:serial.warehouseId,agencyId:mongoose.isValidObjectId(b.agencyId)?b.agencyId:serial.agencyId,notes:text(b.notes),metadata:b.metadata||{}});if(item.result==='FAIL'&&serial.status==='AVAILABLE'){serial.status='REJECTED';await serial.save();}await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'PDI_RECORD_CREATED',entityType:'PDIRecord',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updatePDI=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid PDI id.'});const item=await PDIRecord.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'PDI record not found.'});const before=item.toObject();for(const key of ['supplierName','brand','model','result','certificateUrl','disposition','notes'])if(req.body[key]!==undefined)item[key]=req.body[key];if(req.body.inspectionDate!==undefined)item.inspectionDate=new Date(req.body.inspectionDate);if(Array.isArray(req.body.checklist))item.checklist=req.body.checklist;if(Array.isArray(req.body.evidenceUrls))item.evidenceUrls=req.body.evidenceUrls;if(mongoose.isValidObjectId(req.body.warehouseId))item.warehouseId=req.body.warehouseId;if(mongoose.isValidObjectId(req.body.agencyId))item.agencyId=req.body.agencyId;await item.save();const serial=await InventorySerial.findOne({_id:item.inventorySerialId,companyId:c._id});if(serial&&item.result==='FAIL'&&serial.status==='AVAILABLE'){serial.status='REJECTED';await serial.save();}await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'PDI_RECORD_UPDATED',entityType:'PDIRecord',entityId:item._id,before,after:item.toObject()});res.json({item});};

const contextsFor=async companyId=>BeneficiaryContext.find({companyId}).populate('farmerId').populate('agencyId','name code').populate('programId','name code scheme component').populate('workPackageId','code name geography').lean();
async function reportRows(companyId,type,query={}){
 const contexts=await contextsFor(companyId);let rows=[];
 if(type==='district-agency-synopsis'){
  const map=new Map();for(const x of contexts){const f=x.farmerId;if(!f)continue;const district=f.district||x.workPackageId?.geography?.district||'Unspecified',agency=x.agencyId?.name||'Unassigned',key=`${district}||${agency}`,r=map.get(key)||{District:district,Agency:agency,Agency_Code:x.agencyId?.code||'',Beneficiaries:0,Survey_Pending:0,Survey_Completed:0,Ready_For_Installation:0,Installation_Completed:0,Complaints:0};r.Beneficiaries++;if(f.inspectionStatus==='Completed')r.Survey_Completed++;else r.Survey_Pending++;if(f.applicationStatus==='Ready for Installation')r.Ready_For_Installation++;if(['Installation Completed','Closed','Complaint Raised'].includes(f.applicationStatus))r.Installation_Completed++;if(f.applicationStatus==='Complaint Raised'||f.complaintStatus==='Open'||f.complaintStatus==='In Progress')r.Complaints++;map.set(key,r);}rows=[...map.values()].sort((a,b)=>a.District.localeCompare(b.District)||a.Agency.localeCompare(b.Agency));
 }else if(type==='asset-imei-mapping'){
  const assets=await InstalledAsset.find({companyId}).populate('farmerId').populate('itemId','sku name brand model installationRole').populate('agencyId','name code').sort({installedAt:-1}).lean();rows=assets.map(a=>({Application_Number:a.farmerId?.beneficiaryId||'',Beneficiary_Name:a.farmerId?.beneficiaryName||'',District:a.farmerId?.district||'',Agency:a.agencyId?.name||'',Asset_Role:a.assetRole||'',SKU:a.itemId?.sku||'',Item:a.itemId?.name||'',Brand:a.itemId?.brand||'',Model:a.itemId?.model||'',Serial_Number:a.serialNumber||'',IMEI:a.assetRole==='CONTROLLER'?(a.farmerId?.imeiNoUnique||''):'',Installed_At:a.installedAt?new Date(a.installedAt).toISOString():'',Status:a.status||''}));
 }else if(type==='jcr-office'){
  rows=contexts.map(x=>{const f=x.farmerId||{};return{Application_Number:f.beneficiaryId||'',Beneficiary_Name:f.beneficiaryName||'',District:f.district||'',Taluka:f.taluka||'',Village:f.village||'',Scheme:f.scheme||'',Component:x.programId?.component||'',Pump_HP:f.pumpHP||'',Survey_Date:f.surveyDate?new Date(f.surveyDate).toISOString().slice(0,10):'',Survey_Status:f.inspectionStatus||'',Installation_Status:f.applicationStatus||'',Installation_Date:f.installationCompletionDate?new Date(f.installationCompletionDate).toISOString().slice(0,10):'',Pump_Serial:f.pumpNoUnique||'',Motor_Serial:f.motorNoUnique||'',Controller_Serial:f.controllerNoUnique||'',IMEI:f.imeiNoUnique||'',Agency:x.agencyId?.name||'',Work_Package:x.workPackageId?.code||''}});
 }else if(type==='jcr-installer'){
  rows=contexts.map(x=>{const f=x.farmerId||{};return{Installer:x.agencyId?.name||'',Installer_Code:x.agencyId?.code||'',Application_Number:f.beneficiaryId||'',Beneficiary_Name:f.beneficiaryName||'',District:f.district||'',Village:f.village||'',Pump_HP:f.pumpHP||'',Material_Status:f.materialReceivedConfirmationYesNo||'',Dispatch_Date:f.materialDispatchDate?new Date(f.materialDispatchDate).toISOString().slice(0,10):'',Installation_Status:f.applicationStatus||'',Installation_Date:f.installationCompletionDate?new Date(f.installationCompletionDate).toISOString().slice(0,10):'',Pump_Serial:f.pumpNoUnique||'',Motor_Serial:f.motorNoUnique||'',Controller_Serial:f.controllerNoUnique||'',IMEI:f.imeiNoUnique||''}});
 }else throw Object.assign(new Error('Unknown report type.'),{status:404});
 if(query.district)rows=rows.filter(r=>String(r.District||'').toLowerCase()===String(query.district).toLowerCase());if(query.agency)rows=rows.filter(r=>String(r.Agency||r.Installer||'').toLowerCase().includes(String(query.agency).toLowerCase()));return rows;
}
const reportMeta={
 'district-agency-synopsis':{title:'District × Agency Synopsis',file:'district-agency-synopsis'},
 'asset-imei-mapping':{title:'Asset & IMEI Mapping',file:'asset-imei-mapping'},
 'jcr-office':{title:'JCR Office Report',file:'jcr-office-report'},
 'jcr-installer':{title:'JCR Installer Report',file:'jcr-installer-report'}
};
exports.reportCatalog=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({reports:Object.entries(reportMeta).map(([id,x])=>({id,...x,formats:['CSV','XLSX']}))});};
exports.previewReport=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!reportMeta[req.params.type])return res.status(404).json({message:'Report type not found.'});const rows=await reportRows(c._id,req.params.type,req.query);res.json({report:{id:req.params.type,...reportMeta[req.params.type]},rows:rows.slice(0,250),total:rows.length,previewLimit:250});};
exports.exportReport=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const meta=reportMeta[req.params.type];if(!meta)return res.status(404).json({message:'Report type not found.'});const rows=await reportRows(c._id,req.params.type,req.query),format=String(req.query.format||'xlsx').toLowerCase();const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{Message:'No records matched the selected filters.'}]);if(format==='csv'){const csv=XLSX.utils.sheet_to_csv(ws);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${meta.file}.csv"`);return res.send('\ufeff'+csv);}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${meta.file}.xlsx"`);res.send(buf);};
