const mongoose=require('mongoose');
const XLSX=require('xlsx');
const multer=require('multer');
const {cloudinary}=require('../../config/cloudinary');
const Organization=require('../../models/platform/Organization');
const Farmer=require('../../models/Farmer');
const BeneficiaryContext=require('../../models/platform/BeneficiaryContext');
const InstalledAsset=require('../../models/platform/InstalledAsset');
const InventorySerial=require('../../models/platform/InventorySerial');
const ItemMaster=require('../../models/platform/ItemMaster');
const Warehouse=require('../../models/platform/Warehouse');
const InsurancePolicy=require('../../models/platform/InsurancePolicy');
const PDIRecord=require('../../models/platform/PDIRecord');
const ComplianceRecord=require('../../models/platform/ComplianceRecord');
const platformAudit=require('../../utils/platformAudit');
const {REPORTS,catalog:reportCatalogItems,rowsFor:buildReportRows,dateWindow,sanitizeRows}=require('../../utils/reportingService');

const text=v=>String(v??'').trim();
const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
const ensureCompany=async(req,res)=>{const id=companyIdFor(req);if(!id||!mongoose.isValidObjectId(id)){res.status(400).json({message:'Valid company context is required.'});return null;}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null;}return c;};
const toDate=v=>v?new Date(v):undefined;
const effectiveInsuranceStatus=p=>{if(['CANCELLED','CLAIM_OPEN','CLAIM_SETTLED','DRAFT'].includes(p.status))return p.status;const now=Date.now(),end=new Date(p.endDate).getTime();if(end<now)return'EXPIRED';if(end-now<=30*86400000)return'EXPIRING';return'ACTIVE';};

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:8},fileFilter:(req,file,cb)=>{const ok=['application/pdf','image/jpeg','image/png','image/webp'].includes(file.mimetype);cb(ok?null:new Error('Only PDF and image files are supported.'),ok);}});
exports.insuranceUploadMiddleware=upload.single('file');
exports.pdiUploadMiddleware=upload.array('files',8);
const cloudUpload=(buffer,folder,resourceType='auto')=>new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder,resource_type:resourceType},(err,result)=>err?reject(err):resolve(result));stream.end(buffer);});
exports.uploadInsuranceDocument=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!req.file)return res.status(400).json({message:'Choose an insurance document.'});const result=await cloudUpload(req.file.buffer,`Opsynq/Insurance/${String(c._id)}`);res.status(201).json({file:{url:result.secure_url,publicId:result.public_id,fileName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size}});};
exports.uploadPDIEvidence=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!req.files?.length)return res.status(400).json({message:'Choose at least one PDI evidence file.'});const files=[];for(const file of req.files){const result=await cloudUpload(file.buffer,`Opsynq/PDI/${String(c._id)}`);files.push({url:result.secure_url,publicId:result.public_id,fileName:file.originalname,mimeType:file.mimetype,size:file.size});}res.status(201).json({files});};

exports.listInsurance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const filter={companyId:c._id};if(req.query.status)filter.status=req.query.status;if(req.query.farmerId&&mongoose.isValidObjectId(req.query.farmerId))filter.farmerId=req.query.farmerId;let items=await InsurancePolicy.find(filter).populate('farmerId','beneficiaryId beneficiaryName mobile district village').populate({path:'installedAssetId',populate:{path:'itemId',select:'sku name installationRole'}}).sort({endDate:1,createdAt:-1}).lean();const bulk=[];items=items.map(x=>{const status=effectiveInsuranceStatus(x);if(status!==x.status)bulk.push({updateOne:{filter:{_id:x._id},update:{$set:{status}}}});return{...x,status}});if(bulk.length)await InsurancePolicy.bulkWrite(bulk);res.json({items});};
exports.insuranceRefs=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const contexts=await BeneficiaryContext.find({companyId:c._id}).populate('farmerId','beneficiaryId beneficiaryName mobile district village').sort({createdAt:-1}).limit(2000).lean();const assets=await InstalledAsset.find({companyId:c._id,status:{$in:['ACTIVE','REPLACED']}}).populate('itemId','sku name installationRole').populate('farmerId','beneficiaryId beneficiaryName').sort({installedAt:-1}).limit(3000).lean();res.json({beneficiaries:contexts.map(x=>x.farmerId).filter(Boolean),assets});};
exports.createInsurance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!mongoose.isValidObjectId(b.farmerId)||!text(b.policyNumber)||!text(b.insurer)||!b.startDate||!b.endDate)return res.status(400).json({message:'Farmer, policy number, insurer, start date and end date are required.'});const ctx=await BeneficiaryContext.findOne({companyId:c._id,farmerId:b.farmerId});if(!ctx)return res.status(400).json({message:'Farmer does not belong to this company.'});let asset=null;if(b.installedAssetId){asset=await InstalledAsset.findOne({_id:b.installedAssetId,companyId:c._id,farmerId:b.farmerId});if(!asset)return res.status(400).json({message:'Selected installed asset does not belong to this farmer/company.'});}const item=await InsurancePolicy.create({companyId:c._id,farmerId:b.farmerId,installedAssetId:asset?._id,policyNumber:text(b.policyNumber),referenceNumber:text(b.referenceNumber),insurer:text(b.insurer),policyType:b.policyType||'COMPREHENSIVE',coverageAmount:Number(b.coverageAmount||0),premiumAmount:Number(b.premiumAmount||0),currency:b.currency||'INR',startDate:toDate(b.startDate),endDate:toDate(b.endDate),status:b.status||'ACTIVE',documentUrl:text(b.documentUrl),documentFileName:text(b.documentFileName),notes:text(b.notes),metadata:b.metadata||{},createdBy:req.platformUser._id});item.status=effectiveInsuranceStatus(item);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'INSURANCE_POLICY_CREATED',entityType:'InsurancePolicy',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updateInsurance=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid insurance policy id.'});const item=await InsurancePolicy.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Insurance policy not found.'});const before=item.toObject();for(const key of ['referenceNumber','insurer','policyType','currency','status','documentUrl','documentFileName','claimNumber','claimStatus','notes'])if(req.body[key]!==undefined)item[key]=req.body[key];for(const key of ['coverageAmount','premiumAmount'])if(req.body[key]!==undefined)item[key]=Number(req.body[key]||0);for(const key of ['startDate','endDate','claimOpenedAt','claimSettledAt'])if(req.body[key]!==undefined)item[key]=req.body[key]?new Date(req.body[key]):undefined;if(req.body.metadata!==undefined)item.metadata=req.body.metadata||{};item.status=effectiveInsuranceStatus(item);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'INSURANCE_POLICY_UPDATED',entityType:'InsurancePolicy',entityId:item._id,before,after:item.toObject()});res.json({item});};

exports.pdiRefs=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const [serials,items,warehouses,agencies]=await Promise.all([InventorySerial.find({companyId:c._id,status:{$in:['AVAILABLE','ALLOCATED','AGENCY_STOCK','RETURNED','REJECTED','DAMAGED']}}).populate('itemId','sku name brand model manufacturer').sort({createdAt:-1}).limit(4000).lean(),ItemMaster.find({companyId:c._id,isActive:true}).sort({name:1}).lean(),Warehouse.find({companyId:c._id,isActive:true}).sort({name:1}).lean(),Organization.find({type:'AGENCY',parentOrganization:c._id,status:'ACTIVE'}).sort({name:1}).lean()]);res.json({serials,items,warehouses,agencies});};
exports.listPDI=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const filter={companyId:c._id};if(req.query.result)filter.result=req.query.result;if(req.query.disposition)filter.disposition=req.query.disposition;const items=await PDIRecord.find(filter).populate('itemId','sku name brand model installationRole').populate('inventorySerialId','serialNumber barcodeValue status').populate('warehouseId','code name').populate('agencyId','code name').populate('inspectedBy','name role').sort({inspectionDate:-1}).lean();res.json({items});};
exports.createPDI=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!text(b.pdiNumber)||!mongoose.isValidObjectId(b.inventorySerialId))return res.status(400).json({message:'PDI number and inventory serial are required.'});const serial=await InventorySerial.findOne({_id:b.inventorySerialId,companyId:c._id}).populate('itemId');if(!serial)return res.status(400).json({message:'Serial not found in this company.'});const item=await PDIRecord.create({companyId:c._id,pdiNumber:text(b.pdiNumber).toUpperCase(),itemId:serial.itemId._id,inventorySerialId:serial._id,supplierName:text(b.supplierName),brand:text(b.brand)||serial.itemId.brand,model:text(b.model)||serial.itemId.model,inspectionDate:toDate(b.inspectionDate)||new Date(),inspectedBy:req.platformUser._id,result:b.result||'PENDING',checklist:Array.isArray(b.checklist)?b.checklist:[],evidenceUrls:Array.isArray(b.evidenceUrls)?b.evidenceUrls:[],certificateUrl:text(b.certificateUrl),disposition:b.disposition||'NOT_DECIDED',warehouseId:mongoose.isValidObjectId(b.warehouseId)?b.warehouseId:serial.warehouseId,agencyId:mongoose.isValidObjectId(b.agencyId)?b.agencyId:serial.agencyId,notes:text(b.notes),metadata:b.metadata||{}});if(item.result==='FAIL'&&serial.status==='AVAILABLE'){serial.status='REJECTED';await serial.save();}await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'PDI_RECORD_CREATED',entityType:'PDIRecord',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updatePDI=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid PDI id.'});const item=await PDIRecord.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'PDI record not found.'});const before=item.toObject();for(const key of ['supplierName','brand','model','result','certificateUrl','disposition','notes'])if(req.body[key]!==undefined)item[key]=req.body[key];if(req.body.inspectionDate!==undefined)item.inspectionDate=new Date(req.body.inspectionDate);if(Array.isArray(req.body.checklist))item.checklist=req.body.checklist;if(Array.isArray(req.body.evidenceUrls))item.evidenceUrls=req.body.evidenceUrls;if(mongoose.isValidObjectId(req.body.warehouseId))item.warehouseId=req.body.warehouseId;if(mongoose.isValidObjectId(req.body.agencyId))item.agencyId=req.body.agencyId;await item.save();const serial=await InventorySerial.findOne({_id:item.inventorySerialId,companyId:c._id});if(serial&&item.result==='FAIL'&&serial.status==='AVAILABLE'){serial.status='REJECTED';await serial.save();}await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'PDI_RECORD_UPDATED',entityType:'PDIRecord',entityId:item._id,before,after:item.toObject()});res.json({item});};

const reportScope=companyId=>({companyIds:[companyId],agencyIds:[],farmerIds:[]});
const htmlEscape=v=>String(v??'').replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]));
function reportHtml(company,meta,rows,query={}){
 const columns=rows.length?Object.keys(rows[0]):['Message'],data=rows.length?rows:[{Message:'No records matched the selected filters.'}],range=dateWindow(query);
 const th=columns.map(c=>`<th>${htmlEscape(c.replaceAll('_',' '))}</th>`).join(''),body=data.map(r=>`<tr>${columns.map(c=>`<td>${htmlEscape(r[c])}</td>`).join('')}</tr>`).join('');
 return `<!doctype html><html><head><meta charset="utf-8"><title>${htmlEscape(meta.title)}</title><style>body{font-family:Arial,sans-serif;color:#18211f;margin:28px}h1{font-size:22px;margin:0 0 6px}.meta{font-size:12px;color:#5f6b68;margin-bottom:20px}.notice{font-size:11px;border:1px solid #d8dfdc;background:#f7f9f8;padding:10px;margin-bottom:14px}table{border-collapse:collapse;width:100%;font-size:10px}th,td{border:1px solid #d8dfdc;padding:6px;text-align:left;vertical-align:top}th{background:#eef3f1;position:sticky;top:0}@media print{body{margin:10mm}.no-print{display:none}table{font-size:8px}thead{display:table-header-group}}</style></head><body><button class="no-print" onclick="window.print()">Print / Save PDF</button><h1>${htmlEscape(meta.title)}</h1><div class="meta">${htmlEscape(company.name)}${company.code?` · ${htmlEscape(company.code)}`:''} · Generated ${new Date().toLocaleString('en-IN')} ${range.from||range.to?`· Period ${range.from?range.from.toLocaleDateString('en-IN'):'Start'} to ${range.to?range.to.toLocaleDateString('en-IN'):'Today'}`:''}</div><div class="notice">Operational / reconciliation report generated from OPSYNQ source records. Statutory filing eligibility and final figures must be validated against the applicable government portal and accounting/tax records.</div><table><thead><tr>${th}</tr></thead><tbody>${body}</tbody></table></body></html>`;
}
exports.reportCatalog=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({reports:reportCatalogItems(),generatedAt:new Date().toISOString()});};
exports.previewReport=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const meta=REPORTS[req.params.type];if(!meta)return res.status(404).json({message:'Report type not found.'});const rows=await buildReportRows(reportScope(c._id),req.params.type,req.query);res.json({report:{id:req.params.type,...meta},rows:rows.slice(0,500),total:rows.length,previewLimit:500,generatedAt:new Date().toISOString(),period:dateWindow(req.query)});};
exports.exportReport=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const meta=REPORTS[req.params.type];if(!meta)return res.status(404).json({message:'Report type not found.'});const rows=await buildReportRows(reportScope(c._id),req.params.type,req.query),format=String(req.query.format||'xlsx').toLowerCase(),file=req.params.type;await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'REPORT_EXPORTED',entityType:'Report',after:{type:req.params.type,format,rows:rows.length,from:req.query.from||'',to:req.query.to||''}});if(format==='html'||format==='print'){res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Disposition',`inline; filename="${file}.html"`);return res.send(reportHtml(c,meta,rows,req.query));}const exportRows=sanitizeRows(rows.length?rows:[{Message:'No records matched the selected filters.'}]),ws=XLSX.utils.json_to_sheet(exportRows);if(format==='csv'){const csv=XLSX.utils.sheet_to_csv(ws);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${file}.csv"`);return res.send('\ufeff'+csv);}const wb=XLSX.utils.book_new(),range=dateWindow(req.query);const cover=XLSX.utils.aoa_to_sheet([['OPSYNQ REPORT'],['Report',meta.title],['Category',meta.category],['Company',c.name],['Company Code',c.code||''],['Generated At',new Date().toISOString()],['Period From',range.from?range.from.toISOString():'' ],['Period To',range.to?range.to.toISOString():'' ],['Rows',rows.length],[],['Notice','Operational/reconciliation export. Validate statutory figures against applicable government portals and accounting/tax records before filing.']]);XLSX.utils.book_append_sheet(wb,cover,'Cover');XLSX.utils.book_append_sheet(wb,ws,'Report');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${file}.xlsx"`);res.send(buf);};
