const ServiceCase=require('../../models/platform/ServiceCase');
const SLARule=require('../../models/platform/SLARule');
const CommercialClaim=require('../../models/platform/CommercialClaim');
const AssetServicePlan=require('../../models/platform/AssetServicePlan');
const InstalledAsset=require('../../models/platform/InstalledAsset');
const AssetLifecycleEvent=require('../../models/platform/AssetLifecycleEvent');
const Program=require('../../models/platform/Program');
const WorkPackage=require('../../models/platform/WorkPackage');
const Organization=require('../../models/platform/Organization');
const platformAudit=require('../../utils/platformAudit');

const text=v=>String(v??'').trim();
const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.params.companyId||req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
const ensureCompany=async(req,res)=>{const id=companyIdFor(req);if(!id){res.status(400).json({message:'Company context is required.'});return null;}const c=await Organization.findOne({_id:id,type:'COMPANY',status:{$ne:'ARCHIVED'}});if(!c){res.status(404).json({message:'Company not found.'});return null;}return c};
const caseNo=()=>`SC-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const claimNo=()=>`CLM-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const slaState=(dueAt,warningHours=4)=>{if(!dueAt)return'NOT_APPLICABLE';const ms=new Date(dueAt)-Date.now();if(ms<0)return'BREACHED';if(ms<=warningHours*3600000)return'DUE_SOON';return'ON_TRACK'};

async function pickRule(companyId,appliesTo,caseType,priority){return SLARule.findOne({companyId,appliesTo,isActive:true,$and:[{$or:[{caseType:{$exists:false}},{caseType:null},{caseType:''},{caseType}]},{$or:[{priority:{$exists:false}},{priority:null},{priority:''},{priority}]}]}).sort({caseType:-1,priority:-1,createdAt:-1}).lean()}
async function refreshServiceSla(doc){if(!doc||['RESOLVED','CLOSED','CANCELLED'].includes(doc.status))return doc;const rule=await pickRule(doc.companyId,'SERVICE_CASE',doc.type,doc.priority);if(rule){if(!doc.dueAt)doc.dueAt=new Date(doc.openedAt.getTime()+rule.targetHours*3600000);doc.slaState=slaState(doc.dueAt,rule.warningHours)}else doc.slaState=slaState(doc.dueAt);await doc.save();return doc}

exports.dashboard=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id};const now=new Date(),soon=new Date(now.getTime()+30*86400000);const [open,breached,critical,resolved30,claimAgg,warrantyExpiring,plansActive,recent]=await Promise.all([
 ServiceCase.countDocuments({...q,status:{$in:['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART']}}),
 ServiceCase.countDocuments({...q,status:{$in:['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART']},$or:[{slaState:'BREACHED'},{dueAt:{$lt:now}}]}),
 ServiceCase.countDocuments({...q,priority:'CRITICAL',status:{$nin:['RESOLVED','CLOSED','CANCELLED']}}),
 ServiceCase.countDocuments({...q,resolvedAt:{$gte:new Date(now.getTime()-30*86400000)}}),
 CommercialClaim.aggregate([{$match:q},{$group:{_id:null,gross:{$sum:'$grossAmount'},eligible:{$sum:'$eligibleAmount'},approved:{$sum:'$approvedAmount'},paid:{$sum:'$paidAmount'},blocked:{$sum:'$blockedAmount'},count:{$sum:1}}}]),
 AssetServicePlan.countDocuments({...q,status:'ACTIVE',endDate:{$gte:now,$lte:soon}}),
 AssetServicePlan.countDocuments({...q,status:'ACTIVE',endDate:{$gte:now}}),
 ServiceCase.find(q).populate('farmerId','beneficiaryName beneficiaryId').populate('installedAssetId','serialNumber assetRole').sort({updatedAt:-1}).limit(8).lean()
 ]);const claims=claimAgg[0]||{gross:0,eligible:0,approved:0,paid:0,blocked:0,count:0};res.json({open,breached,critical,resolved30,warrantyExpiring,plansActive,claims,recent});};

exports.listCases=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id};if(req.query.status)q.status=req.query.status;if(req.query.agencyId)q.agencyId=req.query.agencyId;if(req.query.priority)q.priority=req.query.priority;if(req.query.type)q.type=req.query.type;if(req.query.search){const s=new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');q.$or=[{caseNo:s},{title:s},{description:s}]}const items=await ServiceCase.find(q).populate('farmerId','beneficiaryName beneficiaryId mobile').populate('installedAssetId','serialNumber assetRole warrantyEnd').sort({createdAt:-1}).limit(500);for(const x of items)await refreshServiceSla(x);res.json({items});};
exports.createCase=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!text(b.title))return res.status(400).json({message:'Case title is required.'});let asset=null;if(b.installedAssetId){asset=await InstalledAsset.findOne({_id:b.installedAssetId,companyId:c._id});if(!asset)return res.status(400).json({message:'Installed asset not found in this company.'})}const rule=await pickRule(c._id,'SERVICE_CASE',b.type||'COMPLAINT',b.priority||'MEDIUM');const openedAt=new Date();const dueAt=b.dueAt?new Date(b.dueAt):(rule?new Date(openedAt.getTime()+rule.targetHours*3600000):undefined);const item=await ServiceCase.create({companyId:c._id,agencyId:b.agencyId||asset?.agencyId,farmerId:b.farmerId||asset?.farmerId,installedAssetId:asset?._id,caseNo:caseNo(),type:b.type||'COMPLAINT',priority:b.priority||'MEDIUM',title:text(b.title),description:text(b.description),source:b.source||'COMPANY',openedAt,dueAt,slaState:slaState(dueAt,rule?.warningHours)});if(asset)await AssetLifecycleEvent.create({companyId:c._id,agencyId:item.agencyId,farmerId:item.farmerId,installedAssetId:asset._id,inventorySerialId:asset.inventorySerialId,eventType:'SERVICE_OPENED',reason:item.title,performedByPlatformUser:req.platformUser._id,evidence:{serviceCaseId:String(item._id),caseNo:item.caseNo}});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'SERVICE_CASE_CREATED',entityType:'ServiceCase',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updateCase=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await ServiceCase.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Service case not found.'});const before=item.toObject(),b=req.body;if(b.status)item.status=b.status;if(b.priority)item.priority=b.priority;if(b.resolution!==undefined)item.resolution=text(b.resolution);if(b.description!==undefined)item.description=text(b.description);if(b.assignedToPlatformUser!==undefined)item.assignedToPlatformUser=b.assignedToPlatformUser||null;if(['IN_PROGRESS','ASSIGNED'].includes(item.status)&&!item.firstResponseAt)item.firstResponseAt=new Date();if(item.status==='RESOLVED'&&!item.resolvedAt)item.resolvedAt=new Date();if(item.status==='CLOSED'&&!item.closedAt)item.closedAt=new Date();const closing=!['RESOLVED','CLOSED'].includes(before.status)&&['RESOLVED','CLOSED'].includes(item.status);await refreshServiceSla(item);await item.save();if(closing&&item.installedAssetId)await AssetLifecycleEvent.create({companyId:c._id,agencyId:item.agencyId,farmerId:item.farmerId,installedAssetId:item.installedAssetId,eventType:'SERVICE_CLOSED',reason:item.resolution||item.title,performedByPlatformUser:req.platformUser._id,evidence:{serviceCaseId:String(item._id),caseNo:item.caseNo}});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'SERVICE_CASE_UPDATED',entityType:'ServiceCase',entityId:item._id,before,after:item.toObject()});res.json({item});};

exports.listRules=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;res.json({items:await SLARule.find({companyId:c._id}).populate('programId','name code').sort({createdAt:-1}).lean()});};
exports.createRule=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!text(b.name)||!b.appliesTo||!Number(b.targetHours))return res.status(400).json({message:'Name, appliesTo and targetHours are required.'});const item=await SLARule.create({companyId:c._id,programId:b.programId||null,name:text(b.name),appliesTo:b.appliesTo,caseType:b.caseType||'',priority:b.priority||'',targetHours:Number(b.targetHours),warningHours:Number(b.warningHours||4),isActive:b.isActive!==false,createdBy:req.platformUser._id});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'SLA_RULE_CREATED',entityType:'SLARule',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updateRule=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await SLARule.findOneAndUpdate({_id:req.params.id,companyId:c._id},{$set:req.body},{new:true,runValidators:true});if(!item)return res.status(404).json({message:'SLA rule not found.'});res.json({item});};

exports.listClaims=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const q={companyId:c._id};if(req.query.status)q.status=req.query.status;if(req.query.agencyId){const ids=await WorkPackage.find({companyId:c._id,agencyId:req.query.agencyId}).distinct('_id');q.workPackageId={$in:ids};}res.json({items:await CommercialClaim.find(q).populate('programId','name code').populate('workOrderId','number title').populate({path:'workPackageId',select:'code name agencyId',populate:{path:'agencyId',select:'name code'}}).sort({createdAt:-1}).lean()});};
exports.createClaim=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;if(!b.programId||!text(b.title))return res.status(400).json({message:'Program and claim title are required.'});const p=await Program.findOne({_id:b.programId,companyId:c._id});if(!p)return res.status(400).json({message:'Invalid program.'});const gross=Number(b.grossAmount||0),eligible=Number(b.eligibleAmount||gross),approved=Number(b.approvedAmount||0),paid=Number(b.paidAmount||0);const initialStatus=b.status||'DRAFT';const claimRule=await pickRule(c._id,'CLAIM','','');const submittedAt=initialStatus==='SUBMITTED'?new Date():undefined;const dueAt=submittedAt&&claimRule?new Date(submittedAt.getTime()+claimRule.targetHours*3600000):undefined;const item=await CommercialClaim.create({companyId:c._id,programId:p._id,contractId:b.contractId||null,workOrderId:b.workOrderId||null,workPackageId:b.workPackageId||null,claimNo:text(b.claimNo)||claimNo(),title:text(b.title),status:initialStatus,currency:b.currency||'INR',grossAmount:gross,eligibleAmount:eligible,approvedAmount:approved,paidAmount:paid,blockedAmount:Number(b.blockedAmount||Math.max(0,eligible-approved)),blockedReason:text(b.blockedReason),beneficiaryCount:Number(b.beneficiaryCount||0),notes:text(b.notes),submittedAt,dueAt,slaState:slaState(dueAt,claimRule?.warningHours)});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'CLAIM_CREATED',entityType:'CommercialClaim',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
exports.updateClaim=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const item=await CommercialClaim.findOne({_id:req.params.id,companyId:c._id});if(!item)return res.status(404).json({message:'Claim not found.'});const before=item.toObject(),b=req.body;for(const k of ['status','blockedReason','notes'])if(b[k]!==undefined)item[k]=b[k];for(const k of ['grossAmount','eligibleAmount','approvedAmount','paidAmount','blockedAmount','beneficiaryCount'])if(b[k]!==undefined)item[k]=Number(b[k]||0);if(item.status==='READY'&&!item.readyAt)item.readyAt=new Date();if(item.status==='SUBMITTED'&&!item.submittedAt){item.submittedAt=new Date();const rule=await pickRule(c._id,'CLAIM','','');if(rule&&!item.dueAt)item.dueAt=new Date(item.submittedAt.getTime()+rule.targetHours*3600000);item.slaState=slaState(item.dueAt,rule?.warningHours)}if(['APPROVED','PARTIALLY_APPROVED'].includes(item.status)&&!item.approvedAt)item.approvedAt=new Date();if(item.status==='PAID'&&!item.paidAt)item.paidAt=new Date();if(!['PAID','CANCELLED'].includes(item.status))item.slaState=slaState(item.dueAt);await item.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'CLAIM_UPDATED',entityType:'CommercialClaim',entityId:item._id,before,after:item.toObject()});res.json({item});};

exports.listPlans=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const now=new Date();await AssetServicePlan.updateMany({companyId:c._id,status:{$in:['ACTIVE','EXPIRING']},endDate:{$lt:now}},{$set:{status:'EXPIRED'}});const soon=new Date(now.getTime()+30*86400000);await AssetServicePlan.updateMany({companyId:c._id,status:'ACTIVE',endDate:{$gte:now,$lte:soon}},{$set:{status:'EXPIRING'}});res.json({items:await AssetServicePlan.find({companyId:c._id}).populate({path:'installedAssetId',select:'serialNumber assetRole farmerId itemId',populate:[{path:'farmerId',select:'beneficiaryName beneficiaryId'},{path:'itemId',select:'name sku'}]}).sort({endDate:1}).lean()});};
exports.createPlan=async(req,res)=>{const c=await ensureCompany(req,res);if(!c)return;const b=req.body;const asset=await InstalledAsset.findOne({_id:b.installedAssetId,companyId:c._id});if(!asset)return res.status(400).json({message:'Installed asset is required.'});if(!b.startDate||!b.endDate)return res.status(400).json({message:'Start and end dates are required.'});const item=await AssetServicePlan.create({companyId:c._id,installedAssetId:asset._id,planType:b.planType||'WARRANTY',provider:text(b.provider),referenceNo:text(b.referenceNo),startDate:new Date(b.startDate),endDate:new Date(b.endDate),coverage:text(b.coverage),terms:text(b.terms)});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'SERVICE_PLAN_CREATED',entityType:'AssetServicePlan',entityId:item._id,after:item.toObject()});res.status(201).json({item});};
