const bcrypt=require('bcryptjs');
const PlatformUser=require('../../models/platform/PlatformUser');
const Organization=require('../../models/platform/Organization');
const LegacyUser=require('../../models/User');
const platformAudit=require('../../utils/platformAudit');
const {validatePassword}=require('../../utils/passwordSecurity');

const assignableRoles=['company_admin','operations_manager','program_manager','inventory_manager','procurement_manager','finance_user','quality_user','logistics_manager','viewer'];
const safe=user=>{const x=user.toObject?user.toObject():{...user};delete x.password;return x};
const companyIdFor=req=>req.platformUser.role==='platform_superadmin'?(req.query.companyId||req.body.companyId):String(req.tenant.companyId||'');
async function company(req,res){const id=companyIdFor(req);if(!id)return res.status(400).json({message:'Company context is required.'});const c=await Organization.findOne({_id:id,type:'COMPANY'});if(!c){res.status(404).json({message:'Company not found.'});return null}return c}

exports.list=async(req,res)=>{const c=await company(req,res);if(!c)return;const q=String(req.query.q||'').trim();const filter={organizationId:c._id,role:{$ne:'platform_superadmin'}};if(q)filter.$or=[{name:new RegExp(q,'i')},{email:new RegExp(q,'i')},{mobile:new RegExp(q,'i')},{role:new RegExp(q,'i')}];const items=await PlatformUser.find(filter).select('-password').sort({role:1,name:1}).lean();res.json({items,assignableRoles});};

exports.create=async(req,res)=>{const c=await company(req,res);if(!c)return;const {name,email,mobile,password,role='viewer'}=req.body;if(!name||!email||!mobile||!password||!assignableRoles.includes(role))return res.status(400).json({message:'Name, email, mobile, password and a valid company role are required.'});const passwordCheck=validatePassword(password);if(!passwordCheck.ok)return res.status(400).json({message:passwordCheck.message});const clauses=[{mobile:String(mobile).trim()}];if(email)clauses.push({email:String(email).trim().toLowerCase()});if((await PlatformUser.findOne({$or:clauses}))||(await LegacyUser.findOne({$or:clauses}).select('_id').lean()))return res.status(409).json({message:'Mobile/email already exists.'});const user=await PlatformUser.create({name:String(name).trim(),email:email?String(email).trim().toLowerCase():undefined,mobile:String(mobile).trim(),password:await bcrypt.hash(String(password),12),role,organizationId:c._id,approvalStatus:'APPROVED',isActive:true});await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'COMPANY_TEAM_USER_CREATED',entityType:'PlatformUser',entityId:user._id,after:{name:user.name,email:user.email,mobile:user.mobile,role:user.role,isActive:true}});res.status(201).json({user:safe(user)});};

exports.update=async(req,res)=>{const c=await company(req,res);if(!c)return;const user=await PlatformUser.findOne({_id:req.params.userId,organizationId:c._id,role:{$ne:'platform_superadmin'}});if(!user)return res.status(404).json({message:'Company user not found.'});if(user.role==='company_owner'&&req.platformUser.role!=='platform_superadmin')return res.status(403).json({message:'Company Owner access can only be changed by the Platform Superadmin.'});if(String(user._id)===String(req.platformUser._id)&&req.body.isActive===false)return res.status(409).json({message:'You cannot deactivate your own signed-in account.'});const before={name:user.name,email:user.email,mobile:user.mobile,role:user.role,isActive:user.isActive};const {name,email,mobile,role,isActive,password}=req.body;if(role!==undefined&&!assignableRoles.includes(role))return res.status(400).json({message:'This role cannot be assigned from Company Team & Access.'});if(mobile!==undefined||email!==undefined){const clauses=[];if(mobile)clauses.push({mobile:String(mobile).trim()});if(email)clauses.push({email:String(email).trim().toLowerCase()});if(clauses.length&&((await PlatformUser.findOne({_id:{$ne:user._id},$or:clauses}))||(await LegacyUser.findOne({$or:clauses}).select('_id').lean())))return res.status(409).json({message:'Mobile/email already exists.'});}
if(name!==undefined)user.name=String(name).trim();if(email!==undefined)user.email=email?String(email).trim().toLowerCase():undefined;if(mobile!==undefined)user.mobile=String(mobile).trim();if(role!==undefined)user.role=role;if(typeof isActive==='boolean')user.isActive=isActive;if(password){const passwordCheck=validatePassword(password);if(!passwordCheck.ok)return res.status(400).json({message:passwordCheck.message});user.password=await bcrypt.hash(String(password),12);user.passwordChangedAt=new Date();user.tokenVersion=Number(user.tokenVersion||0)+1;}await user.save();await platformAudit(req,{companyId:c._id,organizationId:c._id,action:'COMPANY_TEAM_USER_UPDATED',entityType:'PlatformUser',entityId:user._id,before,after:{name:user.name,email:user.email,mobile:user.mobile,role:user.role,isActive:user.isActive}});res.json({user:safe(user)});};
