const router=require('express').Router();
const c=require('../../controllers/platform/aiController');
const {protectPlatform,requirePlatformRoles,requireCompanyScope}=require('../../middleware/platform/platformAuth');
const {rolesFor}=require('../../security/platformCapabilities');
const {aiRateLimit}=require('../../middleware/security');
router.use(protectPlatform,requireCompanyScope);
router.get('/status',requirePlatformRoles(...rolesFor('ai.read')),c.status);
router.post('/brief',aiRateLimit,requirePlatformRoles(...rolesFor('ai.run')),c.brief);
router.post('/scan',aiRateLimit,requirePlatformRoles(...rolesFor('automation.run')),c.scan);
module.exports=router;
