const router=require('express').Router();
const c=require('../../controllers/platform/assuranceController');
const {protectPlatform,requirePlatformRoles,requireCompanyScope}=require('../../middleware/platform/platformAuth');
const {rolesFor}=require('../../security/platformCapabilities');
const read=rolesFor('assurance.read');
const assuranceRead=rolesFor('assurance.read');
const approvalRead=rolesFor('approvals.decide');
const write=rolesFor('assurance.write');
const decide=rolesFor('approvals.decide');
router.use(protectPlatform,requireCompanyScope);
router.get('/compliance',requirePlatformRoles(...assuranceRead),c.listCompliance);
router.get('/compliance/summary',requirePlatformRoles(...read),c.complianceSummary);
router.post('/compliance',requirePlatformRoles(...write),c.createCompliance);
router.patch('/compliance/:id',requirePlatformRoles(...write),c.updateCompliance);
router.get('/agency-performance',requirePlatformRoles(...assuranceRead),c.agencyPerformance);
router.get('/action-center',requirePlatformRoles(...assuranceRead),c.actionCenter);
router.get('/approvals',requirePlatformRoles(...approvalRead),c.listApprovals);
router.post('/approvals',requirePlatformRoles(...write),c.createApproval);
router.patch('/approvals/:id/decision',requirePlatformRoles(...decide),c.decideApproval);
router.post('/bulk-masters',requirePlatformRoles(...decide),c.uploadMiddleware,c.bulkMasters);
router.get('/export',requirePlatformRoles(...assuranceRead),c.exportData);
module.exports=router;
