const router = require('express').Router();
const controller = require('../../controllers/platform/authController');
const { protectPlatform } = require('../../middleware/platform/platformAuth');
const { authRateLimit } = require('../../middleware/security');
router.post('/login', authRateLimit, controller.login);
router.post('/register-company', authRateLimit, controller.registerCompany);
router.get('/me', protectPlatform, controller.me);
router.get('/revision', protectPlatform, controller.revision);
router.post('/logout', controller.logout);
module.exports = router;
