const router=require('express').Router();
const multer=require('multer');
const c=require('../../controllers/platform/inventoryController');
const {protectPlatform,requirePlatformRoles,requireCompanyScope}=require('../../middleware/platform/platformAuth');
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>{const ok=/\.(xlsx|xls)$/i.test(file.originalname);cb(ok?null:new Error('Only .xlsx or .xls files are allowed.'),ok);}});
const {rolesFor}=require('../../security/platformCapabilities');
const inventoryRead=rolesFor('inventory.read');
const procurementRead=rolesFor('procurement.read');
const inventoryRoles=rolesFor('inventory.write');
const procurementRoles=rolesFor('procurement.write');
router.use(protectPlatform,requireCompanyScope);
router.get('/dashboard',requirePlatformRoles(...inventoryRead),c.dashboard);
router.get('/items/template',requirePlatformRoles(...inventoryRead),c.downloadItemTemplate);
router.post('/items/scan-prefill',requirePlatformRoles(...inventoryRoles),c.scanItemPrefill);
router.get('/items',requirePlatformRoles(...inventoryRead),c.listItems);router.post('/items',requirePlatformRoles(...inventoryRoles),c.createItem);router.patch('/items/:id',requirePlatformRoles(...inventoryRoles),c.updateItem);router.post('/items/import',requirePlatformRoles(...inventoryRoles),upload.single('file'),c.importItems);
router.get('/warehouses',requirePlatformRoles(...inventoryRead),c.listWarehouses);router.post('/warehouses',requirePlatformRoles(...inventoryRoles),c.createWarehouse);router.patch('/warehouses/:id',requirePlatformRoles(...inventoryRoles),c.updateWarehouse);router.delete('/warehouses/:id',requirePlatformRoles(...inventoryRoles),c.archiveWarehouse);
router.get('/purchase-orders',requirePlatformRoles(...procurementRead),c.listPurchaseOrders);router.post('/purchase-orders',requirePlatformRoles(...procurementRoles),c.createPurchaseOrder);router.post('/purchase-orders/bulk',requirePlatformRoles(...procurementRoles),c.bulkPurchaseOrders);router.patch('/purchase-orders/:id',requirePlatformRoles(...procurementRoles),c.updatePurchaseOrder);router.post('/purchase-orders/:id/cancel',requirePlatformRoles(...procurementRoles),c.cancelPurchaseOrder);
router.post('/receipts',requirePlatformRoles(...procurementRoles),c.receiveGoods);
router.get('/stock',requirePlatformRoles(...inventoryRead),c.listStock);router.post('/transfers',requirePlatformRoles(...inventoryRoles),c.transferStock);
router.get('/scan',requirePlatformRoles(...inventoryRead),c.scanLookup);
router.get('/trace',requirePlatformRoles(...inventoryRead),c.traceAsset);
router.get('/beneficiary-material/:farmerId',requirePlatformRoles(...inventoryRead),c.beneficiaryMaterial);
module.exports=router;
