const router=require('express').Router();
const c=require('../../controllers/platform/regulatoryController');
const {protectPlatform,requirePlatformRoles,requireCompanyScope}=require('../../middleware/platform/platformAuth');
const {rolesFor}=require('../../security/platformCapabilities');
router.use(protectPlatform,requireCompanyScope);
const insuranceRead=requirePlatformRoles(...rolesFor('insurance.read'));
const insuranceWrite=requirePlatformRoles(...rolesFor('insurance.write'));
const pdiRead=requirePlatformRoles(...rolesFor('pdi.read'));
const pdiWrite=requirePlatformRoles(...rolesFor('pdi.write'));
const reportsRead=requirePlatformRoles(...rolesFor('regulatory.read'));
router.post('/insurance/upload',insuranceWrite,c.insuranceUploadMiddleware,c.uploadInsuranceDocument);
router.get('/insurance',insuranceRead,c.listInsurance);
router.get('/insurance/refs',insuranceRead,c.insuranceRefs);
router.post('/insurance',insuranceWrite,c.createInsurance);
router.patch('/insurance/:id',insuranceWrite,c.updateInsurance);
router.post('/pdi/upload',pdiWrite,c.pdiUploadMiddleware,c.uploadPDIEvidence);
router.get('/pdi',pdiRead,c.listPDI);
router.get('/pdi/refs',pdiRead,c.pdiRefs);
router.post('/pdi',pdiWrite,c.createPDI);
router.patch('/pdi/:id',pdiWrite,c.updatePDI);
router.get('/reports',reportsRead,c.reportCatalog);
router.get('/reports/:type/preview',reportsRead,c.previewReport);
router.get('/reports/:type/export',reportsRead,c.exportReport);
module.exports=router;
