import React,{useEffect,useMemo,useRef,useState}from'react';
import{Activity,AlertTriangle,CheckCircle2,Eye,MapPin,RefreshCw,Search,Wifi,WifiOff}from'lucide-react';
import{api,rmsPath,opPath}from'../../../core/api';
import{DetailDrawer,FilterButton,FilterDrawer,InfoGrid,PageHeader,Status}from'../../../components/common';

const fmt=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(n||0));
const dt=v=>v?new Date(v).toLocaleString():'—';
const includes=(v,q)=>String(v||'').toLowerCase().includes(String(q||'').trim().toLowerCase());
const rmsCache=new Map(),rmsInflight=new Map();
const cacheKey=(companyId,path)=>`${companyId||'default'}:${path}`;
const sessionKey=key=>`opsynq.rms.cache:${key}`;
const readCache=key=>{const memory=rmsCache.get(key);if(memory)return memory;try{const saved=JSON.parse(sessionStorage.getItem(sessionKey(key))||'null');if(saved?.data&&Date.now()-Number(saved.ts||0)<600000){const hit={data:saved.data,at:new Date(saved.ts)};rmsCache.set(key,hit);return hit}}catch{}return null};
const writeCache=(key,data)=>{const at=new Date(),entry={data,at};rmsCache.set(key,entry);try{sessionStorage.setItem(sessionKey(key),JSON.stringify({data,ts:at.getTime()}))}catch{}return entry};
const fetchRms=(companyId,path,{force=false}={})=>{const key=cacheKey(companyId,path);if(rmsInflight.has(key))return rmsInflight.get(key);const request=api(rmsPath(companyId,path),{cacheTtl:force?0:30000}).then(data=>writeCache(key,data)).finally(()=>rmsInflight.delete(key));rmsInflight.set(key,request);return request};

function useLoad(companyId,path,deps=[]){
 const key=cacheKey(companyId,path),cached=readCache(key),[data,setData]=useState(cached?.data||null),[error,setError]=useState(''),[loading,setLoading]=useState(!cached),[refreshing,setRefreshing]=useState(false),[updatedAt,setUpdatedAt]=useState(cached?.at||null),[tick,setTick]=useState(0),manualRef=useRef(false);
 useEffect(()=>{let live=true;const cachedNow=readCache(key);if(cachedNow){setData(cachedNow.data);setUpdatedAt(cachedNow.at);setLoading(false)}else if(!data)setLoading(true);const load=async manual=>{if(manual)setRefreshing(true);try{const entry=await fetchRms(companyId,path,{force:manual});if(live){setData(entry.data);setError('');setUpdatedAt(entry.at)}}catch(e){if(live)setError(e.message)}finally{if(live){setLoading(false);if(manual)setRefreshing(false)}}};const manual=manualRef.current;manualRef.current=false;load(manual);const id=setInterval(()=>load(false),30000);return()=>{live=false;clearInterval(id)}},[companyId,path,tick,...deps]);
 return{data,error,loading,refreshing,updatedAt,reload:()=>{manualRef.current=true;setTick(x=>x+1)}};
}

function RmsSkeleton(){return <div className="rms-skeleton" aria-label="Loading RMS data"><div className="rms-skeleton-kpis">{[1,2,3,4,5,6].map(x=><i key={x}/>)}</div><div className="rms-skeleton-panel"/></div>}

function Frame({title,description,loading,refreshing,updatedAt,error,reload,actionError,children}){
 const actions=<><span className="rms-live-state"><i/>{updatedAt?`Live · ${updatedAt.toLocaleTimeString()}`:'Connecting'}</span><button className="btn secondary" disabled={refreshing} onClick={reload}><RefreshCw size={16} className={refreshing?'rms-spin':''}/>{refreshing?'Refreshing…':'Refresh'}</button></>;
 return <div className="rms-workspace"><PageHeader eyebrow="Remote Monitoring System" title={title} text={description} actions={actions}/>{(error||actionError)&&<div className="alert error"><span>{actionError||error}</span><button className="btn secondary small" onClick={reload}>Retry</button></div>}{loading?<RmsSkeleton/>:children}</div>;
}

const Kpi=({label,value,sub,tone=''})=><div className={`rms-stat ${tone}`.trim()}><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>;

function CommandBar({search,setSearch,placeholder='Search…',filterCount=0,onFilters,result}){return <div className="command-bar rms-command-bar"><div className="search-box"><Search size={17}/><input aria-label={placeholder} value={search} onChange={e=>setSearch(e.target.value)} placeholder={placeholder}/></div>{onFilters&&<FilterButton onClick={onFilters} count={filterCount}/>}<span className="result-count">{result}</span></div>}

function DevicesTable({items,onOpen,showCommissioning=false}){return <section className="table-panel rms-table-panel"><div className="table-wrap"><table><thead><tr><th>RMS Device</th><th>Beneficiary</th><th>Agency</th><th>Pump</th><th>Power</th><th>Connectivity</th><th>Health</th>{showCommissioning&&<th>Commissioning</th>}<th>Last seen</th>{onOpen&&<th>Actions</th>}</tr></thead><tbody>{items.map(x=><tr key={x._id} className={onOpen?'clickable-row':''} onClick={()=>onOpen?.(x)}><td><b>{x.externalDeviceId||'Unnamed device'}</b><small>{x.linkedDeviceCount>1?`${x.serialNumber||x.imei||'No serial'} · ${x.linkedDeviceCount} linked records · latest shown`:x.serialNumber||x.imei||'No serial reported'}</small></td><td><b>{x.farmerId?.beneficiaryName||'Unmapped'}</b><small>{x.farmerId?.beneficiaryId||x.mappingStatus||'—'}</small></td><td>{x.agencyId?.name||'—'}</td><td>{String(x.state?.pumpState||'UNKNOWN').replaceAll('_',' ')}</td><td>{x.state?.powerKw==null?'Not available':`${fmt(x.state.powerKw)} kW`}</td><td><Status value={x.state?.communication||'UNKNOWN'}/></td><td><Status value={x.state?.health||'UNKNOWN'}/></td>{showCommissioning&&<td><Status value={x.commissioningStatus||'NOT_STARTED'}/></td>}<td className="rms-nowrap">{dt(x.lastSeenAt)}</td>{onOpen&&<td><button className="mini" onClick={e=>{e.stopPropagation();onOpen(x)}}><Eye size={14}/>View</button></td>}</tr>)}</tbody></table></div></section>}

export function RmsOverviewPage({companyId,onNavigate}){
 const q=useLoad(companyId,'/overview'),d=q.data||{},t=d.totals||{},providers=d.providers||[];
 return <Frame title="RMS Monitoring" description="Live pump health, connectivity, alerts and commissioning from the canonical RMS pipeline." {...q}><div className="rms-stat-grid"><Kpi label="Total devices" value={fmt(t.devices)} sub={`${fmt(t.mapped)} mapped`}/><Kpi label="Online" value={fmt(t.online)} sub="Communicating now" tone="healthy"/><Kpi label="Offline / stale" value={fmt(t.offline)} sub="Needs connectivity review" tone={t.offline?'attention':''}/><Kpi label="Critical" value={fmt(t.critical)} sub="Device health exceptions" tone={t.critical?'critical':''}/><Kpi label="Commissioning pending" value={fmt(t.commissioningPending)} sub="RMS activation pending"/><Kpi label="Active alerts" value={fmt(t.activeAlerts)} sub="Open machine alerts" tone={t.activeAlerts?'attention':''}/></div><div className="rms-overview-grid"><section className="rms-panel"><div className="rms-panel-head"><div><h3>Operational output</h3><p>Current provider-supported operating totals.</p></div></div><div className="rms-metric-grid"><div><small>Active pumps</small><b>{fmt(t.activePumps)}</b></div><div><small>Energy today</small><b>{fmt(t.generationTodayKwh)} kWh</b></div><div><small>Runtime today</small><b>{fmt(t.runtimeTodayMinutes)} min</b></div><div><small>Water discharge</small><b>{fmt(t.waterDischargeLitres)} L</b></div></div></section><section className="rms-panel"><div className="rms-panel-head"><div><h3>Integration health</h3><p>Provider connectivity and latest successful data flow.</p></div></div><div className="rms-provider-list">{providers.length?providers.map(p=><div className="rms-provider-row" key={p.id}><div><b>{p.name}</b><small>{p.mode} · Last data {dt(p.lastDataReceived)}</small></div><Status value={p.status}/></div>):<div className="detail-empty">No provider integrations configured.</div>}</div></section></div><section className="rms-panel"><div className="rms-panel-head"><div><h3>Recent active alerts</h3><p>Machine-detected conditions requiring operational attention.</p></div><button className="btn secondary" onClick={()=>onNavigate?.('rms-alerts')}>View alert center</button></div>{d.recentAlerts?.length?<div className="table-panel rms-table-panel"><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Device</th><th>Beneficiary</th><th>Alert</th><th>Detected</th></tr></thead><tbody>{d.recentAlerts.map(a=><tr key={a._id}><td><Status value={a.severity}/></td><td><b>{a.deviceId?.externalDeviceId||'—'}</b></td><td>{a.farmerId?.beneficiaryName||'Unmapped'}</td><td>{String(a.type||'').replaceAll('_',' ')}</td><td className="rms-nowrap">{dt(a.lastDetectedAt)}</td></tr>)}</tbody></table></div></div>:<div className="rms-empty-state"><CheckCircle2 size={22}/><b>No active RMS alerts</b><span>All monitored assets are clear of open machine alerts.</span></div>}</section></Frame>;
}

export function RmsLiveAssetsPage({companyId,user}){
 const q=useLoad(companyId,'/devices?limit=100'),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[health,setHealth]=useState(''),[communication,setCommunication]=useState(''),[mapping,setMapping]=useState(''),[filters,setFilters]=useState(false),[actionError,setActionError]=useState(''),[detailLoading,setDetailLoading]=useState(false);
 const items=useMemo(()=>(q.data?.items||[]).filter(x=>(!health||x.state?.health===health)&&(!communication||x.state?.communication===communication)&&(!mapping||x.mappingStatus===mapping)&&(!search||[x.externalDeviceId,x.serialNumber,x.imei,x.farmerId?.beneficiaryName,x.farmerId?.beneficiaryId,x.agencyId?.name].some(v=>includes(v,search)))),[q.data,search,health,communication,mapping]);
 const open=async x=>{setActionError('');setDetailLoading(true);try{setSelected(await api(rmsPath(companyId,`/devices/${x._id}`),{cacheTtl:15000}))}catch(e){setActionError(e.message)}finally{setDetailLoading(false)}};
 const filterCount=[health,communication,mapping].filter(Boolean).length;
 return <Frame title="RMS Live Assets" description="Current normalized state for mapped and unmapped RMS devices." actionError={actionError} {...q}><CommandBar search={search} setSearch={setSearch} placeholder="Search device, beneficiary or agency…" onFilters={()=>setFilters(true)} filterCount={filterCount} result={`${fmt(items.length)} of ${fmt(q.data?.total||0)} current assets`}/><FilterDrawer open={filters} close={()=>setFilters(false)} title="RMS asset filters" onReset={()=>{setHealth('');setCommunication('');setMapping('')}}><label>Health<select value={health} onChange={e=>setHealth(e.target.value)}><option value="">All health states</option><option value="HEALTHY">Healthy</option><option value="WARNING">Warning</option><option value="CRITICAL">Critical</option></select></label><label>Connectivity<select value={communication} onChange={e=>setCommunication(e.target.value)}><option value="">All connectivity</option><option value="ONLINE">Online</option><option value="STALE">Stale</option><option value="OFFLINE">Offline</option></select></label><label>Mapping<select value={mapping} onChange={e=>setMapping(e.target.value)}><option value="">All mapping states</option><option value="MAPPED">Mapped</option><option value="UNMAPPED">Unmapped</option></select></label></FilterDrawer>{detailLoading&&<div className="rms-inline-progress">Opening latest device details…</div>}{items.length?<DevicesTable items={items} onOpen={open}/>:<div className="rms-empty-state"><Activity size={22}/><b>No matching RMS assets</b><span>Adjust search or filters to view devices.</span></div>}{selected&&<RmsDeviceDetail companyId={companyId} user={user} data={selected} close={()=>setSelected(null)} reload={()=>{setSelected(null);q.reload()}}/>}</Frame>;
}

function RmsDeviceDetail({companyId,user,data,close,reload}){
 const d=data.device,s=data.state||{},[busy,setBusy]=useState(''),[error,setError]=useState(''),canDemo=['company_owner','company_admin','operations_manager','quality_user','platform_superadmin'].includes(user?.role)&&d.providerId?.mode==='SIMULATED';
 const scenario=async value=>{setBusy(value);setError('');try{await api(rmsPath(companyId,`/demo/devices/${d._id}/scenario`),{method:'POST',body:JSON.stringify({scenario:value})});reload?.()}catch(e){setError(e.message)}finally{setBusy('')}};
 return <DetailDrawer open title={d.externalDeviceId||'RMS device'} subtitle={`${d.serialNumber||d.imei||'No serial'} · ${d.providerId?.name||'RMS provider'}`} close={close}><div className="rms-drawer-status"><Status value={s.health||'UNKNOWN'}/><Status value={s.communication||'UNKNOWN'}/><Status value={s.pumpState||'UNKNOWN'}/></div>{error&&<div className="alert error">{error}</div>}<div className="detail-section"><h3>Current device state</h3><InfoGrid items={[{label:'Beneficiary',value:d.farmerId?.beneficiaryName||'Unmapped'},{label:'Agency',value:d.agencyId?.name},{label:'Assigned technician',value:d.installedAssetId?.technicianUserId?.username||'Unassigned'},{label:'Power',value:s.powerKw==null?'Not available':`${fmt(s.powerKw)} kW`},{label:'Energy today',value:s.energyTodayKwh==null?'Not available':`${fmt(s.energyTodayKwh)} kWh`},{label:'Runtime today',value:s.runtimeTodayMinutes==null?'Not available':`${fmt(s.runtimeTodayMinutes)} min`},{label:'Water flow',value:s.unsupported?.includes('waterFlow')?'Unsupported':s.waterFlowLpm==null?'Not available':`${fmt(s.waterFlowLpm)} L/min`},{label:'Last communication',value:dt(d.lastSeenAt)},{label:'Commissioning',value:String(d.commissioningStatus||'—').replaceAll('_',' ')},{label:'Mapping',value:String(d.mappingStatus||'—').replaceAll('_',' ')},{label:'Active alerts',value:d.activeAlerts||0}]}/></div>{canDemo&&<div className="detail-section"><h3>Demo simulation</h3><p className="detail-help">Simulation controls use the same ingestion, normalization, alert and persistence pipeline as a real provider.</p><div className="rms-demo-actions">{[['HEALTHY_RUNNING','Healthy'],['COMMUNICATION_LOST','Communication loss'],['DRY_RUN','Dry run'],['CONTROLLER_FAULT','Controller fault'],['LOW_PERFORMANCE','Low performance'],['RECOVERY','Recovery']].map(([v,l])=><button className="btn secondary small" key={v} disabled={!!busy} onClick={()=>scenario(v)}>{busy===v?'Applying…':l}</button>)}</div></div>}{(data.linkedDevices||[]).length>1&&<div className="detail-section"><h3>Linked RMS records</h3><p className="detail-help">The list shows the latest record for this beneficiary. All linked RMS devices remain available here for traceability.</p><div className="rms-telemetry-list">{data.linkedDevices.map(x=><div key={x._id}><span>{x.externalDeviceId||'RMS device'}</span><b>{String(x.state?.health||'UNKNOWN').replaceAll('_',' ')}</b><span>{dt(x.lastSeenAt)}</span></div>)}</div></div>}<div className="detail-section"><h3>Recent telemetry</h3>{(data.history||[]).length?<div className="rms-telemetry-list">{(data.history||[]).slice(-20).reverse().map((x,i)=><div key={x._id||i}><span>{new Date(x.telemetryAt).toLocaleTimeString()}</span><b>{x.powerKw==null?'—':`${fmt(x.powerKw)} kW`}</b><span>{String(x.pumpState||'UNKNOWN').replaceAll('_',' ')}</span></div>)}</div>:<div className="detail-empty">No telemetry history available.</div>}</div></DetailDrawer>;
}

export function RmsAlertsPage({companyId,onNavigate}){
 const q=useLoad(companyId,'/alerts?limit=100'),[search,setSearch]=useState(''),[severity,setSeverity]=useState(''),[status,setStatus]=useState(''),[filters,setFilters]=useState(false),[busy,setBusy]=useState(''),[actionError,setActionError]=useState('');
 const items=useMemo(()=>(q.data?.items||[]).filter(a=>(!severity||a.severity===severity)&&(!status||a.status===status)&&(!search||[a.type,a.message,a.deviceId?.externalDeviceId,a.farmerId?.beneficiaryName,a.agencyId?.name].some(v=>includes(v,search)))),[q.data,severity,status,search]);
 const ack=async id=>{setBusy(id);setActionError('');try{await api(rmsPath(companyId,`/alerts/${id}/acknowledge`),{method:'POST',body:'{}'});q.reload()}catch(e){setActionError(e.message)}finally{setBusy('')}};
 return <Frame title="RMS Alert Center" description="Persistent machine alerts, acknowledgement and recovery history." actionError={actionError} {...q}><CommandBar search={search} setSearch={setSearch} placeholder="Search alert, device or beneficiary…" onFilters={()=>setFilters(true)} filterCount={[severity,status].filter(Boolean).length} result={`${fmt(items.length)} alerts`}/><FilterDrawer open={filters} close={()=>setFilters(false)} title="RMS alert filters" onReset={()=>{setSeverity('');setStatus('')}}><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severities</option><option value="CRITICAL">Critical</option><option value="WARNING">Warning</option><option value="INFO">Info</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="RESOLVED">Resolved</option></select></label></FilterDrawer>{items.length?<section className="table-panel rms-table-panel"><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Alert</th><th>Device</th><th>Beneficiary</th><th>Agency</th><th>Assigned technician</th><th>Incident</th><th>Status</th><th>Last detected</th><th>Actions</th></tr></thead><tbody>{items.map(a=><tr key={a._id}><td><Status value={a.severity}/></td><td className="rms-message-cell"><b>{String(a.type||'Alert').replaceAll('_',' ')}</b><small>{a.message||'No additional message'}</small></td><td>{a.deviceId?.externalDeviceId||'—'}</td><td>{a.farmerId?.beneficiaryName||'Unmapped'}</td><td>{a.agencyId?.name||'—'}</td><td>{a.assignedTechnicianUserId?.username||'Unassigned'}</td><td>{a.relatedServiceCaseId?<button className="mini" onClick={()=>onNavigate?.('service-cases')}>{a.relatedServiceCaseId.caseNo||'Open case'}</button>:<span className="muted-action">No incident</span>}</td><td><Status value={a.status}/></td><td className="rms-nowrap">{dt(a.lastDetectedAt)}</td><td>{a.status==='ACTIVE'&&!a.acknowledgedAt?<button className="mini" disabled={busy===a._id} onClick={()=>ack(a._id)}>{busy===a._id?'Saving…':'Acknowledge'}</button>:<span className="muted-action">{a.acknowledgedAt?'Acknowledged':'No action'}</span>}</td></tr>)}</tbody></table></div></section>:<div className="rms-empty-state"><CheckCircle2 size={22}/><b>No matching alerts</b><span>No RMS alerts match the current search and filters.</span></div>}</Frame>;
}

export function RmsHealthPage({companyId}){const q=useLoad(companyId,'/overview'),p=q.data?.providers||[],t=q.data?.totals||{};return <Frame title="Device Health & Connectivity" description="Separate device communication problems from provider integration health." {...q}><div className="rms-stat-grid rms-stat-grid--four"><Kpi label="Online" value={fmt(t.online)} sub="Healthy communication" tone="healthy"/><Kpi label="Offline / stale" value={fmt(t.offline)} sub="Connectivity exceptions" tone={t.offline?'attention':''}/><Kpi label="Warning" value={fmt(t.warning)} sub="Needs monitoring" tone={t.warning?'attention':''}/><Kpi label="Critical" value={fmt(t.critical)} sub="Immediate review" tone={t.critical?'critical':''}/></div><section className="rms-panel"><div className="rms-panel-head"><div><h3>Provider health</h3><p>Integration status and last successful synchronization.</p></div></div><div className="rms-provider-list">{p.length?p.map(x=><div className="rms-provider-row" key={x.id}><div><b>{x.name}</b><small>{x.mode} · Last successful sync {dt(x.lastSuccessfulSync)}</small></div><Status value={x.status}/></div>):<div className="rms-empty-state"><WifiOff size={22}/><b>No providers configured</b><span>RMS provider health will appear here after configuration.</span></div>}</div></section></Frame>}

export function RmsPerformancePage({companyId}){const q=useLoad(companyId,'/overview'),t=q.data?.totals||{};return <Frame title="RMS Performance" description="Available operating output from provider-supported metrics." {...q}><div className="rms-stat-grid rms-stat-grid--four"><Kpi label="Active pumps" value={fmt(t.activePumps)} sub="Currently running"/><Kpi label="Energy today" value={`${fmt(t.generationTodayKwh)} kWh`} sub="Provider-reported generation"/><Kpi label="Runtime today" value={`${fmt(t.runtimeTodayMinutes)} min`} sub="Combined operating time"/><Kpi label="Water discharge" value={`${fmt(t.waterDischargeLitres)} L`} sub="When supported"/></div><section className="rms-panel rms-info-panel"><Activity size={19}/><div><b>Metric availability follows provider capability</b><p>Unsupported metrics remain unavailable instead of being represented as zero. Open Live Assets for device-level telemetry history.</p></div></section></Frame>}

export function RmsMapPage({companyId}){const q=useLoad(companyId,'/devices?limit=100'),[search,setSearch]=useState(''),[health,setHealth]=useState(''),[filters,setFilters]=useState(false);const located=useMemo(()=>(q.data?.items||[]).filter(x=>x.state?.latitude!=null&&x.state?.longitude!=null&&(!health||x.state?.health===health)&&(!search||[x.externalDeviceId,x.farmerId?.beneficiaryName,x.agencyId?.name].some(v=>includes(v,search)))),[q.data,search,health]);return <Frame title="RMS Asset Map" description="Provider-reported GPS coordinates for monitored RMS assets." {...q}><CommandBar search={search} setSearch={setSearch} placeholder="Search located device, beneficiary or agency…" onFilters={()=>setFilters(true)} filterCount={health?1:0} result={`${fmt(located.length)} located assets`}/><FilterDrawer open={filters} close={()=>setFilters(false)} title="Asset map filters" onReset={()=>setHealth('')}><label>Health<select value={health} onChange={e=>setHealth(e.target.value)}><option value="">All health states</option><option value="HEALTHY">Healthy</option><option value="WARNING">Warning</option><option value="CRITICAL">Critical</option></select></label></FilterDrawer>{located.length?<section className="table-panel rms-table-panel"><div className="table-wrap"><table><thead><tr><th>Device</th><th>Beneficiary</th><th>Agency</th><th>Health</th><th>Latitude</th><th>Longitude</th><th>Last seen</th></tr></thead><tbody>{located.map(x=><tr key={x._id}><td><b>{x.externalDeviceId}</b><small>{x.serialNumber||x.imei||'—'}</small></td><td>{x.farmerId?.beneficiaryName||'Unmapped'}</td><td>{x.agencyId?.name||'—'}</td><td><Status value={x.state?.health||'UNKNOWN'}/></td><td>{x.state.latitude}</td><td>{x.state.longitude}</td><td className="rms-nowrap">{dt(x.lastSeenAt)}</td></tr>)}</tbody></table></div></section>:<div className="rms-empty-state"><MapPin size={22}/><b>No located RMS assets</b><span>No device with provider-reported GPS matches the current filters.</span></div>}</Frame>}

export function RmsCommissioningPage({companyId}){const q=useLoad(companyId,'/devices?limit=100'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[filters,setFilters]=useState(false);const items=useMemo(()=>(q.data?.items||[]).filter(x=>x.commissioningStatus!=='COMMISSIONED'&&(!status||x.commissioningStatus===status)&&(!search||[x.externalDeviceId,x.farmerId?.beneficiaryName,x.agencyId?.name].some(v=>includes(v,search)))),[q.data,search,status]);return <Frame title="RMS Commissioning" description="Track RMS activation separately from physical installation status." {...q}><CommandBar search={search} setSearch={setSearch} placeholder="Search pending device, beneficiary or agency…" onFilters={()=>setFilters(true)} filterCount={status?1:0} result={`${fmt(items.length)} pending`}/><FilterDrawer open={filters} close={()=>setFilters(false)} title="Commissioning filters" onReset={()=>setStatus('')}><label>Commissioning status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All pending states</option><option value="NOT_STARTED">Not started</option><option value="PENDING">Pending</option><option value="FAILED">Failed</option></select></label></FilterDrawer>{items.length?<DevicesTable items={items} showCommissioning/>:<div className="rms-empty-state"><CheckCircle2 size={22}/><b>No commissioning pending</b><span>All visible RMS devices are commissioned.</span></div>}</Frame>}

export function RmsMappingPage({companyId}){const q=useLoad(companyId,'/devices?mappingStatus=UNMAPPED&limit=100'),[beneficiaries,setBeneficiaries]=useState([]),[search,setSearch]=useState(''),[pick,setPick]=useState({}),[busy,setBusy]=useState(''),[actionError,setActionError]=useState('');useEffect(()=>{api(opPath(companyId,'/beneficiaries?page=1&pageSize=100')).then(d=>setBeneficiaries(d.items||[])).catch(()=>setBeneficiaries([]))},[companyId]);const rows=useMemo(()=>(q.data?.items||[]).filter(d=>!search||[d.externalDeviceId,d.serialNumber,d.imei,d.providerId?.name].some(v=>includes(v,search))),[q.data,search]);const map=async device=>{const farmerId=pick[device._id];if(!farmerId)return;setBusy(device._id);setActionError('');try{await api(rmsPath(companyId,`/devices/${device._id}/mapping`),{method:'PATCH',body:JSON.stringify({farmerId})});setPick(x=>({...x,[device._id]:''}));q.reload()}catch(e){setActionError(e.message)}finally{setBusy('')}};return <Frame title="RMS Mapping & Reconciliation" description="Resolve unmapped provider devices explicitly. OPSYNQ never guesses uncertain beneficiary ownership." actionError={actionError} {...q}><CommandBar search={search} setSearch={setSearch} placeholder="Search unmapped device or provider…" result={`${fmt(rows.length)} unmapped devices`}/>{rows.length?<section className="table-panel rms-table-panel"><div className="table-wrap"><table><thead><tr><th>Device</th><th>Provider</th><th>Current status</th><th>Map to beneficiary</th><th>Actions</th></tr></thead><tbody>{rows.map(d=><tr key={d._id}><td><b>{d.externalDeviceId}</b><small>{d.serialNumber||d.imei||'—'}</small></td><td>{d.providerId?.name||'Provider'}</td><td><Status value={d.mappingStatus}/></td><td><select className="rms-inline-select" aria-label={`Map ${d.externalDeviceId} to beneficiary`} value={pick[d._id]||''} onChange={e=>setPick(x=>({...x,[d._id]:e.target.value}))}><option value="">Select beneficiary…</option>{beneficiaries.map(x=><option key={x.farmerId?._id} value={x.farmerId?._id}>{x.farmerId?.beneficiaryId||''} · {x.farmerId?.beneficiaryName||'Beneficiary'}</option>)}</select></td><td><button className="btn primary small" disabled={!pick[d._id]||busy===d._id} onClick={()=>map(d)}>{busy===d._id?'Mapping…':'Map device'}</button></td></tr>)}</tbody></table></div></section>:<div className="rms-empty-state"><CheckCircle2 size={22}/><b>No unmapped RMS devices</b><span>All visible devices are reconciled to beneficiaries.</span></div>}</Frame>}

export function RmsIntegrationsPage({companyId}){const q=useLoad(companyId,'/providers'),[busy,setBusy]=useState(''),[actionError,setActionError]=useState('');const test=async id=>{setBusy(id);setActionError('');try{await api(rmsPath(companyId,`/providers/${id}/test`),{method:'POST',body:'{}'});q.reload()}catch(e){setActionError(e.message)}finally{setBusy('')}};const items=q.data?.items||[];return <Frame title="RMS Integrations" description="Provider connection health and safe integration diagnostics. Credentials are never exposed here." actionError={actionError} {...q}>{items.length?<div className="rms-integration-grid">{items.map(p=><section className="rms-integration-card" key={p._id}><div className="rms-integration-head"><div><span>{String(p.type||'Provider').replaceAll('_',' ')}</span><h3>{p.name}</h3><p>{p.mode} · Mapping {p.mappingVersion||'—'}</p></div><Status value={p.status}/></div><div className="rms-integration-meta"><div><small>Last data</small><b>{dt(p.lastDataReceived)}</b></div><div><small>Last successful sync</small><b>{dt(p.lastSuccessfulSync)}</b></div></div><div className="rms-integration-actions"><button className="btn secondary" disabled={busy===p._id} onClick={()=>test(p._id)}>{busy===p._id?'Testing…':'Test connection'}</button></div></section>)}</div>:<div className="rms-empty-state"><Wifi size={22}/><b>No RMS providers configured</b><span>Provider integrations will appear here after configuration.</span></div>}</Frame>}
