import React,{useEffect,useMemo,useState}from'react';
import{Download,Edit3,Plus,Search,UploadCloud,Archive,RefreshCw,Folder,ChevronRight,ArrowLeft,UsersRound,MapPin,Building2,FileText,PackageCheck,Layers3,ClipboardCheck}from'lucide-react';
import {api,opPath,invPath,logPath,servicePath,assurancePath,intelligencePath,API,tokenKey} from '../../../core/api';
import {fmt,get,fmtMoney} from '../../../core/format';
import {PageHeader,Status,Modal,FilterDrawer,FilterButton,DetailDrawer,InfoGrid,MediaGrid,SmartRecordDetails,BeneficiaryLink} from '../../../components/common';
import {SavedViews} from '../../../components/SavedViews';
import {usePermissions} from '../../../core/accessControl.jsx';

const downloadAuth=async(path,filename)=>{const token=localStorage.getItem(tokenKey);const res=await fetch(`${API}${path}`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!res.ok){const b=await res.json().catch(()=>({}));throw new Error(b.message||'Download failed.')}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename||'download';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};

export function CompanyDashboard({companyId,user,onNavigate}){
 const{can}=usePermissions();
 const[d,setD]=useState(null),[svc,setSvc]=useState({claims:{}}),[assure,setAssure]=useState({compliance:{},approvals:0}),[inv,setInv]=useState({}),[log,setLog]=useState({}),[repl,setRepl]=useState({summary:{},items:[]}),[fin,setFin]=useState({company:{},agencies:[]}),[agencyStock,setAgencyStock]=useState({items:[]}),[error,setError]=useState('');
 const role=String(user?.role||'company_admin');
 const load=()=>{setError('');Promise.all([
  api(opPath(companyId,'/dashboard')),
  (can('service.read')||can('finance.read'))?api(servicePath(companyId,'/dashboard')):Promise.resolve({claims:{}}),
  can('assurance.read')?api(assurancePath(companyId,'/compliance/summary')):Promise.resolve({byStatus:[]}),
  can('approvals.decide')?api(assurancePath(companyId,'/approvals?status=PENDING')):Promise.resolve({items:[]}),
  can('inventory.read')?api(invPath(companyId,'/dashboard')):Promise.resolve({}),
  can('logistics.read')?api(logPath(companyId,'/dashboard')):Promise.resolve({}),
  can('procurement.read')?api(intelligencePath(companyId,'/replenishment')):Promise.resolve({summary:{},items:[]}),
  can('finance.read')?api(intelligencePath(companyId,'/finance-control')):Promise.resolve({company:{},agencies:[]}),
  can('logistics.read')?api(intelligencePath(companyId,'/agency-stock')):Promise.resolve({items:[]})
 ]).then(([a,b,c,p,i,l,r,f,as])=>{setD(a);setSvc(b||{claims:{}});setAssure({compliance:c||{byStatus:[]},approvals:p.items?.length||0});setInv(i||{});setLog(l||{});setRepl(r||{summary:{},items:[]});setFin(f||{company:{},agencies:[]});setAgencyStock(as||{items:[]})}).catch(e=>setError(e.message))};
 useEffect(()=>{load()},[companyId,role]);
 const navigate=(page,filter={})=>{try{sessionStorage.setItem(`opsynq.dashboard.filter.${page}`,JSON.stringify(filter))}catch{}onNavigate?.(page)};
 const stageRows=d?.beneficiaryStatus||[],surveyRows=d?.surveyStatus||[],packageRows=d?.packageStatus||[];
 const stageTotal=stageRows.reduce((n,x)=>n+Number(x.count||0),0)||1,totalPackages=packageRows.reduce((n,x)=>n+Number(x.count||0),0)||1;
 const completePackages=Number(packageRows.find(x=>x._id==='COMPLETED')?.count||0),packageCompletion=Math.round(completePackages/totalPackages*100);
 const installations=Number(stageRows.find(x=>x.status==='Installation Completed')?.count||0)+Number(stageRows.find(x=>x.status==='Closed')?.count||0);
 const surveys=Number(surveyRows.find(x=>x.status==='Completed')?.count||0),claims=svc?.claims||{},cmp=Object.fromEntries((assure.compliance?.byStatus||[]).map(x=>[x._id,x.count]));
 const titleMap={company_owner:'Business Command',company_admin:'Administration Command',operations_manager:'Operations Command',program_manager:'Program Delivery',inventory_manager:'Inventory Control',procurement_manager:'Procurement Control',finance_user:'Commercial Control',quality_user:'Quality & Service',logistics_manager:'Logistics Control',viewer:'Executive Summary'};
 const descMap={company_owner:'Company-wide execution and exception visibility.',company_admin:'Company administration, delivery health and pending decisions.',operations_manager:'Field execution, service workload and operational exceptions.',program_manager:'Program delivery, work-package progress and commercial readiness.',inventory_manager:'Stock availability, serialized assets and warehouse exceptions.',procurement_manager:'Purchasing workload, stock coverage and receipt readiness.',finance_user:'Claims, realization, blocked exposure and commercial attention.',quality_user:'Quality exceptions, service SLA, evidence and asset assurance.',logistics_manager:'Shipment movement, fleet readiness and technician material custody.',viewer:'A concise read-only view of company execution.'};
 const kpiByRole={
  company_owner:[['Beneficiaries',d?.beneficiaries,'beneficiary-records'],['Surveys completed',surveys,'beneficiary-records',{survey:'Completed'}],['Installations completed',installations,'beneficiary-records',{status:'Installation Completed'}],['Open service',svc?.open,'service-cases'],['Pending approvals',assure.approvals,'approval-center'],['Blocked claims',fmtMoney(claims.blocked),'claims']],
  company_admin:[['Beneficiaries',d?.beneficiaries,'beneficiary-records'],['Active packages',d?.pendingPackages,'work-packages'],['Installations completed',installations,'beneficiary-records',{status:'Installation Completed'}],['SLA breaches',svc?.breached,'service-cases'],['Pending approvals',assure.approvals,'approval-center'],['Compliance exceptions',(cmp.FAIL||0)+(cmp.IN_REVIEW||0),'compliance']],
  operations_manager:[['Beneficiaries',d?.beneficiaries,'beneficiary-records'],['Surveys completed',surveys,'beneficiary-records',{survey:'Completed'}],['Installations completed',installations,'beneficiary-records',{status:'Installation Completed'}],['Packages in flight',d?.pendingPackages,'work-packages'],['Open service',svc?.open,'service-cases'],['SLA breaches',svc?.breached,'service-cases']],
  program_manager:[['Programs',d?.programs,'programs'],['Work orders',d?.workOrders,'work-orders'],['Packages in flight',d?.pendingPackages,'work-packages'],['Beneficiaries',d?.beneficiaries,'beneficiary-records'],['Package completion',`${packageCompletion}%`,'work-packages'],['Blocked claims',fmtMoney(claims.blocked),'claims']],
  inventory_manager:[['Active items',inv?.items,'item-master'],['On-hand units',inv?.onHand,'stock'],['Critical stock risks',repl?.summary?.critical,'procurement-intelligence'],['Suggested units',repl?.summary?.suggestedUnits,'procurement-intelligence'],['Warehouses',inv?.warehouses,'warehouses'],['Open purchase orders',inv?.openPurchaseOrders,'procurement']],
  procurement_manager:[['Open purchase orders',inv?.openPurchaseOrders,'procurement'],['Critical stock risks',repl?.summary?.critical,'procurement-intelligence'],['Suggested units',repl?.summary?.suggestedUnits,'procurement-intelligence'],['Estimated replenishment',fmtMoney(repl?.summary?.estimatedValue),'procurement-intelligence'],['On-hand units',inv?.onHand,'stock'],['Warehouses',inv?.warehouses,'warehouses']],
  finance_user:[['Receivables',fmtMoney(fin?.company?.receivables),'financial-control'],['Open procurement commitment',fmtMoney(fin?.company?.openProcurementCommitment),'financial-control'],['Inventory book value',fmtMoney(fin?.company?.inventoryBookValue),'financial-control'],['Approved claims',fmtMoney(fin?.company?.claimApproved),'claims'],['Paid claims',fmtMoney(fin?.company?.claimPaid),'claims'],['Blocked claims',fmtMoney(fin?.company?.blocked),'claims']],
  quality_user:[['Open service',svc?.open,'service-cases'],['SLA breaches',svc?.breached,'service-cases'],['Critical cases',svc?.critical,'service-cases'],['Warranty expiring',svc?.warrantyExpiring,'service-plans'],['Compliance exceptions',(cmp.FAIL||0)+(cmp.IN_REVIEW||0),'compliance'],['Beneficiaries',d?.beneficiaries,'beneficiary-records']],
  logistics_manager:[['Shipments',log?.shipments,'shipments'],['In transit',log?.inTransit,'shipments',{status:'IN_TRANSIT'}],['Delivered',log?.delivered,'shipments',{status:'DELIVERED'}],['Agency stock exceptions',(agencyStock?.items||[]).filter(x=>Number(x.damaged||0)+Number(x.missing||0)>0).length,'agency-stock'],['Active drivers',log?.drivers,'fleet'],['Open material issues',log?.openMaterialIssues,'material-issues']],
  viewer:[['Beneficiaries',d?.beneficiaries,'analytics'],['Programs',d?.programs,'analytics'],['Work packages',d?.workPackages,'analytics'],['Execution progress',`${packageCompletion}%`,'analytics']]
 };
 const kpis=(kpiByRole[role]||kpiByRole.viewer).filter(x=>x[1]!==undefined);
 const showExecution=['company_owner','company_admin','operations_manager','program_manager','viewer'].includes(role);
 const showInventory=['inventory_manager','procurement_manager'].includes(role);
 const showFinance=role==='finance_user';
 const showQuality=role==='quality_user';
 const showLogistics=role==='logistics_manager';
 return <div className="command-dashboard">
  <div className="command-dashboard-head"><div><span>{String(role).replaceAll('_',' ')}</span><h1>{titleMap[role]||'Company Dashboard'}</h1><p>{descMap[role]}</p></div><button className="btn secondary compact" onClick={load}><RefreshCw size={15}/> Refresh</button></div>
  {error&&<div className="alert error">{error}</div>}
  <div className={`command-kpis command-kpis--${Math.min(6,kpis.length)}`}>{kpis.map(([label,value,page,filter])=><button key={label} className="command-kpi" onClick={()=>navigate(page,filter||{})}><small>{label}</small><strong>{typeof value==='number'?fmt(value):value??'—'}</strong><span>View details →</span></button>)}</div>
  {showExecution&&<>
   <div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>Execution pipeline</h2><p>Beneficiary distribution across active delivery stages.</p></div><button onClick={()=>navigate('beneficiary-records')}>Open records</button></div><div className="command-bars">{stageRows.sort((a,b)=>b.count-a.count).slice(0,7).map(x=>{const pct=Math.round(Number(x.count||0)/stageTotal*100);return <button key={x.status} onClick={()=>navigate('beneficiary-records',{status:x.status})}><div><span>{x.status}</span><b>{fmt(x.count)}</b></div><i><b style={{width:`${Math.max(4,pct)}%`}}/></i><small>{pct}%</small></button>})}{!stageRows.length&&<div className="empty">No execution data yet.</div>}</div></section>
   <section className="command-panel"><div className="command-panel-head"><div><h2>District execution</h2><p>Progress by operating geography.</p></div>{can('beneficiary.read')&&<button onClick={()=>navigate('geo-operations')}>Open map</button>}</div><div className="command-rank">{(d?.districts||[]).slice(0,6).map((x,i)=><button key={x.district} onClick={()=>navigate('beneficiary-records',{district:x.district})}><em>{i+1}</em><span><b>{x.district}</b><small>{fmt(x.count)} beneficiaries · {fmt(x.agencies)} agencies</small></span><i><b style={{width:`${x.completionPercent}%`}}/></i><strong>{x.completionPercent}%</strong></button>)}{!d?.districts?.length&&<div className="empty">No district execution data yet.</div>}</div></section></div>
   {role!=='viewer'&&<div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>Management attention</h2><p>Exceptions that should be reviewed first.</p></div></div><div className="command-attention">{can('service.read')&&<button onClick={()=>navigate('service-cases')}><span>Open service cases</span><b>{fmt(svc?.open)}</b></button>}{can('service.read')&&<button onClick={()=>navigate('service-cases')}><span>SLA breaches</span><b>{fmt(svc?.breached)}</b></button>}{can('assurance.read')&&<button onClick={()=>navigate('compliance')}><span>Compliance exceptions</span><b>{fmt((cmp.FAIL||0)+(cmp.IN_REVIEW||0))}</b></button>}{can('approvals.decide')&&<button onClick={()=>navigate('approval-center')}><span>Pending approvals</span><b>{fmt(assure.approvals)}</b></button>}{can('finance.read')&&<button onClick={()=>navigate('claims')}><span>Blocked claim value</span><b>{fmtMoney(claims.blocked)}</b></button>}</div></section>
   <section className="command-panel"><div className="command-panel-head"><div><h2>Work package health</h2><p>Portfolio completion and current delivery mix.</p></div><button onClick={()=>navigate('work-packages')}>View packages</button></div><div className="command-progress"><div className="command-progress-ring" style={{'--progress':`${packageCompletion}%`}}><span>{packageCompletion}%</span></div><div>{packageRows.slice(0,6).map(x=><button key={x._id} onClick={()=>navigate('work-packages',{status:x._id})}><span>{String(x._id||'Unknown').replaceAll('_',' ')}</span><b>{fmt(x.count)}</b></button>)}</div></div></section></div>}
  </>}
  {showInventory&&<div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>{role==='procurement_manager'?'Supply readiness':'Serial status'}</h2><p>{role==='procurement_manager'?'Stock coverage supporting purchasing decisions.':'Serialized asset distribution across custody states.'}</p></div><button onClick={()=>navigate(role==='procurement_manager'?'procurement':'scanner')}>Open workspace</button></div><div className="command-bars">{(inv?.serialStatus||[]).slice(0,7).map(x=>{const max=Math.max(1,...(inv?.serialStatus||[]).map(y=>Number(y.count||0)));const pct=Math.round(Number(x.count||0)/max*100);return <button key={x._id} onClick={()=>navigate('scanner')}><div><span>{String(x._id||'Unknown').replaceAll('_',' ')}</span><b>{fmt(x.count)}</b></div><i><b style={{width:`${Math.max(4,pct)}%`}}/></i></button>})}</div></section><section className="command-panel"><div className="command-panel-head"><div><h2>Stock attention</h2><p>Warehouse lines most relevant to replenishment.</p></div><button onClick={()=>navigate('stock')}>Open stock</button></div><div className="command-list">{(inv?.recentStock||[]).slice(0,7).map(x=><button key={x._id} onClick={()=>navigate('stock')}><span><b>{x.itemId?.name||'Item'}</b><small>{x.warehouseId?.name||'Warehouse'} · {x.itemId?.sku||''}</small></span><strong>{fmt(x.onHand)} on hand</strong></button>)}{!inv?.recentStock?.length&&<div className="empty">No stock balances yet.</div>}</div></section></div>}
  {showFinance&&<div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>Claim realization</h2><p>Commercial conversion from eligible to paid value.</p></div><button onClick={()=>navigate('claims')}>Open claims</button></div><div className="finance-stack"><div><span>Eligible</span><b>{fmtMoney(claims.eligible)}</b></div><div><span>Approved</span><b>{fmtMoney(claims.approved)}</b></div><div><span>Paid</span><b>{fmtMoney(claims.paid)}</b></div><div className="attention"><span>Blocked</span><b>{fmtMoney(claims.blocked)}</b></div></div></section><section className="command-panel"><div className="command-panel-head"><div><h2>Commercial attention</h2><p>Actions that can affect realization and cash collection.</p></div></div><div className="command-attention"><button onClick={()=>navigate('claims')}><span>Blocked claim value</span><b>{fmtMoney(claims.blocked)}</b></button><button onClick={()=>navigate('claims')}><span>Total claims</span><b>{fmt(claims.count)}</b></button><button onClick={()=>navigate('insurance')}><span>Insurance register</span><b>Open</b></button><button onClick={()=>navigate('regulatory-reports')}><span>Regulatory reports</span><b>Open</b></button></div></section></div>}
  {['company_owner','company_admin'].includes(role)&&<div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>Supply intelligence</h2><p>Replenishment risks calculated from stock, inbound shipments and open purchase orders.</p></div><button onClick={()=>navigate('procurement-intelligence')}>Open intelligence</button></div><div className="quality-metrics"><div><span>Critical stock risks</span><b>{fmt(repl?.summary?.critical)}</b></div><div><span>Open recommendations</span><b>{fmt(repl?.summary?.open)}</b></div><div><span>Suggested units</span><b>{fmt(repl?.summary?.suggestedUnits)}</b></div><div><span>Estimated value</span><b>{fmtMoney(repl?.summary?.estimatedValue)}</b></div></div></section><section className="command-panel"><div className="command-panel-head"><div><h2>Financial control</h2><p>Procurement commitments, inventory value and receivables.</p></div><button onClick={()=>navigate('financial-control')}>Open finance</button></div><div className="quality-metrics"><div><span>Open procurement commitment</span><b>{fmtMoney(fin?.company?.openProcurementCommitment)}</b></div><div><span>Inventory book value</span><b>{fmtMoney(fin?.company?.inventoryBookValue)}</b></div><div><span>Receivables</span><b>{fmtMoney(fin?.company?.receivables)}</b></div><div><span>Blocked claims</span><b>{fmtMoney(fin?.company?.blocked)}</b></div></div></section></div>}
  {showQuality&&<div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>Quality & service health</h2><p>Cases, SLA pressure and warranty exposure.</p></div><button onClick={()=>navigate('service-cases')}>Open service</button></div><div className="quality-metrics"><div><span>Open cases</span><b>{fmt(svc?.open)}</b></div><div><span>SLA breached</span><b>{fmt(svc?.breached)}</b></div><div><span>Critical</span><b>{fmt(svc?.critical)}</b></div><div><span>Resolved 30d</span><b>{fmt(svc?.resolved30)}</b></div><div><span>Warranty expiring</span><b>{fmt(svc?.warrantyExpiring)}</b></div><div><span>Compliance exceptions</span><b>{fmt((cmp.FAIL||0)+(cmp.IN_REVIEW||0))}</b></div></div></section><section className="command-panel"><div className="command-panel-head"><div><h2>Recent service activity</h2><p>Latest cases requiring quality visibility.</p></div></div><div className="command-list">{(svc?.recent||[]).slice(0,6).map(x=><button key={x._id} onClick={()=>navigate('service-cases',{caseId:x._id})}><span><b>{x.caseNo}</b><small>{x.title}</small></span><Status value={x.status}/></button>)}{!svc?.recent?.length&&<div className="empty">No service activity yet.</div>}</div></section></div>}
  {showLogistics&&<div className="command-grid command-grid--2"><section className="command-panel"><div className="command-panel-head"><div><h2>Shipment movement</h2><p>Current dispatch and delivery position.</p></div><button onClick={()=>navigate('shipments')}>Open shipments</button></div><div className="quality-metrics"><div><span>Total shipments</span><b>{fmt(log?.shipments)}</b></div><div><span>In transit</span><b>{fmt(log?.inTransit)}</b></div><div><span>Delivered</span><b>{fmt(log?.delivered)}</b></div><div><span>Material issues</span><b>{fmt(log?.openMaterialIssues)}</b></div></div></section><section className="command-panel"><div className="command-panel-head"><div><h2>Recent shipments</h2><p>Latest agency movements and fleet assignments.</p></div><button onClick={()=>navigate('fleet')}>Open fleet</button></div><div className="command-list">{(log?.recentShipments||[]).slice(0,6).map(x=><button key={x._id} onClick={()=>navigate('shipments',{shipmentId:x._id})}><span><b>{x.shipmentNo}</b><small>{x.agencyId?.name||'Agency'} · {x.vehicleId?.registrationNo||'Vehicle pending'}</small></span><Status value={x.status}/></button>)}{!log?.recentShipments?.length&&<div className="empty">No shipment activity yet.</div>}</div></section></div>}
 </div>
}

export const resourceConfig={
 programs:{title:'Programs',singular:'Program',eyebrow:'PROGRAM CONTROL',desc:'Define scheme/program context before contracts and allocations.',endpoint:'/programs',cols:[['name','Program'],['code','Code'],['scheme','Scheme'],['financialYear','Financial year'],['status','Status']],fields:[['name','Program name'],['code','Program code'],['authority','Authority'],['scheme','Scheme / initiative'],['component','Component'],['financialYear','Financial year'],['sanctionedQuantity','Sanctioned quantity','number'],['contractValue','Expected value','number'],['status','Status','programStatus']]},
 contracts:{title:'Contracts / LOA',singular:'Contract / LOA',eyebrow:'COMMERCIAL SOURCE',desc:'Create and govern contract, LOA or tender records linked to a program.',endpoint:'/contracts',cols:[['title','Contract'],['number','Number'],['type','Type'],['sanctionedQuantity','Quantity'],['status','Status']],fields:[['programId','Program','program'],['type','Type','contractType'],['number','Contract / LOA number'],['title','Title'],['authority','Authority'],['sanctionedQuantity','Sanctioned quantity','number'],['contractValue','Contract value','number'],['status','Status','programStatus']]},
 'work-orders':{title:'Work Orders',singular:'Work Order',eyebrow:'EXECUTION CONTROL',desc:'Translate awarded work into controlled company work orders.',endpoint:'/work-orders',cols:[['number','Work order'],['title','Title'],['programId.name','Program'],['sanctionedQuantity','Quantity'],['status','Status']],fields:[['programId','Program','program'],['contractId','Contract / LOA','contract'],['number','Work order number'],['title','Title'],['sanctionedQuantity','Sanctioned quantity','number'],['contractValue','Work order value','number'],['status','Status','programStatus']]},
 agencies:{title:'Agencies',singular:'Agency',eyebrow:'EXECUTION NETWORK',desc:'Onboard and govern company agencies without changing their proven ground workflow.',endpoint:'/agencies',cols:[['name','Agency'],['code','Code'],['contact.name','Contact'],['state','State'],['status','Status']],fields:[['name','Agency name'],['code','Agency code'],['state','State / region'],['contact.name','Primary contact'],['contact.mobile','Mobile'],['contact.email','Email'],['status','Status','agencyStatus']]},
};

const entityText=(...parts)=>parts.filter(Boolean).map(x=>typeof x==='object'?Object.values(x).join(' '):String(x)).join(' ').toLowerCase();
const idOf=v=>v&&typeof v==='object'?String(v._id||''):String(v||'');
const PortfolioFolder=({icon:Icon,title,subtitle,metrics,status,onOpen,onEdit,onClose,meta,progress})=><article className="portfolio-folder" onClick={onOpen}><div className="portfolio-folder-icon"><Icon size={20}/></div><div className="portfolio-folder-main"><div className="portfolio-folder-title"><b>{title}</b>{status&&<Status value={status}/>}</div><p>{subtitle||'No additional description'}</p>{meta?.length>0&&<div className="portfolio-folder-meta">{meta.map(([label,value])=><span key={label}><small>{label}</small><b>{value||'—'}</b></span>)}</div>}{Number.isFinite(progress)&&<div className="portfolio-progress"><span><b>{progress}%</b> beneficiary completion</span><i><b style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/></i></div>}<div className="portfolio-folder-metrics">{metrics.map(([label,value])=><span key={label}><strong>{fmt(value||0)}</strong>{label}</span>)}</div></div><div className="portfolio-folder-actions">{onEdit&&<button className="mini" onClick={e=>{e.stopPropagation();onEdit()}}><Edit3 size={13}/> Edit</button>}{onClose&&<button className="mini danger" onClick={e=>{e.stopPropagation();onClose()}}><Archive size={13}/> Close</button>}<ChevronRight size={18}/></div></article>;

const HIERARCHY_PAGES=['programs','contracts','work-orders','work-packages'];
const hierarchyTitle={programs:'Programs',contracts:'Contracts / LOA','work-orders':'Work Orders','work-packages':'Work Packages'};

export function DeliveryPortfolio({companyId,onNavigate,focus='programs'}){
 const{can}=usePermissions(),canManage=can('operations.write');
 const[data,setData]=useState({programs:[],contracts:[],workOrders:[],workPackages:[],agencies:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[folderPage,setFolderPage]=useState(1);
 const[program,setProgram]=useState(null),[contract,setContract]=useState(null),[workOrder,setWorkOrder]=useState(null),[workPackage,setWorkPackage]=useState(null),[edit,setEdit]=useState(null),[beneficiaries,setBeneficiaries]=useState({items:[],total:0,loading:false});
 const[filters,setFilters]=useState({agencyId:'',state:'',district:'',scheme:'',financialYear:'',status:''});
 const contextKey=`opsynq.delivery.context.${companyId}`;
 const load=()=>{setLoading(true);setError('');api(opPath(companyId,'/portfolio')).then(d=>setData(d||{})).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[companyId]);
 const packages=data.workPackages||[],workOrders=data.workOrders||[],contracts=data.contracts||[],programs=data.programs||[],agencies=data.agencies||[];
 useEffect(()=>{if(loading)return;let ctx=null;try{ctx=JSON.parse(sessionStorage.getItem(contextKey)||'null')}catch{};if(ctx?.target===focus){const p=programs.find(x=>String(x._id)===String(ctx.programId||''))||null;const w=workOrders.find(x=>String(x._id)===String(ctx.workOrderId||''))||null;let c=ctx.direct?{_id:'__direct__',_direct:true,number:'Direct / No Contract'}:contracts.find(x=>String(x._id)===String(ctx.contractId||''))||null;if(!c&&w)c=w.contractId?(contracts.find(x=>String(x._id)===idOf(w.contractId))||w.contractId):{_id:'__direct__',_direct:true,number:'Direct / No Contract'};const k=packages.find(x=>String(x._id)===String(ctx.workPackageId||''))||null;setProgram(p);setContract(c);setWorkOrder(w);setWorkPackage(k);return}setProgram(null);setContract(null);setWorkOrder(null);setWorkPackage(null)},[focus,companyId,loading]);
 useEffect(()=>{if(!workPackage){setBeneficiaries({items:[],total:0,loading:false});return}setBeneficiaries(v=>({...v,loading:true}));api(opPath(companyId,`/beneficiaries?workPackageId=${workPackage._id}&page=1&pageSize=25`)).then(d=>setBeneficiaries({items:d.items||[],total:d.total||0,loading:false})).catch(()=>setBeneficiaries({items:[],total:0,loading:false}))},[companyId,workPackage?._id]);
 const states=useMemo(()=>[...new Set(packages.map(x=>x.geography?.state).filter(Boolean))].sort(),[packages]);
 const districts=useMemo(()=>[...new Set(packages.map(x=>x.geography?.district).filter(Boolean))].sort(),[packages]);
 const schemes=useMemo(()=>[...new Set(programs.map(x=>x.scheme).filter(Boolean))].sort(),[programs]);
 const years=useMemo(()=>[...new Set(programs.map(x=>x.financialYear).filter(Boolean))].sort(),[programs]);
 const normalizedQ=q.trim().toLowerCase();
 const pkgPass=p=>(!filters.agencyId||idOf(p.agencyId)===filters.agencyId)&&(!filters.state||p.geography?.state===filters.state)&&(!filters.district||p.geography?.district===filters.district)&&(!filters.status||p.status===filters.status)&&(!normalizedQ||entityText(p.code,p.name,p.status,p.geography,p.agencyId?.name,p.agencyId?.code,p.workOrderId?.number,p.workOrderId?.title,p.programId?.name,p.programId?.code).includes(normalizedQ));
 const pkgIds=new Set(packages.filter(pkgPass).map(x=>String(x._id)));
 const woPass=w=>{const descendant=packages.some(p=>idOf(p.workOrderId)===String(w._id)&&pkgIds.has(String(p._id)));const own=!normalizedQ||entityText(w.number,w.title,w.status,w.programId?.name,w.programId?.code,w.contractId?.number,w.contractId?.title).includes(normalizedQ);const geographyActive=filters.agencyId||filters.state||filters.district;return(!filters.status||w.status===filters.status||descendant)&&(!geographyActive||descendant)&&(own||descendant)};
 const woIds=new Set(workOrders.filter(woPass).map(x=>String(x._id)));
 const contractPass=c=>{const descendant=workOrders.some(w=>idOf(w.contractId)===String(c._id)&&woIds.has(String(w._id)));const own=!normalizedQ||entityText(c.number,c.title,c.type,c.status,c.programId?.name,c.programId?.code).includes(normalizedQ);return(!filters.status||c.status===filters.status||descendant)&&(own||descendant)};
 const contractIds=new Set(contracts.filter(contractPass).map(x=>String(x._id)));
 const programPass=p=>{const descendantContract=contracts.some(c=>idOf(c.programId)===String(p._id)&&contractIds.has(String(c._id)));const descendantDirect=workOrders.some(w=>idOf(w.programId)===String(p._id)&&!w.contractId&&woIds.has(String(w._id)));const own=!normalizedQ||entityText(p.name,p.code,p.scheme,p.authority,p.component,p.financialYear,p.status).includes(normalizedQ);return(!filters.scheme||p.scheme===filters.scheme)&&(!filters.financialYear||p.financialYear===filters.financialYear)&&(!filters.status||p.status===filters.status||descendantContract||descendantDirect)&&(own||descendantContract||descendantDirect)};
 const visiblePrograms=programs.filter(programPass);
 const visibleContracts=program?contracts.filter(c=>idOf(c.programId)===String(program._id)&&contractIds.has(String(c._id))):contracts.filter(c=>contractIds.has(String(c._id)));
 const directWos=program?workOrders.filter(w=>idOf(w.programId)===String(program._id)&&!w.contractId&&woIds.has(String(w._id))):[];
 const visibleWos=program&&contract?workOrders.filter(w=>idOf(w.programId)===String(program._id)&&((contract._direct&&!w.contractId)||idOf(w.contractId)===String(contract._id))&&woIds.has(String(w._id))):workOrders.filter(w=>woIds.has(String(w._id)));
 const visiblePackages=workOrder?packages.filter(p=>idOf(p.workOrderId)===String(workOrder._id)&&pkgIds.has(String(p._id))):packages.filter(p=>pkgIds.has(String(p._id)));
 const level=workPackage?'beneficiaries':workOrder?'work-packages':contract?'work-orders':program?'contracts':focus;
 const levelTitle=level==='beneficiaries'?'Beneficiaries':hierarchyTitle[level];
 const statusOptions=useMemo(()=>[...new Set(([...programs,...contracts,...workOrders,...packages]).map(x=>x.status).filter(Boolean))].sort(),[programs,contracts,workOrders,packages]);
 const activeFilters=Object.values(filters).filter(Boolean).length;
 const FOLDER_PAGE_SIZE=24;
 useEffect(()=>setFolderPage(1),[level,q,filters.agencyId,filters.state,filters.district,filters.scheme,filters.financialYear,filters.status]);
 const setContext=(target,next={})=>{try{sessionStorage.setItem(contextKey,JSON.stringify({target,...next}))}catch{}onNavigate?.(target,{__hierarchyDrill:true})};
 const openProgram=x=>{setProgram(x);setContract(null);setWorkOrder(null);setWorkPackage(null);setQ('');setContext('contracts',{programId:x._id})};
 const openContract=x=>{setContract(x);setWorkOrder(null);setWorkPackage(null);setQ('');setContext('work-orders',{programId:program?._id||idOf(x.programId),contractId:x._direct?'':x._id,direct:!!x._direct})};
 const openWorkOrder=x=>{const p=program||programs.find(v=>String(v._id)===idOf(x.programId))||null;const c=x.contractId?(contracts.find(v=>String(v._id)===idOf(x.contractId))||x.contractId):{_id:'__direct__',_direct:true,number:'Direct / No Contract'};setProgram(p);setContract(c);setWorkOrder(x);setWorkPackage(null);setQ('');setContext('work-packages',{programId:p?._id||idOf(x.programId),contractId:c?._direct?'':c?._id||'',direct:!!c?._direct,workOrderId:x._id})};
 const openPackage=x=>{const w=workOrder||workOrders.find(v=>String(v._id)===idOf(x.workOrderId))||x.workOrderId;const p=program||programs.find(v=>String(v._id)===idOf(x.programId))||x.programId;let c=contract;if(!c&&w){c=w.contractId?(contracts.find(v=>String(v._id)===idOf(w.contractId))||w.contractId):{_id:'__direct__',_direct:true,number:'Direct / No Contract'}}setProgram(p);setContract(c);setWorkOrder(w);setWorkPackage(x);setQ('');try{sessionStorage.setItem(contextKey,JSON.stringify({target:'work-packages',programId:idOf(p),contractId:c?._direct?'':idOf(c),direct:!!c?._direct,workOrderId:idOf(w),workPackageId:x._id}))}catch{}};
 const goCrumb=(target,ctx={})=>{setQ('');if(target==='programs'){setProgram(null);setContract(null);setWorkOrder(null);setWorkPackage(null)}if(target==='contracts'){setContract(null);setWorkOrder(null);setWorkPackage(null)}if(target==='work-orders'){setWorkOrder(null);setWorkPackage(null)}if(target==='work-packages')setWorkPackage(null);setContext(target,ctx)};
 const createCurrent=()=>{if(level==='programs')setEdit({kind:'programs',seed:{}});else if(level==='contracts')setEdit({kind:'contracts',seed:{programId:program?._id||''}});else if(level==='work-orders')setEdit({kind:'work-orders',seed:{programId:program?._id||'',contractId:contract?._direct?'':contract?._id||''}});else if(level==='work-packages')setEdit({kind:'work-packages',seed:{programId:program?._id||'',workOrderId:workOrder?._id||''}})};
 const closeEntity=async(kind,item)=>{const cfg=kind==='work-packages'?{endpoint:'/work-packages',singular:'Work package'}:resourceConfig[kind];if(!confirm(`Close ${cfg.singular} “${item.name||item.title||item.number||item.code}”?`))return;try{await api(opPath(companyId,`${cfg.endpoint}/${item._id}`),{method:'DELETE'});load()}catch(e){setError(e.message)}};
 const openBeneficiaryRecords=()=>{if(!workPackage)return;try{sessionStorage.setItem('opsynq.dashboard.filter.beneficiary-records',JSON.stringify({programId:idOf(program),contractId:contract?._direct?'':idOf(contract),workOrderId:idOf(workOrder),workPackageId:workPackage._id,agencyId:idOf(workPackage.agencyId)}))}catch{}onNavigate?.('beneficiary-records')};
 const focusText={programs:'Program → Contract → Work Order → Work Package → Beneficiary. Contract / LOA records stay inside the Program; open folders to follow the full execution chain.',contracts:'All Contract / LOA records remain anchored to their Program. Open one to see its Work Orders and downstream execution.', 'work-orders':'All Work Orders remain traceable to Program and Contract / LOA. Open one to see its Work Packages.', 'work-packages':'All execution packages show agency, geography and beneficiary load. Open a package to see the beneficiary workspace.'}[focus]||'Program delivery hierarchy';
 const currentRows=level==='programs'?visiblePrograms:level==='contracts'?visibleContracts:level==='work-orders'?visibleWos:level==='work-packages'?visiblePackages:beneficiaries.items;
 const folderRows=level==='programs'?visiblePrograms:level==='contracts'?visibleContracts:level==='work-orders'?visibleWos:level==='work-packages'?visiblePackages:[];
 const folderPages=Math.max(1,Math.ceil(folderRows.length/FOLDER_PAGE_SIZE));
 const pageSlice=rows=>rows.slice((folderPage-1)*FOLDER_PAGE_SIZE,folderPage*FOLDER_PAGE_SIZE);
 const pagedPrograms=pageSlice(visiblePrograms),pagedContracts=pageSlice(visibleContracts),pagedWos=pageSlice(visibleWos),pagedPackages=pageSlice(visiblePackages);
 const currentBeneficiaries=level==='programs'?visiblePrograms.reduce((n,x)=>n+Number(x.metrics?.beneficiaries||0),0):level==='contracts'?visibleContracts.reduce((n,x)=>n+Number(x.metrics?.beneficiaries||0),0)+directWos.reduce((n,x)=>n+Number(x.metrics?.beneficiaries||0),0):level==='work-orders'?visibleWos.reduce((n,x)=>n+Number(x.metrics?.beneficiaries||0),0):level==='work-packages'?visiblePackages.reduce((n,x)=>n+Number(x.metrics?.beneficiaries||0),0):beneficiaries.total;
 const activeCount=(currentRows||[]).filter(x=>!['COMPLETED','CLOSED','ARCHIVED'].includes(x.status)).length;
 const crumbs=[{label:'Delivery',target:'programs',ctx:{}},{label:hierarchyTitle[focus],target:focus,ctx:{}}];
 if(program)crumbs.push({label:program.code||program.name,target:'contracts',ctx:{programId:program._id}});
 if(contract)crumbs.push({label:contract._direct?'Direct':contract.number,target:'work-orders',ctx:{programId:idOf(program),contractId:contract._direct?'':contract._id,direct:!!contract._direct}});
 if(workOrder)crumbs.push({label:workOrder.number,target:'work-packages',ctx:{programId:idOf(program),contractId:contract?._direct?'':idOf(contract),direct:!!contract?._direct,workOrderId:workOrder._id}});
 if(workPackage)crumbs.push({label:workPackage.code,target:null});
 const shortCrumbs=crumbs.filter((x,i,a)=>i===0||x.label!==a[i-1]?.label).slice(-4);
 return <><PageHeader eyebrow="DELIVERY PORTFOLIO" title={focus==='programs'?'Programs & Delivery Hierarchy':hierarchyTitle[focus]||'Delivery Portfolio'} text={focusText} actions={canManage&&level!=='beneficiaries'?<button className="btn primary" onClick={createCurrent}><Plus size={16}/> New {level==='programs'?'Program':level==='contracts'?'Contract / LOA':level==='work-orders'?'Work Order':'Work Package'}</button>:null}/>
  <div className="portfolio-breadcrumb compact-trail">{shortCrumbs.map((c,i)=><React.Fragment key={`${c.label}-${i}`}>{i>0&&<ChevronRight size={13}/>} {c.target?<button onClick={()=>goCrumb(c.target,c.ctx)} className={i===shortCrumbs.length-1&&!workPackage?'active':''}>{c.label}</button>:<strong>{c.label}</strong>}</React.Fragment>)}</div>
  <section className="portfolio-level-summary"><div><small>CURRENT VIEW</small><b>{levelTitle}</b><span>{program?`${program.code} · ${program.name}`:'All company delivery records'}</span></div><div><small>RECORDS</small><b>{level==='contracts'?visibleContracts.length+(directWos.length?1:0):(level==='beneficiaries'?beneficiaries.total:(currentRows||[]).length)}</b><span>Matching current search and filters</span></div><div><small>BENEFICIARIES</small><b>{fmt(currentBeneficiaries)}</b><span>Linked to this view</span></div><div><small>ACTIVE / OPEN</small><b>{level==='beneficiaries'?'—':fmt(activeCount)}</b><span>{level==='beneficiaries'?'Use execution status below':'Records still in execution'}</span></div></section>
  <div className="command-bar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${levelTitle.toLowerCase()}, parent records, agency or geography…`}/></div><FilterButton count={activeFilters} onClick={()=>setFiltersOpen(true)}/><span className="result-count">{level==='programs'?visiblePrograms.length:level==='contracts'?visibleContracts.length+(directWos.length?1:0):level==='work-orders'?visibleWos.length:level==='work-packages'?visiblePackages.length:beneficiaries.total} {levelTitle.toLowerCase()}</span></div>
  <FilterDrawer open={filtersOpen} close={()=>setFiltersOpen(false)} title="Portfolio filters" onReset={()=>setFilters({agencyId:'',state:'',district:'',scheme:'',financialYear:'',status:''})}><label>Scheme / initiative<select value={filters.scheme} onChange={e=>setFilters({...filters,scheme:e.target.value})}><option value="">All schemes</option>{schemes.map(x=><option key={x}>{x}</option>)}</select></label><label>Financial year<select value={filters.financialYear} onChange={e=>setFilters({...filters,financialYear:e.target.value})}><option value="">All years</option>{years.map(x=><option key={x}>{x}</option>)}</select></label><label>Agency<select value={filters.agencyId} onChange={e=>setFilters({...filters,agencyId:e.target.value})}><option value="">All agencies</option>{agencies.map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label><label>State<select value={filters.state} onChange={e=>setFilters({...filters,state:e.target.value})}><option value="">All states</option>{states.map(x=><option key={x}>{x}</option>)}</select></label><label>District<select value={filters.district} onChange={e=>setFilters({...filters,district:e.target.value})}><option value="">All districts</option>{districts.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{statusOptions.map(x=><option key={x}>{String(x).replaceAll('_',' ')}</option>)}</select></label></FilterDrawer>
  {error&&<div className="alert error">{error}</div>}
  {loading?<section className="portfolio-folders"><div className="empty">Loading delivery hierarchy…</div></section>:<section className="portfolio-folders">
   {level==='programs'&&pagedPrograms.map(x=><PortfolioFolder key={x._id} icon={Layers3} title={`${x.code} · ${x.name}`} subtitle={[x.scheme,x.authority,x.financialYear].filter(Boolean).join(' · ')} status={x.status} meta={[["Scheme",x.scheme],["Financial year",x.financialYear]]} metrics={[["Contracts",x.metrics?.contracts],["Work orders",x.metrics?.workOrders],["Packages",x.metrics?.workPackages],["Beneficiaries",x.metrics?.beneficiaries]]} onOpen={()=>openProgram(x)} onEdit={canManage?()=>setEdit({kind:'programs',item:x}):null} onClose={canManage?()=>closeEntity('programs',x):null}/>) }
   {level==='contracts'&&<>{pagedContracts.map(x=><PortfolioFolder key={x._id} icon={ClipboardCheck} title={`${x.number} · ${x.title}`} subtitle={[x.type,x.authority].filter(Boolean).join(' · ')} status={x.status} meta={[["Program",x.programId?.code||x.programId?.name],["Type",x.type]]} metrics={[["Work orders",x.metrics?.workOrders],["Beneficiaries",x.metrics?.beneficiaries]]} onOpen={()=>{const p=program||programs.find(v=>String(v._id)===idOf(x.programId));if(p)setProgram(p);openContract(x)}} onEdit={canManage?()=>setEdit({kind:'contracts',item:x}):null} onClose={canManage?()=>closeEntity('contracts',x):null}/>)}{program&&directWos.length>0&&<PortfolioFolder icon={Folder} title="Direct / No Contract" subtitle="Work orders linked directly to this Program without a Contract / LOA parent" meta={[["Program",program.code],["Relationship","Direct"]]} metrics={[["Work orders",directWos.length],["Beneficiaries",directWos.reduce((n,w)=>n+Number(w.metrics?.beneficiaries||0),0)]]} onOpen={()=>openContract({_id:'__direct__',_direct:true,number:'Direct / No Contract'})}/>}</>}
   {level==='work-orders'&&pagedWos.map(x=><PortfolioFolder key={x._id} icon={FileText} title={`${x.number} · ${x.title||'Work order'}`} subtitle={x.contractId?`${x.contractId.number||'Contract'} · ${x.programId?.name||''}`:`Direct under ${x.programId?.name||'Program'}`} status={x.status} meta={[["Program",x.programId?.code||x.programId?.name],["Contract",x.contractId?.number||'Direct / none']]} metrics={[["Packages",x.metrics?.workPackages],["Beneficiaries",x.metrics?.beneficiaries]]} onOpen={()=>openWorkOrder(x)} onEdit={canManage?()=>setEdit({kind:'work-orders',item:x}):null} onClose={canManage?()=>closeEntity('work-orders',x):null}/>) }
   {level==='work-packages'&&pagedPackages.map(x=>{const am=agencies.find(a=>String(a._id)===idOf(x.agencyId))?.metrics;return <PortfolioFolder key={x._id} icon={PackageCheck} title={`${x.code} · ${x.name||'Work package'}`} subtitle={[x.agencyId?.name,x.geography?.district,x.geography?.state].filter(Boolean).join(' · ')||'Unassigned execution package'} status={x.status} progress={am&&idOf(x.agencyId)?Number(am.completionPercent||0):undefined} meta={[["Work order",x.workOrderId?.number],["Agency",x.agencyId?.name||'Unassigned'],["Location",[x.geography?.district,x.geography?.state].filter(Boolean).join(', ')]]} metrics={[["Beneficiaries",x.metrics?.beneficiaries],["Assigned qty",x.assignedQuantity]]} onOpen={()=>openPackage(x)} onEdit={canManage?()=>setEdit({kind:'work-packages',item:x}):null} onClose={canManage?()=>closeEntity('work-packages',x):null}/>})}
   {['programs','contracts','work-orders','work-packages'].includes(level)&&((level==='programs'&&!visiblePrograms.length)||(level==='contracts'&&!visibleContracts.length&&!directWos.length)||(level==='work-orders'&&!visibleWos.length)||(level==='work-packages'&&!visiblePackages.length))&&<div className="empty portfolio-empty">No matching records. Change filters or create the next record in this hierarchy.</div>}
  </section>}
  {level!=='beneficiaries'&&folderPages>1&&<div className="table-pager portfolio-pager"><button className="btn secondary small" disabled={folderPage<=1} onClick={()=>setFolderPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {folderPage} of {folderPages} · {folderRows.length} records</span><button className="btn secondary small" disabled={folderPage>=folderPages} onClick={()=>setFolderPage(p=>Math.min(folderPages,p+1))}>Next</button></div>}
  {level==='beneficiaries'&&<section className="portfolio-package-workspace record-table-panel"><div className="portfolio-context-grid"><div><small>Program</small><b>{program?.name||'—'}</b><span>{program?.code||''}</span></div><div><small>Contract / LOA</small><b>{contract?._direct?'Direct':contract?.number||'—'}</b><span>{contract?._direct?'No commercial parent':contract?.title||''}</span></div><div><small>Work order</small><b>{workOrder?.number||'—'}</b><span>{workOrder?.title||''}</span></div><div><small>Work package</small><b>{workPackage?.code||'—'}</b><span>{workPackage?.name||workPackage?.status||''}</span></div><div><small>Agency</small><b>{workPackage?.agencyId?.name||'Unassigned'}</b><span>{workPackage?.agencyId?.code||''}</span></div><div><small>Geography</small><b>{workPackage?.geography?.district||'—'}</b><span>{[workPackage?.geography?.state,workPackage?.geography?.taluka].filter(Boolean).join(' · ')}</span></div></div><div className="panel-head padded"><div><h2>Beneficiaries in this work package</h2><p>These records inherit the Program → Contract → Work Order → Work Package context shown above.</p></div>{onNavigate&&<button className="btn secondary" onClick={openBeneficiaryRecords}><UsersRound size={16}/> Open full filtered register</button>}</div><div className="table-wrap record-table-wrap"><table className="record-table"><thead><tr><th>Beneficiary</th><th>Location</th><th>Survey</th><th>Execution</th><th>Agency</th></tr></thead><tbody>{beneficiaries.loading?<tr><td colSpan="5" className="empty">Loading beneficiaries…</td></tr>:beneficiaries.items.map(x=>{const f=x.farmerId||{};return <tr key={x._id}><td><BeneficiaryLink farmerId={f._id}><b>{f.beneficiaryName||'—'}</b></BeneficiaryLink><small>{f.beneficiaryId||''} · {f.mobile||''}</small></td><td>{[f.village,f.taluka,f.district].filter(Boolean).join(', ')||'—'}</td><td><Status value={f.inspectionStatus||'Pending'}/></td><td><Status value={f.applicationStatus||'Pending'}/></td><td>{x.agencyId?.name||'—'}</td></tr>})}{!beneficiaries.loading&&!beneficiaries.items.length&&<tr><td colSpan="5" className="empty">No beneficiaries assigned to this package yet.</td></tr>}</tbody></table></div></section>}
  {edit?.kind&&edit.kind!=='work-packages'&&<ResourceModal cfg={resourceConfig[edit.kind]} companyId={companyId} refs={{programs,contracts}} item={edit.item||null} seed={edit.seed||{}} close={()=>setEdit(null)} done={()=>{setEdit(null);load()}}/>}
  {edit?.kind==='work-packages'&&<PackageModal companyId={companyId} refs={{programs,workOrders,agencies}} item={edit.item||null} seed={edit.seed||{}} close={()=>setEdit(null)} done={()=>{setEdit(null);load()}}/>}
 </>;
}

function AgencyDirectory({companyId,onNavigate}){
 const{can}=usePermissions(),canManage=can('operations.write');
 const[items,setItems]=useState([]),[portfolio,setPortfolio]=useState({workPackages:[],agencies:[]}),[edit,setEdit]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[stateFilter,setStateFilter]=useState(''),[attentionFilter,setAttentionFilter]=useState(''),[filterOpen,setFilterOpen]=useState(false),[page,setPage]=useState(1);
 const cfg=resourceConfig.agencies;
 const load=()=>{setLoading(true);setError('');Promise.all([api(opPath(companyId,'/agencies')),api(opPath(companyId,'/portfolio'))]).then(([d,p])=>{setItems(d.items||[]);setPortfolio(p||{})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[companyId]);
 const metricsFor=id=>portfolio.agencies?.find(a=>String(a._id)===String(id))?.metrics||{};
 const statusOptions=useMemo(()=>[...new Set(items.map(x=>x.status).filter(Boolean))].sort(),[items]),stateOptions=useMemo(()=>[...new Set(items.map(x=>x.state).filter(Boolean))].sort(),[items]);
 const rows=useMemo(()=>items.filter(it=>{const m=metricsFor(it._id);if(statusFilter&&it.status!==statusFilter)return false;if(stateFilter&&it.state!==stateFilter)return false;if(attentionFilter==='issues'&&!(Number(m.issues||0)>0||Number(m.blockedPackages||0)>0))return false;if(attentionFilter==='active'&&Number(m.activePackages||0)===0)return false;if(attentionFilter==='completed'&&Number(m.beneficiaries||0)>0&&Number(m.completionPercent||0)<100)return false;return !query||entityText(it.name,it.code,it.state,it.status,it.contact?.name,it.contact?.mobile,it.contact?.email,it.address).includes(query.toLowerCase())}),[items,portfolio,query,statusFilter,stateFilter,attentionFilter]);
 useEffect(()=>setPage(1),[query,statusFilter,stateFilter,attentionFilter]);
 const PAGE_SIZE=25,pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE)),pageRows=rows.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
 const totalBeneficiaries=(portfolio.agencies||[]).reduce((n,a)=>n+Number(a.metrics?.beneficiaries||0),0),completed=(portfolio.agencies||[]).reduce((n,a)=>n+Number(a.metrics?.completed||0),0),activePackages=(portfolio.agencies||[]).reduce((n,a)=>n+Number(a.metrics?.activePackages||0),0),attention=(portfolio.agencies||[]).filter(a=>Number(a.metrics?.issues||0)>0||Number(a.metrics?.blockedPackages||0)>0).length;
 const archive=async item=>{if(!confirm(`Archive agency “${item.name}”? Active work packages must be reassigned first.`))return;try{await api(opPath(companyId,`/agencies/${item._id}`),{method:'DELETE'});load()}catch(e){setError(e.message)}};
 const linkedPackages=selected?(portfolio.workPackages||[]).filter(x=>idOf(x.agencyId)===String(selected._id)):[],m=selected?metricsFor(selected._id):{},linkedBeneficiaries=Number(m.beneficiaries||0);
 return <><PageHeader eyebrow="EXECUTION NETWORK" title="Agencies" text="Agency capacity, delivery performance, beneficiary progress and operational attention in one company view." actions={canManage?<button className="btn primary" onClick={()=>setEdit({})}><Plus size={16}/> Add Agency</button>:null}/>
 <section className="agency-summary-strip"><div><small>ACTIVE AGENCIES</small><b>{items.filter(x=>x.status==='ACTIVE').length}</b><span>{items.length} total onboarded</span></div><div><small>ACTIVE PACKAGES</small><b>{fmt(activePackages)}</b><span>Currently in execution</span></div><div><small>BENEFICIARIES</small><b>{fmt(totalBeneficiaries)}</b><span>{totalBeneficiaries?Math.round(completed/totalBeneficiaries*100):0}% completed</span></div><div className={attention?'attention':''}><small>NEEDS ATTENTION</small><b>{attention}</b><span>Issue or blocked workload</span></div></section>
 <div className="command-bar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search agency, code, contact, mobile, email or state…"/></div><FilterButton onClick={()=>setFilterOpen(true)} count={[statusFilter,stateFilter,attentionFilter].filter(Boolean).length}/><span className="result-count">{rows.length} agencies</span></div>
 <FilterDrawer open={filterOpen} close={()=>setFilterOpen(false)} title="Agency filters" onReset={()=>{setStatusFilter('');setStateFilter('');setAttentionFilter('')}}><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{statusOptions.map(v=><option key={v}>{String(v).replaceAll('_',' ')}</option>)}</select></label><label>State / region<select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="">All states</option>{stateOptions.map(v=><option key={v}>{v}</option>)}</select></label><label>Operational view<select value={attentionFilter} onChange={e=>setAttentionFilter(e.target.value)}><option value="">All agencies</option><option value="active">Has active packages</option><option value="issues">Needs attention</option><option value="completed">Fully completed beneficiary load</option></select></label></FilterDrawer>
 {canManage&&selectedIds.length>0&&<section className="bulk-record-toolbar"><div><b>{selectedIds.length} selected</b><small>Update operational status without deleting audit history.</small></div><select value={bulk.inspectionStatus} onChange={e=>setBulk({...bulk,inspectionStatus:e.target.value})}><option value="">Survey status…</option>{(options.surveys||[]).map(v=><option key={v}>{v}</option>)}</select><select value={bulk.applicationStatus} onChange={e=>setBulk({...bulk,applicationStatus:e.target.value})}><option value="">Execution status…</option>{(options.statuses||[]).map(v=><option key={v}>{v}</option>)}</select><input value={bulk.remarks} onChange={e=>setBulk({...bulk,remarks:e.target.value})} placeholder="Optional bulk note"/><button className="btn primary small" disabled={bulkBusy} onClick={applyBulk}>{bulkBusy?'Updating…':'Apply update'}</button><button className="btn secondary small" onClick={()=>setSelectedIds([])}>Clear</button></section>}
 {error&&<div className="alert error">{error}</div>}<section className="table-panel agency-table"><div className="table-wrap"><table><thead><tr><th>Agency</th><th>Primary contact</th><th>Coverage</th><th>Workload</th><th>Beneficiary progress</th><th>Attention</th><th>Last activity</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="8" className="empty">Loading agencies…</td></tr>:pageRows.map(it=>{const a=metricsFor(it._id);return <tr key={it._id} className="clickable-row" onClick={()=>setSelected(it)}><td><b>{it.name}</b><small>{it.code} · {it.state||'Region not set'}</small></td><td><b>{it.contact?.name||'—'}</b><small>{it.contact?.mobile||it.contact?.email||'No contact'}</small></td><td><b>{fmt(a.districts||0)} districts</b><small>{fmt(a.workPackages||0)} total packages</small></td><td><b>{fmt(a.activePackages||0)} active</b><small>{fmt(a.completedPackages||0)} completed · {fmt(a.blockedPackages||0)} blocked</small></td><td><div className="agency-progress-cell"><span><b>{fmt(a.completed||0)}</b> / {fmt(a.beneficiaries||0)} complete</span><i><b style={{width:`${Math.max(0,Math.min(100,Number(a.completionPercent||0)))}%`}}/></i><small>{fmt(a.completionPercent||0)}% completion · {fmt(a.inProgress||0)} in progress</small></div></td><td>{Number(a.issues||0)+Number(a.blockedPackages||0)>0?<span className="agency-attention"><b>{fmt(Number(a.issues||0)+Number(a.blockedPackages||0))}</b><small>{fmt(a.pendingSurvey||0)} surveys pending</small></span>:<span className="agency-clear">Clear<small>{fmt(a.pendingSurvey||0)} surveys pending</small></span>}</td><td>{a.lastActivity?new Date(a.lastActivity).toLocaleDateString():'—'}</td><td><ChevronRight size={16}/></td></tr>})}{!loading&&!rows.length&&<tr><td colSpan="8" className="empty">No agencies match this view.</td></tr>}</tbody></table></div>{pages>1&&<div className="table-pager"><button className="btn secondary small" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {page} of {pages} · {rows.length} agencies</span><button className="btn secondary small" disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button></div>}</section>
 {edit&&<ResourceModal cfg={cfg} companyId={companyId} refs={{programs:[],contracts:[]}} item={edit._id?edit:null} close={()=>setEdit(null)} done={()=>{setEdit(null);load()}}/>}
 <DetailDrawer open={!!selected} close={()=>setSelected(null)} title={selected?.name||'Agency'} subtitle={`${selected?.code||''} · execution performance`}><div className="agency-detail-kpis"><div><small>Completion</small><b>{fmt(m.completionPercent||0)}%</b><span>{fmt(m.completed||0)} of {fmt(linkedBeneficiaries)} beneficiaries</span></div><div><small>Active packages</small><b>{fmt(m.activePackages||0)}</b><span>{fmt(m.completedPackages||0)} completed</span></div><div><small>Pending surveys</small><b>{fmt(m.pendingSurvey||0)}</b><span>Field verification outstanding</span></div><div className={(m.issues||m.blockedPackages)?'attention':''}><small>Issues / blockers</small><b>{fmt(Number(m.issues||0)+Number(m.blockedPackages||0))}</b><span>{fmt(m.blockedPackages||0)} blocked packages</span></div></div><div className="detail-section"><h3>Agency profile</h3><InfoGrid items={[{label:'Code',value:selected?.code},{label:'Status',value:selected?.status},{label:'State',value:selected?.state},{label:'Contact',value:selected?.contact?.name},{label:'Mobile',value:selected?.contact?.mobile},{label:'Email',value:selected?.contact?.email},{label:'Districts covered',value:m.districts},{label:'Last field activity',value:m.lastActivity?new Date(m.lastActivity).toLocaleString():'—'}]}/></div><div className="detail-section"><h3>Execution folders</h3><div className="linked-record-list">{linkedPackages.map(x=><button key={x._id} onClick={()=>{try{sessionStorage.setItem(`opsynq.delivery.context.${companyId}`,JSON.stringify({target:'work-packages',programId:idOf(x.programId),workOrderId:idOf(x.workOrderId),workPackageId:x._id}))}catch{}onNavigate?.('work-packages',{__hierarchyDrill:true})}}><span><b>{x.code} · {x.name||'Work package'}</b><small>{x.programId?.name||''} · {x.workOrderId?.number||''} · {[x.geography?.district,x.geography?.state].filter(Boolean).join(', ')}</small></span><Status value={x.status}/><ChevronRight size={15}/></button>)}{!linkedPackages.length&&<div className="empty">No work packages assigned to this agency yet.</div>}</div></div></DetailDrawer></>;
}

export function ResourcePage({kind,companyId,onNavigate}){
 if(['programs','contracts','work-orders'].includes(kind))return <DeliveryPortfolio companyId={companyId} onNavigate={onNavigate} focus={kind}/>;
 if(kind==='agencies')return <AgencyDirectory companyId={companyId} onNavigate={onNavigate}/>;
 const{can}=usePermissions(),canManage=can('operations.write');
 const cfg=resourceConfig[kind],[items,setItems]=useState([]),[edit,setEdit]=useState(null),[selected,setSelected]=useState(null),[refs,setRefs]=useState({programs:[],contracts:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[filterOpen,setFilterOpen]=useState(false);
 const load=()=>{setLoading(true);setError('');return api(opPath(companyId,cfg.endpoint)).then(d=>setItems(d.items||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load();Promise.all([api(opPath(companyId,'/programs')),api(opPath(companyId,'/contracts'))]).then(([p,c])=>setRefs({programs:p.items||[],contracts:c.items||[]})).catch(()=>{})},[kind,companyId]);
 const statusOptions=useMemo(()=>[...new Set(items.map(x=>x.status).filter(Boolean))].sort(),[items]);
 const rows=useMemo(()=>items.filter(it=>{if(statusFilter&&it.status!==statusFilter)return false;const hay=cfg.cols.map(([k])=>{const v=get(it,k);return typeof v==='object'?v?.name||v?.number||v?.code||'':v??''}).join(' ');return !query||String(hay).toLowerCase().includes(query.toLowerCase())}),[items,query,statusFilter,cfg]);
 const archive=async item=>{if(!confirm(`Archive/close ${cfg.singular} “${item.name||item.title||item.number||item.code}”? Historical records will be preserved.`))return;try{await api(opPath(companyId,`${cfg.endpoint}/${item._id}`),{method:'DELETE'});load()}catch(e){setError(e.message)}};
 return <><PageHeader eyebrow={cfg.eyebrow} title={cfg.title} text={cfg.desc} actions={canManage?<button className="btn primary" onClick={()=>setEdit({})}><Plus size={16}/> Add {cfg.singular}</button>:null}/><div className="command-bar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${cfg.title.toLowerCase()}…`}/></div><FilterButton onClick={()=>setFilterOpen(true)} count={statusFilter?1:0}/><span className="result-count">{rows.length} records</span></div><FilterDrawer open={filterOpen} close={()=>setFilterOpen(false)} title={`${cfg.title} filters`} onReset={()=>setStatusFilter('')}><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{statusOptions.map(v=><option key={v} value={v}>{String(v).replaceAll('_',' ')}</option>)}</select></label></FilterDrawer>{error&&<div className="alert error">{error}</div>}<section className="table-panel"><div className="table-wrap"><table><thead><tr>{cfg.cols.map(x=><th key={x[0]}>{x[1]}</th>)}<th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={cfg.cols.length+1} className="empty">Loading records…</td></tr>:rows.map(it=><tr key={it._id} className="clickable-row" onClick={()=>setSelected(it)}>{cfg.cols.map(([k])=><td key={k}>{k==='status'?<Status value={get(it,k)}/>:typeof get(it,k)==='object'?get(it,k)?.name||'—':String(get(it,k)??'—')}</td>)}<td>{canManage?<div className="row-actions"><button className="mini" onClick={e=>{e.stopPropagation();setEdit(it)}}><Edit3 size={14}/> Edit</button><button className="mini danger" onClick={e=>{e.stopPropagation();archive(it)}}><Archive size={14}/> Close</button></div>:<span className="muted-action">View only</span>}</td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={cfg.cols.length+1} className="empty">No matching records.</td></tr>}</tbody></table></div></section>{edit&&<ResourceModal cfg={cfg} companyId={companyId} refs={refs} item={edit._id?edit:null} close={()=>setEdit(null)} done={()=>{setEdit(null);load()}}/>}<DetailDrawer open={!!selected} close={()=>setSelected(null)} title={selected?.name||selected?.title||selected?.number||selected?.code||cfg.singular} subtitle={`${cfg.singular} · complete record`}><SmartRecordDetails record={selected}/></DetailDrawer></>;
}

export function WorkPackages({companyId,onNavigate}){return <DeliveryPortfolio companyId={companyId} onNavigate={onNavigate} focus="work-packages"/>;}

export function ResourceModal({cfg,companyId,refs,item,seed={},close,done}){
 const initial=()=>item?JSON.parse(JSON.stringify(item)):JSON.parse(JSON.stringify(seed||{}));const[form,setForm]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);const set=(path,value)=>{if(path.includes('.')){const[a,b]=path.split('.');setForm(f=>({...f,[a]:{...(f[a]||{}),[b]:value}}))}else setForm(f=>({...f,[path]:value}))};
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await api(opPath(companyId,item?`${cfg.endpoint}/${item._id}`:cfg.endpoint),{method:item?'PATCH':'POST',body:JSON.stringify(form)});done()}catch(x){setError(x.message)}finally{setBusy(false)}};
 const fieldValue=k=>{const v=get(form,k);return v&&typeof v==='object'&&v._id?v._id:(v??'')};
 return <Modal title={`${item?'Edit':'Create'} ${cfg.singular}`} close={close}><form className="form" onSubmit={submit}>{error&&<div className="alert error">{error}</div>}{cfg.fields.map(([k,label,type])=><label key={k}>{label}{type==='program'?<select required value={fieldValue(k)} onChange={e=>set(k,e.target.value)}><option value="">Select program</option>{refs.programs.map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select>:type==='contract'?<select value={fieldValue(k)} onChange={e=>set(k,e.target.value)}><option value="">No contract selected</option>{refs.contracts.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select>:type==='contractType'?<select value={fieldValue(k)||'LOA'} onChange={e=>set(k,e.target.value)}>{['LOA','CONTRACT','TENDER','FRAMEWORK','OTHER'].map(v=><option key={v}>{v}</option>)}</select>:type==='programStatus'?<select value={fieldValue(k)||'DRAFT'} onChange={e=>set(k,e.target.value)}>{['DRAFT','ACTIVE','ON_HOLD','COMPLETED','CLOSED'].map(v=><option key={v}>{v}</option>)}</select>:type==='agencyStatus'?<select value={fieldValue(k)||'ACTIVE'} onChange={e=>set(k,e.target.value)}>{['PENDING','ACTIVE','SUSPENDED','ARCHIVED'].map(v=><option key={v}>{v}</option>)}</select>:<input required={['name','code','number','title'].includes(k)} type={type||'text'} value={fieldValue(k)} onChange={e=>set(k,e.target.value)}/>}</label>)}<div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':item?'Save changes':'Create'}</button></div></form></Modal>
}


export function PackageModal({companyId,refs,item,seed={},close,done}){
 const[f,setF]=useState(item?JSON.parse(JSON.stringify(item)):{geography:{},...(seed||{})}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const idVal=v=>v&&typeof v==='object'?v._id:v||'';
 const submit=async e=>{e.preventDefault();setBusy(true);try{await api(opPath(companyId,item?`/work-packages/${item._id}`:'/work-packages'),{method:item?'PATCH':'POST',body:JSON.stringify({...f,programId:idVal(f.programId),workOrderId:idVal(f.workOrderId),agencyId:idVal(f.agencyId)})});done()}catch(x){setError(x.message)}finally{setBusy(false)}};
 return <Modal title={`${item?'Edit':'Create'} work package`} close={close}><form className="form" onSubmit={submit}>{error&&<div className="alert error">{error}</div>}{!item&&<><label>Program<select required value={idVal(f.programId)} onChange={e=>setF({...f,programId:e.target.value})}><option value="">Select</option>{refs.programs.map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label><label>Work order<select required value={idVal(f.workOrderId)} onChange={e=>setF({...f,workOrderId:e.target.value})}><option value="">Select</option>{refs.workOrders.filter(x=>!idVal(f.programId)||idVal(x.programId)===idVal(f.programId)).map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label></>}<div className="two">{!item&&<label>Package code<input required value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/></label>}<label>Name<input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></label></div><label>Agency<select value={idVal(f.agencyId)} onChange={e=>setF({...f,agencyId:e.target.value})}><option value="">Keep unassigned</option>{refs.agencies.filter(x=>x.status==='ACTIVE').map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label>{item&&idVal(f.agencyId)!==idVal(item.agencyId)&&<label>Reassignment reason<input required value={f.reason||''} onChange={e=>setF({...f,reason:e.target.value})}/></label>}<div className="two"><label>State<input value={f.geography?.state||''} onChange={e=>setF({...f,geography:{...(f.geography||{}),state:e.target.value}})}/></label><label>District<input value={f.geography?.district||''} onChange={e=>setF({...f,geography:{...(f.geography||{}),district:e.target.value}})}/></label></div><div className="two"><label>Due date<input type="date" value={f.dueDate?String(f.dueDate).slice(0,10):''} onChange={e=>setF({...f,dueDate:e.target.value})}/></label>{item&&<label>Status<select value={f.status||'READY'} onChange={e=>setF({...f,status:e.target.value})}>{['DRAFT','READY','ASSIGNED','IN_PROGRESS','BLOCKED','COMPLETED','CLOSED'].map(v=><option key={v}>{v}</option>)}</select></label>}</div><div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':item?'Save changes':'Create package'}</button></div></form></Modal>
}

export function BeneficiaryImports({companyId}){
 const{can}=usePermissions(),canManage=can('operations.write');
 const[refs,setRefs]=useState({programs:[],contracts:[],workOrders:[],workPackages:[],agencies:[]}),[imports,setImports]=useState([]),[form,setForm]=useState({}),[file,setFile]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[historyFilter,setHistoryFilter]=useState({status:'',programId:'',agencyId:''});
 const load=()=>Promise.all([api(opPath(companyId,'/portfolio')),api(opPath(companyId,'/beneficiaries/imports'))]).then(([p,i])=>{setRefs(p||{});setImports(i.items||[])}).catch(e=>setError(e.message));useEffect(()=>{load()},[companyId]);
 const contracts=(refs.contracts||[]).filter(x=>!form.programId||idOf(x.programId)===form.programId),workOrders=(refs.workOrders||[]).filter(x=>(!form.programId||idOf(x.programId)===form.programId)&&(!form.contractId||idOf(x.contractId)===form.contractId)),packages=(refs.workPackages||[]).filter(x=>x.agencyId&&(!form.workOrderId||idOf(x.workOrderId)===form.workOrderId));
 const submit=async e=>{e.preventDefault();setError('');setResult(null);if(!file)return setError('Choose an Excel file.');const fd=new FormData();Object.entries(form).forEach(([k,v])=>{if(k!=='contractId')fd.append(k,v)});fd.append('file',file);setBusy(true);try{const d=await api(opPath(companyId,'/beneficiaries/import'),{method:'POST',body:fd});setResult(d);setFile(null);load()}catch(x){setError(x.message)}finally{setBusy(false)}};
 const template=()=>downloadAuth(opPath(companyId,'/beneficiaries/template'),'opsynq-beneficiary-import-template.xlsx').catch(e=>setError(e.message));
 const errors=batch=>downloadAuth(opPath(companyId,`/beneficiaries/imports/${batch._id}/errors`),`beneficiary-import-errors-${batch._id}.csv`).catch(e=>setError(e.message));
 const programBy=id=>refs.programs?.find(x=>String(x._id)===String(id)),woBy=id=>refs.workOrders?.find(x=>String(x._id)===String(id)),pkgBy=id=>refs.workPackages?.find(x=>String(x._id)===String(id)),agencyBy=id=>refs.agencies?.find(x=>String(x._id)===String(id));
 const history=imports.filter(x=>{const m=x.metadata||{},hay=entityText(x.sourceFileName,x.status,programBy(m.programId)?.name,programBy(m.programId)?.code,woBy(m.workOrderId)?.number,pkgBy(m.workPackageId)?.code,agencyBy(m.agencyId)?.name,x.sourceAuthority);return(!query||hay.includes(query.toLowerCase()))&&(!historyFilter.status||x.status===historyFilter.status)&&(!historyFilter.programId||String(m.programId)===historyFilter.programId)&&(!historyFilter.agencyId||String(m.agencyId)===historyFilter.agencyId)});
 const activeFilters=Object.values(historyFilter).filter(Boolean).length;
 return <><PageHeader eyebrow="APPROVED BENEFICIARY INTAKE" title="Beneficiary Imports" text="Bulk intake follows the same Program → Contract/LOA → Work Order → assigned Work Package hierarchy so every imported beneficiary has traceable execution ownership." actions={<button className="btn secondary" onClick={template}><Download size={16}/> Download template</button>}/><section className="upload-panel"><form className="form" onSubmit={submit}>{error&&<div className="alert error">{error}</div>}{result&&<div className="alert success">Imported {result.success} · Failed {result.failed} · Skipped {result.skipped}</div>}<div className="two"><label>Program<select required value={form.programId||''} onChange={e=>setForm({...form,programId:e.target.value,contractId:'',workOrderId:'',workPackageId:''})}><option value="">Select</option>{(refs.programs||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label><label>Contract / LOA<select value={form.contractId||''} onChange={e=>setForm({...form,contractId:e.target.value,workOrderId:'',workPackageId:''})}><option value="">Direct / no contract</option>{contracts.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label></div><div className="two"><label>Work order<select required value={form.workOrderId||''} onChange={e=>setForm({...form,workOrderId:e.target.value,workPackageId:''})}><option value="">Select</option>{workOrders.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label><label>Assigned work package<select required value={form.workPackageId||''} onChange={e=>setForm({...form,workPackageId:e.target.value})}><option value="">Select</option>{packages.map(x=><option key={x._id} value={x._id}>{x.code} · {x.agencyId?.name}</option>)}</select></label></div><label>Source authority<input value={form.sourceAuthority||''} onChange={e=>setForm({...form,sourceAuthority:e.target.value})} placeholder="Government / authority / approved source"/></label><label className="file-drop"><UploadCloud size={28}/><b>{file?file.name:'Choose .xlsx or .xls file'}</b><small>Use the Opsynq template. Required: Beneficiary ID/Application ID and Beneficiary Name. Mobile, Scheme, District, Village and Pump HP are recognized.</small><input type="file" accept=".xlsx,.xls" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="btn primary" disabled={busy||!canManage}>{canManage?(busy?'Importing…':'Validate & import beneficiaries'):'View-only access'}</button></form></section>
 <div className="command-bar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search import file, Program, WO, package or agency"/></div><FilterButton count={activeFilters} onClick={()=>setFiltersOpen(true)}/><span className="result-count">{history.length} batches</span></div><FilterDrawer open={filtersOpen} close={()=>setFiltersOpen(false)} title="Import history filters" onReset={()=>setHistoryFilter({status:'',programId:'',agencyId:''})}><label>Status<select value={historyFilter.status} onChange={e=>setHistoryFilter({...historyFilter,status:e.target.value})}><option value="">All statuses</option>{[...new Set(imports.map(x=>x.status).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></label><label>Program<select value={historyFilter.programId} onChange={e=>setHistoryFilter({...historyFilter,programId:e.target.value})}><option value="">All programs</option>{(refs.programs||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label><label>Agency<select value={historyFilter.agencyId} onChange={e=>setHistoryFilter({...historyFilter,agencyId:e.target.value})}><option value="">All agencies</option>{(refs.agencies||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label></FilterDrawer>
 <section className="table-panel import-history"><div className="panel-head padded"><div><h2>Import history</h2><p>Every batch retains its Program, Work Order, package, agency, source file and row-level result.</p></div></div><div className="table-wrap"><table><thead><tr><th>File</th><th>Delivery chain</th><th>Agency</th><th>Status</th><th>Total</th><th>Imported</th><th>Failed</th><th>Time</th><th>Errors</th></tr></thead><tbody>{history.map(x=>{const m=x.metadata||{},p=programBy(m.programId),w=woBy(m.workOrderId),k=pkgBy(m.workPackageId),a=agencyBy(m.agencyId);return <tr key={x._id}><td>{x.sourceFileName}</td><td><b>{p?.code||'—'}</b><small>{w?.number||'—'} · {k?.code||'—'}</small></td><td>{a?.name||'—'}</td><td><Status value={x.status}/></td><td>{x.totalRows}</td><td>{x.successRows}</td><td>{x.failedRows}</td><td>{new Date(x.createdAt).toLocaleString()}</td><td>{Number(x.failedRows||0)+Number(x.skippedRows||0)>0?<button className="mini" onClick={()=>errors(x)}><Download size={14}/> CSV</button>:'—'}</td></tr>})}{!history.length&&<tr><td colSpan="9" className="empty">No import batches match this view.</td></tr>}</tbody></table></div></section></>;
}

export function BeneficiaryRecords({companyId}){
 const{can}=usePermissions(),canManage=can('operations.write');
 const initialFilter=()=>{try{const key='opsynq.dashboard.filter.beneficiary-records',v=JSON.parse(sessionStorage.getItem(key)||'{}');sessionStorage.removeItem(key);return v||{}}catch{return{}}};
 const preset=useMemo(initialFilter,[]);
 const[items,setItems]=useState([]),[q,setQ]=useState(preset.q||''),[filtersOpen,setFiltersOpen]=useState(false),[selected,setSelected]=useState(preset.farmerId||null),[selectedIds,setSelectedIds]=useState([]),[bulk,setBulk]=useState({applicationStatus:'',inspectionStatus:'',remarks:''}),[bulkBusy,setBulkBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[meta,setMeta]=useState({total:0,page:1,pages:1}),[portfolio,setPortfolio]=useState({programs:[],contracts:[],workOrders:[],workPackages:[],agencies:[]}),[options,setOptions]=useState({districts:[],talukas:[],villages:[],schemes:[],statuses:[],surveys:[]});
 const[f,setF]=useState({programId:preset.programId||'',contractId:preset.contractId||'',workOrderId:preset.workOrderId||'',workPackageId:preset.workPackageId||'',agencyId:preset.agencyId||'',scheme:preset.scheme||'',state:preset.state||'',district:preset.district||'',taluka:preset.taluka||'',village:preset.village||'',status:preset.status||'',survey:preset.survey||''});
 useEffect(()=>{Promise.all([api(opPath(companyId,'/portfolio')),api(opPath(companyId,'/beneficiary-filter-options'))]).then(([p,o])=>{setPortfolio(p||{});setOptions(o||{})}).catch(()=>{})},[companyId]);
 const load=(page=1)=>{setLoading(true);setError('');const params=new URLSearchParams({page:String(page),pageSize:'50'});if(q.trim())params.set('q',q.trim());Object.entries(f).forEach(([k,v])=>{if(v)params.set(k,v)});api(opPath(companyId,`/beneficiaries?${params.toString()}`)).then(d=>{setItems(d.items||[]);setSelectedIds([]);setMeta({total:d.total||0,page:d.page||1,pages:d.pages||1})}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{const id=setTimeout(()=>load(1),300);return()=>clearTimeout(id)},[companyId,q,JSON.stringify(f)]);
 const setFilter=(k,v,clear=[])=>setF(cur=>{const next={...cur,[k]:v};clear.forEach(x=>next[x]='');return next});
 const contracts=(portfolio.contracts||[]).filter(x=>!f.programId||idOf(x.programId)===f.programId),workOrders=(portfolio.workOrders||[]).filter(x=>(!f.programId||idOf(x.programId)===f.programId)&&(!f.contractId||idOf(x.contractId)===f.contractId)),packages=(portfolio.workPackages||[]).filter(x=>(!f.programId||idOf(x.programId)===f.programId)&&(!f.workOrderId||idOf(x.workOrderId)===f.workOrderId)&&(!f.agencyId||idOf(x.agencyId)===f.agencyId));
 const states=[...new Set((portfolio.workPackages||[]).map(x=>x.geography?.state).filter(Boolean))].sort();
 const activeFilters=Object.values(f).filter(Boolean).length;
 const reset=()=>setF({programId:'',contractId:'',workOrderId:'',workPackageId:'',agencyId:'',scheme:'',state:'',district:'',taluka:'',village:'',status:'',survey:''});
 const toggleId=id=>setSelectedIds(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);const togglePage=()=>{const ids=items.map(x=>String(x.farmerId?._id||'')).filter(Boolean);setSelectedIds(cur=>ids.every(id=>cur.includes(id))?cur.filter(id=>!ids.includes(id)):[...new Set([...cur,...ids])])};const applyBulk=async()=>{if(!selectedIds.length)return;const payload={ids:selectedIds};if(bulk.applicationStatus)payload.applicationStatus=bulk.applicationStatus;if(bulk.inspectionStatus)payload.inspectionStatus=bulk.inspectionStatus;if(bulk.remarks)payload.remarks=bulk.remarks;if(Object.keys(payload).length===1){setError('Choose at least one bulk update field.');return}setBulkBusy(true);setError('');try{await api(opPath(companyId,'/beneficiaries/bulk'),{method:'PATCH',body:JSON.stringify(payload)});setSelectedIds([]);setBulk({applicationStatus:'',inspectionStatus:'',remarks:''});load(meta.page)}catch(err){setError(err.message)}finally{setBulkBusy(false)}};
 return <><PageHeader eyebrow="BENEFICIARY MASTER" title="Beneficiary Records" text="Search the full delivery chain — Program, Contract/LOA, Work Order, Work Package, Agency, scheme, geography and execution status — from one beneficiary register."/><div className="command-bar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search beneficiary ID, name, mobile, village, district, scheme, vendor or technician"/></div><FilterButton onClick={()=>setFiltersOpen(true)} count={activeFilters}/><span className="result-count">{meta.total} beneficiaries</span></div>
 <FilterDrawer open={filtersOpen} close={()=>setFiltersOpen(false)} title="Beneficiary & delivery filters" onReset={reset}><label>Program<select value={f.programId} onChange={e=>setFilter('programId',e.target.value,['contractId','workOrderId','workPackageId'])}><option value="">All programs</option>{(portfolio.programs||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label><label>Contract / LOA<select value={f.contractId} onChange={e=>setFilter('contractId',e.target.value,['workOrderId','workPackageId'])}><option value="">All contracts / direct WOs</option>{contracts.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label><label>Work order<select value={f.workOrderId} onChange={e=>setFilter('workOrderId',e.target.value,['workPackageId'])}><option value="">All work orders</option>{workOrders.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label><label>Work package<select value={f.workPackageId} onChange={e=>setFilter('workPackageId',e.target.value)}><option value="">All work packages</option>{packages.map(x=><option key={x._id} value={x._id}>{x.code} · {x.name||x.agencyId?.name||'Package'}</option>)}</select></label><label>Agency<select value={f.agencyId} onChange={e=>setFilter('agencyId',e.target.value,['workPackageId'])}><option value="">All agencies</option>{(portfolio.agencies||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label><label>Scheme<select value={f.scheme} onChange={e=>setFilter('scheme',e.target.value)}><option value="">All schemes</option>{(options.schemes||[]).map(x=><option key={x}>{x}</option>)}</select></label><label>State<select value={f.state} onChange={e=>setFilter('state',e.target.value)}><option value="">All states</option>{states.map(x=><option key={x}>{x}</option>)}</select></label><label>District<select value={f.district} onChange={e=>setFilter('district',e.target.value)}><option value="">All districts</option>{(options.districts||[]).map(x=><option key={x}>{x}</option>)}</select></label><label>Taluka / block<select value={f.taluka} onChange={e=>setFilter('taluka',e.target.value)}><option value="">All talukas</option>{(options.talukas||[]).map(x=><option key={x}>{x}</option>)}</select></label><label>Village<select value={f.village} onChange={e=>setFilter('village',e.target.value)}><option value="">All villages</option>{(options.villages||[]).map(x=><option key={x}>{x}</option>)}</select></label><label>Execution status<select value={f.status} onChange={e=>setFilter('status',e.target.value)}><option value="">All execution statuses</option>{(options.statuses||[]).map(v=><option key={v}>{v}</option>)}</select></label><label>Survey status<select value={f.survey} onChange={e=>setFilter('survey',e.target.value)}><option value="">All survey statuses</option>{(options.surveys||[]).map(v=><option key={v}>{v}</option>)}</select></label></FilterDrawer>
 {canManage&&selectedIds.length>0&&<section className="bulk-record-toolbar"><div><b>{selectedIds.length} selected</b><small>Update operational status without deleting audit history.</small></div><select value={bulk.inspectionStatus} onChange={e=>setBulk({...bulk,inspectionStatus:e.target.value})}><option value="">Survey status…</option>{(options.surveys||[]).map(v=><option key={v}>{v}</option>)}</select><select value={bulk.applicationStatus} onChange={e=>setBulk({...bulk,applicationStatus:e.target.value})}><option value="">Execution status…</option>{(options.statuses||[]).map(v=><option key={v}>{v}</option>)}</select><input value={bulk.remarks} onChange={e=>setBulk({...bulk,remarks:e.target.value})} placeholder="Optional bulk note"/><button className="btn primary small" disabled={bulkBusy} onClick={applyBulk}>{bulkBusy?'Updating…':'Apply update'}</button><button className="btn secondary small" onClick={()=>setSelectedIds([])}>Clear</button></section>}
 {error&&<div className="alert error">{error}</div>}<section className="table-panel"><div className="table-wrap"><table><thead><tr>{canManage&&<th className="select-col"><input type="checkbox" aria-label="Select page" checked={items.length>0&&items.every(x=>selectedIds.includes(String(x.farmerId?._id||'')))} onChange={togglePage}/></th>}<th>Beneficiary</th><th>Delivery chain</th><th>Location</th><th>Agency / package</th><th>Survey</th><th>Execution</th><th>Evidence</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={canManage?9:8} className="empty">Loading beneficiaries…</td></tr>:items.map(x=>{const farmer=x.farmerId||{};const evidence=[farmer.farmerPhotoUrl,...(farmer.sitePhotosUrls||[]),farmer.installedPhotoUpload,farmer.finalfarmerPhotoUrl,...(farmer.finalsitePhotosUrls||[])].filter(Boolean);return <tr key={x._id} className="clickable-row" onClick={()=>setSelected(farmer._id)}>{canManage&&<td className="select-col"><input type="checkbox" checked={selectedIds.includes(String(farmer._id))} onClick={ev=>ev.stopPropagation()} onChange={()=>toggleId(String(farmer._id))}/></td>}<td><b>{farmer.beneficiaryName||'—'}</b><small>{farmer.beneficiaryId||''} · {farmer.mobile||''}</small></td><td><b>{x.programId?.code||'—'} · {x.workOrderId?.number||'No WO'}</b><small>{x.workOrderId?.contractId?.number||'Direct / no contract'} · {x.workPackageId?.code||'No package'} · {x.programId?.name||''}</small></td><td>{[farmer.village,farmer.taluka,farmer.district].filter(Boolean).join(', ')||'—'}</td><td>{x.agencyId?.name||'—'}<small>{x.workPackageId?.code||''}</small></td><td><Status value={farmer.inspectionStatus||'Pending'}/></td><td><Status value={farmer.applicationStatus||'Pending'}/></td><td>{evidence.length?<span className="evidence-count">{evidence.length} file{evidence.length===1?'':'s'}</span>:'—'}</td><td><button className="mini" onClick={ev=>{ev.stopPropagation();setSelected(farmer._id)}}>View details</button></td></tr>})}{!loading&&!items.length&&<tr><td colSpan={canManage?9:8} className="empty">No beneficiaries match this view.</td></tr>}</tbody></table></div>{meta.pages>1&&<div className="table-pager"><button className="btn secondary small" disabled={meta.page<=1} onClick={()=>load(meta.page-1)}>Previous</button><span>Page {meta.page} of {meta.pages}</span><button className="btn secondary small" disabled={meta.page>=meta.pages} onClick={()=>load(meta.page+1)}>Next</button></div>}</section>{selected&&<BeneficiaryDetailModal companyId={companyId} farmerId={selected} close={()=>setSelected(null)}/>}</>;
}

function BeneficiaryDetailModal({companyId,farmerId,close}){
 const[d,setD]=useState(null),[e,setE]=useState('');useEffect(()=>{api(opPath(companyId,`/beneficiaries/${farmerId}`)).then(setD).catch(x=>setE(x.message))},[companyId,farmerId]);
 const f=d?.farmer||{},ctx=d?.context||{},lineage=d?.lineage||{};
 const legacy=[f.farmerPhotoUrl,...(f.sitePhotosUrls||[]),f.signatureUrl,f.installedPhotoUpload,f.finalfarmerPhotoUrl,...(f.finalsitePhotosUrls||[]),f.finalsignatureUrl,f.finalsurveyorsignatureUrl,...(f.lrPhotoUrls||[])].filter(Boolean);
 const evidenceFiles=(d?.evidenceSubmissions||[]).flatMap(sub=>(sub.files||[]).map(file=>({...file,stage:sub.stage,status:sub.status,label:sub.requirementId?.label||'Field evidence',agency:sub.agencyId?.name,submittedBy:sub.submittedByLegacyUser?.username||sub.submittedByPlatformUser?.name||sub.captureGeo?.capturedByName||'Field user',updatedAt:sub.updatedAt})));
 const allImages=[...new Set([...legacy,...evidenceFiles.map(x=>x.url).filter(Boolean)])];
 return <Modal title="Beneficiary 360° record" close={close} size="xl">{e&&<div className="alert error">{e}</div>}{!d&&!e&&<div className="empty">Loading beneficiary record…</div>}{d&&<div className="beneficiary-detail-modal beneficiary-360">
  <div className="beneficiary-detail-head"><div className="beneficiary-detail-photo">{f.farmerPhotoUrl?<img src={f.farmerPhotoUrl} alt={f.beneficiaryName||'Beneficiary'}/>:<span>{(f.beneficiaryName||'B').slice(0,1)}</span>}</div><div><div className="eyebrow">{f.beneficiaryId||'BENEFICIARY'}</div><h3>{f.beneficiaryName||'Unnamed beneficiary'}</h3><p>{[f.village,f.taluka,f.district].filter(Boolean).join(', ')} · {f.mobile||'No mobile'}</p></div><Status value={f.applicationStatus||'Pending'}/></div>
  <section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Delivery lineage</h4><p>Where this record came from and where it sits in company execution.</p></div></div><div className="lineage-strip"><div><small>Program</small><b>{ctx.programId?.code||'—'}</b><span>{ctx.programId?.name||''}</span></div><i>→</i><div><small>Contract / LOA</small><b>{ctx.workOrderId?.contractId?.number||'Direct'}</b><span>{ctx.workOrderId?.contractId?.title||'No contract layer'}</span></div><i>→</i><div><small>Work Order</small><b>{ctx.workOrderId?.number||'—'}</b><span>{ctx.workOrderId?.title||''}</span></div><i>→</i><div><small>Work Package</small><b>{ctx.workPackageId?.code||'—'}</b><span>{ctx.workPackageId?.name||''}</span></div><i>→</i><div><small>Agency</small><b>{ctx.agencyId?.code||'—'}</b><span>{ctx.agencyId?.name||''}</span></div></div></section>
  <section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Record origin & assignment</h4><p>Import/manual origin and current assignment provenance.</p></div></div><div className="detail-grid"><div><small>Source</small><b>{lineage.source?.type||'—'}</b></div><div><small>Import file</small><b>{lineage.source?.batch?.sourceFileName||'Manual / not available'}</b></div><div><small>Source row</small><b>{lineage.source?.row||'—'}</b></div><div><small>Source authority</small><b>{lineage.source?.authority||'—'}</b></div><div><small>Assigned</small><b>{lineage.assignment?.assignedAt?new Date(lineage.assignment.assignedAt).toLocaleString():'—'}</b></div><div><small>Validation</small><b>{ctx.validationStatus||'—'}</b></div></div></section>
  <section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Survey & field verification</h4><p>Agency survey status, surveyor identity and synchronized evidence.</p></div><Status value={f.inspectionStatus||'Pending'}/></div><div className="detail-grid"><div><small>Surveyor</small><b>{lineage.survey?.surveyorName||f.surveyorName||'—'}</b></div><div><small>Surveyor mobile</small><b>{lineage.survey?.surveyorMobile||f.surveyorMobile||'—'}</b></div><div><small>Survey date</small><b>{f.surveyDate?new Date(f.surveyDate).toLocaleString():'—'}</b></div><div><small>Site depth</small><b>{f.siteDepth||'—'}</b></div><div><small>Land holding</small><b>{f.landHoldingAcre||'—'}</b></div><div><small>Actual head</small><b>{f.actualHeadM||'—'}</b></div><div><small>Source depth</small><b>{f.sourceDepthFeet||'—'}</b></div><div><small>Site geo</small><b>{f.siteLocation||'—'}</b></div></div>{evidenceFiles.length>0&&<div className="evidence-provenance-list">{(d.evidenceSubmissions||[]).map(sub=><div key={sub._id}><span><b>{sub.requirementId?.label||'Evidence'}</b><small>{String(sub.stage||'').replaceAll('_',' ')} · {sub.agencyId?.name||ctx.agencyId?.name||'Agency'} · {sub.submittedByLegacyUser?.username||sub.submittedByPlatformUser?.name||sub.captureGeo?.capturedByName||'Field user'}</small></span><span><Status value={sub.status}/><small>{sub.updatedAt?new Date(sub.updatedAt).toLocaleString():''}</small></span></div>)}</div>}</section>
  {allImages.length>0&&<section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Photo & signature evidence</h4><p>Survey, installation and final evidence visible to Company from the same beneficiary record.</p></div><span className="evidence-count">{allImages.length} files</span></div><div className="beneficiary-image-grid evidence-gallery">{allImages.map((src,i)=><a href={src} target="_blank" rel="noreferrer" key={`${src}-${i}`}><img src={src} alt={`Field evidence ${i+1}`}/><span>Open proof {i+1}</span></a>)}</div></section>}
  <section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Material & dispatch custody</h4><p>Company dispatch → agency receipt → technician issue → installed asset chain.</p></div></div>{(d.shipments||[]).length?<div className="compact-record-table"><table><thead><tr><th>Shipment</th><th>Status</th><th>From → To</th><th>Dispatch / delivery</th><th>Qty / receipt</th></tr></thead><tbody>{d.shipments.map(s=><tr key={s._id}><td><b>{s.shipmentNo}</b><small>{s.agencyId?.name||ctx.agencyId?.name||''}</small></td><td><Status value={s.status}/></td><td>{s.fromWarehouseId?.code||'—'} → {s.toWarehouseId?.code||'Agency'}</td><td>{s.dispatchedAt?new Date(s.dispatchedAt).toLocaleDateString():'—'}<small>{s.deliveredAt?`Delivered ${new Date(s.deliveredAt).toLocaleDateString()}`:''}</small></td><td>{(s.items||[]).reduce((n,x)=>n+Number(x.quantity||0),0)}<small>Received {(s.items||[]).reduce((n,x)=>n+Number(x.receivedQty||0),0)}</small></td></tr>)}</tbody></table></div>:<div className="detail-empty">No Work Package shipment is recorded yet.</div>}{(d.materialIssues||[]).length>0&&<div className="beneficiary-asset-list material-issue-list">{d.materialIssues.map(x=><div key={x._id}><span>TECHNICIAN ISSUE</span><b>{x.issueNo}</b><small>{x.technicianUserId?.username||'Technician'} · {(x.items||[]).reduce((n,i)=>n+Number(i.quantity||0),0)} units · {x.issuedAt?new Date(x.issuedAt).toLocaleString():''}</small></div>)}</div>}</section>
  {d.assets?.length>0&&<section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Installed assets</h4><p>Serialized assets currently or historically tied to this beneficiary.</p></div></div><div className="beneficiary-asset-list">{d.assets.map(a=><div key={a._id}><span>{a.assetRole}</span><b>{a.serialNumber}</b><small>{a.itemId?.sku||''} · {a.itemId?.name||''} · {a.status}</small></div>)}</div></section>}
  {d.serviceCases?.length>0&&<section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Service / complaints</h4><p>Post-installation operational history.</p></div></div>{d.serviceCases.map(s=><div className="beneficiary-service-row" key={s._id}><div><b>{s.caseNo} · {s.title}</b><small>{s.type} · {s.priority}</small></div><Status value={s.status}/></div>)}</section>}
  {d.evidenceChecklist?.length>0&&<section className="beneficiary-section"><div className="beneficiary-section-head"><div><h4>Evidence compliance checklist</h4><p>Company-required evidence by execution stage.</p></div></div><div className="evidence-checklist">{d.evidenceChecklist.map((x,i)=><div key={x.requirement?._id||i}><span><b>{x.requirement?.label}</b><small>{String(x.requirement?.stage||'').replaceAll('_',' ')} · {x.requirement?.evidenceType}</small></span><Status value={x.submission?.status||'PENDING'}/></div>)}</div></section>}
 </div>}</Modal>
}

