import React,{useEffect,useState}from'react';
import{BrainCircuit,RefreshCw,Send,ShieldCheck,TriangleAlert,CheckCircle2,Check,RotateCcw}from'lucide-react';
import{api,aiPath,assurancePath}from'../../../core/api';
import{PageHeader,Status}from'../../../components/common';
import{usePermissions}from'../../../core/accessControl.jsx';

const scopes=[['EXECUTIVE','Executive'],['DELIVERY','Program delivery'],['SUPPLY','Supply operations'],['SERVICE','Service & quality'],['FINANCE','Finance operations']];
export function AIOperationsPage({companyId}){
 const{can}=usePermissions(),canDecide=can('approvals.decide');
 const[status,setStatus]=useState(null),[scanResult,setScanResult]=useState(null),[scope,setScope]=useState('EXECUTIVE'),[question,setQuestion]=useState(''),[result,setResult]=useState(null),[proposals,setProposals]=useState([]),[busy,setBusy]=useState(false),[decisionBusy,setDecisionBusy]=useState(''),[error,setError]=useState('');
 const loadStatus=()=>api(aiPath(companyId,'/status')).then(setStatus).catch(e=>setError(e.message));
 const loadProposals=()=>{if(!canDecide)return setProposals([]);return api(assurancePath(companyId,'/approvals?status=PENDING')).then(d=>setProposals((d.items||[]).filter(x=>x.requestOrigin==='SYSTEM'))).catch(e=>setError(e.message))};
 const refresh=()=>{setError('');return Promise.all([loadStatus(),loadProposals()])};
 useEffect(()=>{refresh()},[companyId,canDecide]);
 const runScan=async()=>{setBusy(true);setError('');try{const r=await api(aiPath(companyId,'/scan'),{method:'POST'});setScanResult(r);await loadProposals()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const run=async()=>{setBusy(true);setError('');try{setResult(await api(aiPath(companyId,'/brief'),{method:'POST',body:JSON.stringify({scope,question})}))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const decide=async(item,statusValue)=>{const reason=window.prompt(`${statusValue==='APPROVED'?'Confirmation':'Rejection'} note:`)||'';setDecisionBusy(item._id);setError('');try{await api(assurancePath(companyId,`/approvals/${item._id}/decision`),{method:'PATCH',body:JSON.stringify({status:statusValue,reason})});await loadProposals()}catch(e){setError(e.message)}finally{setDecisionBusy('')}};
 const brief=result?.brief;
 return <><PageHeader eyebrow="OPERATIONS INTELLIGENCE" title="Operations Intelligence" text="Monitor operational signals, prepare safe draft actions and surface decisions that still require an authorized person to confirm." actions={<><button className="btn secondary" disabled={busy} onClick={runScan}><RefreshCw size={16}/>Run monitoring now</button><button className="btn secondary" onClick={refresh}>Refresh</button></>}/>
 {error&&<div className="alert error">{error}</div>}
 <section className="panel padded ai-status-panel"><div className="panel-head"><div><h2>Decision support status</h2><p>Decision credentials stay on the API service. No deployment secret is exposed to the browser.</p></div><Status value={status?.ready?'READY':status?.configured?'ATTENTION':'NOT CONFIGURED'}/></div><div className="quality-metrics"><div><span>Configured</span><b>{status?.configured?'Yes':'No'}</b></div><div><span>Connection</span><b>{status?.ready?'Ready':'Not ready'}</b></div><div><span>Automation</span><b>Detect + draft</b></div><div><span>Control</span><b>Human confirmation</b></div></div>{status?.message&&<p className="detail-copy">{status.message}</p>}</section>
 <section className="panel padded"><div className="panel-head"><div><h2>How governed automation works</h2><p>Opsynq detects risk, prepares a non-binding action where the workflow supports it, then waits for an authorized user before the controlled change is applied.</p></div></div><div className="intelligence-columns"><div><h3>Detect</h3><p>Stock risk, SLA breach, claim delay, coverage expiry and operational exceptions are monitored from live company data.</p></div><div><h3>Prepare</h3><p>Supported workflows create a reviewable proposal. Low stock can prepare a draft purchase order without issuing it.</p></div><div><h3>Confirm</h3><p>An authorized user checks quantity, supplier, priority, dates and evidence, then approves or rejects the proposal.</p></div><div><h3>Execute & audit</h3><p>Only approved proposals continue through the normal controlled workflow, with decision history retained.</p></div></div></section>
 {scanResult&&<div className="alert success">Monitoring completed. {scanResult.results?.filter(x=>x.status==='COMPLETED').length||0} controls refreshed; review any pending proposals below.</div>}
 {canDecide&&<section className="table-panel"><div className="panel-head padded"><div><h2>Pending automated proposals</h2><p>System-prepared actions waiting for human confirmation. Nothing below has executed yet.</p></div><span className="result-count">{proposals.length} pending</span></div><div className="table-wrap"><table><thead><tr><th>Proposal</th><th>Area</th><th>Suggested action</th><th>Created</th><th>Decision</th></tr></thead><tbody>{proposals.map(x=><tr key={x._id}><td><b>{x.title}</b><small>{x.description}</small></td><td>{String(x.type||'OTHER').replaceAll('_',' ')}</td><td>{String(x.payload?.proposalKind||'REVIEW').replaceAll('_',' ')}{x.payload?.proposedPriority&&<small>Proposed priority: {x.payload.proposedPriority}</small>}</td><td>{new Date(x.createdAt).toLocaleString()}</td><td className="row-actions"><button className="mini approve" disabled={decisionBusy===x._id} onClick={()=>decide(x,'APPROVED')}><Check size={13}/>Confirm</button><button className="mini" disabled={decisionBusy===x._id} onClick={()=>decide(x,'REJECTED')}><RotateCcw size={13}/>Reject</button></td></tr>)}{!proposals.length&&<tr><td colSpan="5" className="empty">No automated proposal currently requires confirmation.</td></tr>}</tbody></table></div></section>}
 <section className="panel padded"><div className="panel-head"><div><h2>Generate a grounded operations brief</h2><p>Choose a business scope. Only a compact operational snapshot is analyzed; controlled records are not changed.</p></div></div><div className="ai-scope-grid">{scopes.map(([id,label])=><button key={id} className={scope===id?'ai-scope active':'ai-scope'} onClick={()=>setScope(id)}><b>{label}</b><small>{id==='EXECUTIVE'?'Company-wide signals':id==='DELIVERY'?'Programs, packages and beneficiaries':id==='SUPPLY'?'Procurement, stock, dispatch and fleet':id==='SERVICE'?'Service workload and execution':'Claims and operational finance'}</small></button>)}</div><label className="ai-question">Optional question<textarea rows="3" value={question} maxLength={1200} onChange={e=>setQuestion(e.target.value)} placeholder="Example: Which operational risks need a decision today?"/></label><div className="modal-actions"><button className="btn primary" disabled={busy||!status?.ready} onClick={run}><Send size={16}/>{busy?'Generating…':'Generate brief'}</button></div></section>
 {brief&&<section className="panel padded intelligence-brief"><div className="panel-head"><div><h2>{scopes.find(x=>x[0]===result.scope)?.[1]||result.scope} brief</h2><p>{brief.executiveSummary}</p></div><span className="health-pill">{brief.confidence||'—'} confidence</span></div><div className="intelligence-columns"><div><h3>Findings</h3>{(brief.findings||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Risks</h3>{(brief.risks||[]).length?(brief.risks||[]).map((x,i)=><p key={i}>• {x}</p>):<p>No material risk was identified from the supplied snapshot.</p>}</div><div><h3>Actions for confirmation</h3>{(brief.recommendedActions||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Data limitations</h3>{(brief.dataLimitations||[]).length?(brief.dataLimitations||[]).map((x,i)=><p key={i}>• {x}</p>):<p>None reported.</p>}</div></div><div className="risk-note"><ShieldCheck size={17}/><div><b>Human confirmation remains mandatory</b><small>Decision support cannot independently approve, issue, dispatch, pay or delete controlled records.</small></div></div></section>}
 {!status?.configured&&<div className="risk-note"><TriangleAlert size={17}/><div><b>Operations intelligence is not configured</b><small>Add the API-service intelligence credential in deployment environment variables, then redeploy.</small></div></div>}
 {status?.ready&&<div className="risk-note"><CheckCircle2 size={17}/><div><b>Operations intelligence is ready</b><small>Live company data can be analyzed and supported workflows can prepare drafts for human confirmation.</small></div></div>}
 </>;
}
