import React,{useEffect,useMemo,useState}from'react';
import{Activity,BrainCircuit,RefreshCw,Send,ShieldCheck,TriangleAlert,CheckCircle2,Check,RotateCcw,Clock3,History,PlayCircle}from'lucide-react';
import{api,aiPath,assurancePath}from'../../../core/api';
import{PageHeader,Status}from'../../../components/common';
import{usePermissions}from'../../../core/accessControl.jsx';

const scopes=[['EXECUTIVE','Executive'],['DELIVERY','Program delivery'],['SUPPLY','Supply operations'],['SERVICE','Service & quality'],['FINANCE','Finance operations']];
const fmtDate=v=>v?new Date(v).toLocaleString():'—';
export function AIOperationsPage({companyId,onNavigate}){
 const{can}=usePermissions(),canDecide=can('approvals.decide');
 const[startScope]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('opsynq.dashboard.filter.ai-operations')||'{}')?.scope||'EXECUTIVE'}catch{return'EXECUTIVE'}});
 const[status,setStatus]=useState(null),[scanResult,setScanResult]=useState(null),[scope,setScope]=useState(startScope),[question,setQuestion]=useState(''),[result,setResult]=useState(null),[proposals,setProposals]=useState([]),[busy,setBusy]=useState(false),[decisionBusy,setDecisionBusy]=useState(''),[error,setError]=useState(''),[view,setView]=useState('PENDING');
 const loadStatus=()=>api(aiPath(companyId,'/status')).then(setStatus).catch(e=>setError(e.message));
 const loadProposals=()=>api(assurancePath(companyId,'/approvals')).then(d=>setProposals((d.items||[]).filter(x=>x.requestOrigin==='SYSTEM'))).catch(e=>setError(e.message));
 const refresh=()=>{setError('');return Promise.all([loadStatus(),loadProposals()])};
 useEffect(()=>{refresh()},[companyId]);
 const pending=useMemo(()=>proposals.filter(x=>x.status==='PENDING'),[proposals]);
 const decided=useMemo(()=>proposals.filter(x=>x.status!=='PENDING').slice(0,80),[proposals]);
 const runScan=async()=>{setBusy(true);setError('');try{const r=await api(aiPath(companyId,'/scan'),{method:'POST'});setScanResult(r);await loadProposals();setView('PENDING')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const run=async()=>{setBusy(true);setError('');try{setResult(await api(aiPath(companyId,'/brief'),{method:'POST',body:JSON.stringify({scope,question})}))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const decide=async(item,statusValue)=>{const reason=window.prompt(`${statusValue==='APPROVED'?'Confirmation':'Rejection'} note:`)||'';if(statusValue==='APPROVED'&&!window.confirm('Confirm this system-prepared action? The controlled workflow will proceed only after this confirmation.'))return;setDecisionBusy(item._id);setError('');try{await api(assurancePath(companyId,`/approvals/${item._id}/decision`),{method:'PATCH',body:JSON.stringify({status:statusValue,reason})});await loadProposals()}catch(e){setError(e.message)}finally{setDecisionBusy('')}};
 const brief=result?.brief;
 return <div className="ai-ops-page"><PageHeader eyebrow="AI OPERATIONS" title="AI Operations" text="See what automated monitoring detected, what draft actions were prepared, and which decisions still need a person to confirm." actions={<><button className="btn secondary" disabled={busy} onClick={runScan}><PlayCircle size={16}/>{busy?'Checking…':'Run checks now'}</button><button className="btn secondary" onClick={refresh}><RefreshCw size={16}/>Refresh</button></>}/>
 {error&&<div className="alert error">{error}</div>}
 <section className="ai-hero-grid"><article className="ai-hero-card"><span className="ai-card-icon"><BrainCircuit size={19}/></span><small>Automation status</small><strong>{status?.ready?'Ready':status?.configured?'Needs attention':'Not configured'}</strong><p>{status?.ready?'Monitoring can analyze live company signals and prepare reviewable actions.':status?.message||'Connect the API-side intelligence credential to enable assisted monitoring.'}</p></article><article className="ai-hero-card"><span className="ai-card-icon"><Clock3 size={19}/></span><small>Awaiting confirmation</small><strong>{pending.length}</strong><p>System-prepared actions that cannot execute until an authorized user confirms them.</p></article><article className="ai-hero-card"><span className="ai-card-icon"><History size={19}/></span><small>Decision history</small><strong>{decided.length}</strong><p>Recent approved, rejected or cancelled system proposals retained for audit.</p></article><article className="ai-hero-card"><span className="ai-card-icon"><ShieldCheck size={19}/></span><small>Control model</small><strong>Human gated</strong><p>No purchase, dispatch, payment, deletion or controlled status decision is finalized autonomously.</p></article></section>
 <section className="panel padded ai-process"><div className="panel-head"><div><h2>How it works</h2><p>Automation helps teams notice risks earlier without removing human accountability.</p></div><Status value={status?.ready?'READY':status?.configured?'ATTENTION':'NOT CONFIGURED'}/></div><div className="ai-process-steps"><div><b>1. Detect</b><span>Stock, SLA, claim, coverage and execution exceptions.</span></div><div><b>2. Prepare</b><span>A draft action or proposal using the current company context.</span></div><div><b>3. Review</b><span>User checks quantities, dates, supplier, priority and evidence.</span></div><div><b>4. Confirm</b><span>Only an authorized manual confirmation lets the controlled workflow proceed.</span></div></div></section>
 {scanResult&&<div className="alert success">Monitoring completed. {scanResult.results?.filter(x=>x.status==='COMPLETED').length||0} controls refreshed. Any new proposal is shown below for review.</div>}
 <section className="table-panel ai-proposals"><div className="panel-head padded"><div><h2>Automation activity</h2><p>Review pending actions first, then use history to see exactly what the system prepared and what people decided.</p></div><div className="segmented-control"><button className={view==='PENDING'?'active':''} onClick={()=>setView('PENDING')}>Needs confirmation <span>{pending.length}</span></button><button className={view==='HISTORY'?'active':''} onClick={()=>setView('HISTORY')}>Decision history <span>{decided.length}</span></button></div></div><div className="table-wrap"><table><thead><tr><th>Proposal</th><th>Area</th><th>Prepared action</th><th>{view==='PENDING'?'Prepared':'Decision'}</th><th>{view==='PENDING'?'Manual confirmation':'Outcome'}</th></tr></thead><tbody>{(view==='PENDING'?pending:decided).map(x=><tr key={x._id}><td><b>{x.title}</b><small>{x.description}</small></td><td>{String(x.type||'OTHER').replaceAll('_',' ')}</td><td>{String(x.payload?.proposalKind||'REVIEW').replaceAll('_',' ')}{x.payload?.proposedPriority&&<small>Suggested priority: {x.payload.proposedPriority}</small>}{x.payload?.poNumber&&<small>Draft PO: {x.payload.poNumber}</small>}</td><td>{view==='PENDING'?fmtDate(x.createdAt):<><Status value={x.status}/><small>{fmtDate(x.decidedAt)}</small></>}</td><td>{view==='PENDING'?(canDecide?<div className="row-actions"><button className="mini approve" disabled={decisionBusy===x._id} onClick={()=>decide(x,'APPROVED')}><Check size={13}/>Confirm</button><button className="mini" disabled={decisionBusy===x._id} onClick={()=>decide(x,'REJECTED')}><RotateCcw size={13}/>Reject</button></div>:<span className="muted-action">Authorized approver required</span>):<span>{x.decidedBy?.name||'System / authorized user'}{x.decisionReason&&<small>{x.decisionReason}</small>}</span>}</td></tr>)}{!(view==='PENDING'?pending:decided).length&&<tr><td colSpan="5" className="empty">{view==='PENDING'?'No automated proposal currently needs confirmation.':'No system decision history yet.'}</td></tr>}</tbody></table></div></section>
 <section className="panel padded"><div className="panel-head"><div><h2>Ask for an operations brief</h2><p>Use this for analysis and prioritization. It does not change company records.</p></div></div><div className="ai-scope-grid">{scopes.map(([id,label])=><button key={id} className={scope===id?'ai-scope active':'ai-scope'} onClick={()=>setScope(id)}><b>{label}</b><small>{id==='EXECUTIVE'?'Company-wide signals':id==='DELIVERY'?'Programs, packages and beneficiaries':id==='SUPPLY'?'Procurement, stock, dispatch and fleet':id==='SERVICE'?'Service workload and execution':'Claims and operational finance'}</small></button>)}</div><label className="ai-question">Optional question<textarea rows="3" value={question} maxLength={1200} onChange={e=>setQuestion(e.target.value)} placeholder="Example: Which operational risks need a decision today?"/></label><div className="modal-actions"><button className="btn primary" disabled={busy||!status?.ready} onClick={run}><Send size={16}/>{busy?'Generating…':'Generate brief'}</button></div></section>
 {brief&&<section className="panel padded intelligence-brief"><div className="panel-head"><div><h2>{scopes.find(x=>x[0]===result.scope)?.[1]||result.scope} brief</h2><p>{brief.executiveSummary}</p></div><span className="health-pill">{brief.confidence||'—'} confidence</span></div><div className="intelligence-columns"><div><h3>Findings</h3>{(brief.findings||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Risks</h3>{(brief.risks||[]).length?(brief.risks||[]).map((x,i)=><p key={i}>• {x}</p>):<p>No material risk was identified from the supplied snapshot.</p>}</div><div><h3>Actions for confirmation</h3>{(brief.recommendedActions||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Data limitations</h3>{(brief.dataLimitations||[]).length?(brief.dataLimitations||[]).map((x,i)=><p key={i}>• {x}</p>):<p>None reported.</p>}</div></div><div className="risk-note"><ShieldCheck size={17}/><div><b>Manual confirmation remains mandatory</b><small>Analysis can recommend and prepare; controlled transactions still require the existing permission and approval workflow.</small></div></div></section>}
 {!status?.configured&&<div className="risk-note"><TriangleAlert size={17}/><div><b>AI Operations is not configured</b><small>Add the API-service intelligence credential in deployment environment variables, then redeploy.</small></div></div>}
 {status?.ready&&<div className="risk-note"><CheckCircle2 size={17}/><div><b>AI Operations is ready</b><small>Live company data can be analyzed and supported workflows can prepare drafts for manual confirmation.</small></div></div>}
 </div>;
}
