import React,{useEffect,useMemo,useState}from'react';
import{BrainCircuit,RefreshCw,Send,ShieldCheck,TriangleAlert,Check,RotateCcw,Clock3,History,PlayCircle,ArrowUpRight,Eye,Activity}from'lucide-react';
import{api,aiPath,assurancePath}from'../../../core/api';
import{PageHeader,Status,DetailDrawer,InfoGrid}from'../../../components/common';
import{usePermissions}from'../../../core/accessControl.jsx';

const scopes=[['EXECUTIVE','Executive','Company-wide priorities, exceptions and decisions'],['DELIVERY','Program delivery','Programs, packages, agencies and beneficiaries'],['SUPPLY','Supply operations','Procurement, stock, dispatch and fleet'],['SERVICE','Service & quality','Service workload, warranty and execution'],['FINANCE','Finance operations','Claims and operational-finance signals']];
const fmtDate=v=>v?new Date(v).toLocaleString():'—';
const pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const proposalTarget=x=>{const k=String(x?.payload?.proposalKind||'');if(k==='REPLENISHMENT_PO')return{page:'procurement-intelligence',label:'Open replenishment plan'};if(k==='SERVICE_PRIORITY_ESCALATION')return{page:'service-cases',label:'Open service cases'};if(k==='CLAIM_FOLLOWUP')return{page:'claims',label:'Open claims'};if(k==='COVERAGE_REVIEW')return{page:'service-plans',label:'Open warranty & AMC'};if(k==='INSURANCE_REVIEW')return{page:'insurance',label:'Open insurance'};return{page:'approval-center',label:'Open Approval Center'}};

export function AIOperationsPage({companyId,onNavigate}){
 const{can}=usePermissions(),canDecide=can('approvals.decide');
 const[startScope]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('opsynq.dashboard.filter.ai-operations')||'{}')?.scope||'EXECUTIVE'}catch{return'EXECUTIVE'}});
 const[status,setStatus]=useState(null),[scanResult,setScanResult]=useState(null),[scope,setScope]=useState(startScope),[question,setQuestion]=useState(''),[result,setResult]=useState(null),[proposals,setProposals]=useState([]),[busy,setBusy]=useState(false),[decisionBusy,setDecisionBusy]=useState(''),[error,setError]=useState(''),[view,setView]=useState('PENDING'),[selected,setSelected]=useState(null);
 const loadStatus=()=>api(aiPath(companyId,'/status')).then(setStatus).catch(e=>setError(e.message));
 const loadProposals=()=>api(assurancePath(companyId,'/approvals')).then(d=>setProposals((d.items||[]).filter(x=>x.requestOrigin==='SYSTEM'))).catch(e=>setError(e.message));
 const refresh=()=>{setError('');return Promise.all([loadStatus(),loadProposals()])};
 useEffect(()=>{refresh()},[companyId]);
 const pending=useMemo(()=>proposals.filter(x=>x.status==='PENDING'),[proposals]);
 const decided=useMemo(()=>proposals.filter(x=>x.status!=='PENDING').slice(0,100),[proposals]);
 const runScan=async()=>{setBusy(true);setError('');try{const r=await api(aiPath(companyId,'/scan'),{method:'POST'});setScanResult(r);await loadProposals();setView('PENDING')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const run=async()=>{setBusy(true);setError('');try{setResult(await api(aiPath(companyId,'/brief'),{method:'POST',body:JSON.stringify({scope,question})}))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const decide=async(item,statusValue)=>{const reason=window.prompt(`${statusValue==='APPROVED'?'Confirmation':'Rejection'} note:`)||'';if(statusValue==='APPROVED'&&!window.confirm('Confirm this prepared action? The controlled workflow will proceed only after this manual confirmation.'))return;setDecisionBusy(item._id);setError('');try{await api(assurancePath(companyId,`/approvals/${item._id}/decision`),{method:'PATCH',body:JSON.stringify({status:statusValue,reason})});setSelected(null);await loadProposals()}catch(e){setError(e.message)}finally{setDecisionBusy('')}};
 const openSource=item=>{const target=proposalTarget(item);try{sessionStorage.setItem(`opsynq.dashboard.filter.${target.page}`,JSON.stringify({entityId:item.entityId,approvalId:item._id,source:'ai-operations'}))}catch{}onNavigate?.(target.page)};
 const brief=result?.brief,currentScope=scopes.find(x=>x[0]===scope);
 const rows=view==='PENDING'?pending:decided;
 return <div className="ai-ops-page"><PageHeader eyebrow="OPERATIONS INTELLIGENCE" title="AI Operations" text="Monitor risks, review system-prepared actions and keep every controlled change behind an explicit human decision." actions={<><button className="btn secondary" disabled={busy} onClick={runScan}><PlayCircle size={16}/>{busy?'Running checks…':'Run monitoring now'}</button><button className="btn secondary" onClick={refresh}><RefreshCw size={16}/>Refresh</button></>}/>
 {error&&<div className="alert error">{error}</div>}
 {!status?.configured&&<div className="ai-config-banner"><TriangleAlert size={18}/><div><b>AI Operations is not configured on this deployment.</b><span>Add the server-side API credential in Vercel Environment Variables and redeploy. The credential is never exposed to the browser.</span></div></div>}
 {status?.configured&&!status?.ready&&<div className="ai-config-banner warning"><TriangleAlert size={18}/><div><b>AI service needs attention.</b><span>{status?.message||'The credential is present but the provider could not be verified.'}</span></div></div>}
 <section className="ai-hero-grid"><article className="ai-hero-card"><span className="ai-card-icon"><Activity size={19}/></span><small>Automation status</small><strong>{status?.ready?'Ready':status?.configured?'Attention':'Not configured'}</strong><p>{status?.ready?'Live company signals can be analyzed and reviewable actions can be prepared.':'Configuration must be healthy before analysis can run.'}</p></article><article className="ai-hero-card"><span className="ai-card-icon"><Clock3 size={19}/></span><small>Needs confirmation</small><strong>{pending.length}</strong><p>Prepared actions waiting for an authorized person.</p></article><article className="ai-hero-card"><span className="ai-card-icon"><History size={19}/></span><small>Decision history</small><strong>{decided.length}</strong><p>Approved, rejected and cancelled proposals retained for audit.</p></article><article className="ai-hero-card"><span className="ai-card-icon"><ShieldCheck size={19}/></span><small>Control model</small><strong>Human gated</strong><p>No controlled action is finalized without confirmation.</p></article></section>
 <section className="panel padded ai-process"><div className="panel-head"><div><h2>Controlled automation flow</h2><p>Automation detects and prepares. People remain accountable for final decisions.</p></div><Status value={status?.ready?'READY':status?.configured?'ATTENTION':'NOT CONFIGURED'}/></div><div className="ai-process-steps"><div><b>1. Detect</b><span>Stock, SLA, claims, coverage and execution signals.</span></div><div><b>2. Prepare</b><span>Draft action with source-record context and rationale.</span></div><div><b>3. Review</b><span>User opens the linked operational record and checks impact.</span></div><div><b>4. Confirm</b><span>Only authorized manual approval allows execution.</span></div></div></section>
 {scanResult&&<div className="alert success">Monitoring completed. {scanResult.results?.filter(x=>x.status==='COMPLETED').length||0} controls refreshed. New proposals are listed below.</div>}
 <section className="table-panel ai-proposals"><div className="panel-head padded"><div><h2>Prepared actions & decision history</h2><p>Click any row to inspect why it was created, what will change and which source record it belongs to.</p></div><div className="segmented-control"><button className={view==='PENDING'?'active':''} onClick={()=>setView('PENDING')}>Needs confirmation <span>{pending.length}</span></button><button className={view==='HISTORY'?'active':''} onClick={()=>setView('HISTORY')}>Decision history <span>{decided.length}</span></button></div></div><div className="table-wrap"><table><thead><tr><th>Proposal</th><th>Area</th><th>Prepared action</th><th>{view==='PENDING'?'Prepared':'Decision'}</th><th>{view==='PENDING'?'Action':'Outcome'}</th></tr></thead><tbody>{rows.map(x=><tr key={x._id} className="clickable-row" onClick={()=>setSelected(x)}><td><b>{x.title}</b><small>{x.description}</small></td><td>{pretty(x.type||'OTHER')}</td><td>{pretty(x.payload?.proposalKind||'REVIEW')}{x.payload?.proposedPriority&&<small>Suggested priority: {x.payload.proposedPriority}</small>}{x.payload?.poNumber&&<small>Draft PO: {x.payload.poNumber}</small>}</td><td>{view==='PENDING'?fmtDate(x.createdAt):<><Status value={x.status}/><small>{fmtDate(x.decidedAt)}</small></>}</td><td>{view==='PENDING'?(canDecide?<div className="row-actions"><button className="mini" onClick={e=>{e.stopPropagation();openSource(x)}}><ArrowUpRight size={13}/>Open</button><button className="mini approve" disabled={decisionBusy===x._id} onClick={e=>{e.stopPropagation();decide(x,'APPROVED')}}><Check size={13}/>Confirm</button><button className="mini" disabled={decisionBusy===x._id} onClick={e=>{e.stopPropagation();decide(x,'REJECTED')}}><RotateCcw size={13}/>Reject</button></div>:<button className="mini" onClick={e=>{e.stopPropagation();openSource(x)}}><ArrowUpRight size={13}/>Open</button>):<span>{x.decidedBy?.name||'Authorized user'}{x.decisionReason&&<small>{x.decisionReason}</small>}</span>}</td></tr>)}{!rows.length&&<tr><td colSpan="5" className="empty">{view==='PENDING'?'No prepared action currently needs confirmation.':'No system decision history yet.'}</td></tr>}</tbody></table></div></section>
 <section className="panel padded ai-brief-builder"><div className="panel-head"><div><h2>Operations brief</h2><p>Ask for analysis and prioritization. This is advisory and never changes records.</p></div></div><div className="ai-scope-grid">{scopes.map(([id,label,desc])=><button type="button" key={id} className={scope===id?'ai-scope active':'ai-scope'} onClick={()=>setScope(id)}><b>{label}</b><small>{desc}</small></button>)}</div><label className="ai-question"><span>Optional question</span><textarea rows="3" value={question} maxLength={1200} onChange={e=>setQuestion(e.target.value)} placeholder="Example: Which operational risks need a decision today?"/></label><div className="ai-brief-actions"><div><small>Selected scope</small><b>{currentScope?.[1]}</b></div><button className="btn primary" disabled={busy||!status?.ready} onClick={run}><Send size={16}/>{busy?'Generating…':'Generate brief'}</button></div></section>
 {brief&&<section className="panel padded intelligence-brief"><div className="panel-head"><div><h2>{scopes.find(x=>x[0]===result.scope)?.[1]||result.scope} brief</h2><p>{brief.executiveSummary}</p></div><span className="health-pill">{brief.confidence||'—'} confidence</span></div><div className="intelligence-columns"><div><h3>Findings</h3>{(brief.findings||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Risks</h3>{(brief.risks||[]).length?(brief.risks||[]).map((x,i)=><p key={i}>• {x}</p>):<p>No material risk identified.</p>}</div><div><h3>Actions for confirmation</h3>{(brief.recommendedActions||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Data limitations</h3>{(brief.dataLimitations||[]).length?(brief.dataLimitations||[]).map((x,i)=><p key={i}>• {x}</p>):<p>None reported.</p>}</div></div><div className="risk-note"><ShieldCheck size={17}/><div><b>Manual confirmation remains mandatory</b><small>Analysis can recommend and prepare; controlled transactions still require permission and approval.</small></div></div></section>}
 <DetailDrawer open={!!selected} close={()=>setSelected(null)} title={selected?.title||'Prepared action'} subtitle={selected?.requestNo||pretty(selected?.type)} actions={selected?<><button className="btn secondary" onClick={()=>openSource(selected)}><ArrowUpRight size={15}/>Open source record</button>{selected.status==='PENDING'&&canDecide&&<button className="btn primary" disabled={decisionBusy===selected._id} onClick={()=>decide(selected,'APPROVED')}><Check size={15}/>Confirm action</button>}</>:null}><div className="detail-section"><h3>Why this was prepared</h3><p className="detail-copy">{selected?.description||'System monitoring prepared this action from the linked operational signal.'}</p><InfoGrid items={[{label:'Area',value:pretty(selected?.type)},{label:'Prepared action',value:pretty(selected?.payload?.proposalKind||'REVIEW')},{label:'Status',value:selected?.status},{label:'Prepared at',value:fmtDate(selected?.createdAt)},{label:'Source entity',value:selected?.entityType},{label:'Source record ID',value:selected?.entityId},{label:'Suggested priority',value:selected?.payload?.proposedPriority},{label:'Draft PO',value:selected?.payload?.poNumber}]}/></div><div className="detail-section"><h3>Decision & audit</h3><InfoGrid items={[{label:'Decision',value:selected?.status},{label:'Decided by',value:selected?.decidedBy?.name},{label:'Decided at',value:fmtDate(selected?.decidedAt)},{label:'Decision note',value:selected?.decisionReason,wide:true}]}/>{selected?.status==='PENDING'&&<div className="risk-note"><ShieldCheck size={16}/><div><b>Nothing has executed yet</b><small>Open the linked record, verify the recommendation, then Confirm or Reject.</small></div></div>}</div></DetailDrawer>
 </div>
}
