const Shipment=require('../models/platform/Shipment');
const InventorySerial=require('../models/platform/InventorySerial');
const InventoryBalance=require('../models/platform/InventoryBalance');
const StockMovement=require('../models/platform/StockMovement');
const AuditLog=require('../models/platform/AuditLog');
const Notification=require('../models/platform/Notification');
const {resolveAgencyScope}=require('../utils/agencyScope');
const text=v=>String(v??'').trim();
async function balance(companyId,warehouseId,itemId,onHandDelta=0,inTransitDelta=0){const b=await InventoryBalance.findOne({companyId,warehouseId,itemId});const nextOn=Number(b?.onHand||0)+onHandDelta,nextTransit=Number(b?.inTransit||0)+inTransitDelta;if(nextOn<0||nextTransit<0)throw new Error('Inventory balance would become negative.');return InventoryBalance.findOneAndUpdate({companyId,warehouseId,itemId},{$set:{onHand:nextOn,inTransit:nextTransit,lastMovementAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});}
async function scopeFor(req,res){const scope=await resolveAgencyScope(req.user);if(!scope.linked||!scope.agencyIds.length){res.status(403).json({message:'This Agency user is not linked to an active Opsynq Agency.'});return null;}return scope;}
exports.listInbound=async(req,res)=>{const scope=await scopeFor(req,res);if(!scope)return;const page=Math.max(1,Number(req.query.page||1)),pageSize=Math.min(100,Math.max(10,Number(req.query.pageSize||25)));const q={agencyId:{$in:scope.agencyIds},status:{$in:['DISPATCHED','IN_TRANSIT','PARTIAL','DELIVERED']}};if(req.query.status)q.status=req.query.status;const search=String(req.query.q||'').trim();if(search)q.$or=[{shipmentNo:{$regex:search,$options:'i'}},{trackingNumber:{$regex:search,$options:'i'}}];const [total,items]=await Promise.all([Shipment.countDocuments(q),Shipment.find(q).populate('fromWarehouseId','code name').populate('toWarehouseId','code name').populate('agencyId','code name').populate('driverId','name mobile').populate('vehicleId','registrationNo registrationNumber type').populate('workPackageId','code name').populate('items.itemId','sku name serialTracked').populate('items.serialIds','serialNumber barcodeValue status').sort({createdAt:-1}).skip((page-1)*pageSize).limit(pageSize).lean()]);res.json({items,total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))});};
exports.receive=async(req,res)=>{const scope=await scopeFor(req,res);if(!scope)return;const s=await Shipment.findOne({_id:req.params.id,agencyId:{$in:scope.agencyIds}});if(!s)return res.status(404).json({message:'Inbound shipment not found for your Agency.'});if(!['IN_TRANSIT','PARTIAL'].includes(s.status))return res.status(409).json({message:'Shipment is not receivable in its current state.'});let receipts=Array.isArray(req.body.receipts)?req.body.receipts:[];let fullyAccounted=true;for(const line of s.items){const itemId=String(line.itemId),r=receipts.find(x=>String(x.itemId)===itemId)||{};const previously=Number(line.receivedQty||0)+Number(line.damagedQty||0)+Number(line.missingQty||0),remaining=Math.max(0,Number(line.quantity||0)-previously);const good=Math.max(0,Number(r.receivedQty??remaining)),damaged=Math.max(0,Number(r.damagedQty||0)),missing=Math.max(0,Number(r.missingQty||0)),accounted=good+damaged+missing;if(accounted>remaining)return res.status(400).json({message:'Receipt quantities exceed the remaining shipment quantity.'});if(accounted<remaining)fullyAccounted=false;const allCodes=[...(r.receivedSerials||[]),...(r.damagedSerials||[]),...(r.missingSerials||[])].map(text).filter(Boolean);if(line.serialIds?.length){if(allCodes.length!==accounted)return res.status(400).json({message:'Serialized receipt requires one serial/barcode for every accepted, damaged or missing unit.'});const docs=await InventorySerial.find({_id:{$in:line.serialIds},companyId:s.companyId,status:'IN_TRANSIT',$or:[{serialNumber:{$in:allCodes}},{barcodeValue:{$in:allCodes}}]});if(docs.length!==accounted)return res.status(409).json({message:'One or more receipt serials are invalid, duplicated or no longer in transit.'});const map=new Map();for(const d of docs){map.set(String(d.serialNumber).toLowerCase(),d);if(d.barcodeValue)map.set(String(d.barcodeValue).toLowerCase(),d)}for(const code of r.receivedSerials||[]){const d=map.get(text(code).toLowerCase());if(!d)continue;d.status='AGENCY_STOCK';d.warehouseId=s.toWarehouseId;d.agencyId=s.agencyId;await d.save()}for(const code of r.damagedSerials||[]){const d=map.get(text(code).toLowerCase());if(!d)continue;d.status='DAMAGED';d.warehouseId=null;d.metadata={...(d.metadata||{}),damageReason:text(r.notes)||'Damaged at Agency receipt',damagedAt:new Date()};await d.save()}for(const code of r.missingSerials||[]){const d=map.get(text(code).toLowerCase());if(!d)continue;d.status='MISSING';d.warehouseId=null;d.metadata={...(d.metadata||{}),missingReason:text(r.notes)||'Missing at Agency receipt',missingAt:new Date()};await d.save()}}
 if(accounted>0)await balance(s.companyId,s.fromWarehouseId,line.itemId,0,-accounted);if(good>0)await balance(s.companyId,s.toWarehouseId,line.itemId,good,0);if(good>0)await StockMovement.create({companyId:s.companyId,itemId:line.itemId,quantity:good,movementType:'TRANSFER',fromWarehouseId:s.fromWarehouseId,toWarehouseId:s.toWarehouseId,fromOrganizationId:s.companyId,toOrganizationId:s.agencyId,referenceType:'Shipment',referenceId:s._id,reason:`Agency receipt ${s.shipmentNo}`,performedBy:req.user._id});if(damaged>0)await StockMovement.create({companyId:s.companyId,itemId:line.itemId,quantity:damaged,movementType:'DAMAGE',fromWarehouseId:s.fromWarehouseId,toOrganizationId:s.agencyId,referenceType:'Shipment',referenceId:s._id,reason:text(r.notes)||`Damaged at Agency receipt ${s.shipmentNo}`,performedBy:req.user._id});if(missing>0)await StockMovement.create({companyId:s.companyId,itemId:line.itemId,quantity:missing,movementType:'ADJUSTMENT',fromWarehouseId:s.fromWarehouseId,toOrganizationId:s.agencyId,referenceType:'Shipment',referenceId:s._id,reason:text(r.notes)||`Missing at Agency receipt ${s.shipmentNo}`,performedBy:req.user._id});line.receivedQty=Number(line.receivedQty||0)+good;line.damagedQty=Number(line.damagedQty||0)+damaged;line.missingQty=Number(line.missingQty||0)+missing;line.receiptNotes=text(r.notes)||line.receiptNotes||'';}
 s.status=fullyAccounted?'DELIVERED':'PARTIAL';if(fullyAccounted)s.deliveredAt=new Date();s.proofOfDelivery={...(s.proofOfDelivery||{}),receiverName:text(req.body.receiverName)||req.user.username,receiverMobile:text(req.body.receiverMobile)||req.user.mobile,notes:text(req.body.notes),receivedAt:new Date(),confirmedByAgencyUserId:String(req.user._id)};await s.save();await AuditLog.create({companyId:s.companyId,organizationId:s.agencyId,actorId:req.user._id,actorType:'User',action:fullyAccounted?'AGENCY_SHIPMENT_RECEIVED':'AGENCY_SHIPMENT_PARTIAL_RECEIPT',entityType:'Shipment',entityId:s._id,after:{shipmentNo:s.shipmentNo,status:s.status,proofOfDelivery:s.proofOfDelivery}});await Notification.create({companyId:s.companyId,recipientRoles:['company_owner','company_admin','inventory_manager','logistics_manager','operations_manager'],type:fullyAccounted?'SUCCESS':'WARNING',title:`Agency ${fullyAccounted?'received':'partially received'} · ${s.shipmentNo}`,message:`${req.user.username} confirmed ${fullyAccounted?'complete':'partial'} receipt for shipment ${s.shipmentNo}.`,entityType:'Shipment',entityId:s._id,actionUrl:'agency-material-control'});res.json({item:s});};
