const XLSX=require('xlsx');
const Organization=require('../models/platform/Organization');
const AuditLog=require('../models/platform/AuditLog');
const {resolveAgencyScope}=require('../utils/agencyScope');
const {REPORTS,catalog,rowsFor,dateWindow,sanitizeRows}=require('../utils/reportingService');

const esc=v=>String(v??'').replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]));
async function scopeFor(req,res){const s=await resolveAgencyScope(req.user);if(!s.linked||!s.agencyIds.length){res.status(403).json({message:'Agency reporting requires an active OPSYNQ agency link.'});return null;}return{companyIds:s.companyIds,agencyIds:s.agencyIds,farmerIds:s.farmerIds};}
async function agencyNames(ids){return Organization.find({_id:{$in:ids}}).select('name code').lean();}
function html(meta,agencies,rows,query){const columns=rows.length?Object.keys(rows[0]):['Message'],data=rows.length?rows:[{Message:'No records matched the selected filters.'}],range=dateWindow(query),head=columns.map(c=>`<th>${esc(c.replaceAll('_',' '))}</th>`).join(''),body=data.map(r=>`<tr>${columns.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('');return`<!doctype html><html><head><meta charset="utf-8"><title>${esc(meta.title)}</title><style>body{font-family:Arial,sans-serif;color:#18211f;margin:28px}h1{font-size:22px;margin:0 0 6px}.meta{font-size:12px;color:#5f6b68;margin-bottom:20px}.notice{font-size:11px;border:1px solid #d8dfdc;background:#f7f9f8;padding:10px;margin-bottom:14px}table{border-collapse:collapse;width:100%;font-size:10px}th,td{border:1px solid #d8dfdc;padding:6px;text-align:left;vertical-align:top}th{background:#eef3f1}@media print{body{margin:10mm}.no-print{display:none}table{font-size:8px}thead{display:table-header-group}}</style></head><body><button class="no-print" onclick="window.print()">Print / Save PDF</button><h1>${esc(meta.title)}</h1><div class="meta">${esc(agencies.map(a=>a.name).join(', '))} · Generated ${new Date().toLocaleString('en-IN')} ${range.from||range.to?`· Period ${range.from?range.from.toLocaleDateString('en-IN'):'Start'} to ${range.to?range.to.toLocaleDateString('en-IN'):'Today'}`:''}</div><div class="notice">Agency-scoped operational report. Data is restricted to the agencies linked to the signed-in user.</div><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></body></html>`;}

exports.catalog=async(req,res)=>{const scope=await scopeFor(req,res);if(!scope)return;const agencies=await agencyNames(scope.agencyIds);res.json({reports:catalog({agency:true}),agencies,generatedAt:new Date().toISOString()});};
exports.preview=async(req,res)=>{const scope=await scopeFor(req,res);if(!scope)return;const meta=REPORTS[req.params.type];if(!meta||!catalog({agency:true}).some(x=>x.id===req.params.type))return res.status(404).json({message:'Agency report type not found.'});const rows=await rowsFor(scope,req.params.type,req.query);res.json({report:{id:req.params.type,...meta},rows:rows.slice(0,500),total:rows.length,previewLimit:500,generatedAt:new Date().toISOString(),period:dateWindow(req.query)});};
exports.export=async(req,res)=>{const scope=await scopeFor(req,res);if(!scope)return;const meta=REPORTS[req.params.type];if(!meta||!catalog({agency:true}).some(x=>x.id===req.params.type))return res.status(404).json({message:'Agency report type not found.'});const rows=await rowsFor(scope,req.params.type,req.query),format=String(req.query.format||'xlsx').toLowerCase(),agencies=await agencyNames(scope.agencyIds);await AuditLog.create({companyId:scope.companyIds[0]||null,organizationId:scope.agencyIds[0]||null,actorId:req.user._id,actorType:'User',action:'AGENCY_REPORT_EXPORTED',entityType:'Report',after:{type:req.params.type,format,rows:rows.length,agencyIds:scope.agencyIds,from:req.query.from||'',to:req.query.to||''}});if(format==='html'||format==='print'){res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Disposition',`inline; filename="${req.params.type}.html"`);return res.send(html(meta,agencies,rows,req.query));}const exportRows=sanitizeRows(rows.length?rows:[{Message:'No records matched the selected filters.'}]),ws=XLSX.utils.json_to_sheet(exportRows);if(format==='csv'){res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${req.params.type}.csv"`);return res.send('\ufeff'+XLSX.utils.sheet_to_csv(ws));}const wb=XLSX.utils.book_new(),range=dateWindow(req.query),cover=XLSX.utils.aoa_to_sheet([['OPSYNQ AGENCY REPORT'],['Report',meta.title],['Category',meta.category],['Agency',agencies.map(a=>`${a.name}${a.code?` (${a.code})`:''}`).join(', ')],['Generated At',new Date().toISOString()],['Period From',range.from?range.from.toISOString():'' ],['Period To',range.to?range.to.toISOString():'' ],['Rows',rows.length],[],['Scope','Only records belonging to the signed-in user’s linked agency/agency group are included.']]);XLSX.utils.book_append_sheet(wb,cover,'Cover');XLSX.utils.book_append_sheet(wb,ws,'Report');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${req.params.type}.xlsx"`);res.send(buf);};
