import React,{useEffect,useMemo,useState}from'react';
import{ArrowRight,BrainCircuit,CheckCircle2,CircleAlert,ClipboardCheck,PackageOpen,PackagePlus,ShoppingCart,Truck,UsersRound,Warehouse,ChevronDown,ArrowRightLeft}from'lucide-react';
import{api,invPath,logPath}from'../../../core/api';
import{fmt}from'../../../core/format';
import{PageHeader,Status}from'../../../components/common';
import{roleModuleIds}from'../../../layout/moduleRegistry';

const quickActions=[
 {id:'item-master',label:'Add inventory item',help:'Create SKU, tracking and reorder rules',icon:PackagePlus,action:'new-item'},
 {id:'procurement',label:'Create purchase order',help:'Start a governed supplier commitment',icon:ShoppingCart,action:'new-po'},
 {id:'procurement',label:'Receive / scan GRN',help:'Receive PO lines and capture serials',icon:ClipboardCheck,action:'receive'},
 {id:'stock',label:'Transfer stock',help:'Move stock between warehouses',icon:ArrowRightLeft,action:'transfer'},
 {id:'shipments',label:'Create dispatch',help:'Plan company-to-agency movement',icon:Truck,action:'new-dispatch'}
];
const areas=[
 {id:'procurement',title:'Procurement & Receiving',text:'Plan purchases, receive material and close incoming quality checks.',icon:ShoppingCart,primary:['procurement','Open procurement & GRN'],tools:[['procurement-intelligence','Replenishment review'],['pdi','PDI & asset inspection']]},
 {id:'inventory',title:'Inventory & Warehousing',text:'Control item masters, warehouse balances, transfers and serial traceability.',icon:Warehouse,primary:['stock','Open warehouse stock'],tools:[['item-master','Item master'],['warehouses','Warehouses']]},
 {id:'dispatch',title:'Dispatch & Delivery',text:'Plan shipments, assign capacity, monitor ETA and close agency delivery.',icon:Truck,primary:['shipments','Open dispatch tracking'],tools:[['fleet','Fleet & capacity'],['logistics-overview','Dispatch overview']]},
 {id:'field',title:'Agency & Field Custody',text:'Track receipt accountability, technician issue and beneficiary installation.',icon:PackageOpen,primary:['agency-stock','Open agency accountability'],tools:[['material-issues','Technician material custody'],['installed-assets','Installed assets'],['reconciliation','Reconciliation']]}
];
const Metric=({label,value,help,onClick})=>{const Tag=onClick?'button':'article';return <Tag type={onClick?'button':undefined} className={onClick?'supply-metric supply-metric--clickable':'supply-metric'} onClick={onClick}><small>{label}</small><strong>{fmt(value)}</strong><span>{help}</span>{onClick&&<ArrowRight size={14}/>}</Tag>};
export function SupplyChainWorkspace({companyId,onNavigate,user}){
 const[inv,setInv]=useState(null),[log,setLog]=useState(null),[tower,setTower]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;Promise.all([api(invPath(companyId,'/dashboard')),api(logPath(companyId,'/dashboard')),api(logPath(companyId,'/control-tower'))]).then(([a,b,c])=>{if(live){setInv(a);setLog(b);setTower(c)}}).catch(e=>live&&setError(e.message));return()=>{live=false}},[companyId]);
 const status=useMemo(()=>Object.fromEntries((tower?.status||[]).map(x=>[x._id,x.count])),[tower]);
 const activeDeliveries=Number(status.DISPATCHED||0)+Number(status.IN_TRANSIT||0)+Number(status.PARTIAL||0);const exceptions=Number(log?.exceptions||0)+Number(log?.openMaterialIssues||0);const allowed=useMemo(()=>new Set(roleModuleIds(user?.role)),[user?.role]);
 const attention=[
  {label:'Low stock positions',value:Number(inv?.lowStock||0),help:'Review replenishment before allocation',target:'stock',filter:{health:'LOW'}},
  {label:'Deliveries beyond ETA',value:Number(tower?.overdue||0),help:'Shipment follow-up required',target:'shipments',filter:{overdue:'true'}},
  {label:'Receipt / route exceptions',value:Number(log?.exceptions||0),help:'Damaged, missing or route attention',target:'shipments',filter:{attention:'true'}},
  {label:'Open technician custody issues',value:Number(log?.openMaterialIssues||0),help:'Field material reconciliation required',target:'material-issues',filter:{status:'OPEN'}}
 ].filter(x=>x.value>0);
 return <div className="supply-control-page">
  <PageHeader eyebrow="SUPPLY OPERATIONS" title="Supply Chain Control" text="See material flow end-to-end, open the workspace that needs action, and review automated supply recommendations before confirming them." actions={<button className="btn secondary" onClick={()=>onNavigate?.('ai-operations',{scope:'SUPPLY'})}><BrainCircuit size={16}/>Review AI actions</button>}/>
  {error&&<div className="alert error">{error}</div>}
  <section className="supply-start-card"><div className="section-title-row"><div><span>START WORK</span><h2>Common inventory & procurement actions</h2><p>Start the task directly. You do not need to open a module first and then find the action.</p></div></div><div className="supply-quick-actions">{quickActions.filter(x=>allowed.has(x.id)).map(x=><button key={`${x.id}-${x.action}`} onClick={()=>onNavigate?.(x.id,{action:x.action,__supplyDrill:true})}><span className="quick-icon"><x.icon size={18}/></span><span><b>{x.label}</b><small>{x.help}</small></span><ArrowRight size={15}/></button>)}</div></section>
  <section className="supply-overview-card"><div className="supply-overview-copy"><span>OPERATING FLOW</span><h2>Material from purchase request to beneficiary installation</h2><p>Start common work immediately, then use the focused workspaces for deeper control. The stage rail keeps material custody visible from purchase through installation.</p></div><div className="supply-stage-rail" aria-label="Supply chain operating flow"><div><i>1</i><span><b>Procure</b><small>PO & supplier</small></span></div><em>→</em><div><i>2</i><span><b>Receive</b><small>GRN & PDI</small></span></div><em>→</em><div><i>3</i><span><b>Store</b><small>Warehouse</small></span></div><em>→</em><div><i>4</i><span><b>Dispatch</b><small>Fleet & shipment</small></span></div><em>→</em><div><i>5</i><span><b>Agency</b><small>Receipt</small></span></div><em>→</em><div><i>6</i><span><b>Field</b><small>Issue & install</small></span></div></div></section>
  <div className="supply-metrics"><Metric label="Open purchase orders" value={inv?.openPurchaseOrders} help="Awaiting full receipt or closure" onClick={()=>onNavigate?.('procurement',{__supplyDrill:true})}/><Metric label="On-hand inventory" value={inv?.onHand} help={`${fmt(inv?.lowStock)} low-stock position(s)`} onClick={()=>onNavigate?.('stock',{__supplyDrill:true})}/><Metric label="Active deliveries" value={activeDeliveries} help={`${fmt(tower?.overdue)} beyond ETA`} onClick={()=>onNavigate?.('shipments',{__supplyDrill:true,status:'IN_TRANSIT'})}/><Metric label="Operational exceptions" value={exceptions} help="Transit, receipt or field custody attention" onClick={()=>onNavigate?.('logistics-overview',{__supplyDrill:true})}/></div>
  <section className="supply-section-block"><div className="section-title-row"><div><span>DAILY WORKSPACES</span><h2>Open the area where work happens</h2><p>Primary actions stay visible. Specialist tools remain one level deeper so the control tower stays easy to scan.</p></div></div><div className="supply-folder-grid supply-folder-grid--clean">{areas.map(a=>{const primaryAllowed=allowed.has(a.primary[0]);const tools=a.tools.filter(([id])=>allowed.has(id));return <article className="supply-folder" key={a.id}><div className="supply-folder-head"><span className="folder-icon"><a.icon size={19}/></span><div><h2>{a.title}</h2><p>{a.text}</p></div></div>{primaryAllowed&&<button className="supply-primary-link" onClick={()=>onNavigate?.(a.primary[0],{__supplyDrill:true})}><span>{a.primary[1]}</span><ArrowRight size={15}/></button>}{tools.length>0&&<details className="supply-tools"><summary><ChevronDown size={14}/>More tools</summary><div className="supply-folder-links">{tools.map(([id,label])=><button key={id} onClick={()=>onNavigate?.(id,{__supplyDrill:true})}><span>{label}</span><ArrowRight size={14}/></button>)}</div></details>}</article>})}</div></section>
  <div className="supply-bottom-grid"><section className="panel supply-attention-panel"><div className="panel-head"><div><h2>Needs attention</h2><p>Only exceptions that currently require an operational decision.</p></div></div>{attention.length?<div className="attention-list">{attention.map(x=><button key={x.label} onClick={()=>onNavigate?.(x.target,{...x.filter,__supplyDrill:true})}><CircleAlert size={16}/><span><b>{x.label}</b><small>{x.help}</small></span><strong>{fmt(x.value)}</strong><ArrowRight size={14}/></button>)}</div>:<div className="supply-clear-state"><CheckCircle2 size={20}/><div><b>No immediate supply-chain exceptions</b><small>Current inventory, delivery and custody signals are within normal operating range.</small></div></div>}</section><section className="panel supply-capacity-panel"><div className="panel-head"><div><h2>Dispatch capacity</h2><p>Current resources available before assigning the next shipment.</p></div><button className="btn secondary small" onClick={()=>onNavigate?.('fleet',{__supplyDrill:true,availability:'AVAILABLE'})}>Open fleet</button></div><div className="capacity-list"><div><UsersRound size={17}/><span><b>{fmt(log?.availableDrivers)} drivers available</b><small>Not assigned to an active delivery</small></span></div><div><Truck size={17}/><span><b>{fmt(log?.availableVehicles)} vehicles available</b><small>Available for dispatch planning</small></span></div><div><ClipboardCheck size={17}/><span><b>{fmt(log?.inTransit)} shipments in transit</b><small>Currently moving through the network</small></span></div></div></section></div>
  <section className="table-panel supply-recent-table"><div className="panel-head padded"><div><h2>Recent dispatch activity</h2><p>Latest shipment movement only. Open a record for tracking, receipt or exception actions.</p></div><button className="btn secondary small" onClick={()=>onNavigate?.('shipments',{__supplyDrill:true})}>View all dispatches</button></div><div className="table-wrap"><table><thead><tr><th>Shipment</th><th>Agency</th><th>Work Package</th><th>Driver / Vehicle</th><th>Status</th><th>Last updated</th></tr></thead><tbody>{(log?.recentShipments||[]).slice(0,8).map(x=><tr className="clickable-row" key={x._id} onClick={()=>onNavigate?.('shipments',{q:x.shipmentNo,__supplyDrill:true})}><td><b>{x.shipmentNo}</b></td><td>{x.agencyId?.name||'Internal transfer'}</td><td>{x.workPackageId?.code||'—'}<small>{x.workPackageId?.name||''}</small></td><td>{x.driverId?.name||'Unassigned'}<small>{x.vehicleId?.registrationNo||''}</small></td><td><Status value={x.status}/></td><td>{x.updatedAt?new Date(x.updatedAt).toLocaleString():'—'}</td></tr>)}{!log?.recentShipments?.length&&<tr><td colSpan="6" className="empty">No shipment activity yet.</td></tr>}</tbody></table></div></section>
 </div>;
}
