import React,{useEffect,useMemo,useState}from'react';
import{MapContainer,TileLayer,CircleMarker,Popup,useMap}from'react-leaflet';
import'leaflet/dist/leaflet.css';
import{MapPin,Search,Navigation,UsersRound}from'lucide-react';
import{api,opPath}from'../../../core/api';
import{FilterButton,FilterDrawer,Status,DetailDrawer,InfoGrid}from'../../../components/common';

const tone=status=>status==='Complaint Raised'?'#b4473f':['Installation Completed','Closed'].includes(status)?'#2f7d5b':status==='Ready for Installation'?'#3d6f9f':status==='Dispatch Completed'?'#7b6a42':'#8b7854';
const idOf=v=>v&&typeof v==='object'?String(v._id||v.id||''):String(v||'');
function MapViewport({pins}){const map=useMap();useEffect(()=>{const refresh=()=>map.invalidateSize({pan:false});const frame=requestAnimationFrame(refresh);const timer=setTimeout(refresh,180);const container=map.getContainer();const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(refresh):null;observer?.observe(container);window.addEventListener('resize',refresh);return()=>{cancelAnimationFrame(frame);clearTimeout(timer);observer?.disconnect();window.removeEventListener('resize',refresh)}},[map]);useEffect(()=>{if(!pins.length)return;map.invalidateSize({pan:false});const bounds=pins.map(p=>[p.latitude,p.longitude]);map.fitBounds(bounds,{padding:[28,28],maxZoom:11})},[map,pins]);return null}
export function GeoOperationsPage({companyId,onNavigate}){
 const[data,setData]=useState({pins:[],districts:[],statuses:[]}),[portfolio,setPortfolio]=useState({programs:[],contracts:[],workOrders:[],workPackages:[],agencies:[]}),[options,setOptions]=useState({districts:[],talukas:[],villages:[],schemes:[],statuses:[],surveys:[]}),[q,setQ]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[detailBusy,setDetailBusy]=useState(false),[error,setError]=useState('');
 const[f,setF]=useState(()=>{const base={programId:'',contractId:'',workOrderId:'',workPackageId:'',agencyId:'',scheme:'',state:'',district:'',taluka:'',village:'',status:'',survey:''};try{return {...base,...JSON.parse(sessionStorage.getItem('opsynq.dashboard.filter.geo-operations')||'{}')}}catch{return base}});
 useEffect(()=>{Promise.all([api(opPath(companyId,'/portfolio')),api(opPath(companyId,'/beneficiary-filter-options'))]).then(([p,o])=>{setPortfolio(p||{});setOptions(o||{})}).catch(()=>{})},[companyId]);
 const load=()=>{setError('');const qs=new URLSearchParams();Object.entries(f).forEach(([k,v])=>{if(v)qs.set(k,v)});api(opPath(companyId,`/geo-overview?${qs}`)).then(setData).catch(e=>setError(e.message))};
 useEffect(()=>{if(!selected?.farmerId){setDetail(null);return;}let live=true;setDetailBusy(true);api(opPath(companyId,`/beneficiaries/${selected.farmerId}`)).then(d=>{if(live)setDetail(d)}).catch(()=>{if(live)setDetail(null)}).finally(()=>{if(live)setDetailBusy(false)});return()=>{live=false}},[companyId,selected?.farmerId]);
 useEffect(()=>{load()},[companyId,JSON.stringify(f)]);
 const pins=useMemo(()=>(data.pins||[]).filter(p=>Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude))&&Math.abs(Number(p.latitude))<=90&&Math.abs(Number(p.longitude))<=180).filter(p=>!q||`${p.beneficiaryId} ${p.name} ${p.mobile||''} ${p.scheme||''} ${p.district} ${p.taluka} ${p.village} ${p.agency?.name||''} ${p.program?.name||''} ${p.workOrder?.number||''} ${p.workPackage?.code||''}`.toLowerCase().includes(q.toLowerCase())),[data.pins,q]);
 const contracts=(portfolio.contracts||[]).filter(x=>!f.programId||idOf(x.programId)===f.programId),workOrders=(portfolio.workOrders||[]).filter(x=>(!f.programId||idOf(x.programId)===f.programId)&&(!f.contractId||idOf(x.contractId)===f.contractId)),packages=(portfolio.workPackages||[]).filter(x=>(!f.programId||idOf(x.programId)===f.programId)&&(!f.workOrderId||idOf(x.workOrderId)===f.workOrderId)&&(!f.agencyId||idOf(x.agencyId)===f.agencyId));
 const states=[...new Set((portfolio.workPackages||[]).map(x=>x.geography?.state).filter(Boolean))].sort();
 const setFilter=(k,v,clear=[])=>setF(cur=>{const n={...cur,[k]:v};clear.forEach(x=>n[x]='');return n});
 const filterCount=Object.values(f).filter(Boolean).length;
 const reset=()=>setF({programId:'',contractId:'',workOrderId:'',workPackageId:'',agencyId:'',scheme:'',state:'',district:'',taluka:'',village:'',status:'',survey:''});
 return <>
  <div className="command-bar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search beneficiary, Program, WO, package, agency or geography"/></div><FilterButton count={filterCount} onClick={()=>setFiltersOpen(true)}/><span className="result-count">{pins.length} mapped sites</span></div>
  <FilterDrawer open={filtersOpen} close={()=>setFiltersOpen(false)} title="Geo & delivery filters" onReset={reset}>
   <label>Program<select value={f.programId} onChange={e=>setFilter('programId',e.target.value,['contractId','workOrderId','workPackageId'])}><option value="">All programs</option>{(portfolio.programs||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label>
   <label>Contract / LOA<select value={f.contractId} onChange={e=>setFilter('contractId',e.target.value,['workOrderId','workPackageId'])}><option value="">All contracts</option>{contracts.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label>
   <label>Work order<select value={f.workOrderId} onChange={e=>setFilter('workOrderId',e.target.value,['workPackageId'])}><option value="">All work orders</option>{workOrders.map(x=><option key={x._id} value={x._id}>{x.number} · {x.title}</option>)}</select></label>
   <label>Work package<select value={f.workPackageId} onChange={e=>setFilter('workPackageId',e.target.value)}><option value="">All work packages</option>{packages.map(x=><option key={x._id} value={x._id}>{x.code} · {x.name||x.agencyId?.name||'Package'}</option>)}</select></label>
   <label>Agency<select value={f.agencyId} onChange={e=>setFilter('agencyId',e.target.value,['workPackageId'])}><option value="">All agencies</option>{(portfolio.agencies||[]).map(x=><option key={x._id} value={x._id}>{x.code} · {x.name}</option>)}</select></label>
   <label>Scheme<select value={f.scheme} onChange={e=>setFilter('scheme',e.target.value)}><option value="">All schemes</option>{(options.schemes||[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label>State<select value={f.state} onChange={e=>setFilter('state',e.target.value)}><option value="">All states</option>{states.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>District<select value={f.district} onChange={e=>setFilter('district',e.target.value)}><option value="">All districts</option>{(options.districts||[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Taluka / block<select value={f.taluka} onChange={e=>setFilter('taluka',e.target.value)}><option value="">All talukas</option>{(options.talukas||[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Village<select value={f.village} onChange={e=>setFilter('village',e.target.value)}><option value="">All villages</option>{(options.villages||[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Execution status<select value={f.status} onChange={e=>setFilter('status',e.target.value)}><option value="">All statuses</option>{(options.statuses||[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Survey status<select value={f.survey} onChange={e=>setFilter('survey',e.target.value)}><option value="">All survey states</option>{(options.surveys||[]).map(x=><option key={x}>{x}</option>)}</select></label>
  </FilterDrawer>
  {error&&<div className="alert error">{error}<button className="btn secondary small" onClick={load}>Retry</button></div>}
  <section className="geo-command-grid">
   <div className="geo-map-panel"><div className="geo-map-head"><span><MapPin size={17}/><b>Live execution geography</b></span><small>Filtered Program → Work Package → Beneficiary execution footprint</small></div><div className="geo-map-canvas">{pins.length?<MapContainer key={companyId} center={[20.5,78.9]} zoom={6} scrollWheelZoom preferCanvas><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapViewport pins={pins}/>{pins.map(p=><CircleMarker key={p.farmerId} center={[p.latitude,p.longitude]} radius={8} pathOptions={{color:tone(p.status),fillColor:tone(p.status),fillOpacity:.82,weight:2}} eventHandlers={{click:()=>setSelected(p)}}><Popup><div className="geo-popup"><b>{p.name}</b><span>{p.beneficiaryId}</span><span>{p.program?.code} · {p.workOrder?.number} · {p.workPackage?.code}</span><span>{p.village}, {p.district}</span><span>{p.status}</span><button onClick={()=>setSelected(p)}>View details</button></div></Popup></CircleMarker>)}</MapContainer>:<div className="map-empty"><MapPin/><b>No mapped sites match this view.</b></div>}</div></div>
   <aside className="geo-summary-panel"><div className="geo-summary-title"><Navigation size={17}/><div><b>Execution coverage</b><small>Current filtered portfolio</small></div></div><div className="geo-stat"><strong>{pins.length}</strong><span>Mapped beneficiaries</span></div><div className="geo-list">{(data.statuses||[]).slice(0,8).map(x=><button key={x.status} onClick={()=>setFilter('status',x.status)}><span><i style={{background:tone(x.status)}}/>{x.status}</span><b>{x.count}</b></button>)}</div><div className="geo-districts"><small>Top districts</small>{(data.districts||[]).slice(0,6).map(x=><button key={x.district} onClick={()=>setFilter('district',x.district)}><span>{x.district}</span><b>{x.count}</b></button>)}</div></aside>
  </section>
  {selected&&<DetailDrawer open title={selected.name} subtitle={`${selected.beneficiaryId} · ${selected.village||selected.district}`} close={()=>{setSelected(null);setDetail(null)}} actions={<button className="btn primary" onClick={()=>onNavigate?.('beneficiary-records',{farmerId:selected.farmerId,programId:selected.program?.id||'',workOrderId:selected.workOrder?.id||'',workPackageId:selected.workPackage?.id||'',agencyId:selected.agency?.id||''})}><UsersRound size={16}/> Open beneficiary 360°</button>}>
   <div className="detail-section"><h3>Delivery chain & location</h3><InfoGrid items={[{label:'Program',value:selected.program?.name},{label:'Work order',value:selected.workOrder?.number},{label:'Work package',value:selected.workPackage?.code},{label:'Agency',value:selected.agency?.name},{label:'Execution status',value:selected.status},{label:'Survey status',value:selected.surveyStatus},{label:'Scheme',value:selected.scheme},{label:'District',value:selected.district},{label:'Taluka',value:selected.taluka},{label:'Village',value:selected.village},{label:'Latitude',value:selected.latitude},{label:'Longitude',value:selected.longitude},{label:'Accuracy',value:selected.accuracy?`${Math.round(selected.accuracy)} m`:'Site record'},{label:'Geo source',value:selected.geoSource},{label:'Captured',value:selected.capturedAt?new Date(selected.capturedAt).toLocaleString():'Recorded site coordinate'}]}/></div>
   <div className="geo-coordinate-card"><MapPin size={18}/><div><b>{Number(selected.latitude).toFixed(6)}, {Number(selected.longitude).toFixed(6)}</b><small>{selected.geoSource} · {selected.district}</small></div></div>
   {detailBusy&&<div className="detail-empty">Loading beneficiary operational context…</div>}
   {detail&&<>
    <div className="detail-section"><h3>Survey & verification</h3><InfoGrid items={[{label:'Surveyor',value:detail.farmer?.surveyorName},{label:'Surveyor mobile',value:detail.farmer?.surveyorMobile},{label:'Survey date',value:detail.farmer?.surveyDate?new Date(detail.farmer.surveyDate).toLocaleString():''},{label:'Site depth',value:detail.farmer?.siteDepth},{label:'Land holding',value:detail.farmer?.landHoldingAcre},{label:'Actual head',value:detail.farmer?.actualHeadM},{label:'Source depth',value:detail.farmer?.sourceDepthFeet},{label:'Deviation / JSR',value:detail.farmer?.jsrDeviationYesNo}]}/></div>
    <div className="detail-section"><h3>Photo & field evidence</h3>{(()=>{const files=(detail.evidenceSubmissions||[]).flatMap(sub=>(sub.files||[]).map(file=>({...file,label:sub.requirementId?.label||sub.stage,status:sub.status})));return files.length?<div className="beneficiary-evidence-grid">{files.slice(0,12).map((f,i)=><a key={`${f.url}-${i}`} href={f.url} target="_blank" rel="noreferrer" className="beneficiary-evidence-card"><img src={f.url} alt={f.label||`Evidence ${i+1}`}/><span><b>{f.label||`Evidence ${i+1}`}</b><small>{f.status||'SUBMITTED'}</small></span></a>)}</div>:<div className="detail-empty">No synchronized evidence files are available for this mapped site yet.</div>})()}</div>
    <div className="detail-section"><h3>Material, assets & service</h3><InfoGrid items={[{label:'Shipments linked',value:detail.shipments?.length||0},{label:'Material issues',value:detail.materialIssues?.length||0},{label:'Installed assets',value:detail.assets?.length||0},{label:'Open service cases',value:(detail.serviceCases||[]).filter(x=>!['RESOLVED','CLOSED','CANCELLED'].includes(x.status)).length},{label:'Compliance records',value:detail.compliance?.length||0},{label:'Evidence controls',value:detail.evidenceChecklist?.length||0}]}/></div>
   </>}
  </DetailDrawer>}
 </>
}
