const os=require('os');
const crypto=require('crypto');
const AutomationRun=require('../models/platform/AutomationRun');
const AutomationLock=require('../models/platform/AutomationLock');
const Organization=require('../models/platform/Organization');
const ServiceCase=require('../models/platform/ServiceCase');
const CommercialClaim=require('../models/platform/CommercialClaim');
const AssetServicePlan=require('../models/platform/AssetServicePlan');
const InventorySerial=require('../models/platform/InventorySerial');
const InstalledAsset=require('../models/platform/InstalledAsset');
const InsurancePolicy=require('../models/platform/InsurancePolicy');
const Notification=require('../models/platform/Notification');
const ApprovalRequest=require('../models/platform/ApprovalRequest');
const {buildReplenishment,createReorderNotifications,autoPrepareReplenishmentDrafts}=require('../controllers/platform/intelligenceController');

const OWNER=`${os.hostname()}-${process.pid}-${crypto.randomBytes(4).toString('hex')}`;
const ACTIVE_SERVICE=['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART'];
const ACTIVE_CLAIM=['SUBMITTED','UNDER_REVIEW'];
const recentNotification=async(companyId,entityType,entityId,title)=>Notification.exists({companyId,entityType,entityId,title,createdAt:{$gte:new Date(Date.now()-24*3600*1000)}});
const notify=async(companyId,type,title,message,entityType,entityId,actionUrl='',recipientRoles=[])=>{
 if(await recentNotification(companyId,entityType,entityId,title))return false;
 await Notification.create({companyId,type,title,message,entityType,entityId,actionUrl,recipientRoles});return true;
};

async function ensureSystemProposal({companyId,type,title,description,entityType,entityId,payload={}}){
 const existing=await ApprovalRequest.findOne({companyId,type,entityType,entityId,status:'PENDING',requestOrigin:'SYSTEM'}).lean();
 if(existing)return existing;
 return ApprovalRequest.create({companyId,requestNo:`APR-SYS-${Date.now().toString(36).toUpperCase()}-${String(entityId||'GEN').slice(-4).toUpperCase()}`,type,title,description,entityType,entityId,requestedBy:null,requestOrigin:'SYSTEM',payload});
}

const stateFor=(dueAt,warningHours=4)=>{if(!dueAt)return'NOT_APPLICABLE';const ms=new Date(dueAt).getTime()-Date.now();if(ms<0)return'BREACHED';if(ms<=warningHours*3600000)return'DUE_SOON';return'ON_TRACK'};

async function acquire(key,minutes=8){const now=new Date(),expiresAt=new Date(Date.now()+minutes*60000);try{const row=await AutomationLock.findOneAndUpdate({key,$or:[{expiresAt:{$lte:now}},{owner:OWNER}]},{$set:{owner:OWNER,expiresAt}},{new:true,upsert:true,setDefaultsOnInsert:true});return row?.owner===OWNER}catch(e){if(e.code===11000)return false;throw e}}
async function release(key){await AutomationLock.deleteOne({key,owner:OWNER}).catch(()=>{})}

async function serviceSla(companyId){const q={status:{$in:ACTIVE_SERVICE},...(companyId?{companyId}:{})};const rows=await ServiceCase.find(q);let changed=0,alerts=0,breached=0,dueSoon=0;for(const row of rows){const next=stateFor(row.dueAt,4);if(next==='BREACHED')breached++;if(next==='DUE_SOON')dueSoon++;if(row.slaState!==next){const previous=row.slaState;row.slaState=next;await row.save();changed++;if(['BREACHED','DUE_SOON'].includes(next)){alerts+=await notify(row.companyId,next==='BREACHED'?'CRITICAL':'WARNING',`Service SLA ${next==='BREACHED'?'breached':'due soon'} · ${row.caseNo}`,`${row.title} moved from ${previous} to ${next}.`,'ServiceCase',row._id,'service-cases',['company_owner','company_admin','operations_manager','quality_user'])?1:0;}}if(['BREACHED','DUE_SOON'].includes(next)){await ensureSystemProposal({companyId:row.companyId,type:'SERVICE_EXCEPTION',title:`Confirm service escalation · ${row.caseNo}`,description:`${row.title} is ${next==='BREACHED'?'past its SLA':'approaching its SLA'}. Review and confirm the proposed priority escalation.`,entityType:'ServiceCase',entityId:row._id,payload:{proposalKind:'SERVICE_PRIORITY_ESCALATION',proposedPriority:next==='BREACHED'?'CRITICAL':'HIGH',slaState:next,caseNo:row.caseNo}});}}return{scanned:rows.length,changed,breached,dueSoon,alerts}}
async function claimSla(companyId){const q={status:{$in:ACTIVE_CLAIM},...(companyId?{companyId}:{})};const rows=await CommercialClaim.find(q);let changed=0,alerts=0,breached=0,dueSoon=0;for(const row of rows){const next=stateFor(row.dueAt,8);if(next==='BREACHED')breached++;if(next==='DUE_SOON')dueSoon++;if(row.slaState!==next){const previous=row.slaState;row.slaState=next;await row.save();changed++;if(['BREACHED','DUE_SOON'].includes(next)){alerts+=await notify(row.companyId,next==='BREACHED'?'CRITICAL':'WARNING',`Claim SLA ${next==='BREACHED'?'breached':'due soon'} · ${row.claimNo}`,`${row.title} moved from ${previous} to ${next}.`,'CommercialClaim',row._id,'claims',['company_owner','company_admin','program_manager','finance_user'])?1:0;}}if(['BREACHED','DUE_SOON'].includes(next)){await ensureSystemProposal({companyId:row.companyId,type:'CLAIM_EXCEPTION',title:`Confirm claim follow-up · ${row.claimNo}`,description:`${row.title} is ${next==='BREACHED'?'past its review SLA':'approaching its review SLA'}. Confirm a formal follow-up flag for the finance/program team.`,entityType:'CommercialClaim',entityId:row._id,payload:{proposalKind:'CLAIM_FOLLOWUP',slaState:next,claimNo:row.claimNo}});}}return{scanned:rows.length,changed,breached,dueSoon,alerts}}
async function warranty(companyId){const q={status:{$nin:['CANCELLED']},...(companyId?{companyId}:{})};const rows=await AssetServicePlan.find(q);let changed=0,expiring=0,expired=0,alerts=0;for(const row of rows){const days=(new Date(row.endDate).getTime()-Date.now())/86400000;const next=days<0?'EXPIRED':days<=30?'EXPIRING':'ACTIVE';if(next==='EXPIRING')expiring++;if(next==='EXPIRED')expired++;if(row.status!==next){row.status=next;await row.save();changed++;if(['EXPIRING','EXPIRED'].includes(next)){alerts+=await notify(row.companyId,next==='EXPIRED'?'CRITICAL':'WARNING',`${row.planType} ${next.toLowerCase()}`,`${row.planType} coverage ${next==='EXPIRED'?'has expired':'expires within 30 days'}.`,'AssetServicePlan',row._id,'service-plans',['company_owner','company_admin','operations_manager','quality_user'])?1:0;}}if(['EXPIRING','EXPIRED'].includes(next)){await ensureSystemProposal({companyId:row.companyId,type:'SERVICE_EXCEPTION',title:`Confirm ${row.planType} coverage review`,description:`Coverage is ${next.toLowerCase()}. Confirm a renewal/review action so the service team can follow it through.`,entityType:'AssetServicePlan',entityId:row._id,payload:{proposalKind:'COVERAGE_REVIEW',coverageType:row.planType,state:next}});}}return{scanned:rows.length,changed,expiring,expired,alerts}}

async function insurance(companyId){const q={status:{$nin:['CANCELLED','CLAIM_SETTLED','DRAFT']},...(companyId?{companyId}:{})};const rows=await InsurancePolicy.find(q);let changed=0,expiring=0,expired=0,alerts=0;for(const row of rows){if(row.status==='CLAIM_OPEN')continue;const days=(new Date(row.endDate).getTime()-Date.now())/86400000;const next=days<0?'EXPIRED':days<=30?'EXPIRING':'ACTIVE';if(next==='EXPIRING')expiring++;if(next==='EXPIRED')expired++;if(row.status!==next){row.status=next;await row.save();changed++;if(['EXPIRING','EXPIRED'].includes(next)){alerts+=await notify(row.companyId,next==='EXPIRED'?'CRITICAL':'WARNING',`Insurance policy ${next.toLowerCase()} · ${row.policyNumber}`,`Insurance coverage ${next==='EXPIRED'?'has expired':'expires within 30 days'}.`,'InsurancePolicy',row._id,'insurance',['company_owner','company_admin','finance_user','quality_user'])?1:0;}}if(['EXPIRING','EXPIRED'].includes(next)){await ensureSystemProposal({companyId:row.companyId,type:'OTHER',title:`Confirm insurance coverage review · ${row.policyNumber}`,description:`Policy coverage is ${next.toLowerCase()}. Confirm a renewal/review flag before the finance/assurance team proceeds.`,entityType:'InsurancePolicy',entityId:row._id,payload:{proposalKind:'INSURANCE_REVIEW',state:next,policyNumber:row.policyNumber}});}}return{scanned:rows.length,changed,expiring,expired,alerts}}

async function replenishment(companyId){let rows=await buildReplenishment(companyId,{persist:true,withAi:false});const sixHours=6*3600000;const aiStale=!!(process.env.AI_PROVIDER_API_KEY||process.env.GEMINI_API_KEY)&&rows.some(x=>!x.ai?.generatedAt||Date.now()-new Date(x.ai.generatedAt).getTime()>sixHours);if(aiStale)rows=await buildReplenishment(companyId,{persist:true,withAi:true});await createReorderNotifications(companyId,rows);const prepared=await autoPrepareReplenishmentDrafts(companyId,rows);return{plans:rows.length,critical:rows.filter(x=>x.urgency==='CRITICAL').length,high:rows.filter(x=>x.urgency==='HIGH').length,suggestedUnits:rows.reduce((n,x)=>n+Number(x.suggestedQty||0),0),preparedDrafts:prepared,intelligence:aiStale?'refreshed':'current'}}

async function integrity(companyId){const base=companyId?{companyId}:{};const installedSerials=await InventorySerial.find({...base,status:'INSTALLED'}).select('_id companyId serialNumber farmerId').lean();const assetSerialIds=new Set((await InstalledAsset.find(base).select('inventorySerialId').lean()).map(x=>String(x.inventorySerialId)));
 const missingAsset=installedSerials.filter(x=>!assetSerialIds.has(String(x._id)));
 const activeAssets=await InstalledAsset.find({...base,status:'ACTIVE'}).select('_id companyId inventorySerialId serialNumber').lean();const serialIds=activeAssets.map(x=>x.inventorySerialId);const serialMap=new Map((await InventorySerial.find({_id:{$in:serialIds}}).select('_id status').lean()).map(x=>[String(x._id),x.status]));const custodyMismatch=activeAssets.filter(x=>serialMap.get(String(x.inventorySerialId))!=='INSTALLED');
 return{installedSerials:installedSerials.length,activeAssets:activeAssets.length,missingInstalledAsset:missingAsset.length,custodyMismatch:custodyMismatch.length,examples:{missingInstalledAsset:missingAsset.slice(0,10).map(x=>x.serialNumber),custodyMismatch:custodyMismatch.slice(0,10).map(x=>x.serialNumber)}}}
const JOBS={service_sla:serviceSla,claim_sla:claimSla,warranty,insurance,replenishment,integrity};
async function executeJob(job,{companyId=null,trigger='SYSTEM',requestedBy=null,useLock=true}={}){if(!JOBS[job])throw new Error(`Unknown automation job: ${job}`);const lockKey=`automation:${job}:${companyId||'global'}`;if(useLock&&!await acquire(lockKey)){return await AutomationRun.create({companyId,job,trigger,status:'SKIPPED',completedAt:new Date(),metrics:{reason:'Another instance owns the automation lease.'},requestedBy,host:OWNER})}const run=await AutomationRun.create({companyId,job,trigger,status:'RUNNING',requestedBy,host:OWNER});try{run.metrics=await JOBS[job](companyId);run.status='COMPLETED';run.completedAt=new Date();await run.save();return run}catch(e){run.status='FAILED';run.errors=[e.message];run.completedAt=new Date();await run.save();return run}finally{if(useLock)await release(lockKey)}}
async function runCycle(trigger='SCHEDULED'){const companies=await Organization.find({type:'COMPANY',status:'ACTIVE'}).select('_id').lean();const results=[];for(const c of companies){for(const job of Object.keys(JOBS))results.push(await executeJob(job,{companyId:c._id,trigger}));}return results}
let timer=null;function startScheduler(){if(timer)return;const run=()=>runCycle('SCHEDULED').catch(e=>console.error('Opsynq automation cycle failed:',e.message));setTimeout(run,60*1000);timer=setInterval(run,15*60*1000);console.log('Opsynq automation scheduler active (15-minute cycle).')}
module.exports={executeJob,runCycle,startScheduler,JOBS};
