const Organization=require('../models/platform/Organization');
const Farmer=require('../models/Farmer');
const BeneficiaryContext=require('../models/platform/BeneficiaryContext');
const InstalledAsset=require('../models/platform/InstalledAsset');
const InventorySerial=require('../models/platform/InventorySerial');
const InventoryBalance=require('../models/platform/InventoryBalance');
const StockMovement=require('../models/platform/StockMovement');
const Shipment=require('../models/platform/Shipment');
const MaterialIssue=require('../models/platform/MaterialIssue');
const ServiceCase=require('../models/platform/ServiceCase');
const CommercialClaim=require('../models/platform/CommercialClaim');
const RmsDevice=require('../models/platform/RmsDevice');
const RmsAlert=require('../models/platform/RmsAlert');
const RmsTelemetry=require('../models/platform/RmsTelemetry');
const AuditLog=require('../models/platform/AuditLog');
const AdminChangeLog=require('../models/AdminChangeLog');
const PurchaseOrder=require('../models/platform/PurchaseOrder');
const GoodsReceipt=require('../models/platform/GoodsReceipt');
const InsurancePolicy=require('../models/platform/InsurancePolicy');
const PDIRecord=require('../models/platform/PDIRecord');
const ComplianceRecord=require('../models/platform/ComplianceRecord');
const ApprovalRequest=require('../models/platform/ApprovalRequest');
const PlatformUser=require('../models/platform/PlatformUser');
const LegacyUser=require('../models/User');

const isoDate=v=>v?new Date(v).toISOString().slice(0,10):'';
const isoTime=v=>v?new Date(v).toISOString():'';
const num=v=>Number(v||0);
const label=v=>String(v||'').replaceAll('_',' ');

const REPORTS={
 'executive-summary':{title:'Executive Operating Summary',category:'Management',cadence:['DAILY','WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Cross-functional operating summary covering beneficiaries, installations, service, RMS and commercial realization.'},
 'district-agency-synopsis':{title:'District × Agency Synopsis',category:'Execution',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'District and installer execution position with survey, installation and complaint counts.'},
 'beneficiary-progress':{title:'Beneficiary Progress Register',category:'Execution',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Beneficiary-level survey, material, installation, commissioning and complaint status.'},
 'agency-performance':{title:'Agency Performance Register',category:'Execution',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Agency portfolio progress, completion, complaints and RMS coverage.'},
 'technician-productivity':{title:'Technician Productivity Register',category:'Field Operations',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Installer/technician activity based on installed assets, assigned service cases and beneficiary execution.'},
 'installation-register':{title:'Installation & Commissioning Register',category:'Field Operations',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Installation completion, commissioning and serialized asset traceability.'},
 'asset-imei-mapping':{title:'Asset & IMEI Mapping Register',category:'Asset Control',cadence:['DAILY','MONTHLY','YEARLY'],description:'Beneficiary-to-serialized asset/controller/IMEI mapping.'},
 'inventory-serial-register':{title:'Serialized Inventory Register',category:'Inventory',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Serial/barcode custody state across warehouse, agency, beneficiary and installed lifecycle.'},
 'stock-position-register':{title:'Stock Position & Reorder Register',category:'Inventory',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Warehouse-wise on-hand, allocated, transit, damaged and reorder exposure.'},
 'stock-movement-register':{title:'Stock Movement & Custody Ledger',category:'Inventory',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Auditable receipt, transfer, dispatch, issue, install, return and adjustment movements.'},
 'barcode-traceability-register':{title:'Barcode / QR Traceability Register',category:'Asset Control',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Scanned identity, encoded metadata, current custody and installation linkage for serialized hardware.'},
 'procurement-register':{title:'Purchase Order Register',category:'Procurement',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Purchase orders, supplier, quantities, value and receipt progress.'},
 'goods-receipt-register':{title:'Goods Receipt / GRN Register',category:'Procurement',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Goods receipt, accepted/rejected quantity and source PO traceability.'},
 'dispatch-delivery-register':{title:'Dispatch, Delivery & POD Register',category:'Logistics',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Shipment movement, delivery state, agency destination and proof-of-delivery readiness.'},
 'material-custody-register':{title:'Material Issue & Custody Register',category:'Inventory',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Material issued to agency/technician/beneficiary with quantity and custody status.'},
 'service-sla-register':{title:'Service, Complaint & SLA Register',category:'Service',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Complaint/breakdown cases, assignment, SLA, resolution and beneficiary/agency traceability.'},
 'rms-device-health':{title:'RMS Device Health Register',category:'RMS',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Mapped RMS assets, latest connectivity/telemetry timestamps and commissioning state.'},
 'rms-alert-register':{title:'RMS Alert & Incident Register',category:'RMS',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'RMS alerts with agency, technician and service-case escalation traceability.'},
 'rms-daily-performance':{title:'RMS Energy / Runtime Performance',category:'RMS',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Telemetry roll-up for power, energy, runtime and water output.'},
 'insurance-warranty-register':{title:'Insurance / Warranty Coverage Register',category:'Assurance',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Beneficiary/asset insurance coverage, expiry and claim position.'},
 'pdi-quality-register':{title:'PDI Quality Inspection Register',category:'Quality',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Pre-dispatch inspection result, disposition, evidence and serialized material traceability.'},
 'compliance-evidence-register':{title:'Compliance & Evidence Register',category:'Compliance',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Installation/final-inspection/commissioning compliance checks with review status and evidence counts.'},
 'approval-exception-register':{title:'Approvals & Exception Decisions',category:'Governance',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Controlled approvals, exceptions, requester/decision timestamps and decision rationale.'},
 'commercial-claims-register':{title:'Commercial Claims & Payment Register',category:'Commercial',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Claim lifecycle and eligible/approved/paid/blocked commercial values.'},
 'commercial-exposure-summary':{title:'Commercial Exposure & Realization Summary',category:'Commercial',cadence:['WEEKLY','MONTHLY','QUARTERLY','YEARLY'],description:'Procurement commitment, tax exposure and claim realization in one management summary.'},
 'invoice-waybill-readiness':{title:'Invoice / Waybill / Delivery Challan Register',category:'GST & Logistics Readiness',cadence:['DAILY','MONTHLY','QUARTERLY','YEARLY'],description:'Operational source register for invoice, waybill and delivery-challan reconciliation; not a GST return.'},
 'audit-trail':{title:'System Audit Trail Register',category:'Governance',cadence:['DAILY','WEEKLY','MONTHLY','YEARLY'],description:'Who changed what, when, from which client, with before/after traceability.'},
 'statutory-readiness':{title:'India Statutory Data Readiness',category:'Compliance',cadence:['MONTHLY','QUARTERLY','HALF_YEARLY','YEARLY'],description:'Data-readiness checklist for GST/e-way/MCA/MSME/TDS workflows. This is a readiness report, not statutory filing.'},
 'jcr-office':{title:'JCR Office Report',category:'Government / Program',cadence:['WEEKLY','MONTHLY','YEARLY'],description:'Office-side beneficiary execution register.'},
 'jcr-installer':{title:'JCR Installer Report',category:'Government / Program',cadence:['WEEKLY','MONTHLY','YEARLY'],description:'Installer-side execution and serialized equipment register.'},
};

function dateWindow(query={}){
 const from=query.from?new Date(query.from):null,to=query.to?new Date(query.to):null;
 if(from&&!Number.isNaN(from.getTime()))from.setHours(0,0,0,0);
 if(to&&!Number.isNaN(to.getTime()))to.setHours(23,59,59,999);
 return{from:from&&!Number.isNaN(from.getTime())?from:null,to:to&&!Number.isNaN(to.getTime())?to:null};
}
function dateMatch(field,{from,to}){if(!from&&!to)return{};const q={};if(from)q.$gte=from;if(to)q.$lte=to;return{[field]:q};}
function baseMatch(scope){const q={};if(scope.companyIds?.length)q.companyId={$in:scope.companyIds};if(scope.agencyIds?.length)q.agencyId={$in:scope.agencyIds};return q;}
function farmerMatch(scope){return scope.farmerIds?.length?{_id:{$in:scope.farmerIds}}:{};}
function contextMatch(scope){const q=baseMatch(scope);if(scope.farmerIds?.length)q.farmerId={$in:scope.farmerIds};return q;}
async function scopedFarmerIds(scope){if(scope.farmerIds?.length)return scope.farmerIds;const q={};if(scope.companyIds?.length)q.companyId={$in:scope.companyIds};if(scope.agencyIds?.length)q.agencyId={$in:scope.agencyIds};const rows=await BeneficiaryContext.find(q).select('farmerId').lean();return[...new Set(rows.map(x=>String(x.farmerId)).filter(Boolean))];}
function applyTextFilters(rows,query={}){let out=rows;if(query.district){const q=String(query.district).toLowerCase();out=out.filter(r=>String(r.District||'').toLowerCase()===q);}if(query.agency){const q=String(query.agency).toLowerCase();out=out.filter(r=>String(r.Agency||r.Installer||'').toLowerCase().includes(q));}if(query.search){const q=String(query.search).toLowerCase();out=out.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q)));}return out;}

async function contextsFor(scope){return BeneficiaryContext.find(contextMatch(scope)).populate('farmerId').populate('agencyId','name code').populate('programId','name code scheme component').populate('workPackageId','code name geography').lean();}

async function rowsFor(scope,type,query={}){
 const range=dateWindow(query),match=baseMatch(scope),contextsNeeded=['executive-summary','district-agency-synopsis','beneficiary-progress','agency-performance','jcr-office','jcr-installer'].includes(type);
 const contexts=contextsNeeded?await contextsFor(scope):[];let rows=[];
 if(type==='executive-summary'){
  const farmerIds=contexts.map(x=>x.farmerId?._id).filter(Boolean),agencyIds=[...new Set(contexts.map(x=>String(x.agencyId?._id||x.agencyId||'')).filter(Boolean))];
  const qFarm=farmerIds.length?{_id:{$in:farmerIds}}:{_id:{$in:[]}},qAssets={...match,...dateMatch('installedAt',range)},qService={...match,...dateMatch('openedAt',range)},qAlerts={...match,...dateMatch('firstDetectedAt',range)},qClaims={...match,...dateMatch('createdAt',range)};
  const [beneficiaries,completed,assets,openService,breached,criticalAlerts,claims]=await Promise.all([
   Farmer.countDocuments(qFarm),Farmer.countDocuments({...qFarm,applicationStatus:{$in:['Installation Completed','Closed','Complaint Raised']}}),InstalledAsset.countDocuments(qAssets),ServiceCase.countDocuments({...qService,status:{$in:['OPEN','ASSIGNED','IN_PROGRESS','WAITING_PART']}}),ServiceCase.countDocuments({...qService,slaState:'BREACHED'}),RmsAlert.countDocuments({...qAlerts,status:'ACTIVE',severity:'CRITICAL'}),CommercialClaim.aggregate([{$match:qClaims},{$group:{_id:null,eligible:{$sum:'$eligibleAmount'},approved:{$sum:'$approvedAmount'},paid:{$sum:'$paidAmount'},blocked:{$sum:'$blockedAmount'}}}])]);
  const c=claims[0]||{};rows=[{Period_From:isoDate(range.from),Period_To:isoDate(range.to),Agencies:agencyIds.length,Beneficiaries:beneficiaries,Installation_Completed:completed,Assets_Installed:assets,Open_Service_Cases:openService,SLA_Breaches:breached,Critical_RMS_Alerts:criticalAlerts,Claim_Eligible:num(c.eligible),Claim_Approved:num(c.approved),Claim_Paid:num(c.paid),Claim_Blocked:num(c.blocked)}];
 }else if(type==='district-agency-synopsis'){
  const map=new Map();for(const x of contexts){const f=x.farmerId;if(!f)continue;const district=f.district||x.workPackageId?.geography?.district||'Unspecified',agency=x.agencyId?.name||'Unassigned',key=`${district}||${agency}`,r=map.get(key)||{District:district,Agency:agency,Agency_Code:x.agencyId?.code||'',Beneficiaries:0,Survey_Pending:0,Survey_Completed:0,Ready_For_Installation:0,Installation_Completed:0,Complaints:0};r.Beneficiaries++;if(f.inspectionStatus==='Completed')r.Survey_Completed++;else r.Survey_Pending++;if(f.applicationStatus==='Ready for Installation')r.Ready_For_Installation++;if(['Installation Completed','Closed','Complaint Raised'].includes(f.applicationStatus))r.Installation_Completed++;if(f.applicationStatus==='Complaint Raised'||['Open','In Progress'].includes(f.complaintStatus))r.Complaints++;map.set(key,r);}rows=[...map.values()].sort((a,b)=>a.District.localeCompare(b.District)||a.Agency.localeCompare(b.Agency));
 }else if(type==='beneficiary-progress'){
  rows=contexts.map(x=>{const f=x.farmerId||{};return{Application_Number:f.beneficiaryId||'',Beneficiary_Name:f.beneficiaryName||'',Mobile:f.mobile||'',District:f.district||'',Taluka:f.taluka||'',Village:f.village||'',Scheme:f.scheme||'',Agency:x.agencyId?.name||'',Work_Package:x.workPackageId?.code||'',Survey_Status:f.inspectionStatus||'',Survey_Date:isoDate(f.surveyDate),Material_Received:f.materialReceivedConfirmationYesNo||'',Application_Status:f.applicationStatus||'',Installation_Date:isoDate(f.installationCompletionDate||f.installationDate),Commissioning_Date:isoDate(f.commissioningDate),Complaint_Status:f.complaintStatus||'',Pump_Serial:f.pumpNoUnique||'',Motor_Serial:f.motorNoUnique||'',Controller_Serial:f.controllerNoUnique||'',IMEI:f.imeiNoUnique||''}});
 }else if(type==='agency-performance'){
  const map=new Map();for(const x of contexts){const f=x.farmerId||{},id=String(x.agencyId?._id||x.agencyId||'unassigned'),r=map.get(id)||{Agency:x.agencyId?.name||'Unassigned',Agency_Code:x.agencyId?.code||'',Beneficiaries:0,Survey_Completed:0,Installation_Completed:0,Open_Complaints:0};r.Beneficiaries++;if(f.inspectionStatus==='Completed')r.Survey_Completed++;if(['Installation Completed','Closed','Complaint Raised'].includes(f.applicationStatus))r.Installation_Completed++;if(f.applicationStatus==='Complaint Raised'||['Open','In Progress'].includes(f.complaintStatus))r.Open_Complaints++;map.set(id,r);}
  const [deviceCounts,alertCounts]=await Promise.all([RmsDevice.aggregate([{$match:match},{$group:{_id:'$agencyId',count:{$sum:1}}}]),RmsAlert.aggregate([{$match:{...match,status:'ACTIVE'}},{$group:{_id:'$agencyId',count:{$sum:1}}}])]),dm=new Map(deviceCounts.map(x=>[String(x._id||''),x.count])),am=new Map(alertCounts.map(x=>[String(x._id||''),x.count]));
  rows=[...map.entries()].map(([id,r])=>({...r,RMS_Devices:dm.get(id)||0,Active_RMS_Alerts:am.get(id)||0,Completion_Percent:r.Beneficiaries?Math.round(r.Installation_Completed*100/r.Beneficiaries):0}));
 }else if(type==='technician-productivity'){
  const assets=await InstalledAsset.find({...match,...dateMatch('installedAt',range)}).populate('technicianUserId','username mobile').populate('agencyId','name code').lean();const cases=await ServiceCase.find({...match,...dateMatch('openedAt',range),assignedToLegacyUser:{$ne:null}}).populate('assignedToLegacyUser','username mobile').lean();const map=new Map();for(const a of assets){const id=String(a.technicianUserId?._id||a.technicianUserId||'');if(!id)continue;const r=map.get(id)||{Technician:a.technicianUserId?.username||'',Mobile:a.technicianUserId?.mobile||'',Agency:a.agencyId?.name||'',Assets_Installed:0,Service_Cases:0,Resolved_Cases:0};r.Assets_Installed++;map.set(id,r);}for(const c of cases){const id=String(c.assignedToLegacyUser?._id||c.assignedToLegacyUser||'');if(!id)continue;const r=map.get(id)||{Technician:c.assignedToLegacyUser?.username||'',Mobile:c.assignedToLegacyUser?.mobile||'',Agency:'',Assets_Installed:0,Service_Cases:0,Resolved_Cases:0};r.Service_Cases++;if(['RESOLVED','CLOSED'].includes(c.status))r.Resolved_Cases++;map.set(id,r);}rows=[...map.values()].sort((a,b)=>b.Assets_Installed-a.Assets_Installed);
 }else if(type==='installation-register'){
  const assets=await InstalledAsset.find({...match,...dateMatch('installedAt',range)}).populate('farmerId','beneficiaryId beneficiaryName district village commissioningDate').populate('agencyId','name code').populate('technicianUserId','username mobile').populate('itemId','sku name brand model').sort({installedAt:-1}).lean();rows=assets.map(a=>({Application_Number:a.farmerId?.beneficiaryId||'',Beneficiary_Name:a.farmerId?.beneficiaryName||'',District:a.farmerId?.district||'',Village:a.farmerId?.village||'',Agency:a.agencyId?.name||'',Technician:a.technicianUserId?.username||'',Technician_Mobile:a.technicianUserId?.mobile||'',Asset_Role:a.assetRole,SKU:a.itemId?.sku||'',Item:a.itemId?.name||'',Brand:a.itemId?.brand||'',Model:a.itemId?.model||'',Serial_Number:a.serialNumber||'',Installed_At:isoTime(a.installedAt),Commissioning_Date:isoDate(a.farmerId?.commissioningDate),Asset_Status:a.status||''}));
 }else if(type==='asset-imei-mapping'){
  const assets=await InstalledAsset.find({...match,...dateMatch('installedAt',range)}).populate('farmerId').populate('itemId','sku name brand model installationRole').populate('agencyId','name code').sort({installedAt:-1}).lean();rows=assets.map(a=>({Application_Number:a.farmerId?.beneficiaryId||'',Beneficiary_Name:a.farmerId?.beneficiaryName||'',District:a.farmerId?.district||'',Agency:a.agencyId?.name||'',Asset_Role:a.assetRole||'',SKU:a.itemId?.sku||'',Item:a.itemId?.name||'',Brand:a.itemId?.brand||'',Model:a.itemId?.model||'',Serial_Number:a.serialNumber||'',IMEI:a.assetRole==='CONTROLLER'?(a.farmerId?.imeiNoUnique||''):'',Installed_At:isoTime(a.installedAt),Status:a.status||''}));
 }else if(type==='inventory-serial-register'){
  const items=await InventorySerial.find({...match,...dateMatch('updatedAt',range)}).populate('itemId','sku name brand model').populate('warehouseId','code name').populate('agencyId','code name').populate('farmerId','beneficiaryId beneficiaryName').sort({updatedAt:-1}).lean();rows=items.map(x=>({Serial_Number:x.serialNumber,Barcode:x.barcodeValue||'',SKU:x.itemId?.sku||'',Item:x.itemId?.name||'',Brand:x.itemId?.brand||'',Model:x.itemId?.model||'',Status:x.status,Warehouse:x.warehouseId?.name||'',Agency:x.agencyId?.name||'',Beneficiary_ID:x.farmerId?.beneficiaryId||'',Beneficiary:x.farmerId?.beneficiaryName||'',Installed_At:isoTime(x.installedAt),Last_Updated:isoTime(x.updatedAt)}));
 }else if(type==='stock-position-register'){
  const docs=await InventoryBalance.find({companyId:{$in:scope.companyIds||[]}}).populate('itemId','sku name category brand model minStock reorderLevel').populate('warehouseId','code name type').sort({updatedAt:-1}).lean();rows=docs.map(x=>{const threshold=num(x.itemId?.reorderLevel||x.itemId?.minStock),available=Math.max(0,num(x.onHand)-num(x.allocated));return{Warehouse_Code:x.warehouseId?.code||'',Warehouse:x.warehouseId?.name||'',Warehouse_Type:x.warehouseId?.type||'',SKU:x.itemId?.sku||'',Item:x.itemId?.name||'',Category:x.itemId?.category||'',Brand:x.itemId?.brand||'',Model:x.itemId?.model||'',On_Hand:num(x.onHand),Allocated:num(x.allocated),Available:available,In_Transit:num(x.inTransit),Damaged:num(x.damaged),Reorder_Level:threshold,Reorder_Gap:Math.max(0,threshold-num(x.onHand)),Stock_Health:threshold>0&&num(x.onHand)<=threshold?'REORDER':'OK',Last_Movement:isoTime(x.lastMovementAt),Last_Updated:isoTime(x.updatedAt)}});
 }else if(type==='stock-movement-register'){
  const docs=await StockMovement.find({companyId:{$in:scope.companyIds||[]},...dateMatch('occurredAt',range)}).populate('itemId','sku name').populate('serialIds','serialNumber barcodeValue').populate('fromWarehouseId','code name').populate('toWarehouseId','code name').populate('fromOrganizationId','code name type').populate('toOrganizationId','code name type').sort({occurredAt:-1}).lean();rows=docs.map(x=>({Occurred_At:isoTime(x.occurredAt),Movement_Type:x.movementType,SKU:x.itemId?.sku||'',Item:x.itemId?.name||'',Quantity:num(x.quantity),Serial_Count:(x.serialIds||[]).length,Serials:(x.serialIds||[]).map(v=>v.serialNumber||v.barcodeValue).filter(Boolean).join(', '),From_Warehouse:x.fromWarehouseId?.name||'',To_Warehouse:x.toWarehouseId?.name||'',From_Organization:x.fromOrganizationId?.name||'',To_Organization:x.toOrganizationId?.name||'',Reference_Type:x.referenceType||'',Reference_ID:String(x.referenceId||''),Reason:x.reason||''}));
 }else if(type==='barcode-traceability-register'){
  const docs=await InventorySerial.find({...match,...dateMatch('updatedAt',range)}).populate('itemId','sku name category brand model installationRole').populate('warehouseId','code name').populate('agencyId','code name').populate('farmerId','beneficiaryId beneficiaryName district').sort({updatedAt:-1}).lean(),ids=docs.map(x=>x._id),assets=ids.length?await InstalledAsset.find({companyId:{$in:scope.companyIds||[]},inventorySerialId:{$in:ids}}).populate('technicianUserId','username mobile').lean():[],am=new Map(assets.map(a=>[String(a.inventorySerialId),a]));rows=docs.map(x=>{const a=am.get(String(x._id)),meta=x.metadata?.scanAttributes||{};return{Serial_Number:x.serialNumber,Barcode:x.barcodeValue||'',SKU:x.itemId?.sku||'',Item:x.itemId?.name||'',Asset_Role:x.itemId?.installationRole||'',Status:x.status,Warehouse:x.warehouseId?.name||'',Agency:x.agencyId?.name||'',Beneficiary_ID:x.farmerId?.beneficiaryId||'',Beneficiary:x.farmerId?.beneficiaryName||'',District:x.farmerId?.district||'',Technician:a?.technicianUserId?.username||'',Installed_At:isoTime(a?.installedAt),Scan_Source:x.metadata?.source||'',Receipt_No:x.metadata?.receiptNo||'',GTIN:meta.gtin||meta.GTIN||'',Batch:meta.batchNo||x.batchNo||'',IMEI:meta.imei||meta.IMEI||meta.imeiNo||'',Encoded_Fields:Object.keys(meta).length,Scan_Metadata:Object.keys(meta).length?JSON.stringify(meta):'',Last_Updated:isoTime(x.updatedAt)}});
 }else if(type==='procurement-register'){
  const pos=await PurchaseOrder.find({...match,...dateMatch('orderDate',range)}).populate('warehouseId','code name').populate('supplierId','name code').sort({orderDate:-1}).lean();rows=pos.map(p=>({PO_Number:p.number,Supplier:p.supplierId?.name||p.supplierName||'',Warehouse:p.warehouseId?.name||'',Order_Date:isoDate(p.orderDate),Expected_Date:isoDate(p.expectedDate),Status:p.status,Currency:p.currency||'INR',Ordered_Qty:(p.lines||[]).reduce((n,l)=>n+num(l.orderedQty),0),Received_Qty:(p.lines||[]).reduce((n,l)=>n+num(l.receivedQty),0),Taxable_Value:(p.lines||[]).reduce((n,l)=>n+num(l.orderedQty)*num(l.unitPrice),0),Tax_Amount:(p.lines||[]).reduce((n,l)=>n+num(l.orderedQty)*num(l.unitPrice)*num(l.taxPercent)/100,0)}));
 }else if(type==='goods-receipt-register'){
  const docs=await GoodsReceipt.find({...match,...dateMatch('receivedAt',range)}).populate('purchaseOrderId','number supplierName').populate('warehouseId','code name').populate('receivedBy','name email').sort({receivedAt:-1}).lean();rows=docs.map(g=>({GRN_Number:g.number,PO_Number:g.purchaseOrderId?.number||'',Supplier:g.purchaseOrderId?.supplierName||'',Warehouse:g.warehouseId?.name||'',Received_At:isoTime(g.receivedAt),Received_By:g.receivedBy?.name||'',Quantity:(g.lines||[]).reduce((n,l)=>n+num(l.quantity),0),Accepted_Qty:(g.lines||[]).reduce((n,l)=>n+num(l.acceptedQty),0),Rejected_Qty:(g.lines||[]).reduce((n,l)=>n+num(l.rejectedQty),0),Supplier_Document:g.supplierDocument||'',Notes:g.notes||''}));
 }else if(type==='dispatch-delivery-register'){
  const docs=await Shipment.find({...match,...dateMatch('createdAt',range)}).populate('agencyId','name code').populate('fromWarehouseId','code name').populate('toWarehouseId','code name').populate('driverId','name mobile').populate('vehicleId','registrationNo type').sort({createdAt:-1}).lean();rows=docs.map(s=>({Shipment_No:s.shipmentNo,Agency:s.agencyId?.name||'',From:s.fromWarehouseId?.name||'',To:s.toWarehouseId?.name||'',Driver:s.driverId?.name||'',Vehicle:s.vehicleId?.registrationNo||'',Status:s.status,Priority:s.priority,Dispatched_At:isoTime(s.dispatchedAt),Expected_Delivery:isoTime(s.expectedDeliveryAt),Delivered_At:isoTime(s.deliveredAt),POD_Available:Object.keys(s.proofOfDelivery||{}).length?'YES':'NO',Issue:s.issueFlag?'YES':'NO',Issue_Note:s.issueNote||''}));
 }else if(type==='material-custody-register'){
  const docs=await MaterialIssue.find({...match,...dateMatch('issuedAt',range)}).populate('agencyId','name code').populate('warehouseId','name code').populate('technicianUserId','username mobile').populate('farmerId','beneficiaryId beneficiaryName').populate('items.itemId','sku name').sort({issuedAt:-1}).lean();rows=docs.map(m=>({Issue_No:m.issueNo,Issued_At:isoTime(m.issuedAt),Agency:m.agencyId?.name||'',Warehouse:m.warehouseId?.name||'',Technician:m.technicianUserId?.username||'',Technician_Mobile:m.technicianUserId?.mobile||'',Beneficiary_ID:m.farmerId?.beneficiaryId||'',Beneficiary:m.farmerId?.beneficiaryName||'',Status:m.status,Total_Qty:(m.items||[]).reduce((n,l)=>n+num(l.quantity),0),Serialized_Qty:(m.items||[]).reduce((n,l)=>n+(l.serialIds||[]).length,0),Notes:m.notes||''}));
 }else if(type==='service-sla-register'){
  const docs=await ServiceCase.find({...match,...dateMatch('openedAt',range)}).populate('agencyId','name code').populate('farmerId','beneficiaryId beneficiaryName district').populate('assignedToLegacyUser','username mobile').populate('assignedToPlatformUser','name email').sort({openedAt:-1}).lean();rows=docs.map(s=>({Case_No:s.caseNo,Opened_At:isoTime(s.openedAt),Type:s.type,Priority:s.priority,Status:s.status,SLA_State:s.slaState,Due_At:isoTime(s.dueAt),Resolved_At:isoTime(s.resolvedAt),Agency:s.agencyId?.name||'',Beneficiary_ID:s.farmerId?.beneficiaryId||'',Beneficiary:s.farmerId?.beneficiaryName||'',District:s.farmerId?.district||'',Assigned_To:s.assignedToLegacyUser?.username||s.assignedToPlatformUser?.name||'',Source:s.source,Title:s.title,Resolution:s.resolution||''}));
 }else if(type==='rms-device-health'){
  const docs=await RmsDevice.find({...match,...dateMatch('updatedAt',range)}).populate('agencyId','name code').populate('farmerId','beneficiaryId beneficiaryName district').populate('providerId','name code mode').sort({lastSeenAt:-1}).lean();rows=docs.map(d=>({External_Device_ID:d.externalDeviceId,Serial:d.serialNumber||'',IMEI:d.imei||'',Provider:d.providerId?.name||'',Mode:d.providerId?.mode||'',Agency:d.agencyId?.name||'',Beneficiary_ID:d.farmerId?.beneficiaryId||'',Beneficiary:d.farmerId?.beneficiaryName||'',District:d.farmerId?.district||'',Mapping_Status:d.mappingStatus,Commissioning_Status:d.commissioningStatus,Lifecycle_Status:d.lifecycleStatus,Last_Seen:isoTime(d.lastSeenAt),Last_Telemetry:isoTime(d.lastTelemetryAt)}));
 }else if(type==='rms-alert-register'){
  const docs=await RmsAlert.find({...match,...dateMatch('firstDetectedAt',range)}).populate('deviceId','externalDeviceId serialNumber').populate('agencyId','name code').populate('farmerId','beneficiaryId beneficiaryName district').populate('assignedTechnicianUserId','username mobile').populate('relatedServiceCaseId','caseNo status').sort({lastDetectedAt:-1}).lean();rows=docs.map(a=>({First_Detected:isoTime(a.firstDetectedAt),Last_Detected:isoTime(a.lastDetectedAt),Status:a.status,Severity:a.severity,Alert_Type:a.type,Device:a.deviceId?.externalDeviceId||'',Serial:a.deviceId?.serialNumber||'',Agency:a.agencyId?.name||'',Beneficiary_ID:a.farmerId?.beneficiaryId||'',Beneficiary:a.farmerId?.beneficiaryName||'',Technician:a.assignedTechnicianUserId?.username||'',Service_Case:a.relatedServiceCaseId?.caseNo||'',Service_Status:a.relatedServiceCaseId?.status||'',Message:a.message||''}));
 }else if(type==='rms-daily-performance'){
  const grouped=await RmsTelemetry.aggregate([{$match:{...match,...dateMatch('telemetryAt',range)}},{$sort:{telemetryAt:1}},{$group:{_id:{day:{$dateToString:{format:'%Y-%m-%d',date:'$telemetryAt',timezone:'Asia/Kolkata'}},deviceId:'$deviceId',agencyId:'$agencyId',farmerId:'$farmerId'},Samples:{$sum:1},Max_Power_kW:{$max:'$powerKw'},Max_Energy_Today_kWh:{$max:'$energyTodayKwh'},Max_Runtime_Today_Min:{$max:'$runtimeTodayMinutes'},Max_Water_Discharge_L:{$max:'$waterDischargeLitres'},Latest_Fault:{$last:'$normalizedFault'}}},{$sort:{'_id.day':-1}}]);
  const deviceIds=[...new Set(grouped.map(x=>String(x._id.deviceId||'')).filter(Boolean))],agencyIds=[...new Set(grouped.map(x=>String(x._id.agencyId||'')).filter(Boolean))],farmerIds=[...new Set(grouped.map(x=>String(x._id.farmerId||'')).filter(Boolean))];
  const [devices,agencies,farmers]=await Promise.all([RmsDevice.find({_id:{$in:deviceIds}}).select('externalDeviceId serialNumber').lean(),Organization.find({_id:{$in:agencyIds}}).select('name code').lean(),Farmer.find({_id:{$in:farmerIds}}).select('beneficiaryId beneficiaryName').lean()]),dm=new Map(devices.map(x=>[String(x._id),x])),am=new Map(agencies.map(x=>[String(x._id),x])),fm=new Map(farmers.map(x=>[String(x._id),x]));
  rows=grouped.map(x=>{const d=dm.get(String(x._id.deviceId))||{},a=am.get(String(x._id.agencyId))||{},f=fm.get(String(x._id.farmerId))||{};return{Date:x._id.day,Device:d.externalDeviceId||'',Serial:d.serialNumber||'',Agency:a.name||'',Beneficiary_ID:f.beneficiaryId||'',Beneficiary:f.beneficiaryName||'',Samples:x.Samples,Max_Power_kW:num(x.Max_Power_kW),Max_Energy_Today_kWh:num(x.Max_Energy_Today_kWh),Max_Runtime_Today_Min:num(x.Max_Runtime_Today_Min),Max_Water_Discharge_L:num(x.Max_Water_Discharge_L),Latest_Fault:x.Latest_Fault||''}});
 }else if(type==='insurance-warranty-register'){
  const farmerIds=await scopedFarmerIds(scope),docs=await InsurancePolicy.find({companyId:{$in:scope.companyIds||[]},farmerId:{$in:farmerIds},...dateMatch('createdAt',range)}).populate('farmerId','beneficiaryId beneficiaryName district village').populate({path:'installedAssetId',populate:{path:'itemId',select:'sku name'}}).sort({endDate:1}).lean();rows=docs.map(x=>({Policy_Number:x.policyNumber,Reference:x.referenceNumber||'',Beneficiary_ID:x.farmerId?.beneficiaryId||'',Beneficiary:x.farmerId?.beneficiaryName||'',District:x.farmerId?.district||'',Asset:x.installedAssetId?.itemId?.name||'Comprehensive',Asset_Serial:x.installedAssetId?.serialNumber||'',Insurer:x.insurer,Policy_Type:x.policyType,Coverage_Amount:num(x.coverageAmount),Premium_Amount:num(x.premiumAmount),Start_Date:isoDate(x.startDate),End_Date:isoDate(x.endDate),Status:x.status,Claim_Number:x.claimNumber||'',Claim_Status:x.claimStatus||'',Document_Available:x.documentUrl?'YES':'NO'}));
 }else if(type==='pdi-quality-register'){
  const docs=await PDIRecord.find({...match,...dateMatch('inspectionDate',range)}).populate('itemId','sku name brand model').populate('inventorySerialId','serialNumber barcodeValue status').populate('warehouseId','code name').populate('agencyId','code name').populate('inspectedBy','name email').sort({inspectionDate:-1}).lean();rows=docs.map(x=>({PDI_Number:x.pdiNumber,Inspection_Date:isoTime(x.inspectionDate),Result:x.result,Disposition:x.disposition,Agency:x.agencyId?.name||'',Warehouse:x.warehouseId?.name||'',SKU:x.itemId?.sku||'',Item:x.itemId?.name||'',Serial_Number:x.inventorySerialId?.serialNumber||'',Inventory_Status:x.inventorySerialId?.status||'',Inspected_By:x.inspectedBy?.name||'',Checklist_Pass:(x.checklist||[]).filter(c=>c.status==='PASS').length,Checklist_Fail:(x.checklist||[]).filter(c=>c.status==='FAIL').length,Evidence_Count:(x.evidenceUrls||[]).length,Certificate_Available:x.certificateUrl?'YES':'NO',Notes:x.notes||''}));
 }else if(type==='compliance-evidence-register'){
  const docs=await ComplianceRecord.find({...match,...dateMatch('createdAt',range)}).populate('agencyId','name code').populate('farmerId','beneficiaryId beneficiaryName district').populate('reviewedBy','name email').sort({createdAt:-1}).lean();rows=docs.map(x=>({Record_No:x.recordNo,Type:x.type,Status:x.status,Agency:x.agencyId?.name||'',Beneficiary_ID:x.farmerId?.beneficiaryId||'',Beneficiary:x.farmerId?.beneficiaryName||'',District:x.farmerId?.district||'',Required_Items:(x.items||[]).filter(i=>i.required).length,Passed:(x.items||[]).filter(i=>i.status==='PASS').length,Failed:(x.items||[]).filter(i=>i.status==='FAIL').length,Waived:(x.items||[]).filter(i=>i.status==='WAIVED').length,Pending:(x.items||[]).filter(i=>i.status==='PENDING').length,Evidence_Count:(x.items||[]).reduce((n,i)=>n+(i.evidence||[]).length,0),Reviewed_By:x.reviewedBy?.name||'',Reviewed_At:isoTime(x.reviewedAt),Created_At:isoTime(x.createdAt),Notes:x.notes||''}));
 }else if(type==='approval-exception-register'){
  const docs=await ApprovalRequest.find({companyId:{$in:scope.companyIds||[]},...dateMatch('createdAt',range)}).populate('requestedBy','name email role').populate('decidedBy','name email role').sort({createdAt:-1}).lean();rows=docs.map(x=>({Request_No:x.requestNo,Type:x.type,Status:x.status,Origin:x.requestOrigin,Title:x.title,Entity_Type:x.entityType||'',Entity_ID:String(x.entityId||''),Requested_By:x.requestedBy?.name||'System',Requested_At:isoTime(x.createdAt),Decided_By:x.decidedBy?.name||'',Decided_At:isoTime(x.decidedAt),Decision_Reason:x.decisionReason||'',Description:x.description||''}));
 }else if(type==='commercial-claims-register'){
  const docs=await CommercialClaim.find({...match,...dateMatch('createdAt',range)}).populate('workPackageId','code name').sort({createdAt:-1}).lean();rows=docs.map(c=>({Claim_No:c.claimNo,Title:c.title,Status:c.status,Work_Package:c.workPackageId?.code||'',Beneficiary_Count:c.beneficiaryCount||0,Gross_Amount:num(c.grossAmount),Eligible_Amount:num(c.eligibleAmount),Approved_Amount:num(c.approvedAmount),Paid_Amount:num(c.paidAmount),Blocked_Amount:num(c.blockedAmount),Blocked_Reason:c.blockedReason||'',Submitted_At:isoTime(c.submittedAt),Approved_At:isoTime(c.approvedAt),Paid_At:isoTime(c.paidAt),SLA_State:c.slaState||''}));
 }else if(type==='commercial-exposure-summary'){
  const [pos,claims]=await Promise.all([PurchaseOrder.find({companyId:{$in:scope.companyIds||[]},...dateMatch('orderDate',range)}).lean(),CommercialClaim.find({companyId:{$in:scope.companyIds||[]},...dateMatch('createdAt',range)}).lean()]);const taxable=pos.reduce((n,p)=>n+(p.lines||[]).reduce((a,l)=>a+num(l.orderedQty)*num(l.unitPrice),0),0),tax=pos.reduce((n,p)=>n+(p.lines||[]).reduce((a,l)=>a+num(l.orderedQty)*num(l.unitPrice)*num(l.taxPercent)/100,0),0),eligible=claims.reduce((n,c)=>n+num(c.eligibleAmount),0),approved=claims.reduce((n,c)=>n+num(c.approvedAmount),0),paid=claims.reduce((n,c)=>n+num(c.paidAmount),0),blocked=claims.reduce((n,c)=>n+num(c.blockedAmount),0);rows=[{Period_From:isoDate(range.from),Period_To:isoDate(range.to),Purchase_Orders:pos.length,Procurement_Taxable_Value:taxable,Procurement_Tax_Amount:tax,Procurement_Gross_Commitment:taxable+tax,Commercial_Claims:claims.length,Eligible_Claim_Value:eligible,Approved_Claim_Value:approved,Paid_Value:paid,Blocked_Value:blocked,Unrealized_Approved_Value:Math.max(0,approved-paid),Claim_Realization_Percent:approved?Math.round(paid*100/approved):0}];
 }else if(type==='invoice-waybill-readiness'){
  const farmerIds=await scopedFarmerIds(scope),farmers=await Farmer.find({_id:{$in:farmerIds}}).sort({invoiceDate:-1}).lean();rows=farmers.filter(f=>f.invoiceNo||f.waybillNo||f.waybillNoFromCompany||f.deliveryChallanNo).map(f=>({Application_Number:f.beneficiaryId||'',Beneficiary_Name:f.beneficiaryName||'',District:f.district||'',Invoice_No:f.invoiceNo||'',Invoice_Date:isoDate(f.invoiceDate),Company_Waybill_No:f.waybillNoFromCompany||'',Waybill_No:f.waybillNo||'',Delivery_Challan_No:f.deliveryChallanNo||'',Transporter:f.transporterName||'',Vehicle_No:f.transporterVehicleNo||f.vehicleNo||'',Material_Dispatch_Date:isoDate(f.materialDispatchDate),Material_Received:f.materialReceivedConfirmationYesNo||''}));
 }else if(type==='audit-trail'){
  const q={};if(scope.companyIds?.length)q.companyId={$in:scope.companyIds};if(scope.agencyIds?.length)q.organizationId={$in:scope.agencyIds};Object.assign(q,dateMatch('createdAt',range));
  const farmerIds=await scopedFarmerIds(scope),legacyQ={};if(farmerIds.length)legacyQ.$or=[{'details.farmerId':{$in:farmerIds}},{'details.farmerIds':{$in:farmerIds}}];else legacyQ._id={$exists:false};Object.assign(legacyQ,dateMatch('timestamp',range));
  const [docs,legacyDocs]=await Promise.all([AuditLog.find(q).sort({createdAt:-1}).lean(),AdminChangeLog.find(legacyQ).sort({timestamp:-1}).lean()]);
  const ids=[...new Set([...docs.map(x=>x.actorId&&String(x.actorId)),...legacyDocs.map(x=>x.adminId&&String(x.adminId))].filter(Boolean))], [pusers,lusers]=await Promise.all([PlatformUser.find({_id:{$in:ids}}).select('name email mobile role').lean(),LegacyUser.find({_id:{$in:ids}}).select('username mobile role').lean()]),actors=new Map();
  for(const u of pusers)actors.set(String(u._id),{name:u.name,contact:u.email||u.mobile,role:u.role});for(const u of lusers)actors.set(String(u._id),{name:u.username,contact:u.mobile,role:u.role});
  const platformRows=docs.map(a=>{const actor=actors.get(String(a.actorId))||{};return{Timestamp:isoTime(a.createdAt),Actor:actor.name||'System / unknown',Actor_Role:actor.role||a.actorType||'',Actor_Contact:actor.contact||'',Action:label(a.action),Entity_Type:a.entityType,Entity_ID:String(a.entityId||''),Reason:a.reason||'',IP_Address:a.ip||'',Client:a.userAgent||'',Bulk_Operation_ID:a.bulkOperationId||'',Before_JSON:a.before?JSON.stringify(a.before):'',After_JSON:a.after?JSON.stringify(a.after):''}});
  const legacyRows=legacyDocs.map(a=>{const actor=actors.get(String(a.adminId))||{},farmerRefs=[a.details?.farmerId,...(a.details?.farmerIds||[])].filter(Boolean).map(String);return{Timestamp:isoTime(a.timestamp),Actor:actor.name||'Agency user / unknown',Actor_Role:actor.role||'legacy_user',Actor_Contact:actor.contact||'',Action:label(a.changeType),Entity_Type:'Farmer',Entity_ID:farmerRefs.join(', '),Reason:a.details?.reason||'',IP_Address:'',Client:'Legacy agency workflow',Bulk_Operation_ID:'',Before_JSON:'',After_JSON:a.details?.changes?JSON.stringify(a.details.changes):''}});
  rows=[...platformRows,...legacyRows].sort((a,b)=>String(b.Timestamp).localeCompare(String(a.Timestamp)));
 }else if(type==='statutory-readiness'){
  const q=scope.companyIds?.length?{_id:{$in:scope.companyIds}}:{},companies=await Organization.find(q).select('name code metadata').lean(),auditCount=await AuditLog.countDocuments(scope.companyIds?.length?{companyId:{$in:scope.companyIds}}:{}),farmerIds=await scopedFarmerIds(scope),invoiceCount=await Farmer.countDocuments({_id:{$in:farmerIds},invoiceNo:{$nin:[null,'']}}),waybillCount=await Farmer.countDocuments({_id:{$in:farmerIds},$or:[{waybillNo:{$nin:[null,'']}},{waybillNoFromCompany:{$nin:[null,'']}}]});rows=[
   {Authority:'GSTN / GST Portal',Requirement:'GSTR-1 outward-supply reconciliation',Cadence:'Monthly / Quarterly as applicable',Reference:'Form GSTR-1 / IFF',OPSYNQ_Data_Status:invoiceCount?'SOURCE DATA PRESENT':'SOURCE DATA INCOMPLETE',Records:invoiceCount,Notes:'Operational invoice fields can be reconciled/exported; GSTIN, place of supply, HSN, tax rate/value and accounting ledger must be validated before filing.'},
   {Authority:'GSTN e-Invoice / IRP',Requirement:'GST e-Invoice / IRN readiness',Cadence:'Per applicable B2B invoice',Reference:'Notification 10/2023-CT and current IRP rules',OPSYNQ_Data_Status:'GSTIN / HSN / TAX / IRN FIELDS NOT FULLY MODELLED',Records:invoiceCount,Notes:'Notified e-invoice threshold is ₹5 crore AATO from 1 Aug 2023, subject to notified applicability/exemptions. OPSYNQ operational invoice fields alone are not sufficient to generate IRN.'},
   {Authority:'GST e-Way Bill System',Requirement:'e-Way Bill movement reconciliation',Cadence:'Per applicable goods movement',Reference:'CGST Rule 138 / FORM GST EWB-01',OPSYNQ_Data_Status:waybillCount?'SOURCE DATA PRESENT':'SOURCE DATA INCOMPLETE',Records:waybillCount,Notes:'General central threshold is consignment value exceeding ₹50,000, subject to rule/state-specific exceptions. Portal generation and validity remain on the official e-Way Bill system.'},
   {Authority:'Ministry of Corporate Affairs',Requirement:'Companies Act books / accounting audit trail support',Cadence:'Continuous / annual audit evidence',Reference:'Companies Act 2013 section 128 and applicable rules',OPSYNQ_Data_Status:auditCount?'SYSTEM AUDIT TRAIL ACTIVE':'NO AUDIT EVENTS FOUND',Records:auditCount,Notes:'OPSYNQ captures operational before/after audit events. Statutory books and prescribed accounting-software edit-log requirements must also be met in the accounting system; books generally require retention for at least eight financial years.'},
   {Authority:'Ministry of Corporate Affairs',Requirement:'Annual return / financial statement source support',Cadence:'Annual',Reference:'Companies Act 2013 sections 92, 129 and related rules',OPSYNQ_Data_Status:'EXTERNAL FINANCE / SECRETARIAL DATA REQUIRED',Records:companies.length,Notes:'OPSYNQ operational records can support schedules; statutory financial statements and annual return require corporate, shareholding, board and accounting records outside this operational module.'},
   {Authority:'Ministry of Corporate Affairs',Requirement:'MSME Form I supplier ageing',Cadence:'Half-yearly where applicable',Reference:'MSME Form I under section 405 order',OPSYNQ_Data_Status:'PAYABLE AGEING DATA NOT MODELLED',Records:0,Notes:'Requires MSE supplier classification and outstanding/payment ageing beyond 45 days. Do not infer this from PO/GRN alone.'},
   {Authority:'Income Tax Department',Requirement:'TDS/TCS statement source support',Cadence:'Quarterly / prescribed',Reference:'Applicable TDS/TCS statement forms',OPSYNQ_Data_Status:'PAYROLL / TAX DEDUCTION LEDGER NOT MODELLED',Records:0,Notes:'Requires TAN, deductee PAN, section/rate/challan and deduction/payment ledger; maintain and reconcile in payroll/accounting/tax system.'}
  ];
 }else if(type==='jcr-office'){
  rows=contexts.map(x=>{const f=x.farmerId||{};return{Application_Number:f.beneficiaryId||'',Beneficiary_Name:f.beneficiaryName||'',District:f.district||'',Taluka:f.taluka||'',Village:f.village||'',Scheme:f.scheme||'',Component:x.programId?.component||'',Pump_HP:f.pumpHP||'',Survey_Date:isoDate(f.surveyDate),Survey_Status:f.inspectionStatus||'',Installation_Status:f.applicationStatus||'',Installation_Date:isoDate(f.installationCompletionDate),Pump_Serial:f.pumpNoUnique||'',Motor_Serial:f.motorNoUnique||'',Controller_Serial:f.controllerNoUnique||'',IMEI:f.imeiNoUnique||'',Agency:x.agencyId?.name||'',Work_Package:x.workPackageId?.code||''}});
 }else if(type==='jcr-installer'){
  rows=contexts.map(x=>{const f=x.farmerId||{};return{Installer:x.agencyId?.name||'',Installer_Code:x.agencyId?.code||'',Application_Number:f.beneficiaryId||'',Beneficiary_Name:f.beneficiaryName||'',District:f.district||'',Village:f.village||'',Pump_HP:f.pumpHP||'',Material_Status:f.materialReceivedConfirmationYesNo||'',Dispatch_Date:isoDate(f.materialDispatchDate),Installation_Status:f.applicationStatus||'',Installation_Date:isoDate(f.installationCompletionDate),Pump_Serial:f.pumpNoUnique||'',Motor_Serial:f.motorNoUnique||'',Controller_Serial:f.controllerNoUnique||'',IMEI:f.imeiNoUnique||''}});
 }else throw Object.assign(new Error('Unknown report type.'),{status:404});
 return applyTextFilters(rows,query);
}

function catalog({agency=false}={}){const excluded=agency?new Set(['procurement-register','goods-receipt-register','stock-position-register','stock-movement-register','commercial-claims-register','commercial-exposure-summary','statutory-readiness','approval-exception-register']):new Set();return Object.entries(REPORTS).filter(([id])=>!excluded.has(id)).map(([id,x])=>({id,...x,formats:['CSV','XLSX','PRINT']}));}
const safeExportCell=v=>typeof v==='string'&&/^[=+\-@]/.test(v)?`'${v}`:v;
const sanitizeRows=rows=>rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,safeExportCell(v)])));
module.exports={REPORTS,catalog,rowsFor,dateWindow,sanitizeRows};
