const crypto=require('crypto');
const mongoose=require('mongoose');
const RmsProvider=require('../models/platform/RmsProvider');
const RmsDevice=require('../models/platform/RmsDevice');
const RmsRawIngestion=require('../models/platform/RmsRawIngestion');
const RmsTelemetry=require('../models/platform/RmsTelemetry');
const RmsCurrentState=require('../models/platform/RmsCurrentState');
const RmsAlert=require('../models/platform/RmsAlert');
const RmsRuleConfig=require('../models/platform/RmsRuleConfig');
const InstalledAsset=require('../models/platform/InstalledAsset');
const BeneficiaryContext=require('../models/platform/BeneficiaryContext');
const Notification=require('../models/platform/Notification');
const ServiceCase=require('../models/platform/ServiceCase');
const demoAdapter=require('../rms/adapters/demoAdapter');

const DEFAULT_CAPS=demoAdapter.getCapabilities();
const safeNumber=v=>Number.isFinite(Number(v))?Number(v):undefined;
const normalizeFault=code=>{const c=String(code||'').toUpperCase();if(!c)return null;if(['DRY_RUN','07','E07'].includes(c))return'DRY_RUN';if(['CONTROLLER_FAULT','E104','E92','FAULT'].includes(c))return'CONTROLLER_FAULT';return'UNKNOWN_PROVIDER_FAULT'};
const messageKey=(providerId,externalDeviceId,payload)=>String(payload.messageId||payload.id||crypto.createHash('sha256').update(`${providerId}|${externalDeviceId}|${payload.timestamp||payload.telemetryAt||''}|${JSON.stringify(payload)}`).digest('hex'));
const stateFreshness=(state,rules,now=new Date())=>{if(!state?.telemetryAt)return'UNKNOWN';const age=(now-new Date(state.telemetryAt))/60000;if(age>=Number(rules.offlineCriticalAfterMinutes||15))return'OFFLINE';if(age>=Number(rules.offlineWarningAfterMinutes||5))return'STALE';return'ONLINE'};

async function rulesFor(companyId){return await RmsRuleConfig.findOneAndUpdate({companyId},{$setOnInsert:{companyId}},{new:true,upsert:true,setDefaultsOnInsert:true}).lean()}
async function ensureDemoProvider(companyId){return await RmsProvider.findOneAndUpdate({companyId,code:'DEMO-RMS'},{$setOnInsert:{companyId,name:'Demo RMS Simulator',code:'DEMO-RMS',type:'DEMO_SIMULATOR',transport:'SIMULATED',mode:'SIMULATED',status:'ACTIVE',capabilities:DEFAULT_CAPS,mappingVersion:'v1'}},{new:true,upsert:true,setDefaultsOnInsert:true})}
async function ensureDemoDevices(companyId){
 const provider=await ensureDemoProvider(companyId);let existing=await RmsDevice.countDocuments({companyId,providerId:provider._id});if(existing)return provider;
 const assets=await InstalledAsset.find({companyId,status:'ACTIVE'}).sort({installedAt:-1}).limit(12).lean();const farmerIds=[...new Set(assets.map(x=>String(x.farmerId)).filter(Boolean))];
 const contexts=farmerIds.length?await BeneficiaryContext.find({companyId,farmerId:{$in:farmerIds}}).lean():await BeneficiaryContext.find({companyId}).limit(8).lean();const ctxByFarmer=new Map(contexts.map(x=>[String(x.farmerId),x]));
 const source=assets.length?assets:contexts.map(x=>({farmerId:x.farmerId,agencyId:x.agencyId,workPackageId:x.workPackageId,installedAt:new Date()}));
 let i=0;for(const row of source){const ctx=ctxByFarmer.get(String(row.farmerId))||contexts.find(x=>String(x.farmerId)===String(row.farmerId));if(!ctx)continue;i++;await RmsDevice.findOneAndUpdate({companyId,providerId:provider._id,externalDeviceId:`RMS-DEMO-${String(i).padStart(3,'0')}`},{$setOnInsert:{companyId,providerId:provider._id,externalDeviceId:`RMS-DEMO-${String(i).padStart(3,'0')}`,serialNumber:`RMS${String(i).padStart(6,'0')}`,imei:`860000000${String(i).padStart(6,'0')}`,make:'OPSYNQ Demo',model:'RMS-SIM-1',agencyId:ctx.agencyId,programId:ctx.programId,workOrderId:ctx.workOrderId,workPackageId:ctx.workPackageId,farmerId:row.farmerId,installedAssetId:row._id||null,mappingStatus:'MAPPED',lifecycleStatus:'COMMISSIONING',commissioningStatus:'PENDING',installedAt:row.installedAt||new Date(),capabilities:DEFAULT_CAPS,metadata:{simulated:true,scenario:'HEALTHY_RUNNING'}}},{upsert:true,new:true,setDefaultsOnInsert:true});}
 return provider;
}
function normalizePayload(payload,device){const telemetryAt=new Date(payload.timestamp||payload.telemetryAt||Date.now());return{telemetryAt:Number.isNaN(telemetryAt.getTime())?new Date():telemetryAt,pumpState:['RUNNING','STOPPED'].includes(String(payload.pumpState||'').toUpperCase())?String(payload.pumpState).toUpperCase():'UNKNOWN',dcVoltage:safeNumber(payload.dcVoltage),dcCurrent:safeNumber(payload.dcCurrent),powerKw:safeNumber(payload.powerKw),energyTodayKwh:safeNumber(payload.energyTodayKwh),runtimeTodayMinutes:safeNumber(payload.runtimeTodayMinutes),waterFlowLpm:safeNumber(payload.waterFlowLpm),waterDischargeLitres:safeNumber(payload.waterDischargeLitres),signalQuality:safeNumber(payload.signalQuality),externalFaultCode:payload.externalFaultCode?String(payload.externalFaultCode).slice(0,100):null,normalizedFault:normalizeFault(payload.externalFaultCode||payload.fault),latitude:safeNumber(payload.latitude),longitude:safeNumber(payload.longitude),unsupported:Array.isArray(payload.unsupported)?payload.unsupported.map(String).slice(0,30):[],optional:payload.optional&&typeof payload.optional==='object'?payload.optional:{}}}
async function evaluateAlerts(device,state,rules){
 const desired=[];if(state.communication==='OFFLINE')desired.push(['COMMUNICATION_LOST','CRITICAL','Device communication is lost.']);else if(state.communication==='STALE')desired.push(['COMMUNICATION_LOST','WARNING','Device communication is stale.']);
 if(state.normalizedFault==='DRY_RUN')desired.push(['DRY_RUN','CRITICAL','Dry-run condition detected.']);if(['CONTROLLER_FAULT','UNKNOWN_PROVIDER_FAULT'].includes(state.normalizedFault))desired.push(['CONTROLLER_FAULT','CRITICAL','Controller fault detected.']);if(state.pumpState==='RUNNING'&&Number(state.powerKw||0)<Number(rules.lowPerformanceThresholdKw||.4))desired.push(['LOW_PERFORMANCE','WARNING','Running pump performance is below configured threshold.']);
 const active=await RmsAlert.find({deviceId:device._id,status:'ACTIVE'});const desiredTypes=new Set(desired.map(x=>x[0]));for(const a of active)if(!desiredTypes.has(a.type)){a.status='RESOLVED';a.resolvedAt=new Date();a.recoveryAt=new Date();await a.save();}
 for(const [type,severity,message] of desired){const found=active.find(a=>a.type===type);if(found){found.lastDetectedAt=new Date();found.severity=severity;found.message=message;await found.save();}else{const alert=await RmsAlert.create({companyId:device.companyId,providerId:device.providerId,deviceId:device._id,agencyId:device.agencyId,farmerId:device.farmerId,workPackageId:device.workPackageId,type,severity,status:'ACTIVE',firstDetectedAt:new Date(),lastDetectedAt:new Date(),externalFaultCode:state.externalFaultCode,message});if(severity==='CRITICAL'){await Notification.create({companyId:device.companyId,recipientRoles:['company_owner','company_admin','operations_manager','quality_user'],type:'CRITICAL',title:`RMS ${type.replaceAll('_',' ')}`,message:`${device.externalDeviceId}: ${message}`,entityType:'RmsAlert',entityId:alert._id,actionUrl:'rms-alerts'}).catch(()=>{});}if(severity==='CRITICAL'&&rules.autoIncidentPolicy==='AUTO_CREATE_CRITICAL_INCIDENT'){const caseNo=`RMS-${Date.now()}-${String(device._id).slice(-4).toUpperCase()}`;const svc=await ServiceCase.create({companyId:device.companyId,agencyId:device.agencyId,farmerId:device.farmerId,installedAssetId:device.installedAssetId,caseNo,type:'BREAKDOWN',priority:'CRITICAL',status:'OPEN',title:`RMS ${type.replaceAll('_',' ')}`,description:message,source:'SYSTEM',metadata:{rmsAlertId:String(alert._id),rmsDeviceId:String(device._id)}});alert.relatedServiceCaseId=svc._id;await alert.save();}}}
}
async function ingest(provider,externalDeviceId,payload){
 let device=await RmsDevice.findOne({providerId:provider._id,externalDeviceId});const key=messageKey(provider._id,externalDeviceId,payload),receivedAt=new Date();const raw=await RmsRawIngestion.create({companyId:provider.companyId,providerId:provider._id,externalDeviceId,messageKey:key,providerTimestamp:payload.timestamp||payload.telemetryAt||null,receivedAt,mappingVersion:provider.mappingVersion,status:device?'RECEIVED':'UNMAPPED',payload});if(!device){device=await RmsDevice.create({companyId:provider.companyId,providerId:provider._id,externalDeviceId,mappingStatus:'UNMAPPED',lifecycleStatus:'UNMAPPED',commissioningStatus:'NOT_STARTED',capabilities:provider.capabilities||[]});}
 const normalized=normalizePayload(payload,device);try{await RmsTelemetry.create({companyId:device.companyId,providerId:provider._id,deviceId:device._id,agencyId:device.agencyId,farmerId:device.farmerId,messageKey:key,receivedAt,...normalized});}catch(e){if(e?.code===11000){raw.status='DUPLICATE';await raw.save();return{duplicate:true,device};}throw e;}
 const prev=await RmsCurrentState.findOne({deviceId:device._id});const rules=await rulesFor(device.companyId);if(!prev||new Date(normalized.telemetryAt)>=new Date(prev.telemetryAt)){const communication='ONLINE',health=normalized.normalizedFault?(normalized.normalizedFault==='DRY_RUN'||normalized.normalizedFault==='CONTROLLER_FAULT'?'CRITICAL':'WARNING'):'HEALTHY';const next=await RmsCurrentState.findOneAndUpdate({deviceId:device._id},{$set:{companyId:device.companyId,agencyId:device.agencyId,farmerId:device.farmerId,receivedAt,communication,health,...normalized,lastHealthyAt:health==='HEALTHY'?receivedAt:prev?.lastHealthyAt}},{new:true,upsert:true,setDefaultsOnInsert:true});device.lastSeenAt=receivedAt;device.lastTelemetryAt=normalized.telemetryAt;if(device.commissioningStatus==='PENDING'){device.commissioningStatus='COMMISSIONED';device.lifecycleStatus='COMMISSIONED';device.commissionedAt=receivedAt;}if(normalized.latitude!=null&&normalized.longitude!=null)device.reportedLocation={latitude:normalized.latitude,longitude:normalized.longitude};await device.save();await evaluateAlerts(device,next,rules);}
 raw.status='PROCESSED';await raw.save();provider.lastSuccessfulSync=receivedAt;provider.lastDataReceived=receivedAt;provider.status='ACTIVE';await provider.save();return{device};
}
async function refreshStale(companyId){const rules=await rulesFor(companyId),states=await RmsCurrentState.find({companyId});for(const s of states){const comm=stateFreshness(s,rules);if(comm!==s.communication){s.communication=comm;if(comm==='OFFLINE')s.health=s.health==='CRITICAL'?'CRITICAL':'WARNING';await s.save();const device=await RmsDevice.findById(s.deviceId);if(device)await evaluateAlerts(device,s,rules);}}}
async function demoPayload(device,scenario='HEALTHY_RUNNING'){return demoAdapter.fetchLatestTelemetry(device,scenario)}
async function runDemoCycle(companyId,scenarioByDevice={}){const provider=await ensureDemoDevices(companyId);if(provider.status==='DOWN')return;const devices=await RmsDevice.find({companyId,providerId:provider._id});for(const d of devices){const scenario=scenarioByDevice[String(d._id)]||d.metadata?.scenario||'HEALTHY_RUNNING',payload=await demoPayload(d,scenario);if(payload)await ingest(provider,d.externalDeviceId,payload);}await refreshStale(companyId);}
async function setDemoScenario(companyId,deviceId,scenario){const d=await RmsDevice.findOne({_id:deviceId,companyId}).populate('providerId');if(!d||d.providerId?.type!=='DEMO_SIMULATOR')return null;d.metadata={...(d.metadata||{}),simulated:true,scenario};await d.save();if(scenario==='RECOVERY')d.metadata.scenario='HEALTHY_RUNNING';const payload=await demoPayload(d,scenario==='RECOVERY'?'HEALTHY_RUNNING':scenario);if(payload)await ingest(d.providerId,d.externalDeviceId,payload);else{const s=await RmsCurrentState.findOne({deviceId:d._id});if(s){s.telemetryAt=new Date(Date.now()-20*60000);await s.save();await refreshStale(companyId);}}return d;}
module.exports={ensureDemoDevices,runDemoCycle,setDemoScenario,ingest,refreshStale,rulesFor,stateFreshness,DEFAULT_CAPS};
