import React,{Suspense,lazy,useEffect,useMemo,useState} from 'react';
import {ArrowLeft} from 'lucide-react';
import {Shell} from '../../layout/Shell';
import {CompanyDashboard,ResourcePage,resourceConfig,WorkPackages,BeneficiaryImports,BeneficiaryRecords} from './operations/OperationsPages';
import {PermissionProvider} from '../../core/accessControl.jsx';
import {defaultCompanyPageForRole,flattenModulesForUser,roleModuleIds} from '../../layout/moduleRegistry';

const lazyNamed=(path,name)=>lazy(()=>import(path).then(m=>({default:m[name]})));
const InventoryOverview=lazyNamed('./inventory/InventoryPages','InventoryOverview'),ItemMasterPage=lazyNamed('./inventory/InventoryPages','ItemMasterPage'),WarehousesPage=lazyNamed('./inventory/InventoryPages','WarehousesPage'),ProcurementPage=lazyNamed('./inventory/InventoryPages','ProcurementPage'),StockPage=lazyNamed('./inventory/InventoryPages','StockPage'),ScannerPage=lazyNamed('./inventory/InventoryPages','ScannerPage');
const SupplyChainWorkspace=lazyNamed('./inventory/SupplyChainWorkspace.jsx','SupplyChainWorkspace'),ProcurementIntelligencePage=lazyNamed('./inventory/IntelligencePages','ProcurementIntelligencePage'),AgencyStockAccountabilityPage=lazyNamed('./inventory/IntelligencePages','AgencyStockAccountabilityPage'),FinancialControlPage=lazyNamed('./inventory/IntelligencePages','FinancialControlPage');
const LogisticsOverview=lazyNamed('./logistics/LogisticsPages','LogisticsOverview'),FleetPage=lazyNamed('./logistics/LogisticsPages','FleetPage'),ShipmentsPage=lazyNamed('./logistics/LogisticsPages','ShipmentsPage'),MaterialIssuesPage=lazyNamed('./logistics/LogisticsPages','MaterialIssuesPage'),InstalledAssetsPage=lazyNamed('./logistics/LogisticsPages','InstalledAssetsPage'),AssetLifecyclePage=lazyNamed('./logistics/LogisticsPages','AssetLifecyclePage'),ReconciliationPage=lazyNamed('./logistics/LogisticsPages','ReconciliationPage');
const ServiceCasesPage=lazyNamed('./service/ServicePages','ServiceCasesPage'),ServicePlansPage=lazyNamed('./service/ServicePages','ServicePlansPage'),SlaPage=lazyNamed('./service/ServicePages','SlaPage'),ClaimsPage=lazyNamed('./service/ServicePages','ClaimsPage');
const AnalyticsPage=lazyNamed('./governance/GovernancePages','AnalyticsPage'),NotificationsPage=lazyNamed('./governance/GovernancePages','NotificationsPage'),DocumentsPage=lazyNamed('./governance/GovernancePages','DocumentsPage'),AuditPage=lazyNamed('./governance/GovernancePages','AuditPage');
const CompliancePage=lazyNamed('./assurance/AssurancePages','CompliancePage'),AgencyPerformancePage=lazyNamed('./assurance/AssurancePages','AgencyPerformancePage'),ApprovalCenterPage=lazyNamed('./assurance/AssurancePages','ApprovalCenterPage'),BulkCenterPage=lazyNamed('./assurance/AssurancePages','BulkCenterPage'),ActionCenterPage=lazyNamed('./assurance/AssurancePages','ActionCenterPage');
const InsurancePage=lazyNamed('./assurance/RegulatoryPages','InsurancePage'),PDIPage=lazyNamed('./assurance/RegulatoryPages','PDIPage'),RegulatoryReportsPage=lazyNamed('./assurance/RegulatoryPages','RegulatoryReportsPage');
const AutomationPage=lazyNamed('./system/AutomationPage','AutomationPage'),MyWorkspacePage=lazyNamed('./system/ProductivityPage','MyWorkspacePage'),TeamAccessPage=lazyNamed('./system/TeamAccessPage','TeamAccessPage'),ReadinessPage=lazyNamed('./system/ReadinessPage','ReadinessPage');
const MasterDataPage=lazyNamed('./configuration/ConfigurationCenter.jsx','MasterDataPage'),EvidenceControlPage=lazyNamed('./configuration/ConfigurationCenter.jsx','EvidenceControlPage'),GeoOperationsPage=lazyNamed('./geo/GeoOperationsPage','GeoOperationsPage'),AIOperationsPage=lazyNamed('./intelligence/AIOperationsPage.jsx','AIOperationsPage');

const pageComponents={
 'my-workspace':MyWorkspacePage,'company-overview':CompanyDashboard,'ai-operations':AIOperationsPage,'work-packages':WorkPackages,'beneficiary-records':BeneficiaryRecords,'beneficiary-imports':BeneficiaryImports,
 'supply-chain':SupplyChainWorkspace,'inventory-overview':InventoryOverview,'item-master':ItemMasterPage,'warehouses':WarehousesPage,'procurement':ProcurementPage,'procurement-intelligence':ProcurementIntelligencePage,'agency-stock':AgencyStockAccountabilityPage,'financial-control':FinancialControlPage,'stock':StockPage,'scanner':ScannerPage,
 'logistics-overview':LogisticsOverview,'shipments':ShipmentsPage,'fleet':FleetPage,'material-issues':MaterialIssuesPage,'installed-assets':InstalledAssetsPage,'asset-lifecycle':AssetLifecyclePage,'reconciliation':ReconciliationPage,
 'service-cases':ServiceCasesPage,'service-plans':ServicePlansPage,'sla':SlaPage,'claims':ClaimsPage,'insurance':InsurancePage,'pdi':PDIPage,'regulatory-reports':RegulatoryReportsPage,
 'geo-operations':GeoOperationsPage,'action-center':ActionCenterPage,'compliance':CompliancePage,'agency-performance':AgencyPerformancePage,'approval-center':ApprovalCenterPage,'bulk-center':BulkCenterPage,
 'analytics':AnalyticsPage,'notifications':NotificationsPage,'documents':DocumentsPage,'audit':AuditPage,'team-access':TeamAccessPage,'automation':AutomationPage,'master-data':MasterDataPage,'evidence-control':EvidenceControlPage,'readiness':ReadinessPage
};
export function CompanyWorkspace({user,companyId,back,logout}){const pageKey=`opsynq_company_page:${companyId||user?.organizationId||'self'}:${user?.role||'user'}`;const deliveryKey=`opsynq.delivery.context.${companyId}`;const supplyHidden=['inventory-overview','item-master','warehouses','procurement','procurement-intelligence','stock','scanner','logistics-overview','shipments','fleet','material-issues','agency-stock','pdi'];const[page,setPageState]=useState(()=>sessionStorage.getItem(pageKey)||defaultCompanyPageForRole(user?.role));const setPage=(p,filter)=>{sessionStorage.setItem(pageKey,p);const hierarchy=['programs','contracts','work-orders','work-packages'];const isHierarchyDrill=!!filter?.__hierarchyDrill;const isSupplyDrill=!!filter?.__supplyDrill;if(hierarchy.includes(p)&&!isHierarchyDrill){try{sessionStorage.removeItem(deliveryKey)}catch{}}if(filter&&typeof filter==='object'){const clean=Object.fromEntries(Object.entries(filter).filter(([k])=>!k.startsWith('__')));if(!isHierarchyDrill){try{if(Object.keys(clean).length)sessionStorage.setItem(`opsynq.dashboard.filter.${p}`,JSON.stringify(clean));else if(supplyHidden.includes(p))sessionStorage.removeItem(`opsynq.dashboard.filter.${p}`)}catch{}}}else if(supplyHidden.includes(p)){try{sessionStorage.removeItem(`opsynq.dashboard.filter.${p}`)}catch{}}setPageState(p)};const allowed=useMemo(()=>[...new Set([...flattenModulesForUser(user,true).map(m=>m.id),...roleModuleIds(user?.role).filter(x=>['contracts','work-orders','work-packages',...supplyHidden].includes(x))])],[user]);const safePage=allowed.includes(page)?page:(allowed[0]||'company-overview');useEffect(()=>{if(page!==safePage)setPage(safePage)},[page,safePage]);useEffect(()=>{const open=e=>{const farmerId=e?.detail?.farmerId;if(!farmerId)return;try{sessionStorage.setItem('opsynq.dashboard.filter.beneficiary-records',JSON.stringify({farmerId}))}catch{}setPageState('beneficiary-records')};window.addEventListener('opsynq:open-beneficiary',open);return()=>window.removeEventListener('opsynq:open-beneficiary',open)},[companyId]);let content;if(resourceConfig[safePage])content=<ResourcePage kind={safePage} companyId={companyId} onNavigate={setPage}/>;else{const Component=pageComponents[safePage]||CompanyDashboard;content=<Suspense fallback={<div className="module-loader"><span/><b>Loading module…</b></div>}><Component companyId={companyId} onNavigate={setPage} user={user}/></Suspense>;}return <PermissionProvider user={user}><Shell user={user} page={safePage} setPage={setPage} logout={logout} companyMode companyId={companyId}>{back&&<button className="back company-switch" onClick={back}><ArrowLeft size={16}/> Back to platform companies</button>}{content}</Shell></PermissionProvider>}
