import React,{Suspense,lazy,useEffect,useMemo,useState} from 'react';
import {ArrowLeft} from 'lucide-react';
import {Shell} from '../../layout/Shell';
import {CompanyDashboard,ResourcePage,resourceConfig,WorkPackages,BeneficiaryImports,BeneficiaryRecords} from './operations/OperationsPages';
import {PermissionProvider} from '../../core/accessControl.jsx';
import {defaultCompanyPageForRole,flattenModulesForUser,roleModuleIds} from '../../layout/moduleRegistry';

const lazyNamed=(loader,name)=>lazy(()=>loader().then(m=>({default:m[name]})));
const InventoryOverview=lazyNamed(()=>import('./inventory/InventoryPages.jsx'),'InventoryOverview'),ItemMasterPage=lazyNamed(()=>import('./inventory/InventoryPages.jsx'),'ItemMasterPage'),WarehousesPage=lazyNamed(()=>import('./inventory/InventoryPages.jsx'),'WarehousesPage'),ProcurementPage=lazyNamed(()=>import('./inventory/InventoryPages.jsx'),'ProcurementPage'),StockPage=lazyNamed(()=>import('./inventory/InventoryPages.jsx'),'StockPage');
const SupplyChainWorkspace=lazyNamed(()=>import('./inventory/SupplyChainWorkspace.jsx'),'SupplyChainWorkspace'),ProcurementIntelligencePage=lazyNamed(()=>import('./inventory/IntelligencePages.jsx'),'ProcurementIntelligencePage'),AgencyStockAccountabilityPage=lazyNamed(()=>import('./inventory/IntelligencePages.jsx'),'AgencyStockAccountabilityPage'),FinancialControlPage=lazyNamed(()=>import('./inventory/IntelligencePages.jsx'),'FinancialControlPage');
const LogisticsOverview=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'LogisticsOverview'),FleetPage=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'FleetPage'),ShipmentsPage=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'ShipmentsPage'),MaterialIssuesPage=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'MaterialIssuesPage'),InstalledAssetsPage=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'InstalledAssetsPage'),AssetLifecyclePage=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'AssetLifecyclePage'),ReconciliationPage=lazyNamed(()=>import('./logistics/LogisticsPages.jsx'),'ReconciliationPage');
const ServiceCasesPage=lazyNamed(()=>import('./service/ServicePages.jsx'),'ServiceCasesPage'),ServicePlansPage=lazyNamed(()=>import('./service/ServicePages.jsx'),'ServicePlansPage'),SlaPage=lazyNamed(()=>import('./service/ServicePages.jsx'),'SlaPage'),ClaimsPage=lazyNamed(()=>import('./service/ServicePages.jsx'),'ClaimsPage');
const AnalyticsPage=lazyNamed(()=>import('./governance/GovernancePages.jsx'),'AnalyticsPage'),NotificationsPage=lazyNamed(()=>import('./governance/GovernancePages.jsx'),'NotificationsPage'),DocumentsPage=lazyNamed(()=>import('./governance/GovernancePages.jsx'),'DocumentsPage'),AuditPage=lazyNamed(()=>import('./governance/GovernancePages.jsx'),'AuditPage');
const CompliancePage=lazyNamed(()=>import('./assurance/AssurancePages.jsx'),'CompliancePage'),AgencyPerformancePage=lazyNamed(()=>import('./assurance/AssurancePages.jsx'),'AgencyPerformancePage'),ApprovalCenterPage=lazyNamed(()=>import('./assurance/AssurancePages.jsx'),'ApprovalCenterPage'),BulkCenterPage=lazyNamed(()=>import('./assurance/AssurancePages.jsx'),'BulkCenterPage'),ActionCenterPage=lazyNamed(()=>import('./assurance/AssurancePages.jsx'),'ActionCenterPage');
const InsurancePage=lazyNamed(()=>import('./assurance/RegulatoryPages.jsx'),'InsurancePage'),PDIPage=lazyNamed(()=>import('./assurance/RegulatoryPages.jsx'),'PDIPage'),RegulatoryReportsPage=lazyNamed(()=>import('./assurance/RegulatoryPages.jsx'),'RegulatoryReportsPage');
const AutomationPage=lazyNamed(()=>import('./system/AutomationPage.jsx'),'AutomationPage'),MyWorkspacePage=lazyNamed(()=>import('./system/ProductivityPage.jsx'),'MyWorkspacePage'),TeamAccessPage=lazyNamed(()=>import('./system/TeamAccessPage.jsx'),'TeamAccessPage'),ReadinessPage=lazyNamed(()=>import('./system/ReadinessPage.jsx'),'ReadinessPage');
const MasterDataPage=lazyNamed(()=>import('./configuration/ConfigurationCenter.jsx'),'MasterDataPage'),EvidenceControlPage=lazyNamed(()=>import('./configuration/ConfigurationCenter.jsx'),'EvidenceControlPage'),GeoOperationsPage=lazyNamed(()=>import('./geo/GeoOperationsPage.jsx'),'GeoOperationsPage'),AIOperationsPage=lazyNamed(()=>import('./intelligence/AIOperationsPage.jsx'),'AIOperationsPage');

const pageComponents={
 'my-workspace':MyWorkspacePage,'company-overview':CompanyDashboard,'ai-operations':AIOperationsPage,'work-packages':WorkPackages,'beneficiary-records':BeneficiaryRecords,'beneficiary-imports':BeneficiaryImports,
 'supply-chain':SupplyChainWorkspace,'inventory-overview':InventoryOverview,'item-master':ItemMasterPage,'warehouses':WarehousesPage,'procurement':ProcurementPage,'procurement-intelligence':ProcurementIntelligencePage,'agency-stock':AgencyStockAccountabilityPage,'financial-control':FinancialControlPage,'stock':StockPage,
 'logistics-overview':LogisticsOverview,'shipments':ShipmentsPage,'fleet':FleetPage,'material-issues':MaterialIssuesPage,'installed-assets':InstalledAssetsPage,'asset-lifecycle':AssetLifecyclePage,'reconciliation':ReconciliationPage,
 'service-cases':ServiceCasesPage,'service-plans':ServicePlansPage,'sla':SlaPage,'claims':ClaimsPage,'insurance':InsurancePage,'pdi':PDIPage,'regulatory-reports':RegulatoryReportsPage,
 'geo-operations':GeoOperationsPage,'action-center':ActionCenterPage,'compliance':CompliancePage,'agency-performance':AgencyPerformancePage,'approval-center':ApprovalCenterPage,'bulk-center':BulkCenterPage,
 'analytics':AnalyticsPage,'notifications':NotificationsPage,'documents':DocumentsPage,'audit':AuditPage,'team-access':TeamAccessPage,'automation':AutomationPage,'master-data':MasterDataPage,'evidence-control':EvidenceControlPage,'readiness':ReadinessPage
};
export function CompanyWorkspace({user,companyId,back,logout}){const pageKey=`opsynq_company_page:${companyId||user?.organizationId||'self'}:${user?.role||'user'}`;const deliveryKey=`opsynq.delivery.context.${companyId}`;const supplyHidden=['inventory-overview','item-master','warehouses','procurement','procurement-intelligence','stock','logistics-overview','shipments','fleet','material-issues','agency-stock','pdi'];const[page,setPageState]=useState(()=>sessionStorage.getItem(pageKey)||defaultCompanyPageForRole(user?.role));const setPage=(p,filter)=>{sessionStorage.setItem(pageKey,p);const hierarchy=['programs','contracts','work-orders','work-packages'];const isHierarchyDrill=!!filter?.__hierarchyDrill;const isSupplyDrill=!!filter?.__supplyDrill;if(hierarchy.includes(p)&&!isHierarchyDrill){try{sessionStorage.removeItem(deliveryKey)}catch{}}if(filter&&typeof filter==='object'){const clean=Object.fromEntries(Object.entries(filter).filter(([k])=>!k.startsWith('__')));if(!isHierarchyDrill){try{if(Object.keys(clean).length)sessionStorage.setItem(`opsynq.dashboard.filter.${p}`,JSON.stringify(clean));else if(supplyHidden.includes(p))sessionStorage.removeItem(`opsynq.dashboard.filter.${p}`)}catch{}}}else if(supplyHidden.includes(p)){try{sessionStorage.removeItem(`opsynq.dashboard.filter.${p}`)}catch{}}setPageState(p)};const allowed=useMemo(()=>[...new Set([...flattenModulesForUser(user,true).map(m=>m.id),...roleModuleIds(user?.role).filter(x=>['contracts','work-orders','work-packages',...supplyHidden].includes(x))])],[user]);const safePage=allowed.includes(page)?page:(allowed[0]||'company-overview');useEffect(()=>{if(page!==safePage)setPage(safePage)},[page,safePage]);useEffect(()=>{const open=e=>{const farmerId=e?.detail?.farmerId;if(!farmerId)return;try{sessionStorage.setItem('opsynq.dashboard.filter.beneficiary-records',JSON.stringify({farmerId}))}catch{}setPageState('beneficiary-records')};window.addEventListener('opsynq:open-beneficiary',open);return()=>window.removeEventListener('opsynq:open-beneficiary',open)},[companyId]);let content;if(resourceConfig[safePage])content=<ResourcePage kind={safePage} companyId={companyId} onNavigate={setPage}/>;else{const Component=pageComponents[safePage]||CompanyDashboard;content=<Suspense fallback={<div className="module-loader"><span/><b>Loading module…</b></div>}><Component companyId={companyId} onNavigate={setPage} user={user}/></Suspense>;}return <PermissionProvider user={user}><Shell user={user} page={safePage} setPage={setPage} logout={logout} companyMode companyId={companyId}>{back&&<button className="back company-switch" onClick={back}><ArrowLeft size={16}/> Back to platform companies</button>}{content}</Shell></PermissionProvider>}
