import React,{useEffect,useMemo,useState}from'react';
import axios from'axios';
import{FaDownload,FaPrint,FaSearch,FaSyncAlt,FaFileExcel,FaFilter}from'react-icons/fa';
import{API_URL}from'../config';

const auth=()=>{const token=localStorage.getItem('token');return{withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}};
const periodFor=p=>{const now=new Date(),to=new Date(now),from=new Date(now);if(p==='DAILY'){}else if(p==='WEEKLY')from.setDate(now.getDate()-6);else if(p==='MONTHLY')from.setDate(1);else if(p==='QUARTERLY')from.setMonth(Math.floor(now.getMonth()/3)*3,1);else if(p==='HALF_YEARLY')from.setMonth(now.getMonth()<6?0:6,1);else if(p==='YEARLY')from.setMonth(0,1);else return{from:'',to:''};return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)}};
const qs=o=>new URLSearchParams(Object.fromEntries(Object.entries(o).filter(([,v])=>v))).toString();
async function download(type,format,filters){const res=await axios.get(`${API_URL}/api/farmers/reports/${type}/export?${qs({...filters,format})}`,{...auth(),responseType:'blob'}),cd=res.headers['content-disposition']||'',m=cd.match(/filename="?([^";]+)"?/i),url=URL.createObjectURL(res.data),a=document.createElement('a');a.href=url;a.download=m?.[1]||`${type}.${format}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
async function print(type,filters){const res=await axios.get(`${API_URL}/api/farmers/reports/${type}/export?${qs({...filters,format:'print'})}`,{...auth(),responseType:'text'}),w=window.open('','_blank');if(!w)throw new Error('Allow pop-ups to open the printable report.');w.document.open();w.document.write(res.data);w.document.close()}

export default function AgencyReportsPanel(){
 const[catalog,setCatalog]=useState([]),[agencies,setAgencies]=useState([]),[type,setType]=useState('executive-summary'),[preview,setPreview]=useState(null),[preset,setPreset]=useState('MONTHLY'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[search,setSearch]=useState(''),[reportSearch,setReportSearch]=useState(''),[district,setDistrict]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const p=periodFor('MONTHLY');setFrom(p.from);setTo(p.to);axios.get(`${API_URL}/api/farmers/reports`,auth()).then(r=>{setCatalog(r.data.reports||[]);setAgencies(r.data.agencies||[])}).catch(e=>setError(e.response?.data?.message||e.message))},[]);
 const filters={from,to,search,district};
 const load=async()=>{if(!type)return;setBusy(true);setError('');try{const r=await axios.get(`${API_URL}/api/farmers/reports/${type}/preview?${qs(filters)}`,auth());setPreview(r.data)}catch(e){setError(e.response?.data?.message||e.message||'Unable to load report.')}finally{setBusy(false)}};
 useEffect(()=>{load()},[type,from,to,search,district]);
 const groups=useMemo(()=>{const q=reportSearch.trim().toLowerCase(),m=new Map();for(const r of catalog){if(q&&![r.title,r.category,r.description].some(v=>String(v||'').toLowerCase().includes(q)))continue;if(!m.has(r.category))m.set(r.category,[]);m.get(r.category).push(r)}return[...m.entries()]},[catalog,reportSearch]),columns=preview?.rows?.length?Object.keys(preview.rows[0]):[],selected=catalog.find(r=>r.id===type);
 const setPeriod=p=>{setPreset(p);const r=periodFor(p);setFrom(r.from);setTo(r.to)};
 const runExport=async format=>{try{setError('');if(format==='print')await print(type,filters);else await download(type,format,filters)}catch(e){setError(e.response?.data?.message||e.message||'Report export failed.')}};
 return <section className="agency-reports agency-reports--workspace agency-reports--pro"><header className="agency-reports__topbar"><div><span>REPORTING & AUDIT</span><h2>Agency Reports</h2><p>Installation, material, service, RMS, traceability and audit reporting for your assigned scope.</p></div><div className="agency-reports__period-switch" role="group" aria-label="Report period">{['DAILY','WEEKLY','MONTHLY','QUARTERLY','HALF_YEARLY','YEARLY','CUSTOM'].map(p=><button key={p} className={preset===p?'active':''} onClick={()=>setPeriod(p)}>{p.replaceAll('_',' ')}</button>)}</div></header>
 <div className="agency-report-shell agency-report-shell--pro"><aside className="agency-report-library"><div className="agency-report-library__head"><div className="agency-report-library__title"><b>Reports</b><span>{catalog.length}</span></div><label className="agency-report-library__search"><FaSearch/><input value={reportSearch} onChange={e=>setReportSearch(e.target.value)} placeholder="Search reports" aria-label="Search reports"/>{reportSearch&&<button type="button" onClick={()=>setReportSearch('')} aria-label="Clear report search">×</button>}</label></div><div className="agency-report-library-scroll">{groups.map(([category,reports])=><div className="agency-report-group" key={category}><div className="agency-report-group__head"><b>{category}</b><span>{reports.length}</span></div>{reports.map(r=><button key={r.id} className={`agency-report-library-item ${type===r.id?'active':''}`} onClick={()=>setType(r.id)} title={r.title}><FaFileExcel/><span><b>{r.title}</b><small>{r.description}</small></span></button>)}</div>)}{!groups.length&&<div className="agency-rms-empty">No reports match your search.</div>}</div></aside>
 <main className="agency-report-main agency-report-main--pro"><section className="agency-report-selected agency-report-selected--bar"><div className="agency-report-selected__copy"><small>Selected report</small><h3 title={selected?.title||''}>{selected?.title||'Choose a report'}</h3><p>{selected?.description||''}</p></div><div className="agency-report-selected__meta"><span><b>{preview?.total||0}</b> records</span><span><b>{columns.length}</b> columns</span><span><b>{preset.replaceAll('_',' ')}</b> period</span></div><div className="agency-reports__actions"><button className="btn btn-outline-secondary btn-sm" onClick={()=>runExport('print')}><FaPrint/> PDF</button><button className="btn btn-outline-secondary btn-sm" onClick={()=>runExport('csv')}><FaDownload/> CSV</button><button className="btn btn-dark btn-sm" onClick={()=>runExport('xlsx')}><FaFileExcel/> Excel</button></div></section>
 <div className="agency-report-toolbar"><label className="agency-report-data-search"><FaSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search rows in this report" aria-label="Search report rows"/>{search&&<button type="button" onClick={()=>setSearch('')} aria-label="Clear row search">×</button>}</label><div className="agency-report-toolbar__actions"><button className={`agency-report-filter ${filtersOpen?'active':''}`} onClick={()=>setFiltersOpen(v=>!v)}><FaFilter/> Filters</button><button className="btn btn-outline-secondary btn-sm" onClick={load} disabled={busy}><FaSyncAlt className={busy?'agency-rms-spin':''}/> {busy?'Refreshing…':'Refresh'}</button><span>{preview?.total||0} records</span></div></div>
 {filtersOpen&&<div className="agency-report-filters"><label>From<input type="date" value={from} onChange={e=>{setPreset('CUSTOM');setFrom(e.target.value)}}/></label><label>To<input type="date" value={to} onChange={e=>{setPreset('CUSTOM');setTo(e.target.value)}}/></label><label>District<input value={district} onChange={e=>setDistrict(e.target.value)} placeholder="Exact district"/></label><button className="btn btn-outline-secondary btn-sm" onClick={()=>{setPreset('CUSTOM');setFrom('');setTo('');setDistrict('');setSearch('')}}>Reset</button></div>}
 {error&&<div className="alert alert-danger">{error}</div>}
 <div className="agency-report-preview"><div className="agency-report-preview__head"><div><h3>{preview?.report?.title||selected?.title||'Report preview'}</h3><p>{busy?'Updating live records…':`${preview?.total||0} records · preview up to ${preview?.previewLimit||500} · exports include the complete selected-period dataset`}</p></div><span>{from||'All time'} → {to||'Today'}</span></div><div className="agency-rms-table agency-report-table"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{(preview?.rows||[]).map((r,i)=><tr key={i}>{columns.map(c=><td key={c} title={String(r[c]??'')}>{String(r[c]??'')}</td>)}</tr>)}{!preview?.rows?.length&&<tr><td colSpan={Math.max(1,columns.length)} className="agency-rms-empty">{busy?'Loading report records…':'No records match this period and filter.'}</td></tr>}</tbody></table></div></div></main></div></section>
}
