import React,{useEffect,useMemo,useState}from'react';
import axios from'axios';
import{Button,Form,Modal,Spinner,Table,Badge,Alert}from'react-bootstrap';
import{API_URL}from'../config';

const codeOf=s=>s?.serialNumber||s?.barcodeValue||'';
const statusVariant=s=>s==='DELIVERED'?'success':s==='PARTIAL'?'warning':'info';
const PAGE_SIZE=25;

export default function MaterialReceiptsPanel(){
 const[items,setItems]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[q,setQ]=useState(''),[debouncedQ,setDebouncedQ]=useState(''),[meta,setMeta]=useState({page:1,pages:1,total:0});
 const token=localStorage.getItem('token');
 const auth={headers:{Authorization:`Bearer ${token}`}};
 useEffect(()=>{const t=setTimeout(()=>setDebouncedQ(q.trim()),300);return()=>clearTimeout(t)},[q]);
 const load=async(page=1)=>{setLoading(true);setError('');try{const params=new URLSearchParams({page:String(page),pageSize:String(PAGE_SIZE)});if(status)params.set('status',status);if(debouncedQ)params.set('q',debouncedQ);const r=await axios.get(`${API_URL}/api/agency-inventory/shipments?${params}`,auth);setItems(r.data.items||[]);setMeta({page:r.data.page||1,pages:r.data.pages||1,total:r.data.total||0})}catch(e){setError(e.response?.data?.message||e.message)}finally{setLoading(false)}};
 useEffect(()=>{load(1)},[status,debouncedQ]);
 const open=s=>{const lines=(s.items||[]).map(l=>{const accounted=Number(l.receivedQty||0)+Number(l.damagedQty||0)+Number(l.missingQty||0),remaining=Math.max(0,Number(l.quantity||0)-accounted),serials=(l.serialIds||[]).filter(x=>x.status==='IN_TRANSIT').map(codeOf).filter(Boolean);return{itemId:l.itemId?._id||l.itemId,itemName:l.itemId?.name||'Item',sku:l.itemId?.sku||'',serialTracked:!!l.itemId?.serialTracked,remaining,receivedQty:remaining,damagedQty:0,missingQty:0,receivedSerials:serials.join('\n'),damagedSerials:'',missingSerials:'',notes:''}});setSelected(s);setForm({receiverName:localStorage.getItem('username')||'',receiverMobile:localStorage.getItem('mobile')||'',notes:'',lines})};
 const updateLine=(i,k,v)=>setForm({...form,lines:form.lines.map((x,idx)=>idx===i?{...x,[k]:v}:x)});
 const save=async()=>{setSaving(true);setError('');try{const receipts=form.lines.map(l=>({itemId:l.itemId,receivedQty:Number(l.receivedQty||0),damagedQty:Number(l.damagedQty||0),missingQty:Number(l.missingQty||0),receivedSerials:String(l.receivedSerials||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean),damagedSerials:String(l.damagedSerials||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean),missingSerials:String(l.missingSerials||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean),notes:l.notes||''}));await axios.post(`${API_URL}/api/agency-inventory/shipments/${selected._id}/receive`,{receiverName:form.receiverName,receiverMobile:form.receiverMobile,notes:form.notes,receipts},auth);setSelected(null);setForm(null);await load(meta.page)}catch(e){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}};
 const openCount=useMemo(()=>items.filter(x=>['IN_TRANSIT','PARTIAL'].includes(x.status)).length,[items]);
 return <div className="agency-material-page">
  <div className="agency-command-row"><div><strong>Inbound Material & Receipt Accountability</strong><span>{meta.total} shipments in this view · {openCount} on this page awaiting complete accountability</span></div><div className="agency-command-actions"><Form.Control value={q} onChange={e=>setQ(e.target.value)} placeholder="Search shipment / tracking no."/><Form.Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All shipment states</option><option value="IN_TRANSIT">In Transit</option><option value="PARTIAL">Partial</option><option value="DELIVERED">Delivered</option></Form.Select><Button variant="outline-secondary" onClick={()=>load(meta.page)}>Refresh</Button></div></div>
  {error&&<Alert variant="danger">{error}</Alert>}
  {loading?<div className="agency-loading"><Spinner size="sm"/> Loading inbound shipments…</div>:<div className="agency-table-shell"><Table responsive hover><thead><tr><th>Shipment</th><th>Work Package</th><th>From</th><th>Items</th><th>Dispatched</th><th>Status</th><th>Receipt</th></tr></thead><tbody>{items.map(s=><tr key={s._id}><td><strong>{s.shipmentNo}</strong><small>{s.trackingNumber||s.vehicleId?.registrationNo||s.vehicleId?.registrationNumber||''}</small></td><td><strong>{s.workPackageId?.code||'—'}</strong><small>{s.workPackageId?.name||''}</small></td><td>{s.fromWarehouseId?.name||'—'}<small>{s.driverId?.name||''}</small></td><td>{(s.items||[]).reduce((n,l)=>n+Number(l.quantity||0),0)} units</td><td>{s.dispatchedAt?new Date(s.dispatchedAt).toLocaleString():'—'}</td><td><Badge bg={statusVariant(s.status)}>{String(s.status).replaceAll('_',' ')}</Badge></td><td>{['IN_TRANSIT','PARTIAL'].includes(s.status)?<Button size="sm" onClick={()=>open(s)}>Confirm receipt</Button>:<span className="receipt-complete">Confirmed</span>}</td></tr>)}{!items.length&&<tr><td colSpan="7" className="text-center text-muted py-4">No inbound shipments match this view.</td></tr>}</tbody></Table>{meta.pages>1&&<div className="agency-table-pager"><Button size="sm" variant="outline-secondary" disabled={meta.page<=1} onClick={()=>load(meta.page-1)}>Previous</Button><span>Page {meta.page} of {meta.pages} · {meta.total} shipments</span><Button size="sm" variant="outline-secondary" disabled={meta.page>=meta.pages} onClick={()=>load(meta.page+1)}>Next</Button></div>}</div>}
  <Modal show={!!selected} onHide={()=>{setSelected(null);setForm(null)}} size="lg" centered scrollable><Modal.Header closeButton><Modal.Title>Receive {selected?.shipmentNo}</Modal.Title></Modal.Header><Modal.Body>{form&&<><div className="two"><Form.Group><Form.Label>Receiver name</Form.Label><Form.Control value={form.receiverName} onChange={e=>setForm({...form,receiverName:e.target.value})}/></Form.Group><Form.Group><Form.Label>Receiver mobile</Form.Label><Form.Control value={form.receiverMobile} onChange={e=>setForm({...form,receiverMobile:e.target.value})}/></Form.Group></div>{form.lines.map((l,i)=><div className="agency-receipt-line" key={l.itemId}><div className="agency-receipt-line__head"><div><strong>{l.sku} · {l.itemName}</strong><span>{l.remaining} units remaining to account</span></div></div><div className="three"><Form.Group><Form.Label>Good received</Form.Label><Form.Control type="number" min="0" max={l.remaining} value={l.receivedQty} onChange={e=>updateLine(i,'receivedQty',e.target.value)}/></Form.Group><Form.Group><Form.Label>Damaged</Form.Label><Form.Control type="number" min="0" max={l.remaining} value={l.damagedQty} onChange={e=>updateLine(i,'damagedQty',e.target.value)}/></Form.Group><Form.Group><Form.Label>Missing</Form.Label><Form.Control type="number" min="0" max={l.remaining} value={l.missingQty} onChange={e=>updateLine(i,'missingQty',e.target.value)}/></Form.Group></div>{l.serialTracked&&<div className="three"><Form.Group><Form.Label>Good serials</Form.Label><Form.Control as="textarea" rows={4} value={l.receivedSerials} onChange={e=>updateLine(i,'receivedSerials',e.target.value)}/></Form.Group><Form.Group><Form.Label>Damaged serials</Form.Label><Form.Control as="textarea" rows={4} value={l.damagedSerials} onChange={e=>updateLine(i,'damagedSerials',e.target.value)}/></Form.Group><Form.Group><Form.Label>Missing serials</Form.Label><Form.Control as="textarea" rows={4} value={l.missingSerials} onChange={e=>updateLine(i,'missingSerials',e.target.value)}/></Form.Group></div>}<Form.Group><Form.Label>Line notes</Form.Label><Form.Control value={l.notes} onChange={e=>updateLine(i,'notes',e.target.value)} placeholder="Damage, shortage or receipt observations"/></Form.Group></div>)}<Form.Group><Form.Label>Receipt notes</Form.Label><Form.Control as="textarea" rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Form.Group></>}</Modal.Body><Modal.Footer><Button variant="outline-secondary" onClick={()=>{setSelected(null);setForm(null)}}>Cancel</Button><Button disabled={saving} onClick={save}>{saving?'Saving…':'Confirm material receipt'}</Button></Modal.Footer></Modal>
 </div>
}
