import React,{useEffect,useRef,useState} from 'react';
import {CloudOff,RefreshCw} from 'lucide-react';
import {API_URL} from '../config';
import {flushQueuedWrites,queuedCount} from '../offlineStore';

const emitDataRefresh=(detail={})=>window.dispatchEvent(new CustomEvent('opsynq:data-refresh',{detail}));
function unsafe(){const el=document.activeElement;return Boolean((el&&(['INPUT','TEXTAREA','SELECT'].includes(el.tagName)||el.isContentEditable))||document.querySelector('.modal.show,[role="dialog"],.offcanvas.show'));}
function safeReload(){const go=()=>unsafe()?setTimeout(go,1000):location.reload();go();}
export default function ResilienceStatus(){
 const[online,setOnline]=useState(navigator.onLine),[pending,setPending]=useState(0),[syncing,setSyncing]=useState(false),[updateAvailable,setUpdateAvailable]=useState(false);
 const rev=useRef(''),dataRev=useRef(null),shellFingerprint=useRef(''),syncInFlight=useRef(false);
 useEffect(()=>{let live=true;const count=async()=>{const n=await queuedCount();if(live)setPending(n);return n};const sync=async()=>{if(syncInFlight.current||!navigator.onLine)return;syncInFlight.current=true;setOnline(true);setSyncing(true);try{const r=await flushQueuedWrites(API_URL);if(live)setPending(r.pending);if(r.synced>0)emitDataRefresh({reason:'offline-sync',...r})}finally{syncInFlight.current=false;if(live)setSyncing(false)}};const onOnline=()=>{setOnline(true);sync()};const off=()=>setOnline(false);const onSyncState=()=>count();count();window.addEventListener('online',onOnline);window.addEventListener('offline',off);window.addEventListener('opsynq:agency-sync-state',onSyncState);return()=>{live=false;window.removeEventListener('online',onOnline);window.removeEventListener('offline',off);window.removeEventListener('opsynq:agency-sync-state',onSyncState)}},[]);
 useEffect(()=>{let live=true;const check=async()=>{if(!navigator.onLine||!(localStorage.getItem('opsynq_agency_session')==='1'||localStorage.getItem('token')))return;try{const token=localStorage.getItem('token');const r=await fetch(`${API_URL}/api/users/revision`,{credentials:'include',cache:'no-store',headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok)return;const d=await r.json(),current=Number(d.revision||0);if(dataRev.current===null)dataRev.current=current;else if(live&&current!==dataRev.current){dataRev.current=current;emitDataRefresh({reason:'tenant-data-update',revision:current})}}catch{}};check();const id=setInterval(check,12000);return()=>{live=false;clearInterval(id)}},[]);
 useEffect(()=>{if(import.meta.env.DEV)return;let live=true;const check=async()=>{try{const [runtime,shell]=await Promise.all([fetch(`${API_URL}/api/runtime/revision`,{cache:'no-store'}),fetch(`${location.origin}/index.html?opsynq_revision=${Date.now()}`,{cache:'no-store'})]);if(runtime.ok){const d=await runtime.json();if(!rev.current)rev.current=d.revision;else if(live&&d.revision&&d.revision!==rev.current){rev.current=d.revision;setUpdateAvailable(true)}}if(shell.ok){const html=await shell.text();const fp=`${html.length}:${html.slice(0,512)}:${html.slice(-512)}`;if(!shellFingerprint.current)shellFingerprint.current=fp;else if(live&&fp!==shellFingerprint.current){shellFingerprint.current=fp;setUpdateAvailable(true)}}}catch{}};check();const id=setInterval(check,60000);return()=>{live=false;clearInterval(id)}},[]);
 if(updateAvailable)return <div className="agency-resilience update"><RefreshCw size={14}/><span>A newer Opsynq version is available.</span><button type="button" onClick={safeReload}>Update now</button></div>;
 if(online&&!pending&&!syncing)return null;return <div className={`agency-resilience ${online?'syncing':'offline'}`}>{online?<RefreshCw size={14}/>:<CloudOff size={14}/>}<span>{online?(syncing?'Syncing saved changes…':`${pending} saved change${pending===1?'':'s'} pending sync`):`Offline — ${pending?`${pending} change${pending===1?'':'s'} safely queued`:'cached data remains available'}`}</span></div>;
}
