import React,{useEffect,useRef,useState} from 'react';
import {CloudOff,RefreshCw} from 'lucide-react';
import {API_URL} from '../config';
import {flushQueuedWrites,queuedCount} from '../offlineStore';

const KEY='opsynq_agency_continuity';
function saveState(reason){try{sessionStorage.setItem(KEY,JSON.stringify({path:location.pathname,search:location.search,scrollY:window.scrollY,reason,at:Date.now()}))}catch{}}
function restoreScroll(){try{const s=JSON.parse(sessionStorage.getItem(KEY)||'{}');if(Number.isFinite(s.scrollY))requestAnimationFrame(()=>window.scrollTo({top:s.scrollY,behavior:'auto'}))}catch{}}
function unsafe(){const el=document.activeElement;return Boolean((el&&(['INPUT','TEXTAREA','SELECT'].includes(el.tagName)||el.isContentEditable))||document.querySelector('.modal.show,[role="dialog"],.offcanvas.show'));}
function safeReload(reason){saveState(reason);const go=()=>unsafe()?setTimeout(go,1500):location.reload();go();}
export default function ResilienceStatus(){const[online,setOnline]=useState(navigator.onLine),[pending,setPending]=useState(0),[syncing,setSyncing]=useState(false);const rev=useRef(''),dataRev=useRef(null),shellFingerprint=useRef('');
 useEffect(()=>{restoreScroll();let live=true;const count=async()=>{const n=await queuedCount();if(live)setPending(n)};const sync=async()=>{setOnline(true);setSyncing(true);const r=await flushQueuedWrites(API_URL);if(live){setPending(r.pending);setSyncing(false)}if(r.synced>0)safeReload('offline-sync')};const off=()=>setOnline(false);count();window.addEventListener('online',sync);window.addEventListener('offline',off);window.addEventListener('opsynq:agency-sync-state',count);return()=>{live=false;window.removeEventListener('online',sync);window.removeEventListener('offline',off);window.removeEventListener('opsynq:agency-sync-state',count)}},[]);

 useEffect(()=>{let live=true;const check=async()=>{if(!navigator.onLine||!(localStorage.getItem('opsynq_agency_session')==='1'||localStorage.getItem('token')))return;try{const token=localStorage.getItem('token');const r=await fetch(`${API_URL}/api/users/revision`,{credentials:'include',cache:'no-store',headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok)return;const d=await r.json(),current=Number(d.revision||0);if(dataRev.current===null)dataRev.current=current;else if(live&&current!==dataRev.current){dataRev.current=current;safeReload('tenant-data-update')}}catch{}};check();const id=setInterval(check,4000);return()=>{live=false;clearInterval(id)}},[]);
 useEffect(()=>{if(import.meta.env.DEV)return;let live=true;const check=async()=>{try{const [runtime,shell]=await Promise.all([fetch(`${API_URL}/api/runtime/revision`,{cache:'no-store'}),fetch(`${location.origin}/index.html?opsynq_revision=${Date.now()}`,{cache:'no-store'})]);if(runtime.ok){const d=await runtime.json();if(!rev.current)rev.current=d.revision;else if(live&&d.revision&&d.revision!==rev.current)return safeReload('runtime-update');}if(shell.ok){const html=await shell.text();const fp=`${html.length}:${html.slice(0,512)}:${html.slice(-512)}`;if(!shellFingerprint.current)shellFingerprint.current=fp;else if(live&&fp!==shellFingerprint.current)safeReload('frontend-deployment');}}catch{}};check();const id=setInterval(check,12000);return()=>{live=false;clearInterval(id)}},[]);
 if(online&&!pending&&!syncing)return null;return <div className={`agency-resilience ${online?'syncing':'offline'}`}>{online?<RefreshCw size={14}/>:<CloudOff size={14}/>}<span>{online?(syncing?'Syncing saved changes…':`${pending} saved change${pending===1?'':'s'} pending sync`):`Offline — ${pending?`${pending} change${pending===1?'':'s'} safely queued`:'cached data remains available'}`}</span></div>}
