const fs=require('fs');const path=require('path');const mongoose=require('mongoose');
const {validateTarget,accountSnapshot}=require('./demoDbGuard');
const Farmer=require('../models/Farmer');const BeneficiaryContext=require('../models/platform/BeneficiaryContext');const WorkPackage=require('../models/platform/WorkPackage');const InventorySerial=require('../models/platform/InventorySerial');const InstalledAsset=require('../models/platform/InstalledAsset');const AgencyUserLink=require('../models/platform/AgencyUserLink');const EvidenceSubmission=require('../models/platform/EvidenceSubmission');const DocumentRecord=require('../models/platform/DocumentRecord');const InsurancePolicy=require('../models/platform/InsurancePolicy');const PDIRecord=require('../models/platform/PDIRecord');
const fail=(msg)=>{throw new Error(msg)};const ok=(msg)=>console.log(`✓ ${msg}`);
function latestManifest(dbName){const root=path.resolve(__dirname,'../backups');if(!fs.existsSync(root))return null;const files=fs.readdirSync(root).filter(x=>x.startsWith('demo-reset-')).map(x=>path.join(root,x,'manifest.json')).filter(fs.existsSync).map(f=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return null}}).filter(x=>x?.complete&&x.dbName===dbName).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return files[0]||null;}
function mediaName(url){const s=String(url||'');const i=s.indexOf('/demo-media/');return i>=0?s.slice(i+'/demo-media/'.length):'';}
function collectMedia(obj,out=[]){if(!obj)return out;if(typeof obj==='string'){const n=mediaName(obj);if(n)out.push(n);return out}if(Array.isArray(obj)){for(const x of obj)collectMedia(x,out);return out}if(typeof obj==='object'){for(const v of Object.values(obj))collectMedia(v,out)}return out}
(async()=>{
 const {id,protectedState}=await validateTarget({destructive:false});
 const manifest=latestManifest(id.dbName);if(manifest?.protectedAccounts){const before=new Map(manifest.protectedAccounts.map(x=>[`${x.realm}:${x.mobile}`,x]));const after=accountSnapshot(protectedState);for(const x of after){const b=before.get(`${x.realm}:${x.mobile}`);if(!b)continue;for(const k of ['id','email','username','role','organizationId','passwordHash'])if(String(b[k]||'')!==String(x[k]||''))fail(`Protected account changed after reset: ${x.realm}:${x.mobile} field=${k}`)}ok('Protected demo/SuperAdmin identities, password hashes, roles and tenant mappings match the pre-wipe backup');}
 const farmers=await Farmer.find({beneficiaryId:/^OPS-DM-/}).lean();if(farmers.length!==18)fail(`Expected exactly 18 demo beneficiaries, found ${farmers.length}`);ok('Exactly 18 demo beneficiaries');
 const ids=farmers.map(x=>x._id);const contexts=await BeneficiaryContext.find({farmerId:{$in:ids}}).lean();if(contexts.length!==18)fail(`Expected 18 beneficiary contexts, found ${contexts.length}`);const farmerSet=new Set(ids.map(String));if(contexts.some(x=>!farmerSet.has(String(x.farmerId))))fail('Orphan beneficiary context detected');ok('All demo beneficiaries have tenant-scoped execution context');
 const wpIds=[...new Set(contexts.map(x=>String(x.workPackageId)))];for(const wpId of wpIds){const wp=await WorkPackage.findById(wpId).lean();const count=contexts.filter(x=>String(x.workPackageId)===wpId).length;if(!wp||Number(wp.assignedQuantity)!==count)fail(`Work package assignedQuantity mismatch for ${wp?.code||wpId}: expected ${count}, got ${wp?.assignedQuantity}`)}ok('Work-package assigned quantities match beneficiary contexts');
 const links=await AgencyUserLink.find({isActive:true}).lean();for(const c of contexts)if(!links.some(l=>String(l.companyId)===String(c.companyId)&&String(l.agencyId)===String(c.agencyId)))fail(`Agency has no active tenant link for beneficiary ${c.farmerId}`);ok('Agency/company hierarchy links are present');
 const serials=await InventorySerial.find({companyId:{$in:[...new Set(contexts.map(x=>x.companyId))]}}).lean();const serialKeys=new Set();for(const s of serials){const k=`${s.companyId}:${s.serialNumber}`;if(serialKeys.has(k))fail(`Duplicate serial ${s.serialNumber}`);serialKeys.add(k);if(s.status==='INSTALLED'&&!s.farmerId)fail(`Installed serial missing beneficiary: ${s.serialNumber}`);if(s.status==='ISSUED'&&!s.farmerId)fail(`Issued serial missing beneficiary: ${s.serialNumber}`)}
 const assets=await InstalledAsset.find({farmerId:{$in:ids}}).lean();const assetBySerial=new Map(assets.map(a=>[String(a.inventorySerialId),a]));for(const s of serials.filter(x=>x.status==='INSTALLED')){const a=assetBySerial.get(String(s._id));if(!a)fail(`Installed serial has no InstalledAsset: ${s.serialNumber}`);const ctx=contexts.find(c=>String(c.farmerId)===String(s.farmerId));if(!ctx||String(ctx.companyId)!==String(s.companyId)||String(ctx.agencyId)!==String(s.agencyId))fail(`Installed serial tenant mismatch: ${s.serialNumber}`)}ok('Serialized inventory is unique and installed/issued custody is tenant-consistent');
 const mediaDir=path.resolve(__dirname,'../demo-media');const seen=new Set();for(const f of farmers){const names=collectMedia({farmerPhotoUrl:f.farmerPhotoUrl,sitePhotosUrls:f.sitePhotosUrls,signatureUrl:f.signatureUrl,installedPhotoUpload:f.installedPhotoUpload,finalfarmerPhotoUrl:f.finalfarmerPhotoUrl,finalsitePhotosUrls:f.finalsitePhotosUrls,finalsignatureUrl:f.finalsignatureUrl,finalsurveyorsignatureUrl:f.finalsurveyorsignatureUrl,lrPhotoUrls:f.lrPhotoUrls,customFields:f.customFields});for(const n of names){if(seen.has(n))fail(`Demo media reused across beneficiary evidence fields: ${n}`);seen.add(n);if(!fs.existsSync(path.join(mediaDir,n)))fail(`Missing bundled demo media: ${n}`)}}
 const extraDocs=[...await EvidenceSubmission.find({farmerId:{$in:ids}}).lean(),...await DocumentRecord.find({}).lean(),...await InsurancePolicy.find({farmerId:{$in:ids}}).lean(),...await PDIRecord.find({}).lean()];for(const row of extraDocs)for(const n of collectMedia(row)){if(seen.has(n))fail(`Demo media reused across seeded records: ${n}`);seen.add(n);if(!fs.existsSync(path.join(mediaDir,n)))fail(`Missing bundled demo media: ${n}`)}ok(`Bundled demo media exists with no reused file references (${seen.size} linked images)`);
 const edges=Object.fromEntries(farmers.filter(x=>['OPS-DM-017','OPS-DM-018'].includes(x.beneficiaryId)).map(x=>[x.beneficiaryId,x.customFields?.demoLifecycleStatus]));if(edges['OPS-DM-017']!=='ON_HOLD'||edges['OPS-DM-018']!=='REJECTED')fail('ON_HOLD/REJECTED demo edge cases are missing');ok('Lifecycle edge cases ON_HOLD and REJECTED are seeded');
 console.log('✓ Demo sanity verification passed');
})().catch(e=>{console.error(`✗ Demo sanity failed: ${e.message}`);process.exitCode=1}).finally(async()=>{try{await mongoose.connection.close()}catch{}});
